### ISSUE TITLE
Bring colors and typeface in line with web interface

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1132]
This is relevant for both iOS and Android. cc @rperezb @MTRichards @tobiasKaminsky @AndyScherzinger @Kernald @LukeOwncloud @javiergonzper @ggdiez @masensio @nasli @davivel @owncloud/designers 

Currently for example the background of the file list is not white, which is a big factor in making it look different from the web interface and not fit in line with the rest of ownCloud.

Colors should be like this:
- [x] background-color: #fff (white)
- [x] text color: #000 (black)
- [x] secondary text color: #a0a0a0 (for the modified date and file size)
- [ ] color of dividing lines: #eee 
- [ ] background color of highlighted row (if necessary): #f8f8f8
- [ ] highlight text color: #55739a
- [x] header color: #1d2d44 (like now already)

For the text, we should use Open Sans. Light weight for everything, and Semibold where we used bold before. The font is at https://github.com/owncloud/promo/tree/master/Open%20Sans

What do you all think?

**Comment by AndyScherzinger** [comment]
I can work on the color coding :) shouldn't take to much time. We can also change the fonts if you guys want to do that, which would the mean ship the fonts with the app, load them and dynamically set the font type on the UI/text-elements. AFAIK this needs to be done separately for every element,  so font use might be a point for discussion but colors aren't a problem. :+1:

**Comment by AndyScherzinger** [comment]
The background color needs to be changes in setup @jancborchardt  @davivel 
The text highlight color "can't" be changed since it is bound to the material design color names that are already used for the action bar (primary / secondary color)

**Comment by AndyScherzinger** [comment]
@jancborchardt I moved back to #eee for the divider (discussion has been in https://github.com/owncloud/android/issues/1232#issuecomment-153020296). Unfortunately the coloring didn't work for the list even though it seemed like but I found the mistake and fixed it on the material buttons branch (see screenshot attached) and also fixed the thickness of the divider. So requesting feedback if #eee is fine with the latest fixes to the divider and background color being white:
![device-2015-11-04-104954](https://cloud.githubusercontent.com/assets/1315170/10934861/a3a773b8-82e2-11e5-95d3-1b4908199f58.png)

@tobiasKaminsky I already pushed the fix to the beta branch. Hope that is fine with you.

**Comment by raghunayyar** [comment]
I think we should use the OS defaults for mobile, it gives a more native experience. @jancborchardt

**Comment by jancborchardt** [comment]
It would be cool if we can experiment with it – currently we use the OS default, but it would be nice to see how it looks with Open Sans. Cause that gives a more ownCloudy experience.

**Comment by AndyScherzinger** [comment]
We should stay with the OS font at least until we drop support for 4.0 and declare 4.1 the minimum Android version due to the fact that the font support "api wise" is really bad before 4.1 since with for 4.1 we simply declare the font and use it in style definitions, before 4.1 one needs to load the font programmatically and set is on every UI element separately thus cluttered code simply for one Android version. Else we could add it for >= Android 4.1 which than would lead to an inconsistent style throughout the Android version.

Thus I would suggest postponing the font discussion until we drop Android 4.0 support.

**Comment by jancborchardt** [comment]
@AndyScherzinger ok, good point with the compatibility!

**Comment by AndyScherzinger** [comment]
checked secondary text color which has been fixed/released with 2.0.0
