### ISSUE TITLE
Automated synchronization of folders (scope: inside 'owncloud' folder)

### ISSUE THREAD

**Issue by MTRichards** [owncloud/android#1136]
# As an ownCloud user, I want to be able to sync a folder from my Android mobile device to the server so that I can access and edit files easily across devices without thinking about it

Acceptance Criteria:
- Two-way syncing, from the folder set, to all its descendants
- For folders existing in an OC account (syncing local folders only existing in the device is out of the scope of this issue).
- The current Favorites star is to be renamed ~~Sync~~ "Available offline"
- The Sync star icon is to be replaced with  ~~a circular static sync icon~~ an arrow pointing downwards, place over an horizontal line; see more about icons in #1218 
- ~~Sync icon is to be the same color as the star and found in the same location on the iOS device (yellow)~~ (iOS)
- ~~Sync icon will automatically replace existing favorite directories on files currently set as favorites~~
- ~~Sync for iOS can only occur when the app is open, as there is no service mechanism for initiating sync in the background. As a result, every time the app is opened, the local cache is refreshed, and any new files are synced with the server.~~ (iOS)
- Once the app is opened, sync of individual directories happens when the user navigates into the directory
- When a user is browsing files and pulls down to refresh the directory, any files and folders in that directory are synced automatically (including folder children).
- When a directory is syncing, if ~~the app~~any folder is blocked, a circular icon shows that ~~the app~~ the folder is working on the sync

---

@davivel updated after May 16 Design Days

---

edited by @jabarros
- [x] Create 'available_offline_folders' branch from master in android repository @jabarros
- [x] [DEV] Allow set a folder as favorite (menu) @jabarros
- [x] [DEV] Save the favorite folder state on db and unset as favorite all children files that were favorites @jabarros
- [x] [DEV] Modify places where favorite folders are being syncing to sync also folders when file is folder: Case of folders syncing (pull down or enter in) @jabarros
- [x] [DEV] Modify places where favorite folders are being synced to sync also folders when file is folder: Case of full account sync and refresh account (in menu) @jabarros
- [x] [DEV] Check service that observes changes (FileObserveService) to take into account changes inside sync folders @malkomich
- [x] [DEV] Get folder data correctly, to assure a favorite keeps being favorite while a refresh operation is done @malkomich
- [x] [DEV] Create method to check if file is favorite or belongs to a favorite folder @jabarros
- [x] [DEV] Check on unfavorite request if the file is favorite by inheritance or not to allow execute the operation @malkomich
- [x] [DEV] Avoid change the 'favorite' value when syncying and only be able to set value since file item menu interaction @jabarros

SET / UNSET AVAILABLE OFFLINE PROPERTY
- [x] Review propagation of 'Unset as available offline' while browsing the file tree, not all the children files unset.

SYNC CONTENT ON OBSERVED CHANGE -> `FileObserverService` & friends
- [x] Back to a single class for observe available offline files
- [x] Extend `FolderObserver` to observe **any** file it contains, or selected files added one by one
- [x] Remove individual observers when ancestor folder is added to be observed.
- [x] Observe updates of files in subfolders created **after** a folder was set as available offline.
- [x] Check update of observer service when av-off file/folder is renamed 
- [x] Check update of observer service when file in av-off folder is renamed
- [x] Check update of observer service when folder in av-off folder is renamed

- [x] Check update of observer service when av-off file/folder is moved to non-av folder
- [x] Check update of observer service when av-off file/folder is moved into av-off folder 
- [x] Check update of observer service when file/folder is moved out of av-off folder
- [x] Check update of observer service when file/folder is moved into av-off folder
- [x] Check update of observer service when file/folder is moved from av-off folder to other av-off folder

- [x] Grant that av-off property of files sync'ed is NOT modified.

SYNC CONTENT ON POLLED CHANGE -> `RefreshFolderOperation`  & friends
- [x] Review calls to `getAvailableOfflineStatus(...)`.
- [x] Review performance to check server updates, while granting local updates.
- [x] Grant that av-off property of files sync'ed is NOT modified.
- [x] ~~Refactoring: `RefreshFolderOperation` and `SyncFolderOperation` duplicate too much code~~. [WONT]
- [x] ~~Refactoring: merge sync services (tentative)~~. [WONT]

OTHER STUFF
- [X] Changes after CR @jabarros @davivel (WIP)
- [X] [QA] Create 'available_offline' branch in QA Repo @jesmrec
- [X] [QA] Merge 'available_offline' branch in QA Repo @jesmrec
- [X] [QA] Create test plan @jesmrec 
- [x] [QA] Validate test plan @jesmrec
- [x] Merge 'available_offline_folders' branch into master

BUGS & IMPROVEMENTS

- [X] Av offline is lost by pulling down https://github.com/owncloud/android/issues/1136#issuecomment-260283603 [FIXED]
- [X] Browsing back in a structure makes the parent folder losing av. offline https://github.com/owncloud/android/issues/1136#issuecomment-260290056 [FIXED]
- [X] Cancelling does not remove av. offline https://github.com/owncloud/android/issues/1136#issuecomment-260294672 [FIXED]
- [X] `Synchronize` option is useless when folder is av. offline https://github.com/owncloud/android/issues/1136#issuecomment-260313481 [WONT]
- [x] Shared folders lose the icon when become av. offline https://github.com/owncloud/android/issues/1136#issuecomment-260318793 [FIXED] 
- [X] Lack of edit permission in an av. offline folder floods the uploads view https://github.com/owncloud/android/issues/1136#issuecomment-260334941 [OUT OF SCOPE]
- [X] "Unset av offline" option does not switch to "Set av offline" in toolbar https://github.com/owncloud/android/issues/1136#issuecomment-260884464 [FIXED]
- [X] Redirect server shows an error after syncing https://github.com/owncloud/android/issues/1136#issuecomment-260942750 [CANNOT_REPRODUCE] -> [FIXED]
- [X] New file in server in av-off folder discovered but not downloaded https://github.com/owncloud/android/issues/1136#issuecomment-264398458 [FIXED]

**Comment by Kernald** [comment]
Related standard material design icon [here](https://www.google.com/design/icons/#ic_sync).

**Comment by rperezb** [comment]
@jancborchardt we'd appreciate your input as well as @tobiasKaminsky @AndyScherzinger @LukeOwncloud and others.

The key thing is about the icon, does this icon represent that the files or folders are kept-up-to-date?
(The same one will be used on iOS too)

cc/ 
@davivel @masensio @javiergonzper @ggdiez @nasli @jesmrec 

cc/

**Comment by AndyScherzinger** [comment]
Tricky one.
* The sync icon is imho rather an action(-trigger) than a state
* The star is used by others (e.g. Dropbox) for this matter but is also used to highlight/bookmark (e.g. gmail)

So I would keep the star for keep-in-sync since 
* I guess the sync icon is not as bold from the style and thus hard to read on a white background
* the sync icon might (at least by me without any explanation) be interpreted as a sync is running on these folder(s)

Just a personal opinion thought!

**Comment by rperezb** [comment]
Thanks for the answer.

The reason for changing the star is because on the ownCloud web interface it means bookmark, so it´s confusing that on the mobile apps it has a different meaning.

We agree that the sync icon may be understood as an action icos, because of that we are looking for ideas

**Comment by LukeOwncloud** [comment]
I am not sure I understand bullets 5-7 correctly: Does `sync` mean 2-way-sync(5)? Are *all* starred/favorite folders synced on starting app(5)? Or just those folders which are *currently visible*(6,7)? What is the difference between  6 and 7?

Are you aware of https://github.com/owncloud/android/pull/1109? As I understand it is already about syncing folders.If it really keeps folders synced at all times, I like the sync icon. (I never understood what the star is all about anyways.)

**Comment by jancborchardt** [comment]
Right, good point by @AndyScherzinger:

> the sync icon might (at least by me without any explanation) be interpreted as a sync is running on these folder(s)

Sure in the web interface the star means favoriting, but in the desktop app the circular sync arrows mean that a sync is running and the file _isn’t_ synced yet. Exactly the opposite of what this would do.

**Comment by tobiasKaminsky** [comment]
According to "accounts" in android setting a static circular symbol means, that a sync is possible (and started by clicking on it) and a spinning symbol means that a sync is in progress.
Maybe this will also work for us?

**Comment by jancborchardt** [comment]
Our design language (and that of Dropbox and other players of course) uses the circular arrow as »file about to be synced« though. @owncloud/designers any ideas? We could use a new »pinned« metaphor like Google Drive does …

**Comment by LukeOwncloud** [comment]
How about adding a new overlay icon (top left, e.g.) using the default icons? Green circle with white checkmark: synced/up-to-date, blue sync: about to sync, red: sync failed.

**Comment by davivel** [comment]
> the sync icon might (at least by me without any explanation) be interpreted as a sync is running on these folder(s)

Totally agree. 

> How about adding a new overlay icon (top left, e.g.) using the default icons?

I don't think  we need a third overlay icon. I'd use two, as right now: one to show the current *sync state* of the file (sync'ing, downloading, uploading, synced/down, ...) , and the other to show how the user wants that it's sync'ed (kept-in-sync or 'regular'). Let me open a separate issue to discuss about the icon(s), I think it's important they are well balanced.

@LukeOwncloud , about your doubts:
(5) Yes, two-way-sync.
(6,7). The rule is "sync the *contents* of all the kept-in-sync files in the current (visible) folder" ; to allow folders to be kept-in-sync, we need to define the *content of a folder*; let it be *all the contents of its descendents* .
When the app is started, the current folder is root. If a folder in the second level of depth is set to be kept-in-sync, it will not be sync'ed just opening the app.
The difference between (6) and (7) is the event triggering the synchronization. But the synchronization is the same.

**Comment by davivel** [comment]
Sorry for the delay. I opened #1218 to discuss the details about the icon.

**Comment by helmo** [comment]
I noticed that the bounty on #3 - https://www.bountysource.com/issues/541847-two-way-file-sync-for-specific-folders-or-files/backers is still open. 
Should we try to get it moved here?

I tried testing this using the current beta and found that when I edit a file on android that was downloaded via owncloud it uploads the changed file. But a new file created under an existing directory downloaded by owncloud is not uploaded.

**Comment by rperezb** [comment]
@helmo we plan to work within the synced folder feature soon.
cc @MTRichards 

anyhow, about "But a new file created under an existing directory downloaded by owncloud is not uploaded." any new file that you upload using the Android app *has* to be uploaded to the server, if this is not working, please, open a new issue with further details

**Comment by tobiasKaminsky** [comment]
There is no folder observer that monitors if a new file is created and upload it.

**Comment by rperezb** [comment]
@tobiasKaminsky i see, @helmo is talking creating it from the files browser instead of from the app itself
ok, different topic, so

**Comment by helmo** [comment]
Thanks @rperezb @tobiasKaminsky ... I've create a separate issue under #1663

**Comment by rperezb** [comment]
Related to: https://github.com/owncloud/enterprise/issues/435

**Comment by jknockaert** [comment]
I am not sure why the scope of this PR is limited to two-way sync. There's a clear use for one-way sync as well, as I have been arguing before: https://github.com/owncloud/android/issues/3#issuecomment-129753448

**Comment by davivel** [comment]
@jknockaert, the use case you describe is just a different one. If you want to discuss the details about it, I'd suggest you open a specific issue for it.

**Comment by davivel** [comment]
Resuming work here where @jabarros left it.

**Comment by davivel** [comment]
Added some tasks, this is not ready to go yet.

**Comment by davivel** [comment]
Back here

**Comment by davivel** [comment]
I'm very sorry to say this will have to go to be delayed one release. See some details inhttps://github.com/owncloud/android/issues/1750#issuecomment-236118517

**Comment by davivel** [comment]
To be clear: this is blocked waiting for #6 is, at least, developed.

**Comment by rosencreuz** [comment]
I have a directory with 1K+ subdirectories and with 500 GB+ files. I guess my phone is trying to check if anything is changed or not all the time. It would be nice if I could mark this directory as "ignored". Would this issue add such functionality?

**Comment by llucax** [comment]
> It would be nice if I could mark this directory as "ignored".

See https://github.com/owncloud/android/issues/1644 and https://github.com/owncloud/android/issues/960

**Comment by tomatac** [comment]
Is this feature being developed?

**Comment by davivel** [comment]
Yes, we blocked it for a while due to an expected overlap with the solution for instant uploads in Android 7. We'll effectively resume the work on av-off folders next Monday.

It's one of the main features for version 2.2.0, should have no more delays.

**Comment by davivel** [comment]
Updated first comments with pending tasks. Working on them.

**Comment by davivel** [comment]
@jesmrec , ready to test.

**Comment by jesmrec** [comment]
### Bug

Steps

1. Set a folder as av. offline
2. Browse into a folder
3. Pull down to refresh

Current Behaviour

The folder lost the av. offline and browses back to the parent folder. A toast message appears: `Folder xxxx does not exist anymore`

Expected behaviour

After pulling down, the content is updated if necessary. If not, nothing happens.

Tested with Galaxy Note 4 v6, Nexus9 v6, MotoE v4.4.4

Server 9.1.2.

CC @davivel

**Comment by jesmrec** [comment]
### Bug

Steps

1. Set a folder with at least two deep levels (a/b/c) as av. offline
2. Browse into the folder 'c' 
3. Browse back to 'b'

Current Behaviour

The folder structure lost the av.offline. A toast message appears: `Folder /a does not exist anymore`

Expected behaviour

Nothing happens.

Tested with Galaxy Note 4 v6, Nexus9 v6, MotoE v4.4.4

Server 9.1.2.

CC @davivel

**Comment by jesmrec** [comment]
### Bug

Steps

1. Set a folder as av. offline.
2. While the content is being downloaded, cancel it.

Current Behaviour

The folder keeps on being av. offline and is tried to be updated when browsing.

Expected behaviour

The folder is not av. offline anymore. The content downloaded until the cancelling remains downloaded.

Tested with Galaxy Note 4 v6, Nexus9 v6, MotoE v4.4.4

Server 9.1.2.

CC @davivel

**Comment by jesmrec** [comment]
### Improvement

If one or several av. offline folders are selected, the option "Synchronize" is not needed. It appears always as icon in the action bar and in that case, it is useless.

**Comment by jesmrec** [comment]
### Bug

Set as av. offline a shared folder (no matter if it is shared with users/groups or by link)

Current behaviour

Folder does not show the shared icon, only the av. offline icon

Expected behaviour

Folder shows both icons: shared and av. offline

Tested with Galaxy Note 4 v6, Nexus9 v6, MotoE v4.4.4

Server 9.1.2.

CC @davivel

**Comment by jesmrec** [comment]
### Improvement (or feature... who knows)

Steps

1. User1 shares a folder in root with User2, without edit permission.
2. User2 set the shared folder as av. offline.
3. User2 edit a txt file that is into the shared folder

Current behaviour

The file is upload unsuccessfully, due to a lack of permissions. Each time the root folder is displayed  (after switching account, browsing or open the app), the updated file is retried to be uploaded, so the uploads view is flooded of failed tries, all of them of the same file.

Expected behaviour

iOS only shows the error once in uploads view. Suitable for Android?? 

Tested with Galaxy Note 4 v6

Server 9.1.2.

**Comment by davivel** [comment]
About: https://github.com/owncloud/android/issues/1136#issuecomment-260294672

We need to discuss the expectations here. What is being cancelled is not the process of setting the folder as available offline, but the first synchronization after doing it. Maybe we need to clarify it in some way, or maybe not allow to cancel the synchronization of available offline folders?

**Comment by davivel** [comment]
About: https://github.com/owncloud/android/issues/1136#issuecomment-260313481

I'm not sure it's fully useless. A user could want to be sure that the folder is sync'ed even if the folder is marked as available offline. Also, in cases where file observers fail to detect local changes, it's also a tool for the user works around the problem (reminder: Android 6 has bugs in file observation).

In any case, I understand these uses are corner-cases. Hiding the action is easy, we could consider it.

**Comment by jesmrec** [comment]
>About: #1136 (comment)

>We need to discuss the expectations here. What is being cancelled is not the process of setting the >folder as available offline, but the first synchronization after doing it. Maybe we need to clarify it in >some way, or maybe not allow to cancel the synchronization of available offline folders?

So, the point is if the cancellation also removes the "av. offline" condition or not. IMHO, if the user cancels the sync process is because he does not want this folder to be synced. If the cancelled folder is in the root, when the user browses, switches the account and back, closes the app and reopens it... this folder starts again to sync. The "stop sync" status (av offline folder but not synced due to the cancelling) seems to be difficult to stay, so you can not perform any action if you want to prevent the synchronization.

**Comment by jesmrec** [comment]
>About: #1136 (comment)

>I'm not sure it's fully useless. A user could want to be sure that the folder is sync'ed even if the >folder is marked as available offline. Also, in cases where file observers fail to detect local changes, >it's also a tool for the user works around the problem (reminder: Android 6 has bugs in file >observation).

You are right, we could stay the option to prevent file observation problems.

**Comment by jesmrec** [comment]
### Bug

Steps

1. Set a folder as av offline
2. When it is fully synced, unset it as av offline

Current behaviour

In toolbar/menu, is displayed the "Unset as av. offline" option

Expected behaviour

In toolbar/menu, is displayed the "Set as av. offline" option

**Comment by jesmrec** [comment]
###Bug

Steps

1. Login in a redirect server
2. Set a folder as av. offline
3. Try to sync the folder, or refresh manually 

Current behaviour

Message `Synchronization of folder could not be completed`

Actual behaviour

Folder is tried to be synced with no errors

Tested with Galaxy Note 4 v6, Galaxy Nexus 9 v6

Server 8.2.2

**Comment by davivel** [comment]
> So, the point is if the cancellation also removes the "av. offline" condition or not. IMHO, if the user cancels the sync process is because he does not want this folder to be synced. If the cancelled folder is in the root, when the user browses, switches the account and back, closes the app and reopens it... this folder starts again to sync. The "stop sync" status (av offline folder but not synced due to the cancelling) seems to be difficult to stay, so you can not perform (almost) any action if you want to prevent the synchronization.

How does this work in iOS?

**Comment by jesmrec** [comment]
@davivel in iOS you can cancel the process and the folder becomes not av. offline. 

> EDITED: besides, if the user really does not want the folder to be synced, can't we expect that she unsets the folder as available offline right after cancelling the synchronization? What would be a real use case of this? "I set up the wrong folder as available offline and I want to fix it before all the folder tree is sync'ed?"

unsetting the folder as av. offline after cancelling is another valid possibility, that cover the real case you mentioned as well. 

The real case i was thinking about is this one:

1. I set a folder as av. offline
2. I cancel the process (whatever the reason, i don't want the folder synced **right now**. But later, i want it synced)

From that moment:

- If i close the app and open it again -> the folder will sync automatically 
- If i browse through the parent folder -> the folder will sync automatically
- If i switch to another account and then, switch the the folder's account again -> the folder will sync automatically (in this case, only if the av. offline folder is in root)
- If i have the account synced in device settings -> the folder will sync automatically 

I mean, if you set a folder as av. offline but you don't sync it (by cancelling and staying it as av. offline), it's very probably that this folder will sync in a short time itself. If you cancelled, perhaps you don't want that.

If the solution is unsetting as av. offline using the menu option, we can take advantage and do it automatically, if it is possible.

More thoughts are welcome, @nasli @rperezb

**Comment by davivel** [comment]
As agreed offline: let's replace in the action bar the action 'cancel' with 'unset as available offline', making it also cancels the synchronization if it's in progress.

**Comment by davivel** [comment]
Extra BUG discovered while fixing "the last one" : 

1. Set a folder as available offline in the device; the folder should have a tree with at least 2 levels of extra depth inside.
2. In web UI, add a new file deep down the tree of the available offline folder.
3. Refresh the parent folder of the available offline folder.

EXPECTED BEHAVIOUR
1. The new file is downloaded automatically

CURRENT BEHAVIOUR
1. The new file is not downloaded (logs show that it's discovered, but not downloaded in the same moment).

**Comment by davivel** [comment]
@jesmrec , as said offline, all known bugs are ready to be tested.

**Comment by jesmrec** [comment]
@davivel 

Related to https://github.com/owncloud/android/issues/1136#issuecomment-260334941 

The problem is fixed (the upload is not retried forever), but right now, it appears twice in the uploads view. Could it be prevented? (only one appearance on the failed upload)

**Comment by davivel** [comment]
I'll review it, though I might need your help to reproduce it.

**Comment by jesmrec** [comment]
Approved

Nice feature already available!!! great job @davivel :)

**Comment by davivel** [comment]
Really to go with next release. 

Congrats, team.

**Comment by twixi** [comment]
Very need full sync from Server to phone
