### ISSUE TITLE
[2] Release of the new version

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#1489]
#### AC:
- [x] create release branches (app & library)
- [x] Freeze the code 
- [x] Regression test plan 
- [x] Regression test validation

Bugs found:
- [x] Crash after some actions with navigation drawer and FAB #1578
- [x] App crashes when a link is copied (Av4.3) #1579   
- [x] Minor improvements in FAB #1581 
- [x] Uploads from Google Drive #1607 [WONTFIX]
- [x] If password not enforced, error message not found #1608 
- [x] Move photos does not remove the origin #1610 
- [x] Favorites need refresh to show the yellow star #1611
- [x] Syncronizing conflict are not well solved if "Keep Both" is chosen #1612
- [x] When a file is downloading, progress bar and badget are not  shown #1613
- [x] Users/groups to share are not correctly displayed in search view #1614
- [x] Can edit can be enabled when it should not #1615 
- [x]  External app can not upload is passcode is set  #1616

Let it go:
- [ ] Release of the new version

**Comment by davivel** [comment]
Version 1.9.2 becomes version 2. :tada:

**Comment by jesmrec** [comment]
The changes for new version are important, so that it is deserved a higher upload in version number

**Comment by AndyScherzinger** [comment]
Can we than have v2.1 with the new drawer and some of @tobiasKaminsky's PRs :grimacing: 

v2.0.0 is awesome! :tada:

**Comment by rperezb** [comment]
:clap: :new:

**Comment by davivel** [comment]
> Can we than have v2.1 with the new drawer and some of @tobiasKaminsky's PRs :grimacing:

Sure we can, but we don't know when :grimacing:

**Comment by rperezb** [comment]
let's make public the uploads view...and then, keep walking!
JFYI, we do really want to include the multiple selection one https://github.com/owncloud/android/pull/1176 among others

**Comment by AndyScherzinger** [comment]
Sweet, #1176 is quite stable besides the documented issues that need to be resolved.

**Comment by davivel** [comment]
@all, right now all the previously found regressions are fixed.  

Nevertheless, actual regression testing on this branch needs to wait until #1514 is in.

**Comment by davivel** [comment]
Branch release-2 frozen. Let the testing begin :)

**Comment by jesmrec** [comment]
Let's go. I will update the first message

**Comment by davivel** [comment]
Getting there. :popcorn:

**Comment by jesmrec** [comment]
Approved 

Hoping that everybody enjoy the new version :)

**Comment by enoch85** [comment]
Wohoow!

**Comment by davivel** [comment]
Tomorrow will be the day :)

**Comment by enoch85** [comment]
Great work guys!!

**Comment by AndyScherzinger** [comment]
Awesome! And it is already visible in the Google play store :) :tada:

**Comment by davivel** [comment]
It is :)

Thank you all @owncloud/android-developers, contributors, reporters, commenters, wanderers and people searching another repo. This is a great release, and it is so thanks to all of you.
