### ISSUE TITLE
Show Full Name instead of user logged in

### ISSUE THREAD

**Issue by gig13** [owncloud/android#1639]
#Show the user name instead user logged in
Presently It is showing the logged in user instead of the user name

SF 00005346

I will get clarifications from end-users on Full Name/user Name so we are all speaking about the same thing.

TASKS:

- Important: read: https://github.com/owncloud/android/issues/1639#issuecomment-222478088
- [x] Get display name when account is created   @davivel
- [x] Show display name in account selector  @davivel
- [x] Show display name in navigation drawer @davivel
- [x] Update stored display name whenever roof folder of the account is refreshed @davivel
- [x] code review of #1709 and owncloud/android-library#125
- [x] QA create test plan of #1709 @jesmrec
- [x] show full name in uploads view @davivel
- [x] show full name in account selector shown in ReceiveFilesActivity @davivel
- [x] QA validation of #1709 @jesmrec

____

BUGS & IMPROVEMENTS

- [X] Port or no port? https://github.com/owncloud/android/issues/1639#issuecomment-226236722 [FIXED]
- [X] Upgrade https://github.com/owncloud/android/issues/1639#issuecomment-226238742 [FIXED]

@MTRichards @MorrisJobke

**Comment by gig13** [comment]
End-User feedback:
It would be better if the Android app shows up the Full Name just like the web application.

**Comment by LukeOwncloud** [comment]
We are talking about the name in the side drawer, right?
I would even like to see the server, so maybe: `fullname@server`.
Having same user name (with same full name) at two servers, showing just the name is ambiguous.

**Comment by AndyScherzinger** [comment]
@LukeOwncloud you do see the server as soon as my PR gets merged :tada: 
--> see screenshot https://github.com/owncloud/android/pull/1559#issuecomment-206977678

**Comment by AndyScherzinger** [comment]
Is the full name unique on a server? Else you could end up with to exact same user entries because they use the same full name but have different usernames. Probably an edge case but still weird.

**Comment by jesmrec** [comment]
@AndyScherzinger it is not unique. In order to show it on the drawer, only would affect if a person has two accounts in the same server, and both of them has the same full name (absurd).

**Comment by AndyScherzinger** [comment]
@jesmrec yes I am aware of that, that is why I declared it an edge case :grin: Technically still possible. @davivel any idea/plan how to proceed with this since the account object doesn't contain this information?

**Comment by tobiasKaminsky** [comment]
I do not think that the use case that both accounts have the same name is too uncommon.
At least for me I have a private cloud with my full name and a cloud from my work, also with the full name.
So with this issue I can not decide which account I use?

**Comment by AndyScherzinger** [comment]
Imho you do since the idea afaik is too also always display the server. My point was that a full name isn't unique on one server and thus I could create two users with the same full name which then could not be distinguished.

**Comment by tobiasKaminsky** [comment]
Ah, ok. Then I misunderstood.
Two users with the same full name is possible and no problem as you can always use the username?

**Comment by LukeOwncloud** [comment]
Considering the screenshots @AndyScherzinger linked, I'd say: Use the full name just once at very top (in bold letters). Everywhere else use user@server (as shown in screenshots).

**Comment by AndyScherzinger** [comment]
That's fine in my opinion but would require a change since the full name isn't available right now. 
Should be open a new ticket for that @rperezb @davivel or is this one enough for the full name discussion?

**Comment by gig13** [comment]
@bboule @PVince81 @rperezb @MTRichards 
Can we get this tagged for a version?

**Comment by rperezb** [comment]
@gig13 , I'd move this one for the following version, we are about to release, Android 2.2.1, this issue will be included within the next one.

For this request, we will take advantage of @AndyScherzinger 's pr, can you have a look at: https://github.com/owncloud/android/pull/1559

Here, for the moment, if I am not wrong, @AndyScherzinger is not using the full name, I'd go with @LukeOwncloud suggestion

>  I'd say: Use the full name just once at very top (in bold letters). Everywhere else use user@server (as shown in screenshots).

https://github.com/owncloud/android/pull/1559#issuecomment-206977678

will this work?

**Comment by rperezb** [comment]
Certainly, we have to consider whether we want to propagate this change to the other clients (iOS and Android)

I'd say so

**Comment by davivel** [comment]
Besides the changes in UI, we need to retrieve the 'display_name' field from the server for every created account and store it locally. And later keep it sync'ed, since the user can edit it - minimally, getting it on app start-up or when the root folder is refreshed should be good enough.

This will need a new operation in the owncloud/android-library , in the package resources/users ; and changes in the app to store it.

And will reopen the discussion about keep adding user / account properties to the AccountManager, or do it in a new table in the app-owned database. Calling @przybylski FYI.

I would create a separate PR for this, independent of PR #1559.

**Comment by AndyScherzinger** [comment]
I second @davivel's approach :+1: 
@rperezb see also @davivel's comment, the full name isn't available right now in the client and this can be separated from the general drawer discussion. Besides please be also aware of the known issue with the new drawer implementation: #1657 - for some reason the account switching does's seem to work on older Android versions as reported by @LukeOwncloud but I couldn't

**Comment by rperezb** [comment]
right, let's keep them as individual issues; as they are currently.
Having in mind @gig13 comment, lets include the full name within the next version

**Comment by davivel** [comment]
Ey, good news. This will be a bit easier. The only operation in owncloud/android-library , in the package resources/users is already reading the full name (at least the property read from the OCS API is called "display_name", I still didn't test it).

The point is, right now that operation is only called when the server requires Shibboleth authentication. We should just use it with any kind of authentication method to get it in the app. Profit!

We'll have to store it appropriately in any case, the Shibboleth flow saves it instead of the username (it doesn't need it), but that approach is not valid for basic auth, we need to save both username and display_name separately for it.

**Comment by rperezb** [comment]
great @davivel !
We have also to define when we will be checking whether the display_name is updated in the server side to update it accordingly on the app

**Comment by davivel** [comment]
Work in progress in branches 1639_show_display_name_instead_of_login_name in ownCloud/android and ownCloud/android-library repositories.

**Comment by davivel** [comment]
Pushed an update in branches mentioned before. Also created PRs https://github.com/owncloud/android/pull/1709 and https://github.com/owncloud/android-library/pull/125 as work in progress. Comments and additions from anybody @owncloud/android-developers are welcome :) 

Will go on with this tomorrow.

**Comment by davivel** [comment]
Back here... wip

**Comment by davivel** [comment]
Ready to go, @rperezb .

**Comment by rperezb** [comment]
amazing!
@michaelstingl this is interesting for you, it will be included within 2.1.0 version

**Comment by davivel** [comment]
Reopening to add a couple of details; will be fast

**Comment by davivel** [comment]
OK, ready again.

cc @jesmrec

**Comment by jesmrec** [comment]
### Bug 

### Steps to reproduce

1. Install a previous version of the app (for example, `master` branch)
2. Login in accounts
3. Upgrade to this branch

### Actual behaviour

Display name appears as "null". It is needed to browse into the account to the display name to be displayed both in settings view and drawer

### Expected behaviour

Display name is shown when the upgrade is completed.,

Tested with Nexus5 v5.0.1

**Comment by davivel** [comment]
> @davivel @AndyScherzinger question: with the new set up, the port does not appear next to the server name. Perhaps it is not really a very useful info, but we can take in account the case that more than one servers run on the same host (real or virtual).

That's an easy fix. Let me see.

Going for the bug too.

**Comment by davivel** [comment]
@jesmrec , both fixed now.

**Comment by jesmrec** [comment]
both fixed 👍   and approved

@davivel @AndyScherzinger

**Comment by davivel** [comment]
Ready to go.
