### ISSUE TITLE
Updating Sync Capabilities on Mobile

### ISSUE THREAD

**Issue by MTRichards** [owncloud/android#1677]
As an ownCloud user, I want to sync files to my mobile devices automatically so that I can have always the latest files available on my mobile platform

Acceptance Criteria:
-   Current “not granted offline” continues as currently implemented in iOS (tap on a file downloads, tap again downloads latest, changes are uploaded to server if found)
-   Current “not granted offline” in Android needs to be updated to meet user expectations:
-    [x] tap on a file downloads
- [x] tap again downloads latest #333
- [ ] local changes are uploaded to server if found, without user interaction #1683 
-   Current favorite functionality is renamed available offline
-   The available offline overlay icon is a download arrow with a bar underneath
-   Mobile sync error status is changed to red circle x from desktop
-   Successfully synced files are shown with a green check mark from desktop
-   Syncing files are shown with a circular blue arrow from desktop
-   File transfers in process are the same circular blue arrows from desktop

Android
- [x] Badges and changing current favorites to sync folder https://github.com/owncloud/android/issues/1218
- [x] Automated Sync Folder https://github.com/owncloud/android/issues/1136

iOS
- [x] Badges and changing current favorites to sync folder https://github.com/owncloud/ios/issues/463

**Comment by davivel** [comment]
Edited first comment to clarify pending changes

**Comment by Paviluf** [comment]
Great to see improvement on Sync Capabilities !
Can this https://github.com/owncloud/android/issues/1437 be improve too please ?

Thanks !

**Comment by moscicki** [comment]
If a directory on mobile device is requested to be kept in sync with the server would that require regular polling and scanning of local mobile filesystem? What about the battery usage of mobile devices in this case? Is there an OS-provided mechanism to do it efficiently?

**Comment by helmo** [comment]
@moscicki Linux has inotify for that, which android uses as [FileObserver](https://developer.android.com/reference/android/os/FileObserver.html)

**Comment by moscicki** [comment]
@helmo: what are the practical limits on Android for inotify? How many filesystem objects can one process watch?

**Comment by helmo** [comment]
@moscicki I'm not sure

**Comment by davivel** [comment]
@moscicki , @helmo, these questions would be better placed in #1136 and / or #6. 

And they are very good questions. Our current implementations of files being kept in sync extends  [FileObserver](https://developer.android.com/reference/android/os/FileObserver.html) in the class [FolderObserver](https://github.com/owncloud/android/blob/master/src/com/owncloud/android/services/observer/FolderObserver.java). If I recall correctly, this is able to detect changes in all the subtree pending of the observed folder, so the total number of FileObserver shouldn't be a big deal, in theory.

There are other improvements we could address to control battery consumption (such as separating observation to detect a change from uploading that change) , and other problems / uncertainties that may affect the observers (they need to be kept watching indefinitely; the system might not like that). We'll talk about all this in more detail soon.

**Comment by davivel** [comment]
@moscicki , @Paviluf , @helmo , if you really want this get attention, **take the chance of voting for it  in https://github.com/owncloud/core/issues/24684#issuecomment-220038870 . Let us see your hearts there!**

**Comment by davivel** [comment]
Marked checkbox for #333, already merged, to be released soon: #1750

**Comment by davivel** [comment]
Marked checkboxes for #1136 and owncloud/ios#463 , both of them released.

**Comment by davivel** [comment]
Sorry, but we need to drop issues from milestone 2.4.0 to get it out next to OC 10 server.

This time we'll move topics to ```backlog``` instead of directly to next release, so that we can schedule 2.5.0 properly.

In this case, since there is a single independent issue pending to finish, I will label that and close this one.
