### ISSUE TITLE
[2.0.1] Release new version

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#1686]
#### AC:

- [x] [GIT] Create branch release_0.9.12 in owncloud/android-library from master (feature-frozen) @malkomich
- [x] [GIT] Create branch release_2.0.1 in owncloud/android from master (feature-frozen) @malkomich
- [x] [DEV] Update version number and name in AndroidManifest.xml in android module @malkomich
- [x] [DEV] Update version number and name in AndroidManifest.xml in oc_jb_workaround module @malkomich
- [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android @malkomich @davivel
- [x] [DIS] Take relevant screenshot to update in stores, if any @davivel
- [x] [QA] Regression Test plan  @jesmrec
- [x] [GIT] Merge branch release_0.9.12 in owncloud/android-library, into stable @davivel
- [x] [GIT] Merge branch release_2.0.1 in owncloud/android, into stable @davivel
- [x] [DEV] Update official build environments to operate with Gradle instead of ant  @davivel
- [x] [DIS] Generate **test** APKs and BAR files from branch stable in owncloud/android, in official build environment @davivel
- [x] [GIT] Create and sign tag oc-android-library-0.9.12 in HEAD commit of stable branch, in owncloud/android-library @davivel
- [x] [GIT] Create and sign tag oc-android-2.0.1 in HEAD commit of stable branch, in owncloud/android @davivel
- [x] [DIS] Generate **final** APKs and BAR files from branch stable in owncloud/android, in official build environment @davivel
- [x] [DIS] Upload & publish release APK and changelog in Play Store @davivel
- [x] [DIS] Update screenshots and store listing, if needed, in Play Store @davivel
- [x] [DIS] Upload & publish release BAR and changelog in Blackberry World @davivel
- [x] [DIS] Update screenshots and store listing, if needed, in Blackberry World @davivel
- [x] [GIT] merge stable branch into master, in owncloud/android-library @davivel
- [x] [GIT] merge stable branch in master, in owncloud/android @davivel
- [x] [DIS] push OC JB workaround app to Play Store @davivel 

REGRESSION BUGS FOUND:
- [x] Conflicts resolved changing orientation https://github.com/owncloud/android/issues/1686#issuecomment-222476227 @malkomich [FIXED]
- [x] Available offline removed locally https://github.com/owncloud/android/issues/1686#issuecomment-223558744 @malkomich [FIXED]
- [X] Renaming in server loses the av offline in device https://github.com/owncloud/android/issues/1686#issuecomment-223941858 -> https://github.com/owncloud/android/issues/1703
- [X] Allow editing is disabled when other switches change https://github.com/owncloud/android/issues/1686#issuecomment-223948028 @davivel [FIXED]

NOTE:
- Internal Check issue206

BRANDING CHANGES
- Login text color https://github.com/owncloud/android/blob/master/res/values/setup.xml#L32
- Login text color hint https://github.com/owncloud/android/blob/master/res/values/setup.xml#L33
- Logger https://github.com/owncloud/android/blob/master/res/values/setup.xml#L56

**Comment by jesmrec** [comment]
### Bug

## Steps to reproduce

1.- Set a txt file as "available offline"
2.- Enable the airplane mode in the device
3.- Modify the txt both in device and server
4.- Disable the airplane mode
5.- Pull down to refresh -> conflict is detected
6.- Change orientation of the device

## Actual behaviour

Conflict is solved magically

## Expected behaviour

Conflict remains until the user decides what to do, whatever action that he/she performs

Tested with HTC One v4.3, Samsung Galaxy Note4 v5

**Comment by malkomich** [comment]
@jesmrec https://github.com/owncloud/android/issues/1686#issuecomment-222476227 Fixed :)

**Comment by jesmrec** [comment]
## Bug

### Steps to reproduce

1.- Set a file as "available offline"
2.- Remove locally the file

### Actual behaviour

File is locally removed. In this case, if the device lost the connection will not be downloaded and will not be available offline

### Expected behaviour

File can not be locally deleted if it is "Available offline"

Tested with HTC One v4.3, Nexus5

**Comment by jesmrec** [comment]
## Bug

### Steps to reproduce

1.- Set a file as "available offline"
2.- In server or in another client, rename the file

### Actual behaviour

File is not available offline

### Expected behaviour

File keeps on being available offline

Tested with Nexus7 v4.3, Nexus5 v5.0.1

**Comment by jesmrec** [comment]
## Bug

### Steps to reproduce

1.- Share a folder by link
2.- Enable "Allow Editing" option
3.- Enable Password Protect/Expiration Date

### Actual behaviour

"Allow Editing" is disabled. Any change in "Password Protect"/"Expiration Date" switch "Allow editing" if it is enabled.

### Expected behaviour

"Allow editing" is enabled 

File keeps on being available offline

Tested with Nexus7 v4.3, Nexus5 v5.0.1
Server v9.0.2

**Comment by johnripper1** [comment]
Are all these potential bug reports showstoppers for a minor bugfix release?

I mean people are waiting for bugfixing for some major errors that came with 2.0.0 and that broke some core features.

Instead of quickly hot fixing these new errors community makes a long term release for potential bug that are unclear to be one.

**Comment by jesmrec** [comment]
@johnripper1 
The bugs that will be fixed in the new version are already fixed and validated. A new version always leads regression tests to assure the quality of the whole app to avoid new bug fixing versions. Anyway, the new version is close to be released.

**Comment by davivel** [comment]
@jesmrec , about "Renaming in server loses av offlin" in https://github.com/owncloud/android/issues/1686#issuecomment-223941858 ; this is not a regression, I think we should open a new issue and deal with it in future releases.

**Comment by jesmrec** [comment]
@davivel. Opened in https://github.com/owncloud/android/issues/1703. Closed for the current version.

**Comment by davivel** [comment]
The other one https://github.com/owncloud/android/issues/1686#issuecomment-223948028 is not a regression either, but probably it's an easy fix. I'll have a look

**Comment by davivel** [comment]
@jesmrec ,https://github.com/owncloud/android/issues/1686#issuecomment-223948028 is fixed now in release_2.0.1.

**Comment by jesmrec** [comment]
Fixed the bug, and finished the validation

**Comment by davivel** [comment]
Dammit, changelog is not in place... :/

**Comment by davivel** [comment]
And now it's DONE

**Comment by johnripper1** [comment]
It' already in the Play Store. Updates already.

@all: Thank you very much, good Job!
