### ISSUE TITLE
Client does not recognize maintenance mode

### ISSUE THREAD

**Issue by dercorn** [owncloud/android#1722]
### Steps to reproduce
1. Switch ownCloud server into maintenance mode
### Expected behaviour

The Android client should inform the user that the server currently in maintenance mode or unreachable.
### Actual behaviour

The client shows no message and displays folders as empty
### Affected software versions

All

 
### Tell us what could be improved:

Have the client display a notification when the server is unavailable (HTTP 503)

____

BUGS & IMPROVEMENTS

- [X] Error in uploads view https://github.com/owncloud/android/issues/1722#issuecomment-269292313 @davigonz [FIXED] @jesmrec
- [X] Share with users does not show error https://github.com/owncloud/android/issues/1722#issuecomment-269295600 @davigonz [FIXED] @jesmrec
- [X] Shibboleth server does not recognize maintenance mode https://github.com/owncloud/android/issues/1722#issuecomment-269300730 @davigonz [FIXED] @jesmrec
- [X] Unsharing in maintenance mode removes the file https://github.com/owncloud/android/issues/1722#issuecomment-269603786 @davigonz [FIXED] @jesmrec

**Comment by davivel** [comment]
Related: https://github.com/owncloud/ios/issues/714

**Comment by cdamken** [comment]
[00005749](https://na25.salesforce.com/5003100000cobm7)

**Comment by cdamken** [comment]
@davivel could you assign a milestone?

**Comment by dercorn** [comment]
@davivel , after talking to @felixboehm , we agreed that this is clearly a bug and not an enhancement. Although this should cause no serious trouble, it would be extremely nice to see this resolved in the next release.

**Comment by davivel** [comment]
In the case of Android, the next release 2.2.0 needs to be focused in granting operation with Android Nougat. There are quite important bugs coming there.  Maybe we can sneak this in, but I wouldn't bet too high for it.

Release 2.3.0 should not be a problem.

**Comment by dercorn** [comment]
@davivel So, please set the milestone to 2.3.0

**Comment by dercorn** [comment]
excellent!

**Comment by jesmrec** [comment]
### Improvement

In a server in maintenance mode, upload  a file. 

In uploads view is shown `Unknown error`

The message in this case could be clearer, so the cause of the error is known.

**Comment by jesmrec** [comment]
### Bug

Steps

1. In a server in maintenance mode, share  a file/folder with user/group
2. Type a user

Current behaviour

Toast message is empty

Expected behaviour

Correct message error is shown. The error could be displayed (one is enough):
- When the share view is displayed
- When the user taps on "Add user or group"
- When the user types username in search view

Server 9.1.3
Tested with Huawei 6P v7.0

CC @davigonz

**Comment by jesmrec** [comment]
In a shibboleth server with maintenance mode enabled:

Input the server URL -> accepted (should it?)
Webview is shown and credentials can be input
The following error is shown:

`The server does not return a correct user ID`

Could be prevented the login action in this case?

Device: Huawei 6P v7
Server 9.1.3

CC @davigonz

**Comment by jesmrec** [comment]
It is happening the same as in this issue -> https://github.com/owncloud/android/issues/1856

With maintenance mode, the black screen stays.

**Comment by jesmrec** [comment]
### Bug 

Steps

1. Share a file/folder with users or by link
2. Set maintenance mode
3. Unshare the file/folder
4. Return to file list

Current behaviour

The file/folder disappears from list

Expected behaviour

The file is still shared and appears in the file list

Tested with Nexus9 v6, Huawei 6P v7.0
Server 9.1.3

CC @davigonz

**Comment by jesmrec** [comment]
All bugs fixed. Approved.

CC @davigonz @davivel

**Comment by jesmrec** [comment]
New QA needed after the code review. WIP.

**Comment by jesmrec** [comment]
QA passed. Approved again

**Comment by davivel** [comment]
Merged, ready to go in next release, 2.3.0
