### ISSUE TITLE
[2.1.0] Release new version 

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#1750]
#### AC:

- [x] [GIT] Create branch release_x.x in owncloud/android-library from master (feature-frozen) 
- [x] [GIT] Create branch release_2.1.0 in owncloud/android from master (feature-frozen) 
- [x] [DEV] Update version number and name in AndroidManifest.xml in android module 
- [x] [DEV] Update version number and name in AndroidManifest.xml in oc_jb_workaround module 
- [X] [DEV] Update the login icons to the ownCloud community one  @davivel
- [X] [DEV] Update copyright mentions in code #1751 @davivel
- [X]  [DEV] Scale up OC icon (remove transparent borders) @davivel
- [X] [DEV] Update workaround app icon, according to style of new main app icon @davivel
- [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android @davivel
- [X] [DEV] Update build setup to check for presence of icons in new paths (mipmap) @davivel
- [X] [DIS] Take relevant screenshot to update in stores, if any @davivel
- [X] [QA] Design Test plan  @jesmrec
- [X] [QA] Regression Test plan   @jesmrec
- [x] [GIT] Merge branch release_x in owncloud/android-library, into ~~stable~~ master @davivel
- [x] [GIT] Merge branch release_2.1.0 in owncloud/android, into ~~stable~~ master @davivel
- [x] ~~[DEV] Update official build environments to operate with Gradle instead of ant~~ not again :)  
- [x] [DIS] Generate **test** APKs and BAR files from branch ~~stable~~ master in owncloud/android, in official build environment 
- [x] [GIT] Create and sign tag oc-android-library-x.x. in HEAD commit of ~~stable~~ master branch, in owncloud/android-library
- [x] [GIT] Create and sign tag oc-android-2.1.0 in HEAD commit of ~~stable~~ master branch, in owncloud/android 
- [x] [DIS] Generate **final** APKs and BAR files from ~~branch stable~~ signed commit in owncloud/android, in official build environment 
- [x] [DIS] Upload & publish release APK and changelog in Play Store 
- [x] [DIS] Update screenshots and store listing, if needed, in Play Store 
- [x] [DIS] Upload & publish release BAR and changelog in Blackberry World
- [x] [DIS] Update screenshots and store listing, if needed, in Blackberry World
- [x] [GIT] merge ~~stable~~ master branch into ~~master~~ stable, in owncloud/android-library 
- [x] [GIT] merge ~~stable~~ master branch in ~~master~~ stable, in owncloud/android 
- [x] [DIS] push OC JB workaround app to Play Store 

REGRESSION BUGS & IMPROVEMENTS:

- [X] Federated share in server 8.2 https://github.com/owncloud/android/issues/1750#issuecomment-236154125 [FIXED] @davivel
- [X] Removal using multiselection https://github.com/owncloud/android/issues/1750#issuecomment-236943623 [WON'T FIX]

NO REGRESSION

- [X] Conflicts solved with two sync operations https://github.com/owncloud/android/issues/1750#issuecomment-237170538 @davivel [FIXED]

NOTE:
- Internal Check issue206  @davivel [FIXED]

BRANDING CHANGES

- Add to ownBrander new icons related to: https://github.com/owncloud/android/pull/1594
  + res/drawable-xxxhdpi/icon.png 
  + res/drawable-xxhdpi/icon.png
  + doc/icon-playstore.png
   + ref: https://github.com/owncloud/ownbrander/issues/645
- Add to ownBrander new variables within the setup.xml file https://github.com/owncloud/android/commit/699db61ff6d9abb14a1984826cfa571023c80f7f
https://github.com/owncloud/android/commit/87ec08894823cf8f9d8c60e297b7c80273294f2f
    + ref https://github.com/owncloud/ownbrander/issues/646

**Comment by davivel** [comment]
Hello, world & @owncloud/android-developers 

This release is getting quite later than what we estimated before. We'll have to reschedule some important things to have a release soon. Also, we need to focus as soon as possible on the problems we know will arise with Android Nougat, that is expected for the end of summer. See label https://github.com/owncloud/android/labels/Android_N for more details.

The most important change in the plan: available offline folders will have to go to release 2.2.0. The work in this functionality is pretty advanced, but we still need to update FileObserverService to correctly watch for local updates in any file contained in an av-off folder and its subfolders.

At the same time, the plan to keep instant uploads of pictures working in Android N implies updating the same service to watch for new pictures in the camera folder. Hence, instead of rewriting FileObserverService and friends twice, we'll face it's changes with both functions in mind. 

I will update now the milestone to leave only the issues that we can have ready to release in roughly 1 week. I'll move all the other things to milestone 2.2.0, though this might be rescheduled later, since it holds a lot of issues inherited.

**Comment by jesmrec** [comment]
### Bug

### Steps

In a server 8.2, share a folder with a user in another server

### Actual behaviour

In the file list, the folder appears as shared by link.
In the share view, the folder appears as shared by link with "Allow Editing" and "Password Protect" enabled
In the share view, the "Share with users&groups" appears empty
In server side, appears correctly in both servers

### Expected behaviour

Usual behaviour in federated sharing

Tested with Nexus5 v5.0.1, Nexus9 v6
Server that shares:
{"installed":true,"maintenance":false,"version":"8.2.6.2","versionstring":"8.2.6","edition":"Enterprise"}

In servers 9.0 and 9.1, the behaviour is correct.

**Comment by davivel** [comment]
@jesmrec , everything ready to start regression tests.

**Comment by jesmrec** [comment]
let's rock it!

**Comment by jesmrec** [comment]
### Improvement

Several files/folders are selected to be removed. During the removal of these items disables the other operations (disappearing from toolbar). It  would be nice to set an (X) option like the one that appears during syncing/downloading. Now the toolbar appears empty with the three-dot-button menu displaced.

**Comment by davivel** [comment]
Am I the only thinking that the new icon seems too small with the transparent border?
<img src="https://cloud.githubusercontent.com/assets/2225614/17334668/61b412e2-58d7-11e6-85db-6d03299cbad4.png" width="300"> <img src="https://cloud.githubusercontent.com/assets/2225614/17334669/61bf7326-58d7-11e6-8808-9a499bbeba31.png" width="300">

**Comment by davivel** [comment]
Canceling deletion in progress is not an option right now.

**Comment by jesmrec** [comment]
it is a bit smaller that the other ones. I agree that it should not have borders if it makes the icon smaller.

**Comment by AndyScherzinger** [comment]
It is a bit small, yes. Still material design spec in its size but not many apps care for the material spac when it comes to the launcher icon and the square form. So maybe make it slightly bigger even though it is not material compliant then but in this case it seems the right thing to do.

**Comment by davivel** [comment]
I had a fast look to MD specs, and couldn't find anything about the margin. Would you have a link at hand, @AndyScherzinger ?

**Comment by AndyScherzinger** [comment]
Sure: https://material.google.com/style/icons.html#icons-system-icons and scroll down to the item "
Content area" and the following sub-chapters.

**Comment by davivel** [comment]
Thanks a lot!

I would say that's not for this icon. 

> A system icon, or UI icon, symbolizes a command, file, device, or directory. System icons are also used to represent common actions like trash, print, and save.

I think we are talking here about a product icon, and its specs should be those of the previous section: https://material.google.com/style/icons.html#icons-product-icons

> Product icons are the visual expression of a brand’s products, services, and tools.

Seems both are separate sections with separate rules, and for product icons the only reference related to borders is about a 1dp edge.

That would explain why all the other apps show bigger icons, even those materialized, such as Google apps or Twitter.

**Comment by jesmrec** [comment]
### Bug (no regression)

### Steps

1. Switch the device connection off
2. Modify a txt file into a folder both in server and in mobile app
3. Switch the device connection on
4. Sync the folder that contains the file twice

### Actual behaviour

The first sync the folder and the file are marked with the conflict icon. The second sync, the conflict is solved automatically saving the device version in the server

### Expected behaviour

The conflict remains until is solved

Tested with Nexus5 v6 and Nexus7 v4.3
Server v9.1

**Comment by davivel** [comment]
Woa, that's serious...

**Comment by davivel** [comment]
Removed transparent border in icons, moved to mipmap folder and updated workaround-app icons matching new app icon.

**Comment by davivel** [comment]
So, two bugs left and we'll have a release ready. Seems promising :D

**Comment by davivel** [comment]
@jesmrec , but about remote share is now ready to test. 

I found something strange while debugging. Server 8.2 is sending info about remote shares including a ```<url>``` element that is not present in 9.x responses.

**Comment by jesmrec** [comment]
Approved. Thanks to everybody involved in this version :)
