### ISSUE TITLE
[2.1.1] Release new version

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1791]
AC:

- [x] [GIT] Create branch release_0.9.14 in owncloud/android-library from master (feature-frozen)
- [x] [GIT] Create branch release_2.1.1 in owncloud/android from master (feature-frozen)
- [x] [DEV] Update version number and name in AndroidManifest.xml in android module
- [x] [DEV] Update version number and name in AndroidManifest.xml in oc_jb_workaround module
- [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android [DRAFT] 
- [x] [DEV] Add extra logs to research https://github.com/owncloud/android/issues/1457
- [X] [DIS] Take relevant screenshot to update in stores, if any
- [X] [QA] Design Test plan @jesmrec
- [X] [QA] Regression Test plan [WIP] @jesmrec
- [x] [GIT] Merge branch release_0.9.14 in owncloud/android-library, into master [WONT] -> **nothing to merge, identical to master**
- [x] [GIT] Merge branch release_2.1.1 in owncloud/android, into master
- [x] [DEV] Update official build environments for Android platform 24 [WONT] -> delayed
- [x] [DIS] Generate test APKs and BAR files from branch master in owncloud/android ~~, in official build environment~~
- [x] [GIT] Create and sign tag oc-android-library-0.9.14. in HEAD commit of master branch, in owncloud/android-library
- [x] [GIT] Create and sign tag oc-android-2.1.1 in HEAD commit of stable master branch, in owncloud/android 
- [x] [DIS] Generate final APKs and BAR files from signed commit in owncloud/android~~, in official build environment~~
- [x] [DIS] Upload & publish release APK and changelog in Play Store
- [x] [DIS] Update screenshots and store listing, if needed, in Play Store
- [x] [DIS] Upload & publish release BAR and changelog in Blackberry World
- [x] [DIS] Update screenshots and store listing, if needed, in Blackberry World
- [x] [GIT] merge master branch into stable, in owncloud/android-library
- [x] [GIT] merge master branch into stable, in owncloud/android
- [x] [DIS] push OC JB workaround app to Play Store

REGRESSION BUGS & IMPROVEMENTS:

- [X] Change credentials in server make the app crash https://github.com/owncloud/android/issues/1791#issuecomment-243489368  [FIXED]
- [X] "Open with" option make the app crash https://github.com/owncloud/android/issues/1791#issuecomment-243501747 [FIXED]
- [X] Tapping to download make crash  https://github.com/owncloud/android/issues/1791#issuecomment-243510035 [FIXED]
- [X] Folder size of a federated share is -1 https://github.com/owncloud/android/issues/1791#issuecomment-243780866 [FIXED]
- [X] Upgrading to new version, the "Upload Path" of instant uploads builds the paths to upload wrongly https://github.com/owncloud/android/issues/1791#issuecomment-244021548 [FIXED]

NO REGRESSION

**Comment by davivel** [comment]
@jesmrec , ready to test from, my point of view.

**Comment by jesmrec** [comment]
### Bug

### Steps

1. Login in an account
2. In server, change the credentials
3. In device, refresh 

### Actual behaviour

App crashes

### Expected behaviour

Login view to input the new credentials

Tested with Android7 (Nexus 6P), Android5 (Nexus5)
Server 8.2 & 9

cc @davivel

**Comment by jesmrec** [comment]
### Bug

### Steps

1. Download a file
2. Long press on the file -> open with

### Actual behaviour

App crashes

### Expected behaviour

A list with apps is displayed

Tested with Android7 (Nexus 6P)
Server 8.2 & 9

cc @davivel

**Comment by davivel** [comment]
Seen. Will check them tomorrow

**Comment by jesmrec** [comment]
### Bug
(¿? same as https://github.com/owncloud/android/issues/1791#issuecomment-243501747)

### Steps

1. Tap to download a .doc, .xls or .pdf file (i have test with those ones, but it will be more)

### Actual behaviour

App crashes

### Expected behaviour

A list with apps is displayed

Tested with Android7 (Nexus 6P)
Server 8.2 & 9

cc @davivel

**Comment by davivel** [comment]
@jesmrec , first crash ready to test.

**Comment by davivel** [comment]
@jesmrec , all ready to test.

**Comment by jesmrec** [comment]
### Bug 

1. Share a folder with a user in other server
2. In web, Accept the share
3. In app, login with the sharee

### Actual behaviour

The size of the folder is -1. Until the folder is browsed, the size is not updated.

### Expected behaviour

The size of shared folder is correct

Tested with Android7, Android5

cc @davivel

**Comment by davivel** [comment]
Checking. Sure it's a regression?

**Comment by davivel** [comment]
Oh! Size of folder. OK, sure it's new :D

**Comment by davivel** [comment]
@jesmrec , fixed. The size of incoming federated folders is not available immediately. I used the same approach as in the web interface, showing the word "Pending" instead of the size until it's known.

**Comment by davivel** [comment]
@jesmrec , fixed.

**Comment by jesmrec** [comment]
All bugs fixed. Version approved.

**Comment by davivel** [comment]
https://www.youtube.com/watch?v=w5Fgp-KihIA

**Comment by davivel** [comment]
All stuff done. Release out.

![mic-drop](https://cloud.githubusercontent.com/assets/2225614/18168301/4b38c270-7055-11e6-8899-1cf858cf7b28.gif)
