### ISSUE TITLE
[2.2.0] Release new version

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1847]
AC:

 - [x] [GIT] Create branch release_0.9.15 in owncloud/android-library from master  (almost feature-frozen) 
 - [x] [GIT] Create branch release_2.2.0 in owncloud/android from master (almost feature-frozen) 
 - [x] [DEV] Update version number and name in AndroidManifest.xml in android module
 - [x] [DEV] Update version number and name in AndroidManifest.xml in oc_jb_workaround module
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [x] [QA] Design Test plan @borjahawk 
 - [x] [GIT]  Rebase branch release_0.9.15 in owncloud/android-library after merge of owncloud/android-library#141 (feature-frozen)
 - [x] [GIT]  Rebase branch release_2.2.0 in owncloud/android after merge of owncloud/android#1851 (feature-frozen)
 - [x] [QA] Regression Test plan [DONE] @borjahawk
 - [x] [GIT] Merge branch release_0.9.15 in owncloud/android-library, into master
 - [x] [GIT] Merge branch release_2.2.0 in owncloud/android, into master
 - [x] [DIS] Generate test APKs and BAR files from branch master in owncloud/android
 - [x] [GIT] Create and sign tag oc-android-2.2.0 in HEAD commit of stable master branch, in owncloud/android
 - [x] [GIT] Create and sign tag oc-android-library-0.9.15 in HEAD commit of stable master branch, in owncloud/android-library
 - [x] [DIS] Generate final APKs and BAR files from signed commit in owncloud/android
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [DIS] Upload & publish release BAR and changelog in Blackberry World
 - [x] [DIS] Update screenshots and store listing, if needed, in Blackberry World
 - [x] [GIT] merge master branch into stable, in owncloud/android-library
 - [x] [GIT] merge master branch into stable, in owncloud/android
 - [x] [DIS] push OC JB workaround app to Play Store

REGRESSION BUGS & IMPROVEMENTS:
 - [x]  Prevent NPEs [DONE]
 - [x] Cancel and choose buttons at the bottom don't work when copying/moving a file/folder. See https://github.com/owncloud/android/issues/1847#issuecomment-266684363 [FIXED]
 - [x] App stops when the orientation is changed from portrait to landscape. See https://github.com/owncloud/android/issues/1847#issuecomment-266687493 [FIXED] in #1854 
- [x] The app crashes when entering an invalid server address. See https://github.com/owncloud/android/issues/1847#issuecomment-267558274 [FIXED] in #1857
- [x] ~~The share dialog spinner stays Loading ... See https://github.com/owncloud/android/issues/1847#issuecomment-267933549~~ [WONT] **moved to #1860**
- [x] ~~A file cannot be uploaded in a federated shared folder with create permissions. See https://github.com/owncloud/android/issues/1847#issuecomment-267973558~~ [WONT] **moved to #1861**

**Comment by davivel** [comment]
Getting here, pals.

**Comment by joaquinjsb** [comment]
when will be available the streaming of photos  and videos instead of downloading it?

**Comment by davigonz** [comment]
## Cancel and choose buttons at the bottom don't work when copying/moving a file/folder.

### Steps
1. Select files/folders.
2. Select copy/move in contextual menu.
3. Press cancel/choose button at the bottom.

### Current behaviour
Nothing happens

### Expected behaviour
Cancel and choose should have the corresponding behavior: 
- Cancel button: go back to the previous view. 
- Choose button: select folder where copy or move the file/folder.

**Comment by davigonz** [comment]
## App stops when the orientation is changed from portrait to landscape

### Steps
1. Select files/folders.
2. Select copy/move in contextual menu.
3. Rotate screen.

### Current behaviour
App stops

### Expected behaviour
App rotates to landscape mode properly, showing the appropriate view. 

### Device & version
- Samsung Galaxy Note 4
- Android 6.0.1

**Comment by borjahawk** [comment]
## BUG: The app crashes after entering an incorrect server address

### Steps
1. Open the app
2. Enter an incorrect server address. Example: docker.oc.solidgear.es:66075
3. Push on Username

### Current behaviour
The app crashes

### Expected behaviour
The app should not crash

### Device & version
- Moto E v4.4
- Nexus 9 v6.0

**Comment by davivel** [comment]
@borjahawk , to be more specific: this crash appears if an invalid port is used, not with any incorrect URL.

**Comment by SamuAlfageme** [comment]
# The share dialog spinner stays `Loading ...`
Changes in the device orientation can lead to an indefinite spinner in the share dialog. It's hard to isolate the specific condition that is triggering this, but it's happening often. 

## Steps to reproduce:
1. Select a file and choose to share it. 
2. Change the device orientation. Repeat and retry this 2 steps until the load spinner stays stuck. 
3. After this happening once, it's reproduced systematically. 

## Current behavior 
The `Loading...` spinner stays in focus forever. If you try to click the back button, the app doesn't respond, and a couple of minutes after closing it, crashes. 

## Expected behavior 
Spinner should be displayed while getting the share settings for that file and a timeout should be triggered if these settings cannot be pulled from the server. 

## Test environment 
Android 6.0.1 on a Samsung Galaxy Note 4

**Comment by borjahawk** [comment]
## BUG: A file cannot be uploaded in a federated shared folder with create permissions

### Pre-requirements
Have 2 stable servers.

### Steps
1. Share a folder to a user (user1) of another server giving him only create permissions
2. Enter in the server of the user1 (web) and accept the folder
3. Enter in the folder in the app as user1 and upload a file

### Current behaviour
The upload is not done, an Unexpected error is shown in Uploads view.

### Expected behaviour
The upload should be done.

### Device & version
- Nexus 9 v6.0

**Comment by davivel** [comment]
App and JB-workaround-app available now in Google Play Store.

App in review in Blackberry World, will be available as soon as Blackberry approves (soon).

**Comment by davivel** [comment]
Thanks to everybody!!
