### ISSUE TITLE
[2.3.0] Release a new version

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1902]
AC:

 - [X] [GIT] Create branch release_0.9.16 in owncloud/android-library from master  (almost feature-frozen) 
 - [X] [GIT] Create branch release_2.3.0 in owncloud/android from master (almost feature-frozen) 
 - [X] [DEV] Update version number and name in AndroidManifest.xml in android module
 - [X] [DEV] Update version number and name in AndroidManifest.xml in oc_jb_workaround module
 - [X] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [X] [QA] Design Test plan  @jesmrec 
 - [X] [QA] Regression Test plan @jesmrec
 - [x] [GIT] Merge branch release_0.9.16 in owncloud/android-library, into master
 - [x] [GIT] Merge branch release_2.3.0 in owncloud/android, into master
 - [x] [DIS] Generate test APKs and BAR files from branch master in owncloud/android
 - [x] [GIT] Create and sign tag oc-android-2.3.0 in HEAD commit of stable master branch, in owncloud/android
 - [x] [GIT] Create and sign tag oc-android-library-0.9.16 in HEAD commit of stable master branch, in owncloud/android-library
 - [x] [DIS] Generate final APKs and BAR files from signed commit in owncloud/android
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [DIS] Upload & publish release BAR and changelog in Blackberry World
 - [x] [DIS] Update screenshots and store listing, if needed, in Blackberry World
 - [x] [GIT] merge master branch into stable, in owncloud/android-library
 - [x] [GIT] merge master branch into stable, in owncloud/android
 - [x] [DIS] push OC JB workaround app to Play Store

_____

BUGS & IMPROVEMENTS

- [X] Toast instead of snackbar when searching sharee https://github.com/owncloud/android/issues/1902#issuecomment-283938224 [WONT FIX]
- [X] Error incorrect in uploads view when server in maintenance mode https://github.com/owncloud/android/issues/1902#issuecomment-283939792 [FIXED]  @davigonz @jesmrec  (rollback to old status)
- [X] Error when target folder is removed https://github.com/owncloud/android/issues/1902#issuecomment-284386813 [FIXED] @davigonz @jesmrec 
- [X] Error when file is removed https://github.com/owncloud/android/issues/1902#issuecomment-284393522 [FIXED] @davigonz @jesmrec 
- [X] Copy option in preview of txt https://github.com/owncloud/android/issues/1902#issuecomment-284401761 [FIXED] @davigonz @jesmrec 
- [X] Long message in uploads view https://github.com/owncloud/android/issues/1902#issuecomment-284674888 [FIXED] @davigonz @jesmrec 
- [X] Folder error is not correctly displayed in notification https:/github.com/owncloud/android/issues/1902#issuecomment-284711701 [FIXED] @davigonz @jesmrec

**Comment by jesmrec** [comment]
### Improvement

1. Switch connection off
2. Share a file or folder
3. Tap on "Add user or group"
4. Type some characters

Current behaviour

A toast is shown 

Expected behaviour

A snackbar is displayed

Tested with Samsung Galaxy Note 4

**Comment by jesmrec** [comment]
### Bug

Steps

1. Set server in maintenance mode
2. Upload content

Current behaviour

Error in snackbar and notifications shows the correct error, but uploads view shows `Storage not available`

Expected behaviour

Error in snackbar, notifications and uploads view  shows the correct error

Tested with Samsung Galaxy Note 4

**Comment by jesmrec** [comment]
###Bug

Steps

1. Long press over a file/folder and select "Move"
2. Browse into a folder without selecting
3. In web, remove the folder

Expected behaviour

`An error occured while trying to move` (the error in 2.2.0)

Current behaviour

`Conflict' 

Tested with samsung galaxy v6 
server 9.1.4

**Comment by jesmrec** [comment]
### Bug

Steps

Long press over a file/folder and select "Move"
Browse into a folder without selecting
In web, remove the folder
Expected behaviour

`Rename could not be completed`(the error in 2.2.0)

Current behaviour

`Server instance not found`

Tested with samsung galaxy v6
server 9.1.4

**Comment by jesmrec** [comment]
### Bug (not regression)

Steps

1. Open a downloaded txt file

Current behaviour

"Copy" option is shown (only with txt files)

Expected behaviour

"Copy" is not an option in preview mode.

**Comment by jesmrec** [comment]
### Improvement

In a firewall rule bans a upload, the message in uploads view is "You do not have permission to upload in this folder"

The message is too long in uploads view and uses two rows in a phone. It should be shortened.

For example: "Upload not allowed", "Folder with forbidden access"...

**Comment by jesmrec** [comment]
### Bug 

Steps

1. Try to upload files into a folder
2. Before conforming the upload, delete the folder in web
3. Confirm the upload

Current behaviour

In notification is set "Server instance not found"

Expected behaviour

The notification message should refer to "Folder error" or similar. In Uploads view the displayed message is "Folder Error"

**Comment by jesmrec** [comment]
all bug fixed, version approved.

Note: the error messages developed in https://github.com/owncloud/android/pull/1898 and https://github.com/owncloud/android/issues/1722 will be the generic ones in the uploads view (notification will be correct). We will research for a better solution.

**Comment by davivel** [comment]
Available now.
