### ISSUE TITLE
Multiple Share Links

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1928]
#Multiple share links is a new feature in oC10, that allows to create more than one public link over the same file/folder.

Current behaviour:

- The Android mobile app only supports one public link. 
- The behaviour right now is showing the first one of the public links created on the server side. 
- If the link is edited in the Android app, the name is removed from the link in server side -> https://github.com/owncloud/core/issues/27622
- If the link is removed from Android app, the next one in the list is displayed.

It will require some actions:

- [X] Share activity using full screen instead of dialog style
- [X] Update wording of sections according to last update in iOS
- [X] Replace 'Add user or group' button with (+) button
- [X] Replace switch to on/off public link with (+) button
- [x] Move section with details of public links to new DialogFragment 
- [x] Replace section with details of public link in ShareActivity with list of public shares
- [x] Add icon to delete public share in item list
- [x] Add icon to copy-to-clipboard AND share-with-apps public link in item list
- [x] Add angle icon to edit details in item list
- [x] Add name field to section with details of public link
- [x] For all the things below: ** grant compatibility with server <= 9.x **
- [x] Update domain model and database to support multiple public shares per OCFile
- [x] Update domain model and database to support optional name parameter in OCShares
- [x] Update FileDataStorageManager to retrieve list of public shares for a given file
- [x] Update Get operations to support multiple public links per OCFile
- [x] Update domain model and database to add new property with public link added to OCShare with OC 9.0.0
- [x] Update CreatePublicShareOperation to support multiple public links per OCFile
- [x] Update UpdatePublicShareOperation to support multiple public links per OCFile
- [x] Update RemoveShareOperation to support multiple public links per OCFile, and connect to delete icon
- [x] Connect icon to copy-or-share action
- [x] Connect icon to update existing public share
- [x] Adapt dialog to handle both creation and update of shares correctly
- [x] Handle the different cases when updating the public share password
- [x] Ensure that password is required when server enforces it
- [x] Ensure that expiration date is shown by default when server enforces it
- [x] Enable or disable multiple links support depending on the corresponding capability (see https://github.com/owncloud/core/issues/27622) 
- [x] Hide list of public links and title if public share is disabled by admin
- [x] Connect allow editing permissions switch when creating or updating a folder public share 
- [x] Fix UI for private shares after going to full screen ShareActivity
- [X]  Warning about public links: owncloud/enterprise#1914 
- [X] Warning about public links with message "Anyone with the link has access to the file/folder" https://github.com/owncloud/core/pull/27844/files 
- [x] Change policy to show warning about public links: depending on server capability
- [x] Clean unneeded code of the previous sharing version
- [x] [QA] Design test plan @jesmrec
- [X] [QA] Validate test plan @jesmrec

___

BUGS & IMPROVEMENTS

- [X] (1) Soft keyboard automatically displayed to input link password https://github.com/owncloud/android/issues/1928#issuecomment-299834718 [FIXED]
- [X] (2) Ask for confirmation is case of link removing https://github.com/owncloud/android/issues/1928#issuecomment-299839271 [FIXED] 
- [X] (3) Not allowing to disable password switch if it is forced. https://github.com/owncloud/android/issues/1928#issuecomment-299847474 [FIXED]
- [X] (4) App crashes if remove expiration (default) https://github.com/owncloud/android/issues/1928#issuecomment-299849323 [FIXED]
- [X] (5) Link is saved without expiration although it is forced https://github.com/owncloud/android/issues/1928#issuecomment-299852941 [FIXED]
- [X] (6) Hide link name section when multiple share links are not supported [FIXED]
- [x] Using token as public share name in public shares list makes no sense in servers < 10  https://github.com/owncloud/android/issues/1928#issuecomment-300077521 [WILL NOT BE FIXED]
- [X] (7) Creation of more than one link is not being prevented in servers < 10 https://github.com/owncloud/android/issues/1928#issuecomment-299857505 [FIXED]
- [X] (8) Edit public links in servers < 10 https://github.com/owncloud/android/issues/1928#issuecomment-299862239 [FIXED]
- [X] (9) Disabling expiration is not saved https://github.com/owncloud/android/issues/1928#issuecomment-300101852 [OUT OF SCOPE] 
- [X] (10) Error message is improvable https://github.com/owncloud/android/issues/1928#issuecomment-300107439 [FIXED]
- [X] (11) Error messages in landscape make the buttons vanish https://github.com/owncloud/android/issues/1928#issuecomment-300111388 [FIXED] 
- [X] (12) Filename as default https://github.com/owncloud/android/issues/1928#issuecomment-300170065 [FIXED]
- [X] (13) Softkeyboard in servers < 10 https://github.com/owncloud/android/issues/1928#issuecomment-300192697 [FIXED]
- [X] (14) App crashes in landscape in share view after  asking for the passcode https://github.com/owncloud/android/issues/1928#issuecomment-300232970 [FIXED]
- [X] (15) Expiration not set en Galaxy Tab S https://github.com/owncloud/android/issues/1928#issuecomment-300441620 [FIXED]
- [X] (16) Default date to select is today https://github.com/owncloud/android/issues/1928#issuecomment-300520074 [FIXED]
- [X] (17) Autogenerated numbers in links with default name https://github.com/owncloud/android/issues/1928#issuecomment-300707412 [FIXED]
- [X] (18) Users and groups in small screens https://github.com/owncloud/android/issues/1928#issuecomment-300729371 [FIXED]
- [X] (19) Delete PL + Expiration + Create PL = Crash https://github.com/owncloud/android/issues/1928#issuecomment-300760879 [FIXED] 
- [X] (20) Crash rotating in permissions dialog https://github.com/owncloud/android/issues/1928#issuecomment-301011615  [FIXED]
- [X] (21) Scroll in edit link view https://github.com/owncloud/android/issues/1928#issuecomment-301058231 [FIXED]
- [X] (22) Expiration date disappears by rotating https://github.com/owncloud/android/issues/1928#issuecomment-301387117 [FIXED]

**Comment by SamuAlfageme** [comment]
> If the link is edited in the Android app, the name is removed from the link in server side.

https://github.com/owncloud/core/issues/27517

**Comment by davigonz** [comment]
This is how the new UI design for the Share view is looking like, including support for the new multiple links feature. 

Suggestions are welcome :wink:

New share view            |  Dialog for creating a public link
:-------------------------:|:-------------------------:
![device-2017-04-21-143332](https://cloud.githubusercontent.com/assets/15261363/25277726/2c613ef2-26a0-11e7-8335-44ed813dbe43.png)  |  ![device-2017-04-21-143419](https://cloud.githubusercontent.com/assets/15261363/25277696/1d69a9de-26a0-11e7-8679-b4dd70207ea7.png)

@michaelstingl @rperezb @jesmrec @davivel @nasli

**Comment by jesmrec** [comment]
Looks nice. I would only set a little padding between "Users and Groups" and "Public links". 

I would like to see as well:

- When there are no links
- The view for editing (not for creating)

but if you prefer, we can delay this to the QA stage. The look of the view is 👍

**Comment by jesmrec** [comment]
Starting QA stage.

First question:

By enabling the `Password` switch, the user is allowed to set the password empty. Server side behaves it in this way, but it is not using a switch. Why reason to do this?

On the other hand (as impromevent), also related with password: when the `Password` switch is enabled, the soft keyboard should be displayed to avoid the user taps on the field to input the password.

@davivel @davigonz

**Comment by jesmrec** [comment]
### Improvement

The options to get link and to remove the link are close in the screen, and it is posible that someone mistakes and tap on remove instead of getting link. In this case, maybe useful to ask the user a confirmation of deletion if he/she taps on remove, as the server does.

**Comment by jesmrec** [comment]
About the following behaviour:

1. Enforce password protection in server
2. In app, create a public link with password
3. Edit the link by removing the password

From here, switching the `Password` off is allowed, but saving the link. This is not a wrong behaviour, but it would be cooler if the user could not switch the `Password` off if the capability is enabled. If the user switches the option off, he sees it as disabled and is forced to enable it again to save the link. In this case the previous password is persisted, so i think it makes more sense not to allow to disable it, so that the value of the capability is already known.

**Comment by jesmrec** [comment]
### Bug

Steps:

1. In server, enable `Set default expiration date` 
2. In app, create a public link with default options -> expiration date is enabled
3. Switch the `Expiration` off and tap on `Save` 

Current behaviour

Appears the `Send link`view.  Tapping on the back button, appears the calendar. Closing it (cancelling ok OKing) makes the app crash.

Expected behaviour

Expiration can not be disabled or  link can not be saved in this status.

Huawei 6P v7.

**Comment by jesmrec** [comment]
### Bug

Steps:

1. In server, enable `Set default expiration date` and `Enforce expiration`
2. In app, create a public link with default options -> expiration date is enabled
3. Switch the `Expiration` off and tap on `Save` 

Current behaviour

The link is saved and happens the same behaviour as https://github.com/owncloud/android/issues/1928#issuecomment-299849323

Expected behaviour

Expiration is forced, link can not be saved.

Huawei 6P v7.

**Comment by jesmrec** [comment]
In servers older than 10.0, the field `Link Name` did not exist. When a public link is created, this field is being shown and can be confusing for users that do not know the server feature.

**Comment by jesmrec** [comment]
In servers < 10, if a public link is already created the '+' button should be hidden. Right now is already displayed, and the user can tap on it, see the view to create a new public link and save (with any result).

**Comment by davigonz** [comment]
> In servers < 10, if a public link is already created the '+' button should be hidden. Right now is already displayed, and the user can tap on it, see the view to create a new public link and save (with any result).

+ button should be shown when there's no public links so that the user can add a new one. When there is already a public link, it should be hidden. You mean that the + button is being shown even when there's already a public link?

**Comment by davivel** [comment]
About  first question https://github.com/owncloud/android/issues/1928#issuecomment-299834718

> By enabling the Password switch, the user is allowed to set the password empty. Server side behaves it in this way, but it is not using a switch. Why reason to do this?

Ease of development. We come from an implementation with switch, it's easier to keep the switch.

> On the other hand (as impromevent), also related with password: when the Password switch is enabled, the soft keyboard should be displayed to avoid the user taps on the field to input the password. 

Can be done.

> The same would be for Link namebut in this case, it should be displayed just before the view is opened.

Could be done.

**Comment by davivel** [comment]
About confirmation of removal: https://github.com/owncloud/android/issues/1928#issuecomment-299839271

I wouldn't go that way. We can leave some more space between buttons, or think any other position for the cell layout, but confirmation dialogs are annoying. Web UI doesn't ask for confirmation.

**Comment by jesmrec** [comment]
### Bug

Steps:

1. In app, create a public link in  server < 10
2. Tap on `>` to edit the link
3. Update any field

Current behaviour

Link can not be saved due to an error `Wrong or no update parameter given`

Expected behaviour

Link can be updated.

Huawei 6P v7. Server 9.1.5

**Comment by jesmrec** [comment]
@davigonz 

> You mean that the + button is being shown even when there's already a public link?

Yes. Hidden or locked is a good solution. But the problem is that the `Create link share' view is shown when a public link is already created.

**Comment by jesmrec** [comment]
@davivel 

> I wouldn't go that way. We can leave some more space between buttons, or think any other >position for the cell layout, but confirmation dialogs are annoying. Web UI doesn't ask for >confirmation.

I understand, a bit of space can be useful in this issue. 

Web UI asks for confirmation.

**Comment by jesmrec** [comment]
In servers < 10, you are using the token (due to the lack of name) as well as in oC10 servers. This field makes no sense in oC9 and older. Difficult to meet a solution there.

**Comment by jesmrec** [comment]
### Bug

Steps:

1. In server, enable `Set default expiration date` 
2. In app, create a public link with default options -> expiration date is enabled
3. Switch the `Expiration` off and tap on `Save` 
4. Tap on '>' to edit the recent created public link

Current behaviour

Expiration is enabled

Expected behaviour

Expiration is disabled

Huawei 6P v7.

**Comment by jesmrec** [comment]
### Improvement

In the device loses the connection (plane mode, for example), when you tap on `Create`, the error is `Unknown host`. Maybe is not the bes descriptive error for this case.

**Comment by jesmrec** [comment]
### Bug

1. Disable internet connection (plane mode, for example)
2. Open dialog to create a new public link
3. Set the device in landscape

Current behaviour

Buttons `Cancel`and `Save` are almost vanished

Expected behaviour

Scroll view? to view the buttons

Server v10

Huawei 6P v7

**Comment by jesmrec** [comment]
### Improvement

When the public link is created, the server suggest as hint the name of the file in the field. What do you think about including it? @davivel @davigonz

**Comment by jesmrec** [comment]
### Bug

In server < 10, create public link

Current behaviour: softkeyboard is raised
Expected behaviour:  softkeyboard is not raised, so there is no textual fields in this case.

Huawei 6P v7

**Comment by davivel** [comment]
Problems with password or expiration date enforced in server are ready to be tested.

**Comment by jesmrec** [comment]
### (14) Bug 

1. Set passcode in the settings
2. Open share view
3. Set device in landscape
4. Minimize the app (circle button)
5. Open again the app

Current behaviour

App crashes

Expected behaviour

App is opened after typing the passcode

server v10
Huawei 6P v7

**Comment by jesmrec** [comment]
### (15) Bug 

1. Create public link
2. Set an expiration date (in server is neither set by default nor enforced)
3. Save
4. Open the public link

Current behaviour

Expiration is not set. In server either

Expected behaviour

Expiration is set. In server too.

**Only happens in Galaxy Tab S v6**

server v10

**Comment by davivel** [comment]
@jesmrec , library should be fixed now and phantom-bug about removal of name link in update also. 

If Travis doesn't fail in https://github.com/owncloud/android-library/pull/163 we can resume QA.

**Comment by jesmrec** [comment]
### (16) improvement 

1. In server, enable `Set default expiration date` capability
2. In app, create a public link
3. Tap on `Set expiration date` (already enabled with the default date)

Current behaviour

The default date is today

Expected behaviour

Default date is the default in capability (as in server side)

Server v10
Galaxy tab s v6

**Comment by davivel** [comment]
@jesmrec , current expiration date set as selected in the date picker.

**Comment by jesmrec** [comment]
### Improvement

In server, the default names are generated consecutively with numbers: (2), (3) etc...

Look at these steps:

1. Generate 5 files
Photos link
Photos link (2)
Photos link (3)
Photos link (4)
Photos link (5)

Delete Photos link (3) and generate a new public link

Server: generates  Photos link (3). Server fills gaps in the numbers
Android: generates  Photos link (5).

**Comment by jesmrec** [comment]
### (18) Bug (regression)

In a device with small screen (for example MotoG 4,4) tap on `+` of User and groups

- The username overlaps with the icon
- If the device is in landscape, no selection is posible. 

MotoG 4.4

**Comment by jesmrec** [comment]
### (19) Bug 

1. Create public link in SAML server
2. Wait (or force) an expiration
3. Before redirection to login happens, tap on the trashbin icon to delete the public link -> Redirected to login view
4. Enter credentials -> appears share view
5. Tap on "+" to create a new public link

Current behaviour

App crashes

Expected behaviour

Dialog to create new public link

server v10
Huawei 6P v7, Samsung Galaxy Tab S v6

**Comment by davivel** [comment]
@jesmrec , (18) ready to be tested; I changed search view to full screen, besides of fixing the layout of suggestions.

**Comment by davivel** [comment]
(17) ready to test too.

**Comment by jesmrec** [comment]
### (20) Bug 

1. Share with users or groups
2. Select a user or group
3. In search view, tap on ">" to edit permissions
4. Rotate the device

Current behaviour

App crashes

Expected behaviour

Orientation changed

server v10
Huawei 6P v7, Samsung Galaxy Tab S v6

**Comment by jesmrec** [comment]
### (21) Improvement

1. Enforce expiration date and password (dialog is longer in this case)
2. Edit a public link, and tap on link name.

Current behaviour: buttons `Cancel` and `Save`are hidden behind the keyboard. Can not be tapped  until keyboard is collapsed

Expected behaviour: Dialog can be scrolled (same as creation)

server v10
Huawei 6P v7

**Comment by davivel** [comment]
Taking it

**Comment by jesmrec** [comment]
### (22) Bug

1. Create a public link, enabling expiration
2. Rotate the device

Current: Expiration date disappears
Expected: Expiration date does not disappear

**Comment by jesmrec** [comment]
Approved, all fixed.
