### ISSUE TITLE
Migrate app to Android O

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1968]
Official guideline to migrate: https://developer.android.com/about/versions/oreo/android-8.0-migration.html

Android O behaviour changes: https://developer.android.com/about/versions/oreo/android-8.0-changes.html

**Note about background constrains:** Android O includes new restrictions to background operation. We need to check the impact on the app and extend the work done in version 2.4.0 to retry interrupted transfers taking the new constrains into account.

_____
**TASKS:** 

 - [x] Ensure compatibility with Android 8.0 by testing the app without changing the targetSdkVersion. 
 - [x] Upgrade to Android O (26) the next dependencies in both app and library:
    - compileSdkVersion: no warnings/errors
    - targetSdkVersion (include it in travis.yml) 
 - [X] Test the app and look for needed changes. 
 - [x] Apply changes to adapt the app to Android app, if needed. 

_____
**BUGS & IMPROVEMENTS**

 - [X] (1) Uploads/downloads/Play audio notifications don't appear in Android 8 https://github.com/owncloud/android/issues/1968#issuecomment-337558761 [FIXED] @jesmrec 
- [X] (2) Crash after taking a picture with instant uploads enabled https://github.com/owncloud/android/issues/1968#issuecomment-338122211 [WONT BE FIXED HERE] Background service is being killed and will be replaced with a scheduled job, to do in https://github.com/owncloud/android/issues/2028

**Comment by davigonz** [comment]
Since we are currently compiling our app by using SDK version 24, we have to take into account the next statement in Android O documentation:

**"By default, these restrictions (background) only apply to apps that target O. However, users can enable these restrictions for any app from the Settings screen, even if the app has not targetted O."**

**Comment by davigonz** [comment]
Since we are not currently targeting Android O (API 26) in our app but Android N (API 24), we have to take into account the next statement in Android O documentation:

**"By default, these restrictions (background) only apply to apps that target O. However, users can enable these restrictions for any app from the Settings screen, even if the app has not targetted O."**

To enable this option we have to go to Settings menu, Apps & notifications, search ownCloud app, tap it, go to Battery section and disable the option **Background activity** in Manage battery usage section. 

<img src="https://user-images.githubusercontent.com/15261363/31268992-f4be8fd2-aa7e-11e7-81f4-bff7bff54ce6.png" width="60%" height="60%">

By disabling this option, we can test the app with background restriction and prepare the app if an user decides to disable it or for the moment when we decide to target the app in Android O, where this option will be disabled by default.

**Comment by davigonz** [comment]
## BUG (3) [FIXED]

**Steps to reproduce**
1.- Start an upload/download for a file/folder.
2.- The refreshing blue icon appears in the file/folder but not the notification that shows the progress.
3.- The upload/download finish properly but not the notifications.

Current behaviour: Notification doesn't appear at all.
Expected behaviour: Notification appears, showing the upload/download progress and the file/folder name.

Tested with Nexus 5X, Android 8.0.0

**Comment by jesmrec** [comment]
checking with Android M, backwards compatibility in background services for uploads and downloads:

- [X] Basic uploads
- [X] Basic downloads
- [X] Multiple uploads
- [X] Multiple downloads 
- [X] Uploads recovered after being broken by Doze 
- [X] Downloads recovered after being broken by Doze 
- [X] Uploads recovered after connection loss (plane mode, for instance)
- [X] Downloads recovered after connection loss (plane mode, for instance)
- [ ] Instant uploads
- [ ] Streaming
- [ ] https://github.com/owncloud/android/issues/1968#issuecomment-337558761

**Comment by davigonz** [comment]
Checking with Android O:

- [X] Basic uploads
- [X] Basic downloads
- [ ] Multiple uploads
- [ ] Multiple downloads 
- [ ] Uploads recovered after being broken by Doze 
- [ ] Downloads recovered after being broken by Doze 
- [X] Uploads recovered after connection loss (plane mode, for instance)
- [X] Downloads recovered after connection loss (plane mode, for instance)
- [ ] Instant uploads
- [ ] Streaming
- [ ] https://github.com/owncloud/android/issues/1968#issuecomment-337558761

**Comment by davigonz** [comment]
## BUG (2)
Crash with instant uploads

**Steps to reproduce**
1.- Enable instant upload feature.
2.- Kill the app by swiping it.
3.- Take a picture.

**Current behaviour:** The app is stopped. 

**Expected behaviour:** The app is still alive and the instant upload starts automatically.

**Android log:**: `java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.owncloud.android.debug/com.owncloud.android.files.services.FileUploader (has extras) }: app is in background uid...`

Tested with Nexus 5X, Android 8.0.0

**Comment by jesmrec** [comment]
Checking app with target 26 in **Android N**, backwards compatibility in background services for uploads and downloads:

- [ ] Basic uploads
- [ ] Basic downloads
- [ ] Multiple uploads
- [ ] Multiple downloads 
- [ ] Uploads recovered after being broken by Doze 
- [ ] Downloads recovered after being broken by Doze 
- [ ] Uploads recovered after connection loss (plane mode, for instance)
- [ ] Downloads recovered after connection loss (plane mode, for instance)
- [ ] Instant uploads
- [ ] Streaming
- [ ] https://github.com/owncloud/android/issues/1968#issuecomment-337558761
- [ ] https://github.com/owncloud/android/issues/1968#issuecomment-338122211

**Comment by jesmrec** [comment]
Smoke test over Android 5 (Lollipop), because nowadays is still one of the most used Android versions:

- [X] Upload file/folder
- [X] Download file/folder
- [X] Instant Uploads
- [X] Refresh account
- [ ] Move/Copy/Delete/Rename
- [ ] Av. Offline
- [ ] Share with users
- [ ] Share by link
- [ ] Multiaccount

This issue, opened during Doze adaption: https://github.com/owncloud/android/issues/1950, will be checked as well.

**Comment by jesmrec** [comment]
@davigonz bug (1) https://github.com/owncloud/android/issues/1968#issuecomment-337558761 checked and fixed.  

The upgrading to target 26 has not been very buggy. Expecting to keep this line.

Approved
