### ISSUE TITLE
[2.5.0] Release new version

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2008]
PRs: 
_____

AC:

 - [x] [GIT] Create branch release_0.9.18 in owncloud/android-library from master  (almost feature-frozen) 
 - [x] [GIT] Create branch release_2.5.0 in owncloud/android from master (almost feature-frozen) 
 - [x] [DEV] Update version number and name in AndroidManifest.xml in android module 
 - [x] [DEV] Update version number and name in AndroidManifest.xml in oc_jb_workaround module 
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android 
 - [x] [QA] Design Test plan  @jesmrec
 - [x] [QA] Regression Test plan @jesmrec 
 - [x] [DEV] EXTRA BALL: disable permalink for this version, #2032 has to go first
 - [x] [GIT] Merge branch release_0.9.18 in owncloud/android-library, into master 
 - [x] [GIT] Merge branch release_2.5.0 in owncloud/android, into master 
 - [x] [DIS] Generate test APKs files from branch master in owncloud/android
 - [x] [GIT] Create and sign tag oc-android-2.5.0 in HEAD commit of master branch, in owncloud/android 
 - [x] [GIT] Create and sign tag oc-android-library-0.9.18 in HEAD commit of master branch, in  #owncloud/android-library
- [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new release 2.5.0
 - [x] [DIS] Generate final APK files (including oc_jb_workaround) from signed commit in owncloud/android
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [DIS] push OC JB workaround app to Play Store.
 - [x] [COORDINATION] Write in release-coordination chat.
 - [x] [COORDINATION] Write email to release-coordination mailing list.
 - [x] [SPREADTHEWORD] Write a topic in central about the release.
 - [ ] [DOC] Update documentation with the new features.
 - [x] [GIT] merge master branch into stable, in owncloud/android-library
 - [x] [GIT] merge master branch into stable, in owncloud/android

_____

#### BUGS & IMPROVEMENTS
- [X] (1) Login with LDAP 
https://github.com/owncloud/android/issues/2008#issuecomment-327798395 [FIXED] @davigonz @jesmrec 
- [X] (2) apk filename with null instead of version 
https://github.com/owncloud/android/issues/2008#issuecomment-328486877 [FIXED]
- [X] (3) Edit credentials does not keep the initial user https://github.com/owncloud/android/issues/2008#issuecomment-331862468 [FIXED] @davigonz @jesmrec 
- [X] (4) Account name in drawer and in accounts manager https://github.com/owncloud/android/issues/2008#issuecomment-332428924 [FIXED] @davigonz @jesmrec 
- [X] (5) Multiaccount in OAuth2 (same server) https://github.com/owncloud/android/issues/2008#issuecomment-332429298 [FIXED] @davigonz @jesmrec 
- [X] (6) Multiaccount in OAuth2 (different server) https://github.com/owncloud/android/issues/2008#issuecomment-332434502 [FIXED] @davigonz @jesmrec 
- [x] (7) .apk release  #https://github.com/owncloud/android/issues/2008#issuecomment-333457246

Future improvements:
https://github.com/owncloud/android/issues/2008#issuecomment-332832836

**Comment by jesmrec** [comment]
Starting QA here...

**Comment by jesmrec** [comment]
##BUG (1)

Login in a LDAP server with basic auth which id is not the userId 

Current: files view not loaded. Loop to login view
Expected:  files view loaded.

Tested with Nexus 6P v7.1.2.

**Comment by jesmrec** [comment]
## BUG (2)

This is not a funcionality one, but a regression.

The apk generated by the IDE is called

`android_null-debug.apk`
`android_null-release.apk`
`android_null-beta.apk`

instead using the correct version number.

**Comment by davivel** [comment]
Name of APKs should be fine now.

**Comment by davivel** [comment]
I just disabled private link in UI, as we talked before, until #2032 is ready (next version).

cc @michaelstingl

**Comment by jesmrec** [comment]
## BUG (3) 

1.- Login in a OAuth2 server
2.- In "Manage accounts" view, tap on the key icon (edit credentials) -> Login view appears
3.- Input credentials of a different user

Current: Login with other user is succesfully completed but the initial user keeps on being the account's one.
Expected: Error message, so the edit credentials feature must keep the account's user

Tested with Samsung Galaxy Edge v7

**Comment by jesmrec** [comment]
## BUG (4) 

1.- Login in a OAuth2 server
2.- Open Drawer / Open Accounts Manager

Current: Account does not show the username, only `@serverURL`

Expected: Account is shown `user@server`

Tested with Samsung Galaxy Tab2 v5

**Comment by jesmrec** [comment]
## BUG (5) 

1.- Login in a OAuth2 server
2.- Login with another account in the same server

Current: `Already exists an account with the same username`
Expected: Account is attached.

Tested with Samsung Galaxy Tab2 v5

**Comment by jesmrec** [comment]
## BUG (6) 

1.- Login in a OAuth2 server
2.- Login with another account in the other server

Current: `Unknown error`
Expected: Account is attached.

Tested with Samsung Galaxy Tab2 v5

**Comment by jesmrec** [comment]
Regarding https://github.com/owncloud/android/pull/2037/files

we have a feature to improve in future: when username length is lower than 4, blanks have to be added to fit the username while searching. Works correctly, but it could be a bit confusing for users.

**Comment by jesmrec** [comment]
Generated release apk form version 2.5.0 are not correctly installed in devices. Could you check it @davigonz ?

**Comment by jesmrec** [comment]
Version approved.
