### ISSUE TITLE
OAuth2: Bugs & improvements

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2018]
#### Bugs & Improvements
- [ ] **[UX] - Clicking back button on new login view relaunches the URL input form** https://github.com/owncloud/android/issues/2018#issuecomment-324251250
Follow up: https://github.com/owncloud/android/issues/2009
- [ ] **[IMPROVEMENT]** Password field in OAuth webview is covered by the keyboard in tablets in landscape mode https://github.com/owncloud/android/issues/2018#issuecomment-324251378
- [ ] **[BUG]** Basic login is shown in OAuth webview when changing auth endpoint to an incorrect one https://github.com/owncloud/android/issues/2018#issuecomment-324251468

**Comment by davigonz** [comment]
## [UX] - Clicking back button on new login view relaunches the URL input form:

**Device:** Nexus 6P (Android v7.1.2)
**Related with:** https://github.com/owncloud/android/issues/2009

### Steps to reproduce:

| The initial 'connect' view | The basic auth form |
|---|---|
| ![img1](https://user-images.githubusercontent.com/2644445/29171370-a6895154-7ddc-11e7-9799-5ec4825027e9.gif) | ![login_form](https://user-images.githubusercontent.com/2644445/29171780-f5f598e6-7ddd-11e7-9b2d-37991041b9e2.gif)

**Comment by davigonz** [comment]
## **[IMPROVEMENT] [UI]** Password field in OAuth webview is covered by the keyboard 

**Steps**

1. Open the app in a tablet in landscape mode
2. Introduce server and press connect button
3. A webview asking for credentials appears
4. Press username field, the keyboard appears, introduce the data
5. There's no way to introduce the password easily because the field is covered by the keyboard

**Current behaviour**

Password field is covered by the keyboard.

![oauth_tablet](https://user-images.githubusercontent.com/15261363/29448995-522688c0-83f9-11e7-8e51-e79149c262ea.png)

**Expected behaviour**

Webview is resized properly, staying completely above the keyboard or showing a clear scrollbar.

Nexus 10 v5.0.2

**Comment by davigonz** [comment]
## **[BUG]** Basic login is shown in OAuth webview when changing auth endpoint to an incorrect one

**Steps**

1. Go to setup.xml file and change **oauth2_url_endpoint_auth** to an incorrect one such as `index.php/apps/oauth2/authori`instead of `index.php/apps/oauth2/authorize`
2. Open the app, write the server and press the connect button.

**Current behaviour**

| Step 1: Enter credentials | Step 2: Login successful |
|---|---|
| ![screenshot_2017-08-21-10-04-10](https://user-images.githubusercontent.com/15261363/29509618-21c88946-8659-11e7-9a5c-25e5c7636758.png) | ![screenshot_2017-08-21-10-14-24](https://user-images.githubusercontent.com/15261363/29509762-a16910f8-8659-11e7-9dc7-b925bc983dd3.png) |

**Expected behaviour**

Show an error about the incorrect auth endpoint 

**Devices:** 

- Samsung Galaxy Note 4 v6
- Samsung Galaxy Tab S v6

**Comment by davigonz** [comment]
Wrong issue, follow up https://github.com/owncloud/android/issues/1724
