### ISSUE TITLE
[2.6.0] Release new version

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2047]
#AC:
 - [x] [GIT] Create branch release_0.9.19 in owncloud/android-library from master  (almost feature-frozen) [WIP]
 - [x] [GIT] Create branch release_2.6.0 in owncloud/android from master (almost feature-frozen) 
 - [x] [DEV] Update version number and name in build.gradle in android module
 - [x] [DEV] Update version number and name in build.gradle in oc_jb_workaround module 
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android 
 - [X] [QA] Design Test plan @jesmrec
 - [X] [QA] Regression Test plan  @jesmrec
 - [x] [GIT] Merge branch release_0.9.19 in owncloud/android-library, into master [NOT NEEDED, LAST CHANGES ALREADY IN MASTER, ADDED FROM THE LAST BETA] 
 - [x] [GIT] Merge branch release_2.6.0 in owncloud/android, into master 
 - [x] [DIS] Generate test APKs files from branch master in owncloud/android
 - [x] [GIT] Create and sign tag oc-android-2.6.0 in HEAD commit of master branch, in owncloud/android 
 - [x] [GIT] Create and sign tag oc-android-library-0.9.19 in HEAD commit of master branch, in  #owncloud/android-library
- [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new release 2.6.0
 - [x] [DIS] Generate final APK files (including oc_jb_workaround) from signed commit in owncloud/android
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Upload APKs to repo
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [DIS] push OC JB workaround app to Play Store.
 - [x] [COORDINATION] Write in release-coordination chat.
 - [x] [COORDINATION] Write email to release-coordination mailing list.
 - [x] [SPREADTHEWORD] Write a topic in central about the release.
 - [x] [SPREADTHEWORD] Write a post in the blog (https://kanboard.owncloud.com/project/22/task/1817)
 - [x] [DOC] Update documentation with the new features.
 - [x] [GIT] merge master branch into stable, in owncloud/android-library
 - [x] [GIT] merge master branch into stable, in owncloud/android
 - [ ] [DEV] **IMPORTANT:** Update the Android tools and dependencies in
   -  buildTools: 26.0.2
   -  platformTools: 26.0.1
   -  tools: 26.1.1
   - platform: 26

____

BUGS & IMPROVEMENTS

- [x] **[NO REGRESSION, WON'T BE FIXED HERE]** (1) Session finishes suddenly, and redirection to login view https://github.com/owncloud/android/issues/2047#issuecomment-358283999 
- [x] **[SERVER INVOLVED: [Core issue](https://github.com/owncloud/core/issues/30196), WON'T BE FIXED HERE]** (2) https://github.com/owncloud/android/issues/2047#issuecomment-358638864  
- [X] (3) Crash with plane mode https://github.com/owncloud/android/issues/2047#issuecomment-358962515 [FIXED] @jesmrec 
- [X] (4) Changing camera folder for camera uploads https://github.com/owncloud/android/issues/2047#issuecomment-361222871 [FIXED] @jesmrec 
- [X] (5) Changing camera folder uploads previous pics  https://github.com/owncloud/android/issues/2047#issuecomment-361504792  [FIXED] @jesmrec 
- [X] (6) Crash after upgrading to 2.6.0 https://github.com/owncloud/android/issues/2047#issuecomment-361872118

**Comment by jesmrec** [comment]
Should rename to 2.6.0? 2.5.1 is a name for a minor/bugfixing release, and this one will include interesting stuff and some new features.

**Comment by michaelstingl** [comment]
Yes, sounds plausible 👍

**Comment by davigonz** [comment]
Totally agree

**Comment by jesmrec** [comment]
Bug (1)

https://github.com/owncloud/android/issues/1964 is reproducible in the release branch. This is a regression as well.

**Comment by jesmrec** [comment]
Bug (2) 
Session finishes suddenly, and redirection to login view

Steps to reproduce:

1. Add a basic auth account with http and server 9.1
2. Add a OAuth2 auth account with http and server 10.0
3. Switch account from 2. to 1.

Current: Redirected to login view
Expected: Account switching correct

Tested with Nexus 6P v7.1.2

**Comment by davigonz** [comment]
@jesmrec I've managed to reproduce the Bug 2 with the next steps:

1. Add a basic auth account with http and server 9.1
2. Kill the app.
3. Reopen the app.

**Current behaviour**: Redirected to login view
**Expected**: Account switching properly

With 10.0 servers is not reproducible

Tested with Nexus 6P v7.1.2 and Samsung Galaxy S7 edge v7.0

**Comment by jesmrec** [comment]
### Bug (3) 

Steps to reproduce:

1. Set plane mode
2. Tap on a file to download it

Current: App crashes
Expected: Error message, no connection

Tested with Nexus 6P v7.1.2

**Comment by jesmrec** [comment]
Resuming the work here, second review

**Comment by jesmrec** [comment]
### Bug (4) 

Steps to reproduce:

1. Enable instant uploads with default camera folder
2. Take pics/videos -> they are uploaded after maximum 15 minutes
3. Change camera folder to a different one (for example, camera MX)
4. Take pics/videos with the default camera (not with the new one)

Current: Pics/videos are uploaded
Expected: Pics videos are not uploaded, so the camera folder points to a different one

Tested with Nexus 6P v7.1.2

**Comment by jesmrec** [comment]
### Bug (5) 

kind of different to (4), different steps:

Steps to reproduce:

1. Install the app and enable instant uploads with default camera folder
2. Take pics and videos with two different cam apps (for example, the default one  and MX)
3. Pics of default camera are uploaded. MX's are not.
4. Change the camera folder to Camera MX and tap on back arrow

Current: Pics of step 2. are uploaded
Expected: Any pic should be uploaded, so the camera folder was just enabled.

Tested with Nexus 6P v7.1.2

**Comment by jesmrec** [comment]
at this point, all bugs fixed and regression finished. Pending to perform upgrade testing before releasing 2.6.0

**Comment by jesmrec** [comment]
@davigonz could you try to generate a release .apk and install it in a tablet?

**Comment by davigonz** [comment]
> could you try to generate a release .apk and install it in a tablet? installation error received in Android 5 and 6 with tablets, but working fine in phones.

@jesmrec It works for me in a Samsung Galaxy Tab S 6.0.1

**Comment by jesmrec** [comment]
Another issue related with upgrading (6)

Steps:

1.- Install release 2.5.0
2- Attach two accounts, download some files and enable camera uploads and passcode lock.
3- Upgrade to the current 2.6.0

Current: App crashes after typing passcode
Expected: Correct upgrade

Tested with Nexus 6P v7, GalaxyS v6

Stack trace of the crash

01-31 10:18:50.178 3961-4078/? E/AndroidRuntime: FATAL EXCEPTION: Thread-2401
                                                 Process: com.owncloud.android, PID: 3961
                                                 java.lang.NoSuchMethodError: No virtual method getPrivateLink()Ljava/lang/String; in class Lcom/owncloud/android/lib/resources/files/RemoteFile; or its super classes (declaration of 'com.owncloud.android.lib.resources.files.RemoteFile' appears in /data/app/com.owncloud.android-2/base.apk)
                                                     at com.owncloud.android.utils.FileStorageUtils.createOCFileFrom(FileStorageUtils.java:156)
                                                     at com.owncloud.android.operations.SynchronizeFolderOperation.mergeRemoteFolder(SynchronizeFolderOperation.java:299)
                                                     at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:210)
                                                     at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:266)
                                                     at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:142)
                                                     at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:91)
                                                     at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:143)
                                                     at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:266)
                                                     at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:232)
                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by davigonz** [comment]
@jesmrec The crash described in [Bug 6](https://github.com/owncloud/android/issues/2047#issuecomment-361872118) is related to the way in which apks are generated, it's highly recommended to clean the project before building it to avoid that kind of dependency errors.

**Comment by jesmrec** [comment]
All stuff fixed, release QA work finished.

**Comment by icobg** [comment]
Im unable to compile the project as the way described in SETUP.md

C:\Users\home\AndroidStudioProjects\android-oc-android-2.6.0>gradlew.bat --debug clean build
07:59:50.844 [INFO] [org.gradle.internal.nativeintegration.services.NativeServices] Initialized native services in: C:\Users\home\.gradle\native
07:59:50.894 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
07:59:50.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
07:59:50.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
07:59:50.896 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
07:59:50.899 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Could not determine java version from '9.0.4'.
07:59:50.899 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
07:59:50.900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
07:59:50.900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.

I have installed android sdk 267 and 27. SDK-Tool 26.1.1 and SDK Platform tool 27.0.1. 
java --version
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
