### ISSUE TITLE
[2.7.0] Release new version

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2135]
### TASKS
- [x] [WIZARD] Create new steps with important features included in 2.7.0 #2136 
- [x] [COORDINATION] Create task in marketing board to publish a blog post, at least one week before releasing.
 - [X] [GIT] Create branch release_0.9.19 in owncloud/android-library from master  (almost feature-frozen) [DONE, not library changes for this version] 
 - [x] [GIT] Create branch release_2.7.0 in owncloud/android from master (almost feature-frozen) 
 - [x] [DEV] Update version number and name in build.gradle in android module
 - [x] [DEV] Update version number and name in build.gradle in oc_jb_workaround module 
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android 
 - [x] [QA] Design Test plan @jesmrec
 - [X] [QA] Regression Test plan  @jesmrec 
 - [X] [GIT] Merge branch release_0.9.19 in owncloud/android-library, into master [DONE, not library changes for this version] 
 - [x] [GIT] Merge branch release_2.7.0 in owncloud/android, into master 
 - [x] [DIS] Generate test APKs files from branch master in owncloud/android and perform some basic operations.
 - [x] [GIT] Create and sign tag oc-android-2.7.0 in HEAD commit of master branch, in owncloud/android 
 - [X] [GIT] Create and sign tag oc-android-library-0.9.19 in HEAD commit of master branch, in  #owncloud/android-library [DONE, not library changes for this version] 
- [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new release 2.7.0
 - [x] [DIS] Generate final APK files (including oc_jb_workaround) from signed commit in owncloud/android
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Upload APKs to repo
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [DIS] push OC JB workaround app to Play Store.
 - [x] [COORDINATION] Write in release-coordination chat.
 - [x] [COORDINATION] Write email to release-coordination mailing list.
 - [x] [SPREADTHEWORD] Write a topic in central about the release. https://central.owncloud.org/t/owncloud-android-app-2-7-0-released/
 - [x] [SPREADTHEWORD] Write a post in the blog
 - [x] [DOC] Update documentation with the new features. https://github.com/owncloud/documentation/issues/4035
 - [x] [GIT] merge master branch into stable, in owncloud/android-library
 - [x] [GIT] merge master branch into stable, in owncloud/android

_____
### BUGS & IMPROVEMENTS:
 - [x] (1) White screen when tapping around the fingerprint dialog https://github.com/owncloud/android/issues/2135#issuecomment-374151564 [FIXED]
 - [X] (2) Fingerprint asked when uploading picture directly from the camera https://github.com/owncloud/android/issues/2135#issuecomment-374153626 Fix in https://github.com/owncloud/android/pull/2162 [FIXED]
 - [X] (3) File picker view appears behind the "Select camera" option when using upload picture directly from camera feature https://github.com/owncloud/android/issues/2135#issuecomment-374154688 https://github.com/owncloud/android/pull/2168 
- [X] (4) Crash opening Settings in devices 6.0.1 https://github.com/owncloud/android/issues/2135#issuecomment-376086456 [FIXED]
- [X] (5) Pattern lock skipped https://github.com/owncloud/android/issues/2135#issuecomment-378140629 [FIXED]
- [x] (6) Upgrade wizard appears after clearing data in settings https://github.com/owncloud/android/issues/2135#issuecomment-378498173 [WONT FIX]
- [X] (7) Returning form folder with empty grid view to folder with list view makes app crash [FIXED]
- [X] (8) Upgrading wizard is not displayed [FIXED] 
- [x] (9) Allignment in welcome wizard https://github.com/owncloud/android/issues/2135#issuecomment-380525732

**Comment by davigonz** [comment]
### Bug (1)

**Steps to reproduce:**
1. Enable fingerprint lock.
2. Close the app.
3. Open the app.
4. Fingerprint dialog to unlock the app appears.
5. Tap any part of the white screen around the dialog.

**Current**: Fingerprint dialog disappears and screen keeps white, no action can be performed except pressing back button. 

**Expected**: No action when clicking around the dialog.

Tested with Nexus 5X v8.0.0

**Comment by davigonz** [comment]
### Bug (2)

**Steps to reproduce:**
1. Enable fingerprint lock
2. Press + button -> Upload button -> Picture from camera
3. Take a picture to be uploaded

**Current behaviour**: fingerprint is asked

**Expected behaviour**: fingerprint shouldn't be asked

Tested with Nexus 5X v8.0.0

**Comment by davigonz** [comment]
### Bug (3)

**Steps to reproduce:**
1. Press + button -> Upload button -> Picture from camera
2. Android system asks for different apps that can be used to take the picture

**Current behaviour**: file picker appears below the menu to choose the camera app.

**Expected behaviour**: file list should appear below the menu to choose the camera app.

Tested with Nexus 5X v8.0.0

**Comment by jesmrec** [comment]
###Bug (4)

Described in https://github.com/owncloud/android/issues/2159

**Comment by theScrabi** [comment]
Bug two https://github.com/owncloud/android/issues/2135#issuecomment-374153626

Not only applies to the new fingerprint, but also to pattern and pascode unlock.

**Comment by theScrabi** [comment]
I don't realy understand this one:
https://github.com/owncloud/android/issues/2135#issuecomment-374154688

What is the difference between a file picker, and a file list. Could you show me via screen shot?

**Comment by jesmrec** [comment]
> What is the difference between a file picker, and a file list. Could you show me via screen shot?

File picker: This is the file list that appears to select a target/source folder. You can reach it by tapping on FAB -> Upload -> Files
File list: The list of files in your ownCloud

**Comment by jesmrec** [comment]
> Not only applies to the new fingerprint, but also to pattern and pascode unlock. In case of pattern unlock this is nothing new then. So should I only add a fix for fingerprint unlock, or for all three?

i have noticed it. For this case, in which you are expecting a response from the camera, i would take the same fix for all three security methods, in order to keep the same behaviour. If the security is removed form this case, will any other cases be affected?

**Comment by theScrabi** [comment]
> will any other cases be affected?

No, we can make it very fine grained.

**Comment by jesmrec** [comment]
### Bug (5)

**Steps to reproduce:**
1. Enable pattern lock
2. Close the app and open again
3. When the pattern lock is asked, tap on "Back" button

**Current behaviour**:  pattern lock is skipped

**Expected behaviour**: pattern lock is not skipped.

Tested with Samsung Galaxy S7 v7

**Comment by sd1998** [comment]
@jesmrec I will fix this bug.

**Comment by theScrabi** [comment]
> @jesmrec I will fix this bug.

Thank you, but I already took care about that :D

**Comment by jesmrec** [comment]
### Bug (6)

**Steps to reproduce:**
1. Enable passcode after installing the app from scratch
2. Go to device settings -> ownCloud -> Storage 
3. There, clear data and cache
4. Open the app again

**Current behaviour**:  upgrading wizard is shown

**Expected behaviour**: upgrading wizard is not shown

Tested with Nexus 6P v7

**Comment by theScrabi** [comment]
> upgrading wizard is not shown

This is not something we can fix. Also it's not our concern, since other apps behave the same here.

**Comment by theScrabi** [comment]
### Bug (5)

**Steps to reproduce:**
1. set view to list view
2. create new folder
3. enter folder
4. set view to grid view
5. return to previous folder


**Current behaviour**:  app crashes

**Expected behaviour**: app not crashes

Tested with Galaxy tab S

**Comment by jesmrec** [comment]
Having some issues in installin a signed apk for release in order to test the upgrading from latest versions with the following error:

> Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

Checking it. Ideas are welcome, of course.

**Comment by davigonz** [comment]
> Having some issues in installing a signed apk for release in order to test the upgrading from latest versions with the following error

@jesmrec it's working fine for me, I've just updated the version number and name in case it was related. Can you give it another try?

**Comment by jesmrec** [comment]
It worked after your fix. Thanks @davigonz

**Comment by jesmrec** [comment]
I also detected that the upgrading wizard is not being displayed. could you check?

**Comment by davigonz** [comment]
> I also detected that the upgrading wizard is not being displayed. could you check?

Yes, I'm on it

**Comment by davigonz** [comment]
### Bug (8) [READY TO TEST] 

**Steps to reproduce:**
1. Install 2.6.0 version
2. Open the app and log in
3. Install 2.7.0 version
4. Open the app


**Current behaviour**:  upgrading wizard doesn't appear

**Expected behaviour**: upgrading wizard should appear

Tested with Nexus 5

**Comment by jesmrec** [comment]
after the fix in (8) bug, i get again the error

> Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

after installing a signed-for-release apk

**Comment by jesmrec** [comment]
Problem fixed. Depending on the android version, it is needed a different version of the signing algorithm

**Comment by jesmrec** [comment]
Regression test passed. Version approved.

**Comment by davigonz** [comment]
> Regression test passed. Version approved.

Awesome, let's move forward this

**Comment by jesmrec** [comment]
I detected a small defect. These are the steps:

- Set the device in a non-english language (Spanish, German...)
- Install the app from scratch

Current: In the first slide of the welcome wizard, the title is alligned to the left, and not to the center
Expected: all slides' titles are alligned to the center.

@davigonz @theScrabi
