### ISSUE TITLE
[2.7.0 beta v1] Release new beta version

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2147]
### TASKS:
 - [X] [COORDINATION] Create task in [Community Management](https://kanboard.owncloud.com/board/22) board to publish a blog post, several days before releasing: https://kanboard.owncloud.com/project/22/task/1867
 - [x] [DEV] Create **2.7.0_beta_v1** branch from master and:
         - Get rid of previous beta implementation.
         - Update version code and name in build.gradle.
         - Update changelog file (< 500 chars)
 - [X] [DEV] Adapt wizard in **whatsNew_2.7.0** to new beta implementation
 - [X] [DEV] Merge **whatsNew_2.7.0** branch into **2.7.0_beta_v1**
 - [x] [DEV] Adjust whatsNew params to show 2.7.0 features in 2.7.0 beta.
 - [x] [QA] Perform some tests @jesmrec
 - [x] [DEV] Merge **2.7.0_beta_v1** branch into master in owncloud/android https://github.com/owncloud/android/pull/2064
 - [x] [DIS] Generate test APKs files from branch master in owncloud/android 
 - [x] [GIT] Create and sign tag oc-android-2.7.0-beta.1 in HEAD commit of master branch, in owncloud/android 
- [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new pre-release 2.7.0 beta
 - [x] [DIS] Generate final APK files from signed commit in owncloud/android and perform some basic operations
_____
### F-DROID:
 - [x] [RESEARCH] Same package name for beta an final releases in F-Droid
 - [x] [DIS] Delete beta app
 - [x] [DEV] Create MR in F-Droid repo https://gitlab.com/fdroid/fdroiddata/merge_requests/3005
-  [x] [DEV] Merge MR into F-Droid. 
-  [x]  [DIS] MR has had effect: F-Droid sets 2.6.0 as active version (with a white star) in Versions tab and 2.7.0-beta.1 appears at the top of the list.
_____
### PLAY STORE:
 - [x] [DIS] Unpublish beta app
 - [x] [DIS] Create new beta program and upload beta APK

_____
### FINAL TASKS:
 - [x] [SPREADTHEWORD] Write a topic in central about the beta release. https://central.owncloud.org/t/owncloud-android-2-7-0-beta-app-released/12528
-  [x] [SPREADTHEWORD] Share new beta on social media.

**Comment by davigonz** [comment]
Before deleting the previous beta configuration, we need to know if F-Droid supports beta and final release with just one package name, as PlayStore does with beta program. @theScrabi is trying to figure out whether that is possible or not in F-Droid.

**Comment by theScrabi** [comment]
> [RESEARCH] Same package name for beta an final releases in F-Droid [WIP] @theScrabi

According to [this](https://forum.f-droid.org/t/how-to-mark-releases-as-pre-releases/1246/9) commend from krt it is possible to have beta and non beta application within the same package name. An example for that was the package of the fdroid app itself: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.fdroid.fdroid.txt

**Comment by davigonz** [comment]
@jesmrec @theScrabi 2.7.0 beta is already tagged and released on our Github repository, next week we will continue with F-Droid and PlayStore.

**Comment by theScrabi** [comment]
Fdroid PR for new beta release [is out](https://gitlab.com/fdroid/fdroiddata/merge_requests/3005).

**Comment by davigonz** [comment]
> Fdroid PR for new beta release is out.

@theScrabi great, please update the F-Droid tasks in the first comment, I mean, check the ones that are finished.

**Comment by davigonz** [comment]
Our feedback channel for beta will be [https://github.com/owncloud/android/issues](https://github.com/owncloud/android/issues) from now on, any suggestion is welcome anyway.

**Comment by jesmrec** [comment]
i think apps mail should be included as well

**Comment by davigonz** [comment]
> i think apps mail should be included as well

@jesmrec only one feedback channel is allowed 😕

**Comment by jesmrec** [comment]
oooh... i did not expect that. In this case, maybe should we centralize the feedback in one issue?

**Comment by theScrabi** [comment]
So [2.7.0-beta.1](https://f-droid.org/packages/com.owncloud.android/) is now available on fdroid, however fdroid failed to mark it as a beta release, so now it's available as release. I already fixed it however, we still wait for an fdroid maintainer to eventually merge our [pull request](https://gitlab.com/fdroid/fdroiddata/merge_requests/3005).

**Comment by theScrabi** [comment]
Merge request for fdroid repository was merged. And exidental wrong release got fixed.

**Comment by davigonz** [comment]
@theScrabi I've downloaded F-Droid with no ownCloud app installed and seen that Version 2.7.0-beta.1 is the active version when Version 2.6.0 should be the active one

**Comment by theScrabi** [comment]
This is what that pull request should fix. Because of the way the server understood the regex, he thought beta was a release, and added it automatically.

**Comment by mueller-ma** [comment]
Nextcloud releases their beta version under a different package name, so people can install both apps alongside: https://f-droid.org/packages/com.nextcloud.android.beta/
Is there something against this for owncloud?

**Comment by theScrabi** [comment]
Yes we figured that when people use both they would not test the beta application well enough, so we thought about changing this and make users use either beta or the stable.

**Comment by jesmrec** [comment]
Beta released and available
