### ISSUE TITLE
Use a more recent and trustable network library

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2180]
After researching about the available Android network libraries out there and performing some tests by using our sample client app (more details in https://github.com/owncloud/android-library/issues/51), we have finally made the decision to get rid of Jackrabbit WebDAV library and implement [OkHttp](https://github.com/square/okhttp) 3.10.0
___

**TOPICS TO DISCUSS**

1. Include tests by using [OkHttp MockWebServer ](https://github.com/square/okhttp/tree/master/mockwebserver)
___

**TASKS**

1. Involving the app

- [x] Adapt the new OwnCloudClient uses. 
- [ ] Add dav4android link in Settings page. [WIP] @davigonz 

2. Involving the library https://github.com/owncloud/android-library/issues/51
___

**RELATED ISSUES**

- [x] Send a unique X-Request-ID header to allow tracing requests in apache and owncloud logs owncloud/android#2055

- [ ] Multiaccount OAuth2 - basic owncloud/android#2095 [READY TO TEST]

CC / @michaelstingl @jesmrec @theScrabi

**Comment by davigonz** [comment]
To be released in 2.9
