### ISSUE TITLE
As a user, I would like to know the space remaining in my account

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2205]
It would be great to have this feature included in our side menu for example, as suggested [here](https://github.com/owncloud/android/issues/2204).

There's a pretty old PR, https://github.com/owncloud/android/pull/737 that follows a different approach, creating a specific activity to show the quota. Although we can use the library PR maybe, https://github.com/owncloud/android-library/pull/102 and take advantage of `GetRemoteUserQuotaOperation`

___

**TASKS**

- [X] [LIBRARY] Get quota from the server by using GetRemoteUserQuotaOperation. **Already merged via https://github.com/owncloud/android-library/pull/102**
- [X] [APP] Get quota when getting user profile info and stores it in DB. 
- [X] [APP] Include quota in drawer menu, handling different cases with quotas using MB or GB
- [X] [APP] Handle pending, unknown and unlimited quota, switch to WebDAV endpoint. Related: https://github.com/owncloud/core/issues/31376
- [X] [APP] Handle quota 0

**Comment by theScrabi** [comment]
Related to this: https://github.com/owncloud/android/issues/2204

We can put a mark in the sidebar, an optional show more detailed information if one tabs on that mark.

**Comment by davigonz** [comment]
Here we go with some screenshots so you can see how this feature is gonna look like:


| Limited quota | Unlimited quota |
| ------------- | ------------- |
| ![limited](https://user-images.githubusercontent.com/15261363/39805633-b553bf78-5377-11e8-872e-718322349fc8.png) | ![unlimited](https://user-images.githubusercontent.com/15261363/39805641-baeb4fe6-5377-11e8-81ad-b7a28e60ceef.png) |
