### ISSUE TITLE
[2.8.0 beta v1] Release new beta version

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2221]
### TASKS:
 - [x] [COORDINATION] Create task in [Community Management](https://kanboard.owncloud.com/board/22) board to publish a blog post, several days before releasing
 - [x] [DEV] Create **2.8.0_beta_v1** branch from master and:
         - Update naming of drawer resources to be brandable. Have a look at https://github.com/owncloud/ownbrander/issues/801
         - Update version code and name in build.gradle.
         - Update changelog file (< 500 chars)
 - [x] [QA] Perform some tests @jesmrec
 - [x] [DEV] Merge **2.8.0_beta_v1** branch into master in owncloud/android 
 - [x] [DIS] Generate test APKs files from branch master in owncloud/android 
 - [x] [GIT] Create and sign tag oc-android-2.8.0-beta.1 in HEAD commit of master branch, in owncloud/android 
- [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new pre-release 2.8.0 beta
 - [x] [DIS] Generate final APK files from signed commit in owncloud/android and perform some basic operations
_____
### PLAY STORE:
 - [x] [DIS] Upload & publish beta release APK and changelog
_____
### F-DROID:
 - [x] [DEV] Create MR in F-Droid repo to include 2.8.0 beta build https://gitlab.com/fdroid/fdroiddata/merge_requests/3274
-  [x] [DEV] Merge MR into F-Droid. 
_____
### FINAL TASKS:
 - [x] [SPREADTHEWORD] Write a topic in central about the beta release. https://central.owncloud.org/t/owncloud-android-2-8-0-beta-app-released/13853
 - [x] [SPREADTHEWORD] Share new beta on social media.
_____
_____
### BUGS & IMPROVEMENTS:
 - [X] (1) Crash when sharing content with no internet connection [FIXED]
 - [x] (2) Downloaded file size not properly shown [FIXED]
-  [X] (3) Quota after upgrading https://github.com/owncloud/android/issues/2221#issuecomment-393054094 [FIXED]
- [x] (4) Thumbnail in share view https://github.com/owncloud/android/issues/2221#issuecomment-393061414 [FIXED]
- [x] (5) Drawer cloud in the way on phones with small screens https://github.com/owncloud/android/issues/2221#issuecomment-393135456 -> will be brandable
- [X] (6) Translations of new drawer options https://github.com/owncloud/android/issues/2221#issuecomment-393443100 [TRANSIFEX]
- [X] (7) Crash when disabling camera uploads https://github.com/owncloud/android/issues/2221#issuecomment-393453529 [FIXED]
- [X] (8) Crash when tap on square button https://github.com/owncloud/android/issues/2221#issuecomment-393454263 [FIXED]

**Comment by davigonz** [comment]
### Bug (2) 

**Steps to reproduce:**

1. Download a file
2. Wait till is completely downloaded
3. Swipe down the notifications bar

**Current:** Downloaded file size is not properly set, something like `%1$s downloaded` appears.

[<img src="https://user-images.githubusercontent.com/15261363/40610471-c54a5e28-6272-11e8-9449-9409876d5c3a.png" width="300px"/>](https://user-images.githubusercontent.com/15261363/40610471-c54a5e28-6272-11e8-9449-9409876d5c3a.png)

**Expected:** Downloaded file size is properly shown

Tested with Nexus 6P v7.1.2

**Comment by theScrabi** [comment]
fixed https://github.com/owncloud/android/issues/2221#issuecomment-392487886

**Comment by davigonz** [comment]
@jesmrec initial tasks done, ready to test

**Comment by jesmrec** [comment]
### (3)

Steps:

1. Install 2.7.0 (previous release)
2. Upgrade to beta

Current: Quota is displayed as `Loading quota` forever
Expected: Quota is displayed correctly

Tested with Nexus 6P v7.1.2

**Comment by jesmrec** [comment]
### (4)

Steps:

1. Open share view of any file

Current: Thumbnail (top left corner) is too small

![screen shot 2018-05-30 at 09 37 44](https://user-images.githubusercontent.com/14894746/40706154-25aaceda-63ed-11e8-8e29-e4f0acb94393.png)


Expected: as before

![screen shot 2018-05-30 at 09 35 41](https://user-images.githubusercontent.com/14894746/40706091-004cab04-63ed-11e8-8c4d-6d2d68088849.png)

**Comment by theScrabi** [comment]
fixed https://github.com/owncloud/android/issues/2221#issuecomment-393061414

**Comment by theScrabi** [comment]
I noticed that the items in the drawer overlap the cloud in portrait mode if the screen of the phone is to small.
![image](https://user-images.githubusercontent.com/1891273/40718856-cfa13f36-6411-11e8-8161-825953ebe559.png)

**Comment by theScrabi** [comment]
I noticed that the items in the drawer overlap the cloud in portrait mode if the screen of the phone is to small.
![image](https://user-images.githubusercontent.com/1891273/40718963-1fed64f6-6412-11e8-8930-c335d01a7513.png)

**Comment by jesmrec** [comment]
i think that the cloud image as background does not look bad at all

**Comment by jesmrec** [comment]
@michaelstingl yes, we have taken it in account. This oB issue is opened: https://github.com/owncloud/ownbrander/issues/801

**Comment by theScrabi** [comment]
> i think that the cloud image as background does not look bad at all

It should be lighter if we want it to be a background image. @davigonz and me decided to not show it behind the items. Therefore I removed it on smaller screens now.

**Comment by jesmrec** [comment]
### (6)

The new options in the drawer has some dependency on the device language. For example, the spanish translation for `Feedback` is  `Mensajes de retroalimentación` (https://github.com/owncloud/android/blob/5f54c3aa83f894eacf02637a61004b0b3ff85a9e/res/values-es/strings.xml#L31)

there is not enough room for such translation:

![device-2018-05-31-094714](https://user-images.githubusercontent.com/14894746/40769335-02df7920-64b8-11e8-8922-7a83e9622a73.png)

this is only an example, maybe translations in other languages for other options in the drawer happens the same.

**Comment by davigonz** [comment]
> It should be lighter if we want it to be a background image. @davigonz and me decided to not show it behind the items. Therefore I removed it on smaller screens now.

@theScrabi It is not possible to include the cloud resource in ldpi or mdpi resources so it looks smaller?

**Comment by davigonz** [comment]
> there is not enough room for such translation:

@jesmrec IMHO, we cannot handle this in a proper way unless we include a better translation, because ellipsizing the text like `Mensajes de... wouldn't work` for us either. 

What about "Sugerencias"?

**Comment by jesmrec** [comment]
it is an option, i like als other ones like: `Dános tu Feedback` or  `Dános tu opinión`. But, if we can not handle the room for the length of the options (technical fix), it is out of the scope and we can fix it it transifex.

**Comment by jesmrec** [comment]
### (8)

maybe same bug as (7)

Steps:

1. Install the app in a device with Android 8
2. Go to settings, and enable either `Picture upload` or `Video Uploads`
3. Tap on the square button to switch to another app

Current: app crashes
Expected: no crash

**Comment by jesmrec** [comment]
All stuff fixed and test performed. approved.

**Comment by davigonz** [comment]
> All stuff fixed and test performed. approved.

Great @jesmrec , can you please review the [changelog](https://github.com/owncloud/android/pull/2231/files) before merging the beta branch?

**Comment by jesmrec** [comment]
Changelog is correct 👍

**Comment by theScrabi** [comment]
[PR for f-droid](https://gitlab.com/fdroid/fdroiddata/merge_requests/3274) got created
