### ISSUE TITLE
[2.8.0] New release

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2238]
### TASKS
- [x] [WIZARD] Create new steps with important features included in 2.8.0 https://github.com/owncloud/android/issues/2244
- [x] [COORDINATION] Ping community guys to publish a blog post, at least one week before releasing.
 - [x] [GIT] Create branch release_0.9.20 in owncloud/android-library from master, if needed
 - [x] [GIT] Create branch release_2.8.0 in owncloud/android from master 
 - [x] [DEV] Update version number and name in build.gradle in android module
 - [x] [DEV] Update version number and name in build.gradle in oc_jb_workaround module 
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android 
 - [x] [QA] Design Test plan @jesmrec
 - [x] [QA] Regression Test plan  @jesmrec 
 - [x] [GIT] Merge branch release_0.9.20 in owncloud/android-library, into master, if needed
 - [x] [GIT] Merge branch release_2.8.0 in owncloud/android, into master 
 - [x] [DIS] Generate test APKs files from branch master in owncloud/android and perform some basic operations.
 - [x] [GIT] Create and sign tag oc-android-2.8.0 in HEAD commit of master branch, in owncloud/android 
 - [x] [GIT] Create and sign tag oc-android-library-0.9.20 in HEAD commit of master branch, in  #owncloud/android-library 
- [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new release 2.8.0 
 - [x] [DIS] Generate final APK files (including oc_jb_workaround) from signed commit in owncloud/android
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [DIS] push OC JB workaround app to Play Store.
 - [x] [DIS] Upload APKs to repo
 - [x] [SPREADTHEWORD] Write a topic in central about the release. https://central.owncloud.org/t/owncloud-android-app-2-8-0-released/
 - [x] [COORDINATION] Write in corresponding channels.
 - [x] [COORDINATION] Write email to release-coordination mailing list.
 - [x] [SPREADTHEWORD] Write a post in the blog
 - [ ] [DOC] Update documentation with the new features. @settermjd 
 - [x] Publish app in F-Droid 
 - [x] [GIT] merge master branch into stable, in owncloud/android-library
 - [x] [GIT] merge master branch into stable, in owncloud/android

_____
### BUGS & IMPROVEMENTS:

- [x] (1) SAML session expiration does not prompt to login https://github.com/owncloud/android/issues/2238#issuecomment-396660454 [FIXED]
- [x] (2) Toast instead of snackbar https://github.com/owncloud/android/issues/2238#issuecomment-400748691
- [X] (3) Maintenance mode points to authentication error https://github.com/owncloud/android/issues/2238#issuecomment-400932784 [FIXED]
- [x] (4) Toast in copy/move/rename/removed https://github.com/owncloud/android/issues/2238#issuecomment-400949114 [FIXED] 
- [X] (5) Bad error when trying to share with a sharee https://github.com/owncloud/android/issues/2238#issuecomment-401341095 [FIXED] 
- [X] (6) Error when account is deleted https://github.com/owncloud/android/issues/2238#issuecomment-402092692 [FIXED]
- [X] (7) fingerprint lock blocks after upgrading https://github.com/owncloud/android/issues/2238#issuecomment-402517259 [FIXED]

**Comment by jesmrec** [comment]
### (1)

Steps:

1. Open a SAML session and wait until it expires

Current: Snackbar shown and redirected to list of servers. 
Expected: Session is expired, so the only think the user is able to do is login again. 

This issue is caused by https://github.com/owncloud/android/pull/2175, that is valid for basic and OAuth2 where sessions do not expire (only in case of token revokation in OAuth2).

**Comment by davigonz** [comment]
This is ready to code review @theScrabi and QA @jesmrec

**Comment by jesmrec** [comment]
### (2)

Steps:

1. Switch connection off
2. Try to delete/rename/move any item

Current: Error message in a Toast
Expected: Error message in a Snackbar (this is the behaviour in the previous version 2.7.0)

**Comment by jesmrec** [comment]
### (3)

Steps:

1. In server, set maintenance mode (`sudo -u www-data ./occ maintenance:mode --on`)
2. In app, perform any action 

Current: Authentication failed (error 503 is returned)
Expected: System in maintenance mode

**Comment by jesmrec** [comment]
### (4)

Bug (2) also reproducible with the following steps:

1. Select to copy/move items to a new location
2. In web UI, remove the target folder
3. In the app, confirm the operation

Current: Error message in a Toast
Expected: Error message in a Snackbar

**Comment by theScrabi** [comment]
https://github.com/owncloud/android/issues/2238#issuecomment-400748691

fixed

**Comment by theScrabi** [comment]
(3) https://github.com/owncloud/android/issues/2238#issuecomment-400932784
fixed

**Comment by theScrabi** [comment]
(4) https://github.com/owncloud/android/issues/2238#issuecomment-400949114

fixed

**Comment by jesmrec** [comment]
About (3), you set a new message:

https://github.com/owncloud/android/blob/7aad9eb2201063e7606f8680ceb9e9f2681dd711/res/values/strings.xml#L79

Message in 2.7.0 and older is the same you are comparing with, and i think this is the message to be displayed

https://github.com/owncloud/android/blob/7aad9eb2201063e7606f8680ceb9e9f2681dd711/src/com/owncloud/android/ui/activity/FileDisplayActivity.java#L1068

**Comment by theScrabi** [comment]
> Message in 2.7.0 and older is the same you are comparing with, and i think this is the message to be displayed

Ok, I thought I'll make it translatable.
However It came in my mind that maybe the error message send by the server is already translated. Could that be?

**Comment by jesmrec** [comment]
### (5)

Steps:

1. Share content with a user
2. Try to share again with the same user

Current: `It is not posible to move folder into a descendant`
Expected: `Path already shared with this user`

Android 6

**Comment by davigonz** [comment]
(5) https://github.com/owncloud/android/issues/2238#issuecomment-401341095

Fixed

**Comment by jesmrec** [comment]
### (6)

Steps:

1. Login in a basic auth account
2. In server, remove the account
3. In app, pull to refresh or perform any action

Current: `Error: Call to member function getUID() on null`
Expected: Authentication error and link to change account

Android 7 & 8

**Comment by theScrabi** [comment]
[error (3)](https://github.com/owncloud/android/issues/2238#issuecomment-400932784) and [error (6)](https://github.com/owncloud/android/issues/2238#issuecomment-402092692) somehow block each other.

If the cloud is in maintaincance mode it will send a 503 "Service unavailable" which tells us directly that the cloud is not available at the moment. However if one delets an account a 503 is also returned for a PROPFIND. Thus if we are doing only a propfind we can not decide what was the actual cause for the 503.

**Comment by theScrabi** [comment]
ok i found a way by looking into the httpPhrase returned together with the httpcode.

**Comment by theScrabi** [comment]
nr. 6 fixed

**Comment by jesmrec** [comment]
### (7)

To reproduce, it is needed a device with fingerprint lock support

Steps:

1. Install 2.7.0
2. Attach an account and in settings, enable passcode + fingerprint lock
3. Upgrade to 2.8.0 (upgrade wizard appears)
4. Browse through the wizard and tap on the tick of the last slide

Current: Fingerprint asked. By putting your correct finger, app is unlocked with the blue background of the wizard
Expected: By unlocking the app, file list is displayed.

Android 7 & 8

**Comment by davigonz** [comment]
(7) https://github.com/owncloud/android/issues/2238#issuecomment-402517259 fixed

**Comment by jesmrec** [comment]
All stuff fixed and approved. Ready to go.

**Comment by davigonz** [comment]
@theScrabi any update on F-Droid release?

**Comment by jesmrec** [comment]
who is taking care about the documentation? @settermjd?

**Comment by jesmrec** [comment]
Documentation issue, moved to ongoing 2.9.0 https://github.com/owncloud/android/issues/2291

CC @settermjd
