### ISSUE TITLE
[2.9.0 beta v1] Release new beta version

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2289]
### TASKS:
 - [x] [COORDINATION] Get in touch with community/marketing team to publish a blog post, several days before releasing.
 - [x] [DEV] Use **replace_network_library** branch and:
         - Update version code and name in build.gradle.
         - Update changelog file (< 500 chars)
 - [x] [QA] Perform some tests @jesmrec
 - [x] [GIT] Create and sign tag `oc-android-2.9.0-beta.1` in `HEAD` commit of **replace_network_library** branch, in owncloud/android 
 - [x] [QA] Generate final APK files from signed commit in owncloud/android and perform some basic operations
- [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new pre-release 2.9.0 beta
_____
### PLAY STORE:
 - [x] [DIS] Upload & publish beta release APK and changelog 
_____
### F-DROID:
 - [x] [DEV] Create MR in F-Droid repo to include 2.9.0 beta build https://gitlab.com/fdroid/fdroiddata/merge_requests/3680
-  [x] [DEV] Merge MR into F-Droid. 
_____
### FINAL TASKS:
 - [x] [SPREADTHEWORD] Write a topic in central about the beta release. https://central.owncloud.org/t/owncloud-2-9-beta-app-for-android-released/
 - [x] [SPREADTHEWORD] Share new beta on social media.

**Comment by davigonz** [comment]
@jesmrec versionCode, versionName and changelog updated, time for a tiny QA round

**Comment by jesmrec** [comment]
Some test will be executed: 

- [ ] Upgrade version from 2.8.0
- [ ] Add several accounts
- [ ] Download files
- [ ] Upload files
- [ ] Share content
- [ ] Passcode, pattern and fingerprint lock

**Comment by jesmrec** [comment]
### (1)

1. Install 2.8.0
2. Upgrade to 2.9.0 beta1

Current: app crashes
Expected: regular behaviour after upgrading

Nexus 6P v7

**Comment by davigonz** [comment]
@jesmrec first bug fixed

**Comment by jesmrec** [comment]
Smoke test finished, we can move forward the beta @davigonz

**Comment by jesmrec** [comment]
Reported issue: https://github.com/owncloud/android/issues/2294

Not reproducible in my side, because with Samsung Galaxy Edge (Android 7), changing folder leads to a crash.

**Comment by davigonz** [comment]
F-Droid PR to include this beta is already merged so it should be available soon.
