### ISSUE TITLE
[2.9.0] New release

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2291]
### TASKS
- [ ] [WIZARD] Create new steps with important features included in 2.9.0 https://github.com/owncloud/android/issues/2244
 - [ ] [COORDINATION] Ping community guys to publish a blog post, at least one week before releasing.
 - [ ] [GIT] Create branch release_0.9.21 in owncloud/android-library from master, if needed
 - [ ] [GIT] Create branch release_2.9.0 in owncloud/android from master 
 - [ ] [DEV] Update version number and name in build.gradle in android module
 - [ ] [DEV] Update version number and name in build.gradle in oc_jb_workaround module 
 - [ ] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android 
 - [ ] [QA] Design Test plan @jesmrec
 - [ ] [QA] Regression Test plan  @jesmrec 
 - [ ] [GIT] Merge branch release_0.9.21 in owncloud/android-library, into master, if needed
 - [ ] [GIT] Merge branch release_2.9.0 in owncloud/android, into master 
 - [ ] [DIS] Generate test APKs files from branch master in owncloud/android and perform some basic operations.
 - [ ] [GIT] Create and sign tag oc-android-2.9.0 in HEAD commit of master branch, in owncloud/android 
 - [ ] [GIT] Create and sign tag oc-android-library-0.9.21 in HEAD commit of master branch, in  #owncloud/android-library 
- [ ] [DOC] Include new changelog on Releases section of github android repo by drafting the new release 2.9.0 
 - [ ] [DIS] Generate final APK files (including oc_jb_workaround) from signed commit in owncloud/android
 - [ ] [DIS] Upload & publish release APK and changelog in Play Store
 - [ ] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [ ] [DIS] push OC JB workaround app to Play Store.
 - [ ] [DIS] Upload APKs to repo
 - [ ] [SPREADTHEWORD] Write a topic in central about the release. 
 - [ ] [COORDINATION] Write in corresponding channels.
 - [ ] [COORDINATION] Write email to release-coordination mailing list.
 - [ ] [SPREADTHEWORD] Write a post in the blog
 - [ ] [DOC] Update documentation with the new features. @settermjd 
 - [ ] Publish app in F-Droid 
 - [ ] [GIT] merge master branch into stable, in owncloud/android-library
 - [ ] [GIT] merge master branch into stable, in owncloud/android

_____
### BUGS & IMPROVEMENTS:

- [ ] (1) Wrong error message when sharing a file with same user as the active account

**Comment by jesmrec** [comment]
### (3)

1. Remove connection from device
2. Share a file or folder with a user

Current: no error message about lack of connection
Expected: error message (in 2.8.0 was displayed in a Toast)

Nexus 6P v7 server 10.0.10

**Comment by jesmrec** [comment]
### (4)

1. Open Settings view
2. Enable Picture or video uploads
3. Tap on Picture/video upload path

Current: `Cancel` button with incorrect label
Expected: Correct label in `Cancel` button

Nexus 6P v7 server 10.0.10

**Comment by jesmrec** [comment]
### (5)

1. Copy text from an app out of ownCloud (browser, text editor...)
2. Share the copied text with oC (no matter the account and the target folder)
3. Enter a file name

Current: file is not uploaded to oC
Expected: file is uploaded to oC

Nexus 6P v7 server 10.0.10

**Comment by jesmrec** [comment]
### (6)

1. Open a 3rd party app with Document Provider integration
2. Check that oC accounts are correctly there
3. Do any modification in the accounts (remove one, add another one...)
4. Check again the Document Provider account list

Current: Same accounts in 2.. To refresh, it is necesary to reboot the device
Expected: Hot updates(?)

Nexus 6P v7 server 10.0.10

**Comment by jesmrec** [comment]
### (7)

1. User A shares a folder with user B, with no edit permissions 
2. User B uploads a file to the shared folder

Current: Content is uploaded, is shown during a while in the file list, and then is deleted. Upload is successful in uploads view

Expected: Failed upload due to a lack of permissions

NOTE: delete and change operations work as expected (error correct)

Nexus 6P v7 server 10.0.10

**Comment by davigonz** [comment]
[Document provider account manager](https://github.com/owncloud/android/issues/2291#issuecomment-434707232) was not properly working in <= 2.8 either so is not a regression bug and is not going to be fixed here, we could open a ticket with all the left work for document provider.

CC / @jesmrec

**Comment by davigonz** [comment]
[Upload file to a banned folder ](https://github.com/owncloud/android/issues/2291#issuecomment-434760233) bug is server related so is not going to be fixed for this release, have a look at https://github.com/owncloud/android/issues/2070#issuecomment-435377083, I will open a new issue in core with the details.

**Comment by jesmrec** [comment]
### (8)

1. Start to download a file in the app (a big one is better to reproduce)
2. Minimize the app
3. Before the download finishes, switch the connection off
4. Wait some minutes
5. Switch connection on

Current: app crashes
Expected: download is resumed

Nexus 5X v8.1 server 10.0.10

**Comment by jesmrec** [comment]
All stuff fixed, we will deal with two additional issues:

- Document provider will be improved. I will create a new issue about
- Problem in server side regarding chunked uploads: https://github.com/owncloud/core/issues/33416

Ready for the markets

**Comment by davigonz** [comment]
@settermjd can you take care of the documentation for ownCloud 2.8 and 2.9 for Android? Here you have the topics in central with more information about the features included:

- 2.8.0 => https://central.owncloud.org/t/owncloud-android-app-2-8-0-released/
- 2.9.0 => https://central.owncloud.org/t/owncloud-2-9-for-android-released/16634/2

**Comment by esackbauer** [comment]
There seems to be a major issue in 2.90:
https://github.com/owncloud/android/issues/2338

**Comment by davigonz** [comment]
> There seems to be a major issue in 2.90: #2338
Fixed and included in 2.9.1
