### ISSUE TITLE
[2.9.0 beta v2] Release new beta version

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2313]
### TASKS:
 - [x] [COORDINATION] Get in touch with community/marketing team to publish a blog post, several days before releasing.
 - [x] [DEV] Use **fix/av_offline_jobs** branch and:
         - Update version code and name in build.gradle.
         - Update changelog file (< 500 chars)
 - [x] [QA] Perform some tests @davigonz 
    - Install `2.9.0-beta1` or `2.8.0 `
    - Add a couple of accounts
    - Enable passcode, fingerprint, camera uploads
    - Set some files and folders as available offline
    - Upgrade to` 2.9.0-beta2` and check whether the configuration previously set keeps the same or not.
 - [x] [GIT] Create and sign tag `oc-android-2.9.0-beta.2` in `HEAD` commit of **fix/av_offline_jobs** branch, in owncloud/android 
 - [x] [QA] Generate final APK files from signed commit in owncloud/android and perform some basic operations
 - [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new pre-release `2.9.0 beta v2`
_____
### PLAY STORE:
 - [x] [DIS] Upload & publish beta release APK and changelog 
_____
### F-DROID:
 - [x] [DEV] Create MR in F-Droid repo to include 2.9.0 beta v2 build https://gitlab.com/fdroid/fdroiddata/merge_requests/3778
-  [x] [DEV] Merge MR into F-Droid. 
_____
### FINAL TASKS:
 - [x] [SPREADTHEWORD] Write a topic in central about the beta release. https://central./owncloud.org/t/owncloud-2-9-beta-2-for-android-released
 - [x] [SPREADTHEWORD] Share new beta on social media.
_____
### BUGS & IMPROVEMENTS:
- [x] (1) Crash when moving, copying or choosing a folder within camera uploads folder. [FIXED]
