### ISSUE TITLE
[2.9.1] New release with LDAP hot fix

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2340]
### TASKS
 - [x] [GIT] Create branch `release_2.9.1` in owncloud/android from master
 - [x] [GIT] Create branch `release_0.9.22` in owncloud/android-library from master 
 - [x] [DEV] Update version number and name in build.gradle in android module
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [x] [WIZARD] Show wizard when upgrading to 2.9 or 2.9.1
 - [x] [QA] Design Test plan @jesmrec
 - [x] [QA] Regression Test plan  @jesmrec 
 - [x] [GIT] Merge branch `release_0.9.22` in owncloud/android-library, into master, if needed
 - [x] [GIT] Merge branch `release_2.9.1` in owncloud/android, into master 
 - [x] [DIS] Generate test APKs files from branch master in owncloud/android and perform some basic operations.
 - [x] [GIT] Create and sign tag `oc-android-2.9.1` in HEAD commit of master branch, in owncloud/android 
 - [x] [GIT] Create and sign tag `oc-android-library-0.9.22` in HEAD commit of master branch, in  #owncloud/android-library 
- [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new release 2.9.1
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [SPREADTHEWORD] Write a topic in central about the release. https://central.owncloud.org/t/owncloud-2-9-1-for-android-with-ldap-hot-fix/16659/2
 - [x] [COORDINATION] Write in corresponding channels.
 - [x] [SPREADTHEWORD] Write a post in the blog @lefherz 
 - [x] Publish app in F-Droid https://gitlab.com/fdroid/fdroiddata/merge_requests/3912
 - [x] [GIT] merge master branch into stable, in owncloud/android-library
 - [x] [GIT] merge master branch into stable, in owncloud/android

_____
### RELATED

https://github.com/owncloud/android/issues/2338

**Comment by jesmrec** [comment]
Tests:

- [ ] Login with LDAP-uid + browsing
- [ ] Login with LDAP-username + browsing
- [ ] Upgrade from 2.9.0 LDAP 
- [ ] Upgrade from 2.9.0 basic auth 
- [ ] Upgrade from 2.8.0 LDAP 
- [ ] Upgrade from 2.8.0 basic auth 
- [ ] Smoke test basic auth
- [ ] Smoke test OAuth2

**Comment by jesmrec** [comment]
tests finished.
