### ISSUE TITLE
[2.9.2] New release

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2353]
### TASKS
 - [x] [GIT] Create branch `release_2.9.2` in owncloud/android from master
 - [x] [GIT] Create branch `release_0.9.23` in owncloud/android-library from master 
 - [ ] [DEV] Update version number and name in build.gradle in android module
 - [ ] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [ ] [WIZARD] Show wizard when upgrading to 2.9 or 2.9.2
 - [ ] [QA] Design Test plan @jesmrec
 - [ ] [QA] Regression Test plan  @jesmrec 
 - [ ] [GIT] Merge branch `release_0.9.23` in owncloud/android-library, into master, if needed
 - [ ] [GIT] Merge branch `release_2.9.2` in owncloud/android, into master 
 - [ ] [DIS] Generate test APKs files from branch master in owncloud/android and perform some basic operations.
 - [ ] [GIT] Create and sign tag `oc-android-2.9.2` in HEAD commit of master branch, in owncloud/android 
 - [ ] [GIT] Create and sign tag `oc-android-library-0.9.23` in HEAD commit of master branch, in  #owncloud/android-library 
- [ ] [DOC] Include new changelog on Releases section of github android repo by drafting the new release 2.9.2
 - [ ] [DIS] Upload & publish release APK and changelog in Play Store
 - [ ] [SPREADTHEWORD] Write a topic in central about the release.
 - [ ] [COORDINATION] Write in corresponding channels.
 - [ ] [SPREADTHEWORD] Write a post in the blog @lefherz 
 - [ ] Publish app in F-Droid https://gitlab.com/fdroid/fdroiddata/merge_requests/3912
 - [ ] [GIT] merge master branch into stable, in owncloud/android-library
 - [ ] [GIT] merge master branch into stable, in owncloud/android

_____
### RELATED

https://github.com/owncloud/android/issues/2347

**Comment by jesmrec** [comment]
Checks to do:

- [ ] https://github.com/owncloud/android/issues/2347 fixed
- [ ] Upgrade 2.8.0 -> 2.9.2 (Wizard)
- [ ] Upgrade 2.9.0 -> 2.9.2 (no Wizard)
- [ ] Upgrade 2.9.1 -> 2.9.2 (no Wizard)
