### ISSUE TITLE
[2.9.3] New release with usernames containing @ hotfix

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2364]
### TASKS
 - [x] [GIT] Create branch `release_2.9.3` in owncloud/android from master
 - [x] [GIT] Create branch `release_0.9.24` in owncloud/android-library from master 
 - [x] [DEV] Update version code and name in build.gradle in android module
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [x] [WIZARD] Show wizard when upgrading to 2.9.3
 - [x] [QA] Design Test plan @jesmrec
 - [x] [QA] Regression Test plan  @jesmrec 
 - [x] [GIT] Merge branch `release_0.9.24` in owncloud/android-library, into master
 - [x] [GIT] Merge branch `release_2.9.3` in owncloud/android, into master 
 - [x] [DIS] Generate test APKs files from branch master in owncloud/android and perform some basic operations.
 - [x] [GIT] Create and sign tag `oc-android-2.9.3` in HEAD commit of master branch, in owncloud/android 
 - [x] [GIT] Create and sign tag `oc-android-library-0.9.24` in HEAD commit of master branch, in  #owncloud/android-library 
- [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new release 2.9.3
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [SPREADTHEWORD] Write a topic in central about the release. https://central.owncloud.org/t/owncloud-2-9-3-for-android-with-fixes-for-usernames-containing-character/
 - [x] [COORDINATION] Write in corresponding channels.
 - [x] [SPREADTHEWORD] Write a post in the blog or spread the word via twitter @lefherz 
 - [x] [GIT] merge master branch into stable, in owncloud/android-library
 - [x] [GIT] merge master branch into stable, in owncloud/android

_____
### RELATED

https://github.com/owncloud/android/issues/2365

**Comment by prsnbrg** [comment]
What is with the Upload on f-droid?

**Comment by davigonz** [comment]
> What is with the Upload on f-droid?

@prsnbrg F-Droid will automatically update the version by using [this](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.owncloud.android.txt#L331).

**Comment by prsnbrg** [comment]
Oh sorry,
Yes I Updated my App yesterday with f-Droid.
 
In the last Release Checklist we have a point with Upload on f-droid, but now we have only Publishing Google Play.

**Comment by davigonz** [comment]
> In the last Release Checklist we have a point with Upload on f-droid, but now we have only Publishing Google Play.

I might have forgotten to delete that task, but is no longer needed for final versions, only for beta ones.

**Comment by jesmrec** [comment]
List with username checks containing the allowed special characters: .-@_ and the blank:

https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.9.3/fix_encoding_characters_username.md

**Comment by jesmrec** [comment]
Checks to be done:

- [ ] https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.9.3/fix_encoding_characters_username.md
- [ ] Upgrade from 2.9.2
- [ ] Upgrade from 2.9.1
- [ ] Upgrade from 2.9.0
- [ ] Upgrade from 2.8.0
- [ ] Smoke test

**Comment by jesmrec** [comment]
All fixed.
