### ISSUE TITLE
[New architecture] Get public shares for a file

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2403]
**Get public shares for a file** is the first use case to start implementing #2351 , following the next architecture:

![1 1 get public shares for file](https://user-images.githubusercontent.com/15261363/53404435-f7287b80-39b5-11e9-83bd-0ebd6aaf5aab.png)

Thanks to the `ViewModel` and `LiveData` , the shares shown in the view will be binded to the database, updating them automatically when a new change is detected. 

_____
### TASKS

- [x] Include needed dependencies: Kotlin, room, lifecycle, testing...
- [x] Create Share entity
- [x] Create ShareDAO with query to get public shares for a file 
- [x] Use LiveData in ShareDAO
- [x] Implement Room database 
- [x] Create ShareRepository
- [x] Create ShareViewModel 
- [x] Connect SharesFragment with ViewModel to retrieve automatically the public shares.
- [x] Observe shares and errors with livedata
- [x] Error handling 
- [x] Expose shares stored in room by using Content Provider.
- [x] Add additional state (LOADING) to show loading dialog. 
- [x] Database migration
- [x] Tests:
  - [x] ShareContentProvider
  - [x] OCLocalDataSource
  - [x] OCShareDAO
  - [x] OCRemoteDataSource
  - [x] OCShareRepository
  - [x] NetworkBoundResource
  - [x] OCShareViewModel
  - [x] UI tests
