### ISSUE TITLE
[New architecture] Create public shares

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2450]
Let's continue implementing the [new architecture](https://github.com/owncloud/android/issues/2351)  with a new use case, **Create public shares for a file** , following the next architecture:

![owncloud android app architecture](https://user-images.githubusercontent.com/15261363/52778836-2c90a900-3047-11e9-8347-e96ce9e2e20d.png)

_____
### TASKS

- [x] Include insert share query in OCShareDao
- [x] Include insert share operation in OCLocalDataSource
- [x] Include insert share operation OCRemoteDataSource
- [x] Include insert share operation in OCShareRepository
- [x] Include insert share function in OCShareViewmodel.
- [x]  Connect PublicShareDialogFragment with OCShareViewmodel to insert shares.
- [x] Error handling, adapt ErrorMessageAdapter
- [x] Use room implementation in Content Provider to insert shares
- [x] Tests:
  - [x] OCLocalDataSource
  - [x] OCRemoteDataSource
  - [x] OCShareRepository
  - [x] OCShareViewModel
  - [x] UI tests

### PR
- App: https://github.com/owncloud/android/pull/2461
- Library: https://github.com/owncloud/android-library/pull/240

### QA

Checks performed after automatic tests: https://github.com/owncloud/android-library/pull/240#issuecomment-479440004

**Comment by jesmrec** [comment]
done!
