### ISSUE TITLE
Folder with brackets [ ] does not show the content

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2481]
### Steps to reproduce
1.  In web UI create a folder called [Photos] and upload something inside
2. In the app, open the folder 

### Actual behaviour
Content empty

### Expected behaviour
Content shown

Android 7 
ownCloud 10.0.10

-------

### TASKS

- [x] Research
- [x] Create branch fix/content_folder_brackets
- [x] Development tasks
  - [x] Fix issue in dav4android
  - [x] Create new tag with the fix
  - [x] Use tag in oC Android library
  - [x] Clean up dependencies
  - [ ] Send PR to dav4jvm with the bug report and fix https://gitlab.com/bitfireAT/dav4jvm/merge_requests/5
- [x] Design test plan -> not needed in this case. 
- [X] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App https://github.com/owncloud/android/pull/2533
- Library (if needed) https://github.com/owncloud/android-library/pull/248

**Comment by sd1998** [comment]
@jesmrec I would like to work on this.

**Comment by jesmrec** [comment]
go ahead

**Comment by davigonz** [comment]
Hi @sd1998 , what's the status of this?

**Comment by davigonz** [comment]
I will start to work on this since it has high priority
