### ISSUE TITLE
[New architecture] Capabilities

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2495]
The sooner we have capabilities within the new architecture the better since some of the app features depend on them:

- Shares.
- RefreshFolderOp.
- FileMenuFilter.

![2  Capabilities](https://user-images.githubusercontent.com/15261363/54741953-45e5c180-4bc0-11e9-9248-6f5205821cb4.png)

_____
### TASKS

- [x] Create OCCapability entity
- [x] Create OCCapabilityDAO with query to get and insert capabilities 
- [x] Create OCCapabilityLocalDataSource and OCCapabilityRemoteDataSource
- [x] Create OCCapabilityRepository
- [x] Create OCCapabilityViewModel
- [x] Use LiveData in CapabilityDAO
- [x] Get and insert capabilities when needed
- [x] Error handling 
- [ ] Expose capabilities stored in room by using Content Provider => Not possible yet since capabilities are being used from other parts of the code not related to sharing, we will keep capabilities on old and new databases.
- [x] Database migration
- [x] Unit tests:
  - [x] OCCapabilityViewModel
  - [x] OCCapabilityLocalDataSource
  - [x] OCCapabilityRemoteDataSource
  - [x] OCCapabilityRepository
- [x] Instrumented tests:
  - [x] CapabilityContentProvider
  - [x] OCCapabilityDAO
- [x] UI tests
  - [x] Create test plan @jesmrec  -> https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.11.0/2508-new%20architecture_capabilities_autom.md
  - [x] Take into account parts of the UI that should be shown/hidden depending on capabilities, ShareFileFragment and PublicShareDialogFragment.

### PRs
App: https://github.com/owncloud/android/pull/2508
Library: https://github.com/owncloud/android-library/pull/246

**Comment by jesmrec** [comment]
Test plan for UI tests linked in header message. @davigonz you can check if you miss something.

**Comment by jesmrec** [comment]
Tested password policy app with the new architecture implementation. Everything is OK, currently, if the password created under some policies does not match, an error message is shown with the specific error pointing the user to change it to match every policy.

Number of expiration days depending on the public link password are also correctly managed.

CC @michaelstingl
