### ISSUE TITLE
[Document Provider] Edit files and save changes

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2498]
New improvement to Document Provider: Open File Write Mode (API 19) [Doc](https://developer.android.com/reference/android/provider/DocumentsProvider.html#openFile(android.net.Uri,%20java.lang.String,%20android.os.CancellationSignal))

Open a document, edit it, and then save changes.

Current status:
- Allow users to open files within provider
- Changes are not saved

Expected status:
- Allow users to open files within provider
- Save changes and update server with them
- Notification if there is a conflict with file in server

### TASKS

- [x] Research (if needed)
- [x] Create branch document_provider/open_document_write_mode
- [x] Development tasks
  - [x] Enable write mode on openDocument
  - [x] Sync file with server
  - [x] Notify when conflict
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch document_provider/open_document_write_mode into master

### PR
#2527
