### ISSUE TITLE
[Document Provider] Create new folder

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2500]
New improvement to Document Provider : Create new Folder -> [Doc](https://developer.android.com/reference/android/provider/DocumentsProvider.html#createDocument(java.lang.String,%20java.lang.String,%20java.lang.String)) API 19

| Actual behaviour | Expected behaviour | 
| ------------- |-------------| 
| ![ActualBehaviour](https://user-images.githubusercontent.com/47524927/55476817-db00a580-5617-11e9-8f54-bc423d36b8e6.png) | ![ExpectedBehaviour](https://user-images.githubusercontent.com/47524927/55476921-1ac78d00-5618-11e9-97f7-2be044938ecd.gif) |

### TASKS

- [x] Research (if needed)
- [x] Create branch document_provider/create_folder
- [x] Development tasks
  - [x] Add flag to FileCursor
  - [x] Implement createDocument in DocumentsProvider
  - [x] Implement createFolder when mimetype is Dir
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch document_provider/create_folder into master

### PR
#2510
