### ISSUE TITLE
[Release] 2.11

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2515]
### TASKS

 - [x] [COORDINATION] Ping community guys to publish a blog post, at least one week before releasing.
 - [x] [GIT] Create branch release_2.11.0 in owncloud/android from master
 - [x] [GIT] Create branch release_1.0.1 in owncloud/android-library from master 
 - [x] [DEV] Update versionCode and versionName in build.gradle in android module
 - [x] [DEV] Update versionCode and versionName in build.gradle in android library module
 - [x] [DEV] Disable feature to open github from the compilation info (clicks will be used to display logs section)
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android 
 - [x] [QA] Design Test plan @jesmrec  https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.11.0/Regression.md
 - [x] [QA] Regression Test plan  @jesmrec 
 - [x] [DIS] Generate test APKs files from release branch in owncloud/android and perform some basic operations.
 - [x] [GIT] Create and sign tag `oc-android-2.11.0` in HEAD commit of release branch, in owncloud/android 
 - [x] [GIT] Create and sign tag `1.0.1` in HEAD commit of release branch, in  #owncloud/android-library 
 - [x] [DIS] Generate final APK files from signed commit in owncloud/android and perform some basic operations
- [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new release 2.11.0
 - [x] [GIT] Merge branch release_1.0.1 in owncloud/android-library, into master
 - [x] [GIT] Merge branch release_2.11.0 in owncloud/android, into master 
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Upload release APK internal storage
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Storel 
 - [x] [SPREADTHEWORD] Write a topic in central about the release => https://central.owncloud.org/t/owncloud-2-11-for-android-released/
 - [x] [COORDINATION] Write in corresponding channels
 - [x] [COORDINATION] Write email to release-coordination mailing list.
 - [ ] [SPREADTHEWORD] Write a post in the blog @lefherz 
 - [X] [DOC] Create an issue in docs repository with the new features to be included in the user manual: https://github.com/owncloud/docs/issues/1323 
 - [x] Publish app in F-Droid [AUTOMATIC]
 - [x] [GIT] merge master branch into stable, in owncloud/android-library
 - [x] [GIT] merge master branch into stable, in owncloud/android

### PRs:
App: https://github.com/owncloud/android/pull/2571
Library: https://github.com/owncloud/android-library/pull/252

### Test Plan:

https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.11.0/Regression.md

**Comment by davigonz** [comment]
@jesmrec the branches are ready, you could start with the regression test

**Comment by davigonz** [comment]
**Steps included in wizard:**

1. Document provider
<img src="https://user-images.githubusercontent.com/15261363/59348239-e9092b80-8d16-11e9-9283-8b3140d0a2bb.png" width=50%>

2. Logs with search
<img src="https://user-images.githubusercontent.com/15261363/59348267-f3c3c080-8d16-11e9-862f-ddd4edcb4cef.png" width=50%>

@jesmrec please perform the corresponding tests

**Comment by jesmrec** [comment]
Tests passed. In first message you can check the regression test performed. It is noticeable that some parts of the test were not passed, since the development during the release did not accept. Focus was in important blocks like authentication and the isolated new features like document provider and new native manual uploader, as well as other basic and necessary checks.

Upgrading was tested as well with upgrading wizard checks performed.

Ready to go.

CC @davigonz

**Comment by jesmrec** [comment]
Documentation PR was already created: https://github.com/owncloud/docs/issues/1323
