### ISSUE TITLE
[New architecture] Edit public shares

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2516]
New use case, Edit public shares for a file

_____
### TASKS

- [x] Include update public share query in OCShareDao
- [x] Include update public share operation in OCLocalDataSource
- [x] Include update public share operation OCRemoteDataSource
- [x] Include update public share operation in OCShareRepository
- [x] Include update public share function in OCShareViewmodel.
- [x]  Connect PublicShareDialogFragment with OCShareViewmodel to update shares.
- [x] Error handling, adapt ErrorMessageAdapter
- [x] Use room implementation in Content Provider to edit shares
- [x] Tests:
  - [x] OCLocalDataSource
  - [x] OCRemoteDataSource
  - [x] OCShareRepository
  - [x] OCShareViewModel
  - [x] OCShareDao
  - [x] UI tests

### PRs
App: https://github.com/owncloud/android/pull/2522
Library: https://github.com/owncloud/android-library/pull/247

**Comment by davigonz** [comment]
@jesmrec UI tests finished, please have a look at them and tell me whether are enough or we could include more
