### ISSUE TITLE
[New architecture] Delete public shares

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2517]
New use case, Delete public share for a file

_____
### TASKS

- [x] Include delete public share query in OCShareDao
- [x] Include delete public share operation in OCLocalDataSource
- [x] Include delete public share operation OCRemoteDataSource
- [x] Include delete public share operation in OCShareRepository
- [x] Include delete public share function in OCShareViewmodel.
- [x]  Connect ShareFileActivity with OCShareViewmodel to delete shares.
- [x] Error handling, adapt ErrorMessageAdapter
- [x] Clean up some dependencies:
  - [x] Get shares
  - [x] Create shares
  - [x] Edit shares
  - [x] Remove shares
- [x] Fix UI tests after cleaning up dependencies in code
- [x] Use room implementation in Content Provider to delete shares
- [x] Tests:
  - [x] OCLocalDataSource
  - [x] OCRemoteDataSource
  - [x] OCShareRepository
  - [x] OCShareViewModel
  - [x] OCShareDao
  - [x] UI tests (To be completed within #2531)

### TASKS
- App: https://github.com/owncloud/android/pull/2544
- Library, when needed: https://github.com/owncloud/android-library/pull/250
