### ISSUE TITLE
[Document Provider] Account management & Multiaccount

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2518]
This is the current behaviour after installing the app from scratch

1. Add one account to ownCloud  app -> account appears in Files (OK)
2. Add a second (or more) accounts to ownCloud app -> accounts do not appear in Files (NOK, should appear as many accounts as the ones attached to the app)
3. Delete from the app the account added in 1. -> the account is still available in Files (NOK, the account is removed)

As improvement, the account is displayed with the user name, but it would be nice to use the display name, if feasible. 

### TASKS

- [x] Research (if needed)
- [x] Create branch document_provider/account_management
- [x] Development tasks
  - [x] Notify Document Provider when user logs in
  - [x] Notify Document Provider when user logs out
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch document_provider/account_management into master

### PR

#2528

**Comment by abelgardep** [comment]
Multiaccount is supported, but Document Provider is not listening to logins or logouts. I agree that we need to listen to those events for security, so i include this improvement in DocumentsProvider epic.

> As improvement, the account is displayed with the user name, but it would be nice to use the display name, if feasible.

We can display user name or display name or whatever, we can change it without problems.
