### ISSUE TITLE
[Settings tests] Camera uploads section 

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2526]
**Is your feature request related to a problem? Please describe.**
UI tests over the Camera uploads section, inside the Settings activity

### TASKS

- [X] Research (if needed)
- [X] Create branch feature/feature_name
- [x] Development tasks
  - [x] Picture uploads tests
  - [x] Video uploads tests
  - [x] Extra options tests
- [x] Code review and apply changes requested
- [ ] Merge branch feature/feature_name into master

### PR

- App: https://github.com/owncloud/android/pull/2538
- Library (if needed)
