### ISSUE TITLE
[Settings tests] More section

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2530]
**Is your feature request related to a problem? Please describe.**
UI tests over the More section, inside the Settings activity

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/feature_name
- [x] Development tasks
  - [x] Implement whatever
  - [x] ...
- [x] Code review and apply changes requested
- [ ] Design test plan
- [x] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App: https://github.com/owncloud/android/pull/2545
- Library (if needed)
