### ISSUE TITLE
 [New architecture] UI tests for public sharing, using whole flows

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2531]
The tests already developed within the new architecture cover UI in an isolated way for each fragment and tests that take advantage of whole flows when sharing, e.g. create public share and see it in the shares list, would be needed as well.

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/feature_name
- [x] Development tasks
  - [x] Implement whatever
  - [x] ...
- [x] Code review and apply changes requested
- [X] Design test plan -> https://github.com/owncloud/QA/blob/master/Mobile/Android/Templates/Sharing%20Flow%20tests.md
- [x] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App: https://github.com/owncloud/android/pull/2558
