### ISSUE TITLE
[Release] 2.10.1 + oem

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2534]
### TASKS:
 - [x] [GIT] Create `release_2.10.1` branch in owncloud/android from `oc-android-2.10.0` tag
 - [x] [DEV] Update version number and name in build.gradle in android module
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [GIT] Create and sign `oc-android-2.10.1` tag in HEAD commit of `release_2.10.1` branch, in owncloud/android
 - [x] [DIS] Generate test APKs file from  `release_2.10.1` branch in owncloud/android
 - [x] [DIS] Generate final APK file from signed commit in owncloud/android
 - [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new release 2.9.3
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [GIT] Rebase with master
 - [x] [GIT] Merge branch release_2.10.1 in owncloud/android, into master

_____

### PR
App: https://github.com/owncloud/android/pull/2537

_____
