### ISSUE TITLE
[Document Provider] Create Files

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2539]
This feature allows client apps to create files within document provider

Official Docs about it: [Support Document Creation](https://developer.android.com/guide/topics/providers/create-document-provider.html#creating)

### TASKS

- [x] Research (if needed)
- [x] Create branch document_provider/create_files
- [x] Development tasks
  - [x] Enable Create Documents at Root Cursor
  - [x] Implements createFiles at Document Provider 
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch document_provider/create_files

### PR

- App #2541 
- Library (if needed)

### QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.13.0/2541-create_file_provider.md

- [X] (1) File is not uploaded after updating https://github.com/owncloud/android/issues/2539#issuecomment-523788486 [FIXED]

**Comment by jesmrec** [comment]
@abelgardep when a file is created and saved in oC, the is the file removed from original path (moved)?

**Comment by abelgardep** [comment]
> @abelgardep when a file is created and saved in oC, the is the file removed from original path (moved)?

I suppose it depends on how you create that file. If you create a file and u didn't save anywhere, if you save it in OwnCloud it should save only in oC. If you open a file that exists locally and save in oC it should be like a copy.

**Comment by jesmrec** [comment]
thanks for the clarification!

**Comment by jesmrec** [comment]
### (1)

Please check these steps out (regression):

1. Open a file in oC in an external app
2. Change the content of the file

Current: file in oC is not uploaded till you open again the app and open the updated file.
Expected (`master` behaviour): In the moment the changes are saved in the external app, the file is uploaded to oC

MIA2 Android 9

**Comment by davigonz** [comment]
> Open a file in oC in an external app

@jesmrec could you please detail what is the external app you are using?

**Comment by jesmrec** [comment]
@abelgardep i checked with :

- MSWord
- Text Editor (https://play.google.com/store/apps/details?id=com.byteexperts.texteditor&hl=en_US)

**Comment by michaelstingl** [comment]
> * MSWord

Create a new file in MSWord and "Save as…" in ownCloud doesn't work for me yet (with @abelgardep 's `*.APK`)

**Comment by jesmrec** [comment]
details are always welcome. I was able to create and save.

**Comment by jesmrec** [comment]
Checking the feature with the latest beta of Android Q (patch from 1 Aug), also works for me by using MSWrd and the app text editor mentioned above.

**Comment by jesmrec** [comment]
Approved on my side
