### ISSUE TITLE
[Release] 2.11.0 beta1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2547]
### TASKS:
 - [x] Merge 2.10.1 into master
 - [x] [COORDINATION] Get in touch with community/marketing team to publish a blog post, several days before releasing.
 - [x] [GIT] Create **release/1.0.1_beta.1** branch in owncloud/android-library from master
         - Update version code and name in build.gradle.
 - [x] [GIT] Create **release/2.11.0_beta.1** branch from master and:  
         - Update version code and name in build.gradle.
         - Update changelog file (< 500 chars)
 - [x] [QA] Perform some tests @jesmrec
 - [x] [GIT] Create and sign tag `1.0.1-beta.1` in HEAD commit of **release/1.0.1_beta.1** branch, in owncloud/android-library
 - [x] [GIT] Create and sign tag `oc-android-2.11.0-beta.1` in HEAD commit of **release/2.11.0_beta.1** branch, in owncloud/android
 - [x] [DIS] Generate test APKs files from **release/2.11.0_beta.1** branch in owncloud/android 
- [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new pre-release 2.11.0 beta
 - [x] [DIS] Generate final APK files from signed commit in owncloud/android and perform some basic operations
_____
### PLAY STORE:
 - [x] [DIS] Upload & publish beta release APK and changelog
_____
### F-DROID:
 - [x] [DEV] Create MR in F-Droid repo to include 2.11.0 beta build.
-  [x] [DEV] Merge MR into F-Droid: https://gitlab.com/fdroid/fdroiddata/merge_requests/4883
_____
### FINAL TASKS:
 - [x] [GIT] Merge **release/1.0.1_beta.1** branch in owncloud/android-library, into master, if needed
 - [x] [GIT] Merge **release/2.11.0_beta.1** branch into master in owncloud/android 
 - [x] [SPREADTHEWORD] Write a topic in central about the beta release.  https://central.owncloud.org/t/owncloud-2-11-beta-app-for-android
 - [x] [SPREADTHEWORD] Share new beta on social media.
_____

### PRs:
App: https://github.com/owncloud/android/pull/2553
Library: https://github.com/owncloud/android-library/pull/251
_____
### BUGS & IMPROVEMENTS:

**Comment by davigonz** [comment]
All the tasks are already done, closing...
