### ISSUE TITLE
[New architecture] Get + search + create private shares

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2555]
Private share creation (including users and group search) 

- Open search view
- Search sharee (capabilities). Internal & Federated. 
- Create & Show results
- Permissions depending on file/folder
- Unit/UI tests: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.12.0/2584-new_architecture_create_search_shares.md

### TASKS

1. Get and show private shares in list
    - [x] Implement get private shares and show it in private share list
    - [x] Show private shares in search dialog
    - [x] Unit Tests for getting private shares (non instrumented)
    - [x] Unit Tests for getting private shares
    - [x] UI Tests for showing private shares
      - [x] ShareFileFragment
      - [x] SearchShareesFragment

2. Search and show private shares found
    - [x] Create ShareesRepository
    - [x] Move the operation to get sharees from `UsersAndGroupsSearchProvider` to a new repository.
    - [x] Show the sharees retrieved from the server.
    - [x] Unit tests
    - [ ] UI tests, including flow ones => delayed till end to end tests

3. Create private shares
   - [x] Include insertPrivateSharee method in OCShareRepository
   - [x] Include insertPrivateSharee method in OCShareViewModel
   - [x] Call insertPrivateSharee from ShareActivity
   - [x] Unit tests
   - [ ] UI tests => delayed till end to end tests

4. Code review
5. QA: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.12.0/2584-new_architecture_create_search_shares.md

### PRs
- App: https://github.com/owncloud/android/pull/2584
- Library: https://github.com/owncloud/android-library/pull/254
