### ISSUE TITLE
Android 10

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2576]
Android Q is coming soon. Here we can report everything related with the current stable version of the app, including new features, bugs etc...

Checklist:

### Before targeting Android Q
- [x] Install an Android Q beta in any device
- [x] Regression test of the stable version of the app over Android Q
- [X] Fixes

### Targeting Android Q
- [x] Upgrade app target to API 29
- [x] Have a look at TLS v1.3 [Android 10 adds support for TLS 1.3](https://developer.android.com/about/versions/10/features#tls-1.3) -> https://github.com/owncloud/android/issues/2855
- [ ] List of features to implement (https://developer.android.com/about/versions/10)
  - [ ] Scoped Storage: https://developer.android.com/training/data-storage/files/external-scoped -> https://github.com/owncloud/android/issues/2877

Test plan:

https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.12.0/SmokeTestAndroid10.md

Bugfixing

- [X] (1) Refresh account makes the app crash https://github.com/owncloud/android/issues/2576#issuecomment-522510592 [FIXED] @jesmrec 
- [x] (2) OAuth2 token refresh https://github.com/owncloud/android/issues/2576#issuecomment-522541504 [NOT REPRODUCIBLE]

### PR
App: https://github.com/owncloud/android/pull/2897
Library: https://github.com/owncloud/android-library/pull/325

**Comment by jesmrec** [comment]
First round will run over Pixel2 with latest Android Q beta, to the 2.12RC of the app, that will be the one in market when Android Q is released.

**Comment by jesmrec** [comment]
### (1)

1. Attach an account
2. In three-dot-menu, select "Refresh account"

Current: crash
Expected: account refreshed

**Comment by jesmrec** [comment]
### (2)

OAuth2 sessions are not being renewed when token expires. I cheated a server to decrease the expiration time from 1h to some minutes, and at the moment the time is up, the 401 comes but does not trigger the request to renew the token. Not sure which reason for AndroidQ not to behave correctly, but the same scenario with the same server worked correctly with Android 9 and 7.

**Comment by davigonz** [comment]
@jesmrec the bugs are already fixed in `release_2.12` branch

**Comment by abelgardep** [comment]
## Apps targeting API 29+
[Behaviour changes](https://developer.android.com/about/versions/10/behavior-changes-10)
- [ ] Updates to non-SDK interface restrictions
- [ ] Shared memor
- [ ] Removed execute permission for app home directory
- [ ] Android runtime only accepts system-generated OAT files
- [ ] Enforcing AOT correctness in ART
- [ ] Permissions changes for fullscreen intents
- [ ] Support for foldables
- [ ] java.io.FileChannel.map() changes
- [ ] [Privacy changes](https://developer.android.com/about/versions/10/privacy/changes)

# Improvements
[android.preference deprecation](https://developer.android.com/about/versions/10/behavior-changes-all#preferences) Consider migration to androidx.preference ([Guide](https://developer.android.com/guide/topics/ui/settings))
