### ISSUE TITLE
Complete information in Av. Offline shortcut

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2577]
**Is your feature request related to a problem? Please describe.**

The av. offline shortcut, placed in the drawer, let you know to have a list with your av. offline content, like that one:

![Screenshot 2019-06-18 at 09 50 47](https://user-images.githubusercontent.com/14894746/59663090-91ebd680-91ae-11e9-80a0-a035d5dc0d2d.png)

In this view, you have the options to sort, using different criteria: name, size, date. Since the date and the size are not visible, the sorting is not vey clear.

**Describe the solution you'd like**

The list of av. offline stuff should include the date and size of every item as in the file list. This will make the sorting full of sense.

### TASKS

- [x] Research (if needed)
- [x] Create branch available_offline_complete_info
- [x] Development tasks
  - [x] Add new layout that scale dinammicaly
  - [x] Refactor adapter that use that layout
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch feature/feature_name into master

### PR

- App #2654 
- Library (if needed)

**Comment by davigonz** [comment]
Done, will be included in 2.13
