### ISSUE TITLE
[RELEASE] 2.11.1 oem

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2581]
### TASKS:

 - [x] [GIT] Create branch `release_2.11.1_oem` in owncloud/android from master
 - [x] [QA] Reduced Test plan
 - [x] [DIS] Generate test APKs files from branch `release_2.11.1_oem` in owncloud/android
 - [x] [GIT] Create and sign tag `oc-android-2.11.1_oem` in HEAD commit of `release_2.11.1_oem` branch, in owncloud/android
 - [x] [GIT] Create and sign tag `1.0.1_oem` in HEAD commit of master branch, in owncloud/android-library
 - [x] [DIS] Generate final APKs files from signed commit in owncloud/android and perform some basic operations
 - [x] [GIT] Merge branch `release_2.11.1_oem` in owncloud/android, into master
 - [x] [GIT] merge master branch into stable, in owncloud/android

### BUGS & IMPROVEMENTS

https://github.com/owncloud/enterprise/issues/2913
https://github.com/owncloud/ownbrander/pull/877

### PRs:
- App: https://github.com/owncloud/android/pull/2588

**Comment by davigonz** [comment]
I would face https://github.com/owncloud/ownbrander/issues/822 in coming releases since it does not seem to be urgent.

@jesmrec please review https://github.com/owncloud/android/pull/2588, is a tiny one.

**Comment by jesmrec** [comment]
Colors' issue is fixed.

Apart, some checks regarding SAML authentication were done, with successful results.

Ready to move forward.

Approved-
