### ISSUE TITLE
[FEATURE REQUEST] Splash screen

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2582]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

AC:

- [x] Show a splash screen with the ownCloud logo every time the app is opened
- [x] The splash screen should include by default, the cloud icon and the dark blue background color (official oC logo)
- [ ] It should be brandable (logo and background color). [To be done]

Brandable:
- splash_background: A color
- splash_image:
      - (Preferably) A png same size as logo to show background behind
      - An image that will be centered

[Documentation](https://www.bignerdranch.com/blog/splash-screens-the-right-way/ )
[Different Approaches](https://medium.com/@elye.project/which-splash-screen-approaches-is-better-4de3128988fd)
[Image scale](https://developer.android.com/guide/topics/resources/drawable-resource#Bitmap)

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/splash_screen
- [x] Development tasks
  - [x] Use app icon inside the screen
  - [x] Use background (color or image... to discuss)
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/splash_screen into master

### PR

- App: https://github.com/owncloud/android/pull/2713
- Library (if needed)

### QA

Test plan:

https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.14.0/2713-%20Splash_screen.md

**Comment by davigonz** [comment]
Merged
