### ISSUE TITLE
[QUICK RELEASE] 2.11.1

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2585]
### TASKS

 - [x] [COORDINATION] Ping marketing guys
 - [x] [GIT] Create branch `release_2.11.1` in owncloud/android from master
 - [x] [DEV] Update versionCode and versionName in build.gradle in android module
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android 
 - [x] [QA] Design Test plan @jesmrec  https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.11.0/Regression.md
 - [x] [QA] Regression Test plan  @jesmrec 
 - [x] [DIS] Generate test APKs files from release branch in owncloud/android and perform some basic operations.
 - [x] [GIT] Create and sign tag `oc-android-2.11.1` in HEAD commit of release branch, in owncloud/android 
 - [x] [DIS] Generate final APK files from signed commit in owncloud/android and perform some basic operations
- [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new release 2.11.1
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Upload release APK internal storage
 - [x] [GIT] Merge branch `release_2.11.1` in owncloud/android, into master 
 - [x] [COORDINATION] Write in corresponding channels
 - [x] Publish app in F-Droid [AUTOMATIC]
 - [x] [GIT] merge master branch into stable, in owncloud/android

### PRs:
- App: https://github.com/owncloud/android/pull/2586
