### ISSUE TITLE
[FEATURE REQUEST] Make Welcome Wizard brandable

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2591]
**Describe the solution you'd like**
Welcome Wizard is currently hardcoded. We can move it to a external set-up, so everyone can put their own slides.

### TASKS

- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Research if it is posible to include a variable number of slides 
  - [ ] Rename resources, making them more generic
  - [ ] Change implementation not to take in account the number version
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

https://github.com/owncloud/ownbrander/issues/879

### PR

- App
- Library (if needed)

**Comment by hurradieweltgehtunter** [comment]
Wow this would be really nice. Do you have an ETA? Currently this is a blocker in the app release process for owncloud.online. Plan was to publish it end of this month so I have to see which solution works till then.
thanks anyway!

**Comment by michaelstingl** [comment]
@hurradieweltgehtunter please work with @davigonz and @ChrisEdS on a prototype the next few days. This should be sufficient for your urgent needs. I don't have an ETA for the fully parameterised, brandable solution.

**Comment by hurradieweltgehtunter** [comment]
will do. thx
