### ISSUE TITLE
[New arch] Modularization, decoupling and new error handling

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2607]
Specific issue to start modularizing the app, following the guidelines defined in #2351 

- Tasks
    - [x] Split up code into different modules following a layers approach and move the corresponding shares code to those modules:
        - Presentation layer => **owncloudApp** module
        - Domain layer => **owncloudDomain** module
        - Data layer => **owncloudData** module
    - [x] Use mockk instead of mockito in UI and domain unit tests, more prepared to work with Kotlin instead of Java.
    - [x] Transform sharing operations into usecases in domain model.
    - [x] Decouple data and domain modules with the help of dependency injection (Koin). Domain should not depend on data layer directly => Difficult to achieve due to strong ownCloud Client dependencies that force us to use instances of repositories in domain layer when we should use repository interfaces.
    - [x] Create share data and domain models with some Mapper classes to transform them.
    - [x] Create capability data and domain models with some Mapper classes to transform them.
    - [x] Error handling, + info in https://github.com/owncloud/android/issues/2665
    - [x] Create new services as facade for remote operations to decouple that logic from remote datasources and ease remote datasource and repository tests
    - [x] Fix already existing tests: unit and UI. Use corresponding share models in TestUtils.
      - [x] Data layer
         - [x] Datasources
         - [x] Repositories
         - [x] Mappers (model-entities, model-remote)
         - [x] Entity
         - [x] DAOs
      - [x] Domain layer
         - [x] Usecases
      - [x] Presentation layer 
         - [x] ViewModel Tests
         - [x] UI tests
    - [x] New tests for usecases
    - [x] New tests for models
    - [ ] Use StandAloneContext.loadKoinModules. See https://github.com/owncloud/android/pull/2603#discussion_r303351786

### PRs
   - App: https://github.com/owncloud/android/pull/2707
   - Library: https://github.com/owncloud/android-library/pull/278

#### Pending issues (create  separate ones?)
- Consider adding a new module just for data testing. 
- Consider renaming usecases to Fetch...() instead of Refresh...FromServer()

### Bugs and improvements
- [x]  (1) Error is shown again when rotating the device https://github.com/owncloud/android/issues/2607#issuecomment-550279458
- [x] (2) Users and groups search doesn't work
https://github.com/owncloud/android/issues/2607#issuecomment-550301135 [FIXED]

**Comment by davigonz** [comment]
**[BUG] (1) Error is shown again when rotating the device**

1. Open the application with Activity or Fragment
2. Cause an error, e.g. switch airplane mode on and tap a button that makes a request to server
3. Observe the error is shown
4. Rotate the device

Current behavior: Error is shown again and the user has not done any request.
Expected behavior: No error is shown

**Comment by davigonz** [comment]
**[BUG] (2) Users and groups search doesn't work**

1. Tap share icon in a file.
2. Tap + button in users and groups section.
3. Type several characters to search users or groups.

Current behavior: No results
Expected behavior: Users or groups appear

`2019-11-06 13:19:05.425 26092-26488/com.owncloud.android.debug W/SuggestionsAdapter: Search suggestions query threw an exception.
    java.lang.IllegalStateException: Cannot invoke observeForever on a background thread
        at androidx.lifecycle.LiveData.assertMainThread(LiveData.java:461)
        at androidx.lifecycle.LiveData.observeForever(LiveData.java:222)
        at com.owncloud.android.presentation.viewmodels.capabilities.OCCapabilityViewModel.<init>(OCCapabilityViewModel.kt:69)
        at com.owncloud.android.presentation.viewmodels.capabilities.OCCapabilityViewModel.<init>(OCCapabilityViewModel.kt:49)
        at com.owncloud.android.presentation.providers.sharing.UsersAndGroupsSearchProvider.searchForUsersOrGroups(UsersAndGroupsSearchProvider.kt:128)
        at 
`

**Comment by davigonz** [comment]
Merged, great job guys!! @abelgardep @jesmrec @jcmontesmartos

![giphy](https://user-images.githubusercontent.com/15261363/70616007-cbf1de80-1c0d-11ea-8708-163e3d8471c0.gif)

**Comment by hannesa2** [comment]
Are there plans to convert/replace `UserProfilesRepository` , `FileDataStorageManager` and `ProviderMeta` by a [room](https://developer.android.com/topic/libraries/architecture/room) solution ?

**Comment by abelgardep** [comment]
> Are there plans to convert/replace `UserProfilesRepository` , `FileDataStorageManager` and `ProviderMeta` by a [room](https://developer.android.com/topic/libraries/architecture/room) solution ?

For sure, the idea is to migrate the app completely to the new architecture. That means using Room as it is already done with shares functionality. Step by step 👍

**Comment by davigonz** [comment]
In addition to what @abelgardep says

> Are there plans to convert/replace UserProfilesRepository , FileDataStorageManager and ProviderMeta by a room solution ?

Yes, but is going to be done by features, I mean:

**- FileDataStorageManager:** we already removed all the sharing methods from there (~500 lines). We will continue replacing the old implementation in coming issues: files, uploads, camera uploads...

**- ProviderMeta:** the idea is to keep it in the data layer but just with information required by the room solution.

**- UserProfilesRepository:** same, we will convert it.
