### ISSUE TITLE
[New arch] Authentication (login)

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2608]
Login rearchitecture

Branch: `new_arch/login`

### Improvements:
- [x] Improve the UX OAuth2 flow to make it more clear https://github.com/owncloud/enterprise/issues/3451
- [x] Error handling: if server version is not supported, error displayed in login view is not accurate.
- [x] App password handling

### Issues to have a look at:
- [ ] Add a server certificate chain and fingerprint display menu in account settings: https://github.com/owncloud/android/issues/413

**Comment by jesmrec** [comment]
epic done
