### ISSUE TITLE
[RELEASE] 2.12

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2611]
### TASKS:

 - [x] [GIT] Create branch `release_1.0.2` in owncloud/android-library from master  (almost feature-frozen)
 - [x] [GIT] Create branch `release_2.12` in owncloud/android from master (almost feature-frozen)
 - [x] [DEV] Update versionCode and number in build.gradle in android module
 - [x] [DEV] Fix Android Q bugs
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [x] [QA] Design Test plan @jesmrec
 - [x] [QA] Regression Test plan @jesmrec
 - [x] [QA] Android Q smoke test @jesmrec 
 - [x] [DIS] Generate test APK file from `release_2.12` branch in owncloud/android
 - [x] [GIT] Create and sign tag `oc-android-2.12` in HEAD commit of stable master branch, in owncloud/android
 - [x] [GIT] Create and sign tag `oc-android-library_1.0.2` in HEAD commit of stable master branch, in owncloud/android-library
 - [x] [DIS] Generate final APK file from signed commit in owncloud/android
 - [x] [mail] inform john@owncloud.com and emil@owncloud.com about new release.
 - [x] [GIT] Merge branch `release_1.0.2` in owncloud/android-library, into master
 - [x] [GIT] Merge branch `release_2.12` in owncloud/android, into master
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [GIT] merge master branch into stable, in owncloud/android-library
 - [x] [GIT] merge master branch into stable, in owncloud/android

_____

### BUGS & IMPROVEMENTS

- [x] Improve FileContentProvider
- [x] Fixes on Android Q https://github.com/owncloud/android/issues/2576

_____

### PRs:

- App: https://github.com/owncloud/android/pull/2629
- Library: https://github.com/owncloud/android-library/pull/258

**Comment by jesmrec** [comment]
### QA

For this release, will not be performed a whole regression, since the contents will be focued in the re-architecting of the share feature. 

These are the stages after the stuff was finished on a development point of view:

1. Sanity test over the whole sharing feature in Android: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.12.0/Sharing%20-%20regression.md

2. First smoke tests

3. Develop tests to cover the corner cases detected on 1. : https://github.com/owncloud/android/pull/2627

4. Beta version

5. Smoke test over the release branch, with the regular checks:

- [ ] Basic auth
- [ ] OAuth2 auth (grant and refreshing of the token)
- [ ] Transfers: uploads and downloads
- [ ] Basic operations: create folder, copy, move, delete, rename
- [ ] Share with user -> covered in the sanity test
- [ ] Share by link -> covered in the sanity test
- [ ] Av. offline and instant uploads (JobScheduler)
- [ ] Upgrade from 2.11

**Comment by jesmrec** [comment]
Everything fine. Approved on my side.

**Comment by davigonz** [comment]
@jesmrec @michaelstingl everything is ready but since we have published today the architecture article and the release article is planned for tomorrow, I will press the button to roll out the app tomorrow, just to not have more than one blogpost a day 

CC / @lefherz
