### ISSUE TITLE
[RELEASE] 2.12 beta1 

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2621]
### TASKS:
 - [x] [COORDINATION] Get in touch with community/marketing team to publish a blog post, several days before releasing.
 - [x] [GIT] Create **release/1.0.2_beta.1** branch in owncloud/android-library from master
         - Update version code and name in build.gradle.
 - [x] [GIT] Create **release/2.12_beta.1** branch from master and:  
    - [x] Update version code and name in build.gradle.
    - [x] Update changelog file (< 500 chars)
 - [x] [QA] Perform some tests @jesmrec
 - [x] [GIT] Create and sign tag `1.0.2-beta.1` in HEAD commit of **release/1.0.2_beta.1** branch, in owncloud/android-library
 - [x] [GIT] Create and sign tag `oc-android-2.12-beta.1` in HEAD commit of **release/2.12_beta.1** branch, in owncloud/android
 - [x] [DIS] Generate test APKs files from `oc-android-2.12-beta.1` tag in owncloud/android 
- [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new pre-release 2.12 beta
 - [x] [DIS] Generate final APK files from signed commit in owncloud/android and perform some basic operations
_____
### PLAY STORE:
 - [x] [DIS] Upload & publish beta release APK and changelog
_____
### F-DROID:
 - [x] [DEV] Create MR in F-Droid repo to include 2.12 beta build.
-  [x] [DEV] Merge MR into F-Droid: https://gitlab.com/fdroid/fdroiddata/merge_requests/5186
_____
### FINAL TASKS:
 - [x] [GIT] Merge **release/1.0.2_beta.1** branch in owncloud/android-library, into master, if needed
 - [x] [GIT] Merge **release/2.12_beta.1** branch into master in owncloud/android 
 - [x] [SPREADTHEWORD] Write a topic in central about the beta release
 - [x] [SPREADTHEWORD] Share new beta on social media.
_____

### PRs:
- App: https://github.com/owncloud/android/pull/2622
- Library: https://github.com/owncloud/android-library/pull/256
_____
### BUGS & IMPROVEMENTS:

**Comment by jesmrec** [comment]
QA Checks performed (smoke test):

- [X] Auth basic
- [X] Auth OAuth2
- [X] Multiaccount
- [X] Transfers: download and upload
- [X] Basic file operations: move, copy, delete, rename
- [X] Share with user and groups
- [X] Public links
- [X] Upgrade from 2.11.1

Nexus 5X v8
