### ISSUE TITLE
[New arch] Get rid of SAML implementation

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2632]
### TASKS

- [ ] Research (if needed)
- [ ] Create `new_arch/get_rid_saml` branch 
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge `new_arch/get_rid_saml` branch into master

### PR

- App
- Library (if needed)
