### ISSUE TITLE
[New arch] OpenID connect implementation

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2633]
### TASKS

- [x] Check [AppAuth](https://github.com/openid/AppAuth-Android)
- [x] Create `open_id_support` branch 
- [x] Development tasks
  - [x] Use `openid` as scope value
  - [x] Use service discovery or manual endpoints depending on a setup parameter
  - [x] Polish and clean the code
  - [x] Multiaccount
  - [x] Check flow (Oauth2 view or not)
  - [x] Refresh token
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge `open_id_support` branch into master

### Environments

- +Info in https://github.com/owncloud/openidconnect#openid-connect-for-owncloud
- Easily fire up an owncloud server with an open id connect provider https://github.com/owncloud/openidconnect/tree/master/tests/docker

### PRs

- App: https://github.com/owncloud/android/pull/2854
- Library (if needed): https://github.com/owncloud/android-library/pull/315
- iOS solution: https://github.com/owncloud/ios-app/pull/401

**Comment by michaelstingl** [comment]
I'd propose to perform the following checks:

1) Login to https://ocis-latest.owncloud.com/ (`einstein:relativity`)
2) Survive token refresh after 10 Minutes (600s)
