### ISSUE TITLE
[New arch] Login arch: check URL, check credentials and get user info (basic auth)

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2634]
The steps in the login process are: 

1. _FileDisplayActivity_ is created.
2. `addAccount(...)` method from _AccountAuthenticator_ is called, which starts _AuthenticatorActivity_.
3. User introduces username and password and press login button.
4. _AuthenticatorAsyncTask_ creates two clients (with no accounts) using `OwnCloudClientFactory.createOwnCloudClient(...)` and perform _ExistenceCheckRemoteOperation_ and _GetRemoteUserInfoOperation_
5. _AuthenticatorActivity_ waits for _AuthenticatorAsyncTask_ response and creates an _Account_ explicitly using _AccountManager_ if everything worked fine.

### TASKS

- [x] Create branch new_arch/2634-basic_auth
- [x] Development tasks
  - [x] Create domain model
       - [x] UserInfo
       - [x] ServerInfo
       - [x] AuthenticationMethod (enum)
  - [x] Create usecases
       - [x] getServerInfo
       - [x] login
       - [x] getUserInfo
  - [x] Create repositories
       - [x] UserRepository
       - [x] ServerRepository
  - [x] Create datasources (remote or local - pending to check)
       - [x] User (Remote)
       - [x] Server (Remote)
  - [x] Save data retrieved for operations (Not needed)
  - [x] Use dependency injection to obtain simple ownCloud clients via new ownCloudClients factory, without considering ownCloud accounts for now. (maybe done, will check)
- [x] Error handling
- [x] Add units tests (instrumented and not instrumented)
- [x] Code review and apply changes requested
- [x] Tests passing
- [x] Merge branch `new_arch/2634-basic_auth` into `new_arch/login`

### PR

- App: #2809 
- Library https://github.com/owncloud/android-library/pull/302

**Comment by michaelstingl** [comment]
For Basic Authentication, it would be cool if the URL the user enters could include the username

User enters`user@mycloud.domain.com`so **username** is automatically filled with `user` and the  **URL** is `mycloud.domain.com`. In case the **username** itself includes the "`@`", users need to use proper URL encoding `user%40host@mycloud.domain.com`.

**Comment by abelgardep** [comment]
@davigonz Ready to Code Review 👍

**Comment by davigonz** [comment]
@jesmrec code approved

**Comment by abelgardep** [comment]
Merged #2809
