### ISSUE TITLE
[FEATURE REQUEST] Settings accessible even when no account is attached

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2638]
Settings view is only accesible when an account is attached. The only path to get it is in the drawer menu.

Actually, logs are available and in case we have problems in authentication stage, user will not be able to reach "Settings".

To fix that, a link to "Settings" should be placed somewhere in the Login view. Typically, in the bottom right corner (other ideas welcome).

The access to Settings in login view has to be brandable. For example, actually we have a dark-blue background, so the `Settings` word in white color will be correctly highlighted. For someone who has a clear background, the white letters will not be totally visible. It should take the font color from the URL field, as idea (other ideas welcome)

Logs file used to be stored in the app folder in the device. If the device is new, we have to create such folder to store the file in advance.

### TASKS

- [x] Create branch feature/settings_login
- [x] Development tasks
  - [x] Place a new TextView in the login screen that drives to settings screen
  - [x] Show Auto uploads subsections only when account is attached
  - [x] Add UI test
  - [x] Add unit tests
  - [x] Adapt current settings UI tests
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/settings_login into master

### PR

- App #3218 
- Library (if needed)

**Comment by JuancaG05** [comment]
To take into account: in both subsections "Auto picture uploads" and "Auto video uploads", if we try to open "Picture/VIdeo upload path" respectively and we don't have any accounts logged in the app, it will crash.
Just realized doing UI tests in https://github.com/owncloud/android/issues/3130, we already knew it, but we'll have to create a test checking these subsections are not reachable when no account is registered to cover completely the settings testing

**Comment by jesmrec** [comment]
Just an example, how the iOS app looks like in this regard:

![Screen Shot 2021-04-27 at 10 43 52](https://user-images.githubusercontent.com/14894746/116212867-8f148200-a745-11eb-861d-59203154a47d.png)

**Comment by JuancaG05** [comment]
Hey, I have three proposals for this issue, let's see which is the winner:

| Proposal 1 | Proposal 2 | Proposal 3 |
| ---------------------------------------------- | -------------------------------------------- | -------------------------------------------- |
| <img width="270" src="https://user-images.githubusercontent.com/57049315/116516050-66b78f80-a8cd-11eb-9738-f4b2c35386d6.png"> | <img width="270" src="https://user-images.githubusercontent.com/57049315/116516194-98c8f180-a8cd-11eb-8269-59bd96704b8c.png"> | <img width="270" src="https://user-images.githubusercontent.com/57049315/116516315-c3b34580-a8cd-11eb-9313-d130a55542b7.png"> |

The first and the second one would be more similar to the iOS version, but with the flaw that as everything is contained in a LinearLayout here, it's more difficult to place the text just in the right-bottom corner. Me, personally, I like the third one though it's different to the iOS version, but I think it's understandable and very seen nowadays in many apps.

Let me know your thoughts @abelgardep @jesmrec @theScrabi @michaelstingl @tbsbdr

**Comment by michaelstingl** [comment]
> Me, personally, I like the third one though it's different to the iOS version, but I think it's understandable and very seen nowadays in many apps.

Works for me 👍

**Comment by jesmrec** [comment]
I'd discard the first one. 2nd and 3rd one are OK for me.

**Comment by tbsbdr** [comment]
> > Me, personally, I like the third one though it's different to the iOS version, but I think it's understandable and very seen nowadays in many apps.
> 
> Works for me 👍

agree as well. did you try to move the setings-icon to the bottom right similar to the ios layout?

**Comment by hosy** [comment]
I would vote for the first one, because it it for everyone understandable, and as @tbsbdr said, I would put the button on the bottom right.

**Comment by JuancaG05** [comment]
> > > Me, personally, I like the third one though it's different to the iOS version, but I think it's understandable and very seen nowadays in many apps.
> > 
> > 
> > Works for me 👍
> 
> agree as well. did you try to move the setings-icon to the bottom right similar to the ios layout?

Yeah I tried, but the problem is the same as with the TextView, as everything is inside a LinearLayout, new elements will be inserted just below the last element. Setting a margin could be a solution but I don't think it's a good one, as I have to establish an absolute margin and depending on the screen size of the device, a scroll could appear

**Comment by jesmrec** [comment]
Another proposal is replacing the `New to ownCloud` link for the `Settings`.

The `New to ownCloud` is a link to `https://owncloud.com/mobile-apps` . That link points to a web view, that points to the stores. Anyone that reaches the link have the app installed, so the link is meaningless. It'd make sense if it points to the help web, but this will be linked from the `Settings` that will be reachable from login view.

**Comment by JuancaG05** [comment]
Ok, so, following @jesmrec suggestion, we have 3 more proposals (same as before but without the `New to ownCloud?` link)

| Proposal 4 | Proposal 5 | Proposal 6 |
| ---------------------------------------------- | -------------------------------------------- | -------------------------------------------- |
| <img width="270" src="https://user-images.githubusercontent.com/57049315/116524367-97042b80-a8d7-11eb-8f2d-8b3cdfbc6e70.png"> | <img width="270" src="https://user-images.githubusercontent.com/57049315/116524400-a08d9380-a8d7-11eb-86af-61e5299541ce.png"> | <img width="270" src="https://user-images.githubusercontent.com/57049315/116524421-a6837480-a8d7-11eb-8432-0fcd71153784.png"> |

Another solution might be placing the icon (or the text) just above the ownCloud logo, at the top-right.

Let me know what you think @abelgardep @jesmrec @theScrabi @michaelstingl @tbsbdr @hosy

**Comment by jesmrec** [comment]
I'm sorry for the noise... we've realised that the `new to ownCloud` is brandable and customers are using it to set their own welcome. So, we can not get rid of it.

**Comment by abelgardep** [comment]
I would go with the second one. I'm not sure about the icon proposal 🤔  But if it is ok for everyone, let's do it that way.

**Comment by hosy** [comment]
@JuancaG05 you mentioned that you are using a `LinearLayout`. I would vote for a bottom solution and as I'm not totally wrong, it should also possible with a `LinearLayout` and without scrolling. Maybe you need a `FrameLayout` as parent and put the `LinearLayout` inside!?

**Comment by JuancaG05** [comment]
> @JuancaG05 you mentioned that you are using a `LinearLayout`. I would vote for a bottom solution and as I'm not totally wrong, it should also possible with a `LinearLayout` and without scrolling. Maybe you need a `FrameLayout` as parent and put the `LinearLayout` inside!?

Thanks for the suggestion! Finally I used another approach to get it, but same result, just explaining it in the next comment 😉

**Comment by JuancaG05** [comment]
Finally, I could move the link to the settings screen to the bottom. I decided to use text instead of icon so that it looks more similar to iOS app.
Before, the hierarchy of views we had was:
**FrameLayout > ScrollView > LinearLayout for login views > Several other views and layouts inside to organize the content**
Taking into account that a ScrollView can only have 1 child, the solution I took was transforming the hierarchy to:
**FrameLayout > ScrollView > ConstraintLayout > LinearLayout for login views & LinearLayout for settings link button**
That way, using properly the constraints, we can have the settings button at the bottom, being responsive for the different screen sizes.

The final result is:

| Portrait | Landscape |
| ---------------------------------------------- | -------------------------------------------- |
| <img width="270" src="https://user-images.githubusercontent.com/57049315/116537036-fbc68280-a8e5-11eb-99e2-e1f5dcb730e7.png"> | <img width="500" src="https://user-images.githubusercontent.com/57049315/116537042-fec17300-a8e5-11eb-9ea0-65959e706376.png"> |

Hope you like it and users find it comfortable! 😃
