### ISSUE TITLE
[RELEASE] 2.12oem

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2644]
### TASKS:

- [x] [GIT] Create `release_2.12_oem` branch in owncloud/android from master, if there's something new to include.
- [x] [QA] Test plan
- [x] [DIS] Generate test APKs files from `release_2.12_oem` branch in owncloud/android
- [x] [GIT] Create and sign tag `oc-android-2.12_oem` in HEAD commit of `release_2.12_oem` branch or 2.12 commit (depending on if there's new changes or not), in owncloud/android
- [x] [GIT] Create and sign tag `1.0.2_oem` in 1.0.2 commit of master branch, in owncloud/android-library
- [x] [DIS] Generate final APKs files from signed commit in owncloud/android and perform some basic operations
- [x] [GIT] Merge branch `release_2.12_oem` in owncloud/android, into master

_____

### BUGS & IMPROVEMENTS

- [X] (1) Crash when sharing with users https://github.com/owncloud/android/issues/2644#issuecomment-527387496 [FIXED]

**Comment by jesmrec** [comment]
QA.

Checks to do:

- [ ] SAML auth
- [ ] SAML session expiration
- [ ] Transfers: uploads and downloads
- [ ] Basic file operations: folder creation, copy, move, delete, rename

Sharing (main topic):

- [ ] Create private share with user
- [ ] Create private share with group
- [ ] Modify permissions private share
- [ ] Resharing
- [ ] Remove private share

- [ ] Create public share file
- [ ] Create public share folder
- [ ] Edit permissions private share file
- [ ] Edit permissions private share folder 
- [ ] Remove private share

**Comment by jesmrec** [comment]
### (1)

In a SAML server:

1. Attach an account
2. Share a file with another user

Current: when the app looks for the sharee, crashes.

Stacktrace:

```
2019-09-03 11:46:13.254 27121-27182/? E/UsersAndGroupsSearchProvider: Exception while parsing shareWithAdditionalInfo
    org.json.JSONException: No value for shareWithAdditionalInfo
        at org.json.JSONObject.get(JSONObject.java:392)
        at org.json.JSONObject.getString(JSONObject.java:553)
        at com.owncloud.android.sharees.presentation.UsersAndGroupsSearchProvider.searchForUsersOrGroups(UsersAndGroupsSearchProvider.kt:182)
        at com.owncloud.android.sharees.presentation.UsersAndGroupsSearchProvider.query(UsersAndGroupsSearchProvider.kt:116)
        at android.content.ContentProvider.query(ContentProvider.java:1057)
```

Expected: no crash

**Comment by jesmrec** [comment]
bug fixed, and all tests passed. Approved.

**Comment by davigonz** [comment]
Everything is done in our side
