### ISSUE TITLE
[RELEASE] 2.13

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2645]
### TASKS:

 - [x] [GIT] Create branch release_1.0.3 in owncloud/android-library from master
 - [x] [GIT] Create branch release_2.13 in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudComLibrary module
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [DIS] Generate test APK file from `release_2.13` branch in owncloud/android
 - [x] [GIT] Create and sign `oc-android-2.13` tag in HEAD commit of `release_2.13` branch, in owncloud/android
 - [x] [GIT] Create and sign `1.0.3` tag in HEAD commit of stable `release_1.0.3` branch, in owncloud/android-library
 - [x] [DIS] Generate final APKs from signed commit in owncloud/android
 - [x] [QA] Perform some minor tests in the final apk.
 - [x] [DIS] Create new release on Github Android repository
 - [x] [mail] inform john@owncloud.com and emil@owncloud.com about new release.
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [GIT] Merge branch `release_1.0.3` in owncloud/android-library, into master
 - [x] [GIT] Merge branch `release_2.13` in owncloud/android, into master
 - [x] [GIT] merge master branch into stable, in owncloud/android-library
 - [x] [GIT] merge master branch into stable, in owncloud/android

_____

Test plan:

https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.13.0/Doc%20Provider%20-%20regression.md

### BUGS & IMPROVEMENTS

- [x] (1) Copy/move in Android 7 between different providers https://github.com/owncloud/android/issues/2645#issuecomment-535112654 [WON'T BE FIXED, NOT SUPPORTED BY THE ANDROID SYSTEM]

### PRs:
- App: https://github.com/owncloud/android/pull/2666
- Library: https://github.com/owncloud/android-library/pull/267

**Comment by davigonz** [comment]
Initial tasks done and release branches created, @jesmrec ready to test

**Comment by jesmrec** [comment]
### (1)

With Android 7, Copy and Move operations are not performed over folders between different providers.

These are the steps i performed:

1. Attach an oC account to the app, browse, and download some files, to assure the ownCloud directory is created inside the device storage. (to be sure https://github.com/owncloud/android/issues/2662 does not happen)
2. With document provider (Downloads app), copy/move a file from the oC account to "Downloads" -> correctly done
3. With document provider (Downloads app), copy/move a folder that contains files (not necessary subfolders) from oC account to "Downloads"

Current: `Couldn't copy/move` 
Expected: Copied/moved

NOTE: Copie/move inside the same account works properly.

**Comment by davigonz** [comment]
Regarding [(1) bug](https://github.com/owncloud/android/issues/2645#issuecomment-535112654), folder creation is not supported in "Downloads" location so it's not possible to copy folders there. The same behaviour is reproducible when copying folders from other cloud solutions.

**Comment by jesmrec** [comment]
Beyond the document provider, some smoke test checks were performed:

- [X] Authentication basic
- [X] Authentication OAuth2
- [X] Transfers (uploads/downloads)
- [X] Basic file operations (rename, remove, move, copy, open, av. offline)
- [X] Upgrade from 2.12

**Comment by jesmrec** [comment]
Approved on my side.

**Comment by davigonz** [comment]
> Approved on my side.

Let's move it forward then

**Comment by davigonz** [comment]
We are done here, waiting for spreading the word

**Comment by prsnbrg** [comment]
Please publish this version on F-Droid.

**Comment by davigonz** [comment]
> Please publish this version on F-Droid.

It will be automatically updated in the coming days
