### ISSUE TITLE
[RELEASE] 2.13.1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2664]
### TASKS:

- [x] [GIT] Create branch `release_2.13.1` in owncloud/android from master
- [x] [DEV] Update version number and name in build.gradle in owncloudApp module
- [x] [DIS] Create changelog file (< 500 chars) and add to `CHANGELOG.md` in owncloud/android
- [x] [QA] Design Test plan
- [x] [QA] Regression Test plan
- [x] [DIS] Generate test APK file from `release_2.13.1` branch in owncloud/android
- [x] [GIT] Create and sign `oc-android-2.13.1` tag in HEAD commit of `release_2.13` branch, in owncloud/android
- [x] [DIS] Generate final APKs from signed commit in owncloud/android
- [x] [QA] Perform some minor tests in the final apk.
- [x] [DIS] Create new release on Github Android repository
- [x] [mail] inform marketing team about new release.
- [x] [DIS] Upload & publish release APK and changelog in Play Store
- [x] [DIS] Update screenshots and store listing, if needed, in Play Store
- [x] [GIT] Merge branch `release_2.13.1` in owncloud/android, into master
- [x] [GIT] merge master branch into stable, in owncloud/android
- [x] [SPREAD THE WORD] Write topic in central about the new release 

_____

### PRs:
- App: https://github.com/owncloud/android/pull/2681

**Comment by prsnbrg** [comment]
Reminder: Please publish this version on F-Droid after finalizing.

**Comment by davigonz** [comment]
> Reminder: Please publish this version on F-Droid after finalizing.

Same as https://github.com/owncloud/android/issues/2645#issuecomment-535815653, it will be automatically published a few days after the release

**Comment by davigonz** [comment]
@jesmrec ready to QA

**Comment by jesmrec** [comment]
Since this version only includes https://github.com/owncloud/android/pull/2670, check over `release_2.13.1` branch will be:

- [ ] Check OAuth2 flow: renewal and revokal of tokens
- [ ] Basic auth
- [ ] Basic operations (create folder, copy, move, rename, delete)
- [ ] Transfers (uploads, downloads)
- [ ] SAML auth
- [ ] Upgrade from 2.13
- [ ] Upgrade from 2.12 (since 2.13 is a "short" release and it is probably that many people are still at 2.12)

**Comment by jesmrec** [comment]
Everything passed. Approved.

**Comment by davigonz** [comment]
Release completed from our side, closing this...
