### ISSUE TITLE
[FEATURE REQUEST] Additional nuance for download indicator when local file is out of date

### ISSUE THREAD

**Issue by PVince81** [owncloud/android#2688]
**Is your feature request related to a problem? Please describe.**
When a file is not mark as available offline but downloaded locally, it receives a green download indicator. When done once this is fine.
However when the file has changed on the server, I see the mtime change to "a few seconds ago" but the indicator is still green. This many times led me to believe that the file was downloaded already when it wasn't. Also I forgot to mark this file as "available offline" and forgot that an auto-synced file has a pink indicator.

More context: normally one could argue that if I tap the file to open it then it would sync anyway. In my use case it was an APK file which I cannot open through the mobile client for some reason, so I had to resort to an external file manager to open it there. So at the time where I saw that the mtime changed I assumed that the file synced and then switched to the external file manager to install the APK.

**Describe the solution you'd like**
Whenever the local file is different from the remote file, I suggest to use a different indicator.
Maybe the indicator could become gray or green but transparent.
The indicator should clearly convey the idea that the files are different and a manual sync might be necessary.
Apart from the reason stated in my "more context" above, I think a user might be preparing from an offline trip and wants to make sure that his important files were already synced (but ones not marked as available offline). They might see the green indicator and believe that they are up to date when they aren't.

**Describe alternatives you've considered**
None. Well, or always mark files as available offline.
Or maybe have an option that whenever I open a file through the client it automatically becomes always available offline so that I never run into the green indicator issue.

**Additional context**

### TASKS

- [ ] Research (if needed): UX research, visual solution ?
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by DeepDiver1975** [comment]
🤖 Automated issue triage by Claude Code review agent.

This issue was opened before 2020 and has had no activity since then, so we are
closing it as outdated. If this is still relevant on a current ownCloud release,
please **reopen** (or open a fresh issue) with up-to-date details — thank you\!
