### ISSUE TITLE
[FEATURE REQUEST] Sorting by size without obeying file/folder

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2717]
This is the following of https://github.com/owncloud/android/pull/2710

In such PR, the behaviour is applied to "sorting by date". Following the web UI, "sorting by size" must get the same behaviour

### TASKS

- [x] Create branch feature/sortBySizeMix
- [x] Development tasks
  - [x] Implement new way of size sorting
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App #2719 
- Library (if needed)

**Comment by davigonz** [comment]
Merged
