### ISSUE TITLE
[BUG] Snackbar in passcode view is not displayed

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2722]
#### Case 1
1. Open Settings > Passcode lock
2. Enter passcode
3. In the 2nd try, enter a different number

Update: two more cases where this bug appeared were fixed (the solution was the same)

#### Case 2
1. Register a passcode correctly
2. Close the app
3. Open the app and enter an incorrect passcode

#### Case 3
1. Register a passcode correctly
2. Go to Passcode lock to try to remove the current passcode
3. Enter an incorrect passcode

### Actual behaviour
Snackbar that shows the error is hidden between the soft keyboard

### Expected behaviour
Error message is shown just below the passcode input, only when the input error has just happened and the user hasn't introduced another passcode yet, and snackbar is not shown anymore

### TASKS

- [x] Create branch fix/bug_snackbar_passcode
- [x] Development tasks
  - [x] Add a new TextView to the XML file
  - [x] Replace Snackbar creation by printing a message in the TextView
  - [x] Adapt UI tests
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch fix/bug_snackbar_passcode into master

**Comment by JuancaG05** [comment]
I found myself with this bug. Maybe a good approach, instead of hiding the keyboard for the snackbar to be visible (a bit uncomfortable) or displaying the snackbar above the keyboard, is to add a little TextView just above "Enter your passcode" and make it visible only when the passcode confirmation is not correct?

**Comment by jesmrec** [comment]
That makes sense, and interesting improvement we can include. Thanks for the feedback!

**Comment by theScrabi** [comment]
How about we adjust the layout according to visibility of the virtual keyboard:
https://developer.android.com/training/keyboard-input/visibility#Respond

**Comment by JuancaG05** [comment]
> I have another suggestion. We could adjust the layout according to the visibility of the softkeyboard:
> https://developer.android.com/training/keyboard-input/visibility#Respond

The softkeyboard usually fills more or less half of the fragment height (with the device in vertical position), maybe doing what you suggest requires scrolling, what makes it more uncomfortable. Also, if we displayed the snackbar over the keyboard, maybe in small devices it could cover some displayed views such as the button. In this case I think the best way is to simply add a TextView warning about the error, but let's collect more opinions @abelgardep @jesmrec

**Comment by jesmrec** [comment]
> The softkeyboard usually fills more or less half of the fragment height (with the device in vertical position), maybe doing what you suggest requires scrolling, what makes it more uncomfortable. Also, if we displayed the snackbar over the keyboard, maybe in small devices it could cover some displayed views such as the button. In this case I think the best way is to simply add a TextView warning about the error, but let's collect more opinions @abelgardep @jesmrec

agreed.

**Comment by JuancaG05** [comment]
Finally, instead of creating a new TextView to avoid overload the screen with texts, I reused the header TextView to include the message for telling the user about the error:

| Old (snackbar hidden behind sofkeyboard) | New |
| ---------------------------------------------- | -------------------------------------------- |
| <img width="270" alt="device-2021-04-22-105219" src="https://user-images.githubusercontent.com/57049315/115685831-e20ec380-a358-11eb-86b2-0987170d5217.png"> | <img width="270" alt="device-2021-04-22-105810" src="https://user-images.githubusercontent.com/57049315/115686666-b93afe00-a359-11eb-913b-84565abdb025.png"> |

Now, totally visible for the user.

Opinions on this? Suitable message (it's the same which previously appeared in the snackbar)? Suitable place? @abelgardep @jesmrec @theScrabi @michaelstingl @tbsbdr

**Comment by abelgardep** [comment]
I've been checking this more deeply, and I'm not sure about this approach. Replacing the title may not be the best solution.

We could show the message error just below the passcode entry. Something like this. What do you think? 

We could use the same approach for pattern errors to keep them aligned (At the moment a snack bar is shown for pattern errors). New issue?

![passcode_error](https://user-images.githubusercontent.com/47524927/116039494-18a35180-a66b-11eb-8060-3d40eed9304a.png)

**Comment by tbsbdr** [comment]
I think this approach is in line with user expectations of an error message 👍
