### ISSUE TITLE
[RELEASE] 2.14.1

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2765]
### TASKS:
 - [x] [DEV] Only show the server version warning splash screen if one of the connected accounts is an old server
 - [x] [DEV] Only show the Android 4.4 deprecation warning splash screen if the device is affected
 - [x] [GIT] Create branch `release_1.0.4.1` in owncloud/android-library from master
 - [x] [GIT] Create branch `release_2.14.1` in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudComLibrary module
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [DIS] Generate test APK file from `release_2.14.1` branch in owncloud/android
 - [x] [GIT] Create and sign tag `oc-android-2.14.1` in HEAD commit of `release_2.14.1` branch, in owncloud/android
 - [x] [GIT] Create and sign tag `1.0.4.1` in HEAD commit of `release_1.0.4.1` branch, in owncloud/android
 - [x] [DIS] Generate final APKs from signed commit in owncloud/android
 - [x] [QA] Perform some minor tests in the final apk, including an update from previous version.
 - [x] [DIS] Create new release on Github Android repository
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [GIT] Merge branch `release_1.0.4.1` in owncloud/android-library, into master
 - [x] [GIT] Merge branch `release_2.14.1` in owncloud/android, into master
 - [x] [GIT] merge `release_1.0.4.1` branch into stable, in owncloud/android-library
 - [x] [GIT] merge `release_2.14.1` branch tag into stable, in owncloud/android

### PRs:
- App: https://github.com/owncloud/android/pull/2766
- Library: https://github.com/owncloud/android-library/pull/290

**Comment by jesmrec** [comment]
QA

2.14 -> 2.14.1

| | core < 10 | core >= 10 | 
| :-:  | :-: | :-: | 
|Android < 5 || Wizard with 4.4 deprecation displayed |
|Android >= 5 || No wizard displayed |

**Comment by davigonz** [comment]
Done, available in Google Play already
