### ISSUE TITLE
[RELEASE] 2.14.1_oem

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2784]
### TASKS:

 - [ ] Test branded splash screen 
 - [ ] Test removing SAML support
 - [ ] Smoke test over a branded version with all the new stuff
 - [ ] [GIT] Create and sign tag 'oc-android-2.14.1_oem' in HEAD commit of stable master branch, in owncloud/android
 - [ ] [GIT] Create and sign tag 'Y.Y.Y' in HEAD commit of stable master branch, in owncloud/android-library
 - [ ] [COM] inform `#release_coordination` and `#marketing` in internal chat
 - [ ] [DOC] Update owncloud.org/download version numbers (notify rocketchat #marketing)
____
