### ISSUE TITLE
[RELEASE] 2.14.2

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2791]
Bugfixing version. Issues related:

https://github.com/owncloud/android/issues/2785
https://github.com/owncloud/android/pull/2776 (after revision)

### TASKS:

 - [x] [GIT] Create branch release_2.14.2 in owncloud/android from release_2.14.1
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [DIS] Generate test APK file from `release_2.14.2` branch in owncloud/android
 - [x] [GIT] Create and sign tag `oc-android-2.14.2` in HEAD commit of `release_2.14.2` branch, in owncloud/android
 - [x] [DIS] Generate final APKs from signed commit in owncloud/android
 - [x] [COM] inform `#release_coordination` and `#marketing` in internal chat
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [DIS] Create new release on Github Android repository
 - [x] [DIS] Upload release APK to internal owncloud instance
 - [x] [GIT] Rebase and merge `release_2.14.2` branch in owncloud/android, into master
 - [x] [GIT] merge master branch into stable, in owncloud/android

_____

### PR
App: #2797

**Comment by hannesa2** [comment]
I would add something like this https://github.com/owncloud/android/pull/2726 (Error catcher, like Crashlytics) **asap**

**Comment by davigonz** [comment]
@jesmrec ready to test

**Comment by davigonz** [comment]
> I would add something like this #2726 (Error catcher, like Crashlytics) asap

@jesmrec about https://github.com/owncloud/android/pull/2726#issuecomment-555374159 , did you finally create the issue to discuss the topic, I can not find it.

It's very important for us to know whether those tools bring us more information than what we already have in the Android vitals section of Google Play Developer Console.

**Comment by jesmrec** [comment]
No, i will do.

**Comment by jesmrec** [comment]
Done: #2798
