### ISSUE TITLE
AppAuth integration - OAuth2

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2793]
The target is cleaning up the current OAuth2 implementation, and setting AppAuth instead

[AppAuth](https://appauth.io/)

### TASKS

- [X] Research https://github.com/owncloud/android/issues/2755
- [x] Create branch `new_arch/oauth_app_auth`
- [x] Development tasks
  - [x] Add AppAuth as a Build Dependency
  - [x] Create the ServiceConfiguration
  - [x] Build the AuthorizationRequest
  - [x] Handle authorization response
  - [x] Perform access token request
  - [x] Handle access token response
  - [x] Error handling
  - [x] Refresh token operation
  - [x] Multiaccount support
  - [x] Old code cleanup
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch `new_arch/oauth_app_auth` into master

### PR

- App: https://github.com/owncloud/android/pull/2800
- Library (if needed): https://github.com/owncloud/android-library/pull/300

**Comment by abelgardep** [comment]
@jesmrec Ready to QA 👍
