### ISSUE TITLE
[New Arch] Account manager - account creation after login

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2794]
Account manager management in the context of new architecture.

AccountAuthenticator is the main class

### TASKS 

- [x] Research the current status, how the data is retrieved from account manager
- [x] Development tasks:
  - [x] Local datasource
    - [x] `LocalAuthenticationDataSource`
      - [x] addAccount
    - [x] `OCLocalAuthenticationDataSource`
      - [x] addAccount
  - [x] Call account creation from `OCAuthenticationRepository`
  - [x] Fix multiaccount by using `AccountAuthenticatorActivity`
  - [x] OAuth
  - [x] Use cases:
    - [x] getUserData
  - [x] Account update when authorization expires
  - [x] Handle errors
  - [x] Tests
    - [x] Data layer:
      - [x] OCAuthenticationRepositoryTest
      - [x] OCLocalAuthenticationDataSourceTest
    - [x] Domain layer:
      - [x] LoginBasicAsyncUseCase
      - [x] LoginOAuthAsyncUseCase
      - [x] GetBaseUrlUseCase
      - [x] SupportsOAuth2UseCase
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch `new_arch/complete_login_flow` into `new_arch/login`

### PR
- App: https://github.com/owncloud/android/pull/2826
- Library (if needed): https://github.com/owncloud/android-library/pull/309
