### ISSUE TITLE
[New arch] Refactor AuthenticatorActivity

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2808]
AuthenticatorActivity handles UX, network operations, account creation etc..

The main idea is to reduce AuthenticatorActivity responsabilities using usecases created in #2634 

### TASKS

- [x] Research (if needed)
- [x] Create branch new_arch/2808-Refactor_AuthenticationActivity
- [x] Development tasks
  - [x] Convert AuthenticatorActivity from Java to Kotlin
  - [x] Create AuthenticatorViewModel
  - [x] Handle UnsignedCertificate error
  - [x] Fix glitch not showing icons on landscape
  - [x] Call GetServerInfo from viewmodel and handle error
  - [x] Remove AuthenticateAsyncTask
  - [x] Remove callbacks
  - [x] Remove GetServerInfoOperation (Logic moved to ServerRepository)
  - [x] Remove GetAuthenticationMethodsOperation (Logic moved to ServerRepository)
  - [x] Remove GetServerInfoOperation from OperationsService
  - [x] Login using usecase
  - [x] Error handling
  - [x] Handle rotation changes
  - [x] Add UI tests (LoginActivity)
  - [x] Add Unit tests (OCAuthenticationViewModel)
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch new_arch/2808-Refactor_AuthenticationActivity into master

### Questions
- Should we remove landscape mode from login? This would reduce logic and test cases. 

### PR
- App: https://github.com/owncloud/android/pull/2826
- Library (if needed): https://github.com/owncloud/android-library/pull/309
