### ISSUE TITLE
[RELEASE] 2.15

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2813]
### TASKS:

 - [x] [GIT] Create branch `release/2.15.0` in owncloud/android-library from master
 - [x] [GIT] Create branch `release/1.0.5` in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudComLibrary module
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DEV] Add new wizard steps:
   - [x] Authentication / OIDC
   - [x] Bottom navigation bar 
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan 
 - [x] [DIS] Generate test APK file from `release/2.15.0` branch in owncloud/android
 - [x] [GIT] Create and sign tag `oc-android-2.15.0` in HEAD commit of release branch, in owncloud/android, to keep the history
 - [x] [GIT] Create and sign tag `1.0.5` in HEAD commit of release branch, in owncloud/android-library, to keep the history
 - [x] [DIS] Generate final APKs from signed commit in owncloud/android
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [COM] Create blog post in central with the official release
 - [x] [COM] inform `#release_coordination` and `#marketing` in internal chat, so they can start to spread the world
 - [x] [COM] Inform `#updates` when the release is out. Send mail to release-coordination list.
 - [x] [GIT] Merge branch `release/1.0.5` in owncloud/android-library, into master
 - [x] [GIT] Merge branch `release/2.15.0` in owncloud/android, into master
 - [x] [DIS] Upload release APK to internal owncloud instance
 - [x] [GIT] merge master branch into stable, in owncloud/android-library
 - [x] [GIT] merge master branch into stable, in owncloud/android
 - [ ] [DOC] Update owncloud.org/download version numbers (notify rocketchat #marketing) (not blocker)

_____

### QA

Regression test: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.15/Regression_2.15.md

#### BUGS & IMPROVEMENTS

- [x] (1) Check AppAuth for the new version -> create issue -> https://github.com/owncloud/android/issues/2891
- [x] (2) Trailing slash breaks URL request https://github.com/owncloud/android/issues/2813#issuecomment-624699764 [FIXED]
- [x] (3) Chunking oCIS https://github.com/owncloud/android/issues/2813#issuecomment-625079661 [DONE]
- [X] (4) Login view after browser flow https://github.com/owncloud/android/issues/2813#issuecomment-634084176 [FIXED]
- [x] (5) https://github.com/owncloud/android/issues/2882 [FIXED]
- [X] (6) Username with blanks https://github.com/owncloud/android/issues/2813#issuecomment-635139714 [FIXED]
- [X] (7) Downloads in oCIS https://github.com/owncloud/android/issues/2813#issuecomment-635254829 -> [OCIS] https://github.com/owncloud/ocis/issues/296
- [X] (8) https://github.com/owncloud/android/issues/2886 [FIXED]
- [X] (9) Navigation in shortcuts https://github.com/owncloud/android/issues/2813#issuecomment-637382344 [FIXED]

### PR
App: #2876 
Library: https://github.com/owncloud/android-library/pull/319

**Comment by jesmrec** [comment]
### (1)

Check for new release in AppAuth that fixes https://github.com/owncloud/android/pull/2800#issuecomment-585201614

Otherwise, we will point to a fork that includes the fix, till the release takes place.

**Comment by jesmrec** [comment]
### (1)

1. Set an URL with trailing slash

Current: Bad response. Requests are built by adding another trailing slash, so request are sent with double slash. Server response is a 500

Expected: Trailing slash should not break the URL check

Examples of URLS

demo.owncloud.com/
ocis-latest.owncloud.com/

Pixel 2 Android 10

**Comment by jesmrec** [comment]
### (3)

Check chunking implementation in oCIS based in capability `"bigfilechunking": true,`

If true: PUT, PUT, PUT... MOVE
if false or not present: PUT

We have to check if this behaviour also fits oC10

**Comment by jesmrec** [comment]
### (4) (improvement)

After completing OAuth2/OIDC flow in browser, login view appears again before redirecting to file list. This can be confusing for users, so it'd be a good idea to skip it, or showing different information.

CC @michaelstingl @abelgardep

**Comment by jesmrec** [comment]
### (6)

1. Set a correct basic auth URL
2. In the username field, set a correct username but put some blanks before and after the username, like `     user1     `
3. Set the correct password

Current: Login incorrect
Expected: Login correct, as in 2.14.2

Pixel 2 Android 10
`252c420`

**Comment by jesmrec** [comment]
Report (1) keeps happening. It is an AppAuth problem pending to be released there, so, the point is checking if we should upgrade our AppAuth version.

**Comment by jesmrec** [comment]
### (7)

In oCIS instance, i'm not able to download some kind of files (PDF, images). Txt are downloaded and displayed correctly:

![May-28-2020 12-20-52](https://user-images.githubusercontent.com/14894746/83130051-ff51f800-a0dd-11ea-8dd9-652fbb69e673.gif)

Pixel 2 Android 10
`252c420`

**Comment by abelgardep** [comment]
Related with [(7)](https://github.com/owncloud/android/issues/2813#issuecomment-635254829), Android App uses this header to determine the notification progress bar, and to check if file was fully downloaded. The absence of it leads to problems that were not reproducible with oC10 servers. Issue related: https://github.com/owncloud/ocis/issues/296

**Comment by abelgardep** [comment]
Related with [(4)](https://github.com/owncloud/android/issues/2813#issuecomment-634084176) we can not skip login view at that point since we need to exchange for accesstoken, create account and add it to account manager etc. And it can fail, so we can not skip that login view. But we can show the user info about what's happening. Something like: 'A browser should be opened now', 'Getting tokens', 'Tokens received, trying to login', 'Login succesfully, redirecting to file list' and so on. Do you agree @jesmrec @michaelstingl ?

**Comment by jesmrec** [comment]
> Related with (4) we can not skip login view at that point since we need to exchange for accesstoken, create account and add it to account manager etc. And it can fail, so we can not skip that login view. But we can show the user info about what's happening. Something like: 'A browser should be opened now', 'Getting tokens', 'Tokens received, trying to login', 'Login succesfully, redirecting to file list' and so on. Do you agree @jesmrec @michaelstingl ?

works for me

**Comment by michaelstingl** [comment]
Yeah, just add note.

**Comment by abelgardep** [comment]
### (9)

Navigation loop in sharedByLink and Av. Offline

Reproducible in 2.14.2
![shared_by_link_loop](https://user-images.githubusercontent.com/47524927/83498494-482df600-a4bc-11ea-9df8-174ce255631b.gif)

**Comment by jesmrec** [comment]
From my side it is approved

**Comment by jesmrec** [comment]
Release out
