### ISSUE TITLE
[FEATURE REQUEST] New bottom navigation bar

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2817]
Since https://github.com/owncloud/android/issues/2742 is a huge task, we have to split it up and go step by step, delivering changes that users can see in a short-therm.

The first step would be creating a new bottom navigation bar for moving between **Files, Uploads, Av. offline and Shared by link options**, being more accessible for the users than the current location of those options in the side menu. 

Therefore, **Files, Uploads, Av. offline and Shared by link options** will be removed from the side menu and reallocated to the new bottom navigation bar.

### TASKS

- [x] UI design

[<img src="https://user-images.githubusercontent.com/15261363/74657834-55cfa200-5191-11ea-9fe3-f8cf964353ba.png" width="350px"/>](https://user-images.githubusercontent.com/15261363/74657834-55cfa200-5191-11ea-9fe3-f8cf964353ba.png)

- [x] Create branch `feature/bottom_nav_bar`
- [ ] Development tasks
  - [x] Paint the bar with the icons
  - [x] Update icons with vectorized ones [Use all files filled one]
  - [x] Navigate using bottom navigation bar instead of drawer
  - [x] Remove options from drawer
  - [x] Polish code
  - [x] Remove transition from uploads tab
  - [x] Hide the bar in multiselection mode
  - [x] Show snackbar between navigation bar and FAB
  - [x] Fix navigation bar to bottom
  - [ ] N2H: hide bar when scrolling down
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch `feature/bottom_nav_bar` into master

### PR

- App: https://github.com/owncloud/android/pull/2845
- Library (if needed)
