### ISSUE TITLE
[New arch] Synchronization

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2818]
# Introduction
We have been working on updating the old Android App to a new architecture for a long time.

The new architecture is MVVM and we can find more details about it here: https://github.com/owncloud/android/issues/2351

To do this, we started with Shares functionality, we continued with Authentication, and finally, we are working on the most crytical part of the app: the Synchronization. This last epic is huge and we created a milestone to keep track of it: https://github.com/owncloud/android/milestone/43

# Synchronization
App PR: https://github.com/owncloud/android/pull/2934
Library PR: https://github.com/owncloud/android-library/pull/339

### Create folder [QA Passed] ✅ 
Issue: https://github.com/owncloud/android/issues/2861
PR: https://github.com/owncloud/android/pull/2923
QA: https://github.com/owncloud/android/issues/2818#issuecomment-683732010
QA reports fixed:
- [x] (1)

### Rename [QA Passed] ✅ 
Issue: https://github.com/owncloud/android/issues/2863
PR: https://github.com/owncloud/android/pull/3231
QA: https://github.com/owncloud/android/issues/2818#issuecomment-846984004
QA reports fixed:
- [x] (1)
- [x] (2)
- [x] (3)
- [x] (4)

### Remove [Bugfixing]  
Issue: https://github.com/owncloud/android/issues/2864
PR: https://github.com/owncloud/android/pull/3214
QA: https://github.com/owncloud/android/issues/2818#issuecomment-834301102
QA reports fixed:
- [x] (1)
- [x] (2)
- [ ] (3) [P2] Removing many files blocks the app
- [ ] (4) [P2] Txt file removal cleans up the file list

### Copy [Bugfixing] 
Issue: https://github.com/owncloud/android/issues/2866
PR: https://github.com/owncloud/android/pull/3253
QA: https://github.com/owncloud/android/issues/2818#issuecomment-849394483
QA reports fixed:
- [x] (1)
- [x] (2)
- [ ] (3) [P3] Error message too long

### Move [QA Passed] ✅ 
Issue: https://github.com/owncloud/android/issues/2865
PR: https://github.com/owncloud/android/pull/3232
QA: https://github.com/owncloud/android/issues/2818#issuecomment-844022500
QA reports fixed:
- [x] (1)

## Transfers
Transfers have changed completely from the previous version. We have moved from foreground services to WorkManager. They can be done parallely now.

Some notifications have been removed, previously it was a little bit messy when several uploads/downloads were done very fast.

### Uploads [Bugfixing] 
There are two types of uploads at the moment.
Plain Uploads: When we get the content Uri via SAF or Camera Uploads
Plain or Chunks(depending on file size): When we share with oC, via documents provider, upload via camera, and when we upload conflicts.

Issue: https://github.com/owncloud/android/issues/3424
PR: https://github.com/owncloud/android/pull/3686
QA: https://github.com/owncloud/android/issues/2818#issuecomment-1157608496
QA reports fixed:
- [x] (1) [P2] Error takes long to happen
- [x] (2) Upload with no connection [FIXED]
- [ ] (3) [P3] Discussion: create or not a deleted target folder
- [x] (4) Folder error [FIXED]
- [ ] (5) [P2] Notifications missing
- [x] (6) Share txt does not work. [FIXED]
- [X] (7) [NON REPRODUCIBLE]
- [x] (8) [P1] Chunking  [FIXED via https://github.com/owncloud/android/pull/3763)]
- [x] (9) Failed uploads are resumed after removing individually [FIXED]
- [x] (10) Error in maintenance mode [FIXED]
- [X] (11) Folder error  [WONT FIX, same as (4)]
- [x] (12) Share txt does not work. [FIXED]
- [X] (13) Create with external [FIXED]
- [ ] (14) [P2] Not posible to read uploads view when many uploads running
- [x] (15) [P1] Uploading many files, part of them are missing [FIXED]
- [x] (16) Failed uploads are resumed after clearing all [FIXED]
- [x] (17) [P1] Folder error after killing the app [FIXED]
- [ ] (18) [P3] Same status for uploading and pending uploads
- [ ] (19) [P3] Clear button in enqueued section of uploads view

### Downloads [Bugfixing]
Issue: https://github.com/owncloud/android/issues/2872
PR: https://github.com/owncloud/android/pull/2918
QA: https://github.com/owncloud/android/issues/2818#issuecomment-1155115346
QA reports fixed:

- [X] (1) [P1] Crash when download some kind of files [FIXED]
- [X] (2) Notifications [FIXED]
- [X] (3) [P1] Downloads in uploads view [FIXED]
- [X] (4) Green badge in downloaded items [FIXED]
- [x] (5) [P1] Crash when download is cancelled 
- [ ] (6) [P2] OAuth2 expired token 
- [ ] (7) [P2] Progress bar missing

### Open with [Bugfixing]
QA: https://github.com/owncloud/android/issues/2818#issuecomment-1157358210
QA reports fixed:
- [x] (1)

### Store uploads into the new Room database [Bugfixing]
At the moment, we have the uploads database in the old database. We need to move it to the new one. Also, we need to move the current OCUpload model to the domain module. By the way, we should consider adding Downloads to that new table. At the moment we don't store the downloads in the database and it could be beneficial.

Issue: https://github.com/owncloud/android/issues/3426 & https://github.com/owncloud/android/issues/3717
PR: https://github.com/owncloud/android/pull/3710 & https://github.com/owncloud/android/pull/3729

### Transfers view [Bugfixing]
We need to adapt the uploads screen when we migrate the database. The idea is to take advantage of room improvements and observe any change via LiveData or Flow. By the way, we think that it would be a good idea to transform the uploads screen into a Transfer screen where the user could check the latest transfers, not only the uploads but also the downloads.

Issue: https://github.com/owncloud/android/issues/2858
PR: https://github.com/owncloud/android/pull/3718

## File list view [Bugfixing]
The main screen of the app has been refactored. Lots of changes have been applied including recycler view, live data... etc

Issue: https://github.com/owncloud/android/issues/2869
PR: https://github.com/owncloud/android/pull/3517
QA: https://github.com/owncloud/android/issues/2818#issuecomment-1155087211
QA reports fixed:
- [x] (1)
- [x] (2)
- [X] (3) [FIXED]
- [x] (4)
- [x] (5) [DONE]
- [X] (6) [P2] Scroll bar missing [FIXED]

## Av. Offline [Bugfixing]
As we already did some time ago with the camera uploads periodic work, we need to move the av offline job to work manager.

Issue: https://github.com/owncloud/android/issues/3246
PR: https://github.com/owncloud/android/pull/3715
QA: https://github.com/owncloud/android/issues/2818#issuecomment-1198961987
QA reports fixed:
- [X] (1) File automatic [FIXED]
- [ ] (2) [P2] Sync when opening file - more file sync suitable
- [X] (3) [P1] Folder not synced, only discovered [FIXED]
- [ ] (4) [P1] Crash when moving av. offline folder
- [X] (5) [P2] Upload changes in advance [FIXED]
- [ ] (6) [P3] unav. offline icon located in menu, not in toolbar
- [X] (7) Remove all av. offline stuff when account is removed [FIXED]

## Bottom navigation bar [Bugfixing]
At the moment the bottom navigation bar is not working properly. It should update the file list with the new upload list option and show only the files for that shortcut. 

PR: https://github.com/owncloud/android/pull/3719
QA: https://github.com/owncloud/android/issues/2818#issuecomment-1216772525
QA reports fixed:
- [x] (1)
- [x] (2)
- [x] (3)
- [x] (4)
- [ ] (5) [P3] Glitch when browsing back after open in
- [X] (6) To fix in https://github.com/owncloud/android/issues/3016

## Conflicts Management [TO DO]
We need to detect if there are new conflicts between local and remote files and let the user choose to keep local, remote or both.

Issue: https://github.com/owncloud/android/issues/3005

## Refresh folder [Tested with folder synchronization]
Refreshing the folder should keep the folder updated with remote content and also, remove any file locally that is not available on the remote server anymore

Issue: https://github.com/owncloud/android/issues/3268
PR: https://github.com/owncloud/android/pull/3709

## File synchronization [Bugfixing]
Files should be synchronized, updating or removing local data in ScopedStorage and database depending on the remote changes.

Issue: https://github.com/owncloud/android/issues/3350
PR: https://github.com/owncloud/android/pull/3704
QA: https://github.com/owncloud/android/issues/2818#issuecomment-1173699585
QA reports fixed:
- [ ] (1) [P1] Updates in server not reflected 
- [ ] (2) Badge gone

## Folder synchronization [Bugfixing]
Same as file synchronization but for folders. Recursively.
PR: https://github.com/owncloud/android/pull/3707 & https://github.com/owncloud/android/pull/3709
QA: https://github.com/owncloud/android/issues/2818#issuecomment-1176105909
QA reports fixed:
- [x] (1) [P2] Relocation mechanism [WONT FIX]
- [x] (2)
- [x] (3)
- [x] (4)
- [X] (5) [P3] No error message after pulling down if no connection available [DONE]
- [X] (6) [P1] Whole account refreshed after pulling down in root [FIXED]
- [X] (7) [P1] All files synced after reopening [FIXED]
- [X] (8) [P1] Request flooding [FIXED]

## Uploads migration (Under QA)

Issue: https://github.com/owncloud/android/issues/2858
PR: https://github.com/owncloud/android/pull/3718
QA: https://github.com/owncloud/android/issues/2818#issuecomment-1230150745
QA reports:

- [X] (1) Uploads enqueued forever, after upgrade  [FIXED]
- [x] (2) [P1] Sharing big file with oC causes a crash [FIXED]
- [x] https://github.com/owncloud/android/issues/3741
- [x] (3) [P1] Uploads replayed after upgrading [WON'T FIX]
- [ ] (4) [P2] Uploads in progress do not end

## Miscellaneous

https://github.com/owncloud/android/issues/2818#issuecomment-1247805171

- [ ] (1) [P2] Toolbar incorrect after browsing

## Issues to have a look after this:

https://github.com/owncloud/android/issues/3721 [FIXED]
https://github.com/owncloud/android/issues/3741 [P1] [FIXED]
https://github.com/owncloud/android/issues/2070
https://github.com/owncloud/android/issues/2149
https://github.com/owncloud/android/issues/2834
https://github.com/owncloud/android/issues/2829
https://github.com/owncloud/android/issues/2921 [P1] [FIXED]
https://github.com/owncloud/android/issues/3708 [P2] [FIXED]

**Comment by jesmrec** [comment]
### Create Folder

AC:

- Folder created in the current path
- Name must not be already used
- Characters "/" and "\\" are forbidden
- Other errors:
   - No connectivity
   - Server not reached
   - Maintenance mode

**Comment by jesmrec** [comment]
### Fetch List of files https://github.com/owncloud/android/issues/2873

- Once a folder is browsed, list of files is fetched. Important data:

  - File name
  - Extension (to set a thumbnail)
  - Size 
  - Date
  - Permissions?
  - Private/Universal link (if included in the response)

**Comment by abelgardep** [comment]
### Remove file or folder #2864 
AC:
- Support removing the content in local (if downloaded), remote or both
- Removing a file locally, will remove the file from local storage
- Removing a file, will remove the file from the server and from local storage
- Removing a file that was already removed in the server, will remove local storage data
- Removing a folder will delete its content and itself, locally and on the server
- Removing a folder will remove all its hierarchy

**Comment by abelgardep** [comment]
### Download a single file #2872

AC: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.18/3169-Download%20.md

Not finished yet. Following points are needed before approval:
- Group notifications with progress. We need to decide how to show them when several downloads are performed parallelly. - This will have the same behavior for uploads. To be done together.
- No information will be shown in the adapters due to performance issues. (Icon downloading in the file list)
- Tests will be included in upcoming PR because several things will change till the final version.

**Comment by abelgardep** [comment]
### Move #2865 
AC: https://github.com/owncloud/QA/blob/master/Mobile/Android/Sync/Move.md

Pending:

- Check behavior when moving Av. Offline or moving to a folder marked as Av. Offline
- Check performance when moving A LOT OF files (Way to improve if needed)

**Comment by abelgardep** [comment]
### Rename #2863

AC: https://github.com/owncloud/QA/blob/master/Mobile/Android/Sync/Rename.md

**Comment by abelgardep** [comment]
### Copy #2866 

AC: https://github.com/owncloud/QA/blob/master/Mobile/Android/Sync/Copy.md

Files downloaded won't be copied in the local storage. We may save some local space this way, but we could duplicate them if needed.

**Comment by jesmrec** [comment]
## File list view

The main screen of the app has been refactored. Lots of changes have been applied including recycler view, live data... etc

Issue: https://github.com/owncloud/android/issues/2869
PR: https://github.com/owncloud/android/pull/3517

Reports and improvements

### (1) Multiselection

When long pressing, the multiselection checkboxes only displayed for the selected item:

![Screenshot 2022-06-14 at 13 45 24](https://user-images.githubusercontent.com/14894746/173569814-42306bec-efbd-4619-9513-3f8baa0f0114.png)

### (2) Share icons

1. Create a public link over an item -> chain icon is listed
2. Pull down to refresh

Current: Sharing icons are gone
Expected: Sharing icons in the list

### (3) Thumbnails non-downladed files

Thumbnails for non-downloded files are lost. Related: https://github.com/owncloud/android/issues/3525

**Comment by abelgardep** [comment]
@jesmrec Atomic operations are ready to test again

**Comment by jesmrec** [comment]
# Open With

### (1) Crash

1. Select a file from the list
2. Select `Open with`

Current: app crashes

```
2022-06-16 10:01:39.304 18045-18045/com.owncloud.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.owncloud.android.debug, PID: 18045
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(int)' on a null object reference
        at com.owncloud.android.ui.helpers.FileOperationsHelper.getIntentForGuessedMimeType(FileOperationsHelper.java:81)
        at com.owncloud.android.ui.helpers.FileOperationsHelper.openFile(FileOperationsHelper.java:97)
        at com.owncloud.android.presentation.ui.files.filelist.MainFileListFragment.onFileActionChosen(MainFileListFragment.kt:504)
        at com.owncloud.android.presentation.ui.files.filelist.MainFileListFragment.access$onFileActionChosen(MainFileListFragment.kt:82)
        at com.owncloud.android.presentation.ui.files.filelist.MainFileListFragment$actionModeCallback$1.onActionItemClicked(MainFileListFragment.kt:697)
        at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImpl.java:2708)
        at androidx.appcompat.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:140)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
        at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
        at android.widget.AdapterView.performItemClick(AdapterView.java:310)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3132)
        at android.widget.AbsListView$3.run(AbsListView.java:4047)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

Expected: no crash

Android 7
`624608f8`

**Comment by jesmrec** [comment]
# File synchronization 

Issue: https://github.com/owncloud/android/issues/3350

**Comment by jesmrec** [comment]
# Available offline

Issues:

### (1)

1. Set as av. offline a non-downloaded image (if image was downloaded, it is not reproducible)
2. Remove device connection
3. Click on the image to preview it

Current: `Downloading` status forever:

https://user-images.githubusercontent.com/14894746/181705317-80d50651-b8b2-4f1b-a89a-c2a348ac2899.mp4

Expected: Image previewed 

Pixel 5 Android12
`a14fe20c`

**Comment by jesmrec** [comment]
# Bottom Navigation Bar

Referenced: https://github.com/owncloud/android/pull/3719 

Issues:

**Comment by jesmrec** [comment]
# Notifications

status 2022-08-19

| | **master** | **arch** | **expected** |
|:-|:-:|:-:|:-:|
| **Download 1 file correct** | progress bar + finished | only when finished | |
| **Download 1 file error** | error message  | error message |
| **Download many correct** | one notif for every download | one notif for all downloads | one notif for all downloads |
| **Download many errors** |one error message | one error message|
| **Upload 1 file correct** | progress bar + finished | no notif |
| **Upload 1 file error** | error message | error message (unknown error) | error message |
| **Upload many** | one notif for every upload | no notif |
| **Upload many error** | one error message | one error message |

**Comment by jesmrec** [comment]
# Uploads migration 

### (1)

1. Install 2.21
2. Remove device connection (or any other action that cause failed uploads)
3. Upload some files -> They will fail
4. Update to current
5. Go to uploads view and retry failed uploads after recovering connection (or the error cause)

Current: uploads stay in "Enqueued" and never resume
Expected: uploads done finished

`ad0895a8a`
Samsung A51 Android 12

**Comment by jesmrec** [comment]
# Miscellaneous

### (1) [P2]

1. Open `Details` view of any file
2. Click on Share icon on the top
3. Click on back arrow

Current: toolbar is not correct. It includes items of root folder instead of Details view
Expected: Details view items

Samsung A51
Android12
`3fdbcc5d5`
