### ISSUE TITLE
[RELEASE] 2.15-beta1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2843]
### TASKS:
 - [x] [COORDINATION] Get in touch with community/marketing team to publish a blog post, several days before releasing.
 - [x] [GIT] Create **release/1.0.5_beta.1** branch in owncloud/android-library from master
         - Update version code and name in build.gradle.
 - [x] [GIT] Create **release/2.15_beta.1** branch from master and:  
    - [x] Update version code and name in build.gradle.
    - [x] Update changelog file (< 500 chars)
 - [x] [QA] Perform some tests @jesmrec
 - [x] [GIT] Create and sign tag `1.0.5-beta.1` in HEAD commit of **release/1.0.5_beta.1** branch, in owncloud/android-library
 - [x] [GIT] Create and sign tag `oc-android-2.15-beta.1` in HEAD commit of **release/2.15_beta.1** branch, in owncloud/android
 - [x] [DIS] Generate test APKs files from `oc-android-2.15-beta.1` tag in owncloud/android 
- [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new pre-release 2.15 beta
 - [x] [DIS] Generate final APK files from signed commit in owncloud/android and perform some basic operations
_____
### PLAY STORE:
 - [x] [DIS] Upload & publish beta release APK and changelog
_____
### F-DROID:
 - [x] [DEV] Create MR in F-Droid repo to include 2.15 beta build.
-  [x] [DEV] Merge MR into F-Droid
_____
### FINAL TASKS:
 - [x] [GIT] Merge **release/1.0.5_beta.1** branch in owncloud/android-library, into master, if needed
 - [x] [GIT] Merge **release/2.15_beta.1** branch into master in owncloud/android
 - [x] [SPREADTHEWORD] Publish central post and share new beta on social media.
_____

### PRs:
- App: https://github.com/owncloud/android/pull/2870
- Library: https://github.com/owncloud/android-library/pull/316
_____
