### ISSUE TITLE
[FEATURE REQUEST] New search bar

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2847]
Continuation of #2742

First mock up:

![newUi_toolbar](https://user-images.githubusercontent.com/47524927/79344588-5043cd80-7f30-11ea-909e-fda2c7ccb3fd.png)

ACs:

- New search bar will be automatically shown without pressing lens icon (root)
- Lens icon is gone (root)
- Searching means filtering: only in the current folder (same behaviour as current)
- ownCloud word in the hint must be brandable
- If folder is not root, same UI (lens and name of the folder)
- If folder is empty, bar is disabled (N2H)
- Extended top bar at first and then a regular bar. Extended top bar will show the oC icon on the top
- Search bar in all tabs but in uploads 
- Refresh account must be removed from three-dot-menu on the file list to account manager (check if it does not hurt)
- In pickers/share with oC view, Toolbar will show the ownCloud label, the lens, but the avatar 

![image](https://user-images.githubusercontent.com/60343863/100236634-35a5ee00-2f2e-11eb-95a8-e53eaa4d574d.png)

Figma Mockup
https://www.figma.com/file/EVQQcpITjVPiF4yT3eWKuf/Android-Proposals?node-id=0%3A1

### TASKS

- [x] Research (if needed)
- [x] Create branch new_design/search_bar
- [x] Development tasks
  - [x] Implement new toolbar design
  - [x] Connect new toolbar search view with current listeners
  - [X] Move refresh account option to account management
  - [x] Check icons color in account management view
  - [x] Show avatar in root toolbar
  - [x] Use new design in root view and old one in rest of the app
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch new_design/search_bar into master

### PR

- App
- Library (if needed)

**Comment by abelgardep** [comment]
### AC to discuss:

1. Hint root folder -> Search in `app_name` (brandable)
2. Hint other folders -> Search in `folder_name`
3. What happens with uploads toolbar (search is not available there at the moment)?
4. What happens with Av offline and share by link toolbar?

**Comment by michaelstingl** [comment]
@abelgardep examples in other apps you’d recommend to look at?

**Comment by abelgardep** [comment]
> @abelgardep examples in other apps you’d recommend to look at?

You can check some google apps: Drive, GPlay, Gmail for example.

**Comment by jesmrec** [comment]
> 1. Hint root folder -> Search in app_name (brandable)

We have to be careful with this. `Search in app_name` can lead to confusion, because you are not searching on the whole account, only filtering the current folder. 

> 3. What happens with uploads toolbar (search is not available there at the moment)? 
> 4. What happens with Av offline and shared by link toolbar?

Filtering these lists could be an option. But, i thing we should also check further options.

**Comment by CarolinaCst** [comment]
Additional changes to the proposal:
1. Add the Logo just above the Search bar 

![image](https://user-images.githubusercontent.com/60343863/96724360-0987d200-13b0-11eb-90de-c582f65caf19.png)

**Comment by CarolinaCst** [comment]
Additional suggestions

![image](https://user-images.githubusercontent.com/60343863/96734295-afd8d500-13ba-11eb-959c-2654f4b0c02a.png)

**Comment by jesmrec** [comment]
Thanks @CarolinaCst!! 

I'm not sure how it will look like with the logo above, because the size (height) of the upper toolbar will increase. In devices with large screen could be fine, but in smaller screens the action side (file list) could be reduced a lot.

If you think that showing the logo is important, how about showing it just below the searching bar, in between sorting dropdown and grid/list selector? just an idea.

**Comment by michaelstingl** [comment]
> 1. Add the Logo just above the Search bar

@CarolinaCst could you post examples from other apps?

**Comment by CarolinaCst** [comment]
My idea is to combine the designs from iOS and make a new design. 
1. The logo would be at the beginning above the new search bar and as users start scrolling down the logo will disappear and the new search bar remains.

![image](https://user-images.githubusercontent.com/60343863/96978243-6f926780-151e-11eb-8ae4-e3850e410f5e.png)

![image](https://user-images.githubusercontent.com/60343863/96978294-7c16c000-151e-11eb-8a4c-4a3bf37be0b6.png)

**Comment by CarolinaCst** [comment]
I) What happened to the Toolbars: Uploads, Offline and Links?

- Drive stick to a visible Search bar in all the sections of the App.
![image](https://user-images.githubusercontent.com/60343863/97208894-f152f100-17bb-11eb-9307-5b9922ee3478.png)
![image](https://user-images.githubusercontent.com/60343863/97209049-22332600-17bc-11eb-81cb-fd50252bf8ca.png)
![image](https://user-images.githubusercontent.com/60343863/97209123-3f67f480-17bc-11eb-9cf5-08dd4bb118c5.png)

**Comment by jesmrec** [comment]
My thoughts:

- Top bar: showing the extended bar and then the regular bar when scrolling down likes me the most. Google has different capacities, so it's a good reference but use cases are not all the same. 

- Bottom bar: here we have different cases (@abelgardep correct me if i'm wrong):
    - Tabs "Files", "Av offline" and "Links": These tabs show the list of files, complete or filtered. The search bar could be another filter in case of a long list. This is OK
    - Tab "Uploads": this is different because it does not work with the list of files. Here, we could remove it (what should be place there instead?), or give it a different meaning (search in the list of uploads?but  it is limited to only 30 items IIRC). 

- Search by other criteria: Actually "searching" means "filtering" (only works in the current folder). Ftm, i think we will use the name to filter, other criteria depend on how capable is/will be the searching API that is not integrated yet. But is good to have the example as reference

- Recent searches: no strong opinion here, all ideas look good. 

Thanks for the awesome ideas @CarolinaCst !

**Comment by CarolinaCst** [comment]
After the Meeting of 03.11.2020, here are the following agreements:

- Search bar
![image](https://user-images.githubusercontent.com/60343863/98015045-a9a41900-1dfc-11eb-98d3-42da999d3085.png)

- Figma Mockup
https://www.figma.com/file/EVQQcpITjVPiF4yT3eWKuf/Android-Proposals?node-id=0%3A1

**Comment by jesmrec** [comment]
copying new ACs, mockups etc... to the first message on the top

**Comment by jesmrec** [comment]
About the uploads view

- We have to move all the stuff in the three-dot-menu somewhere to set there the avatar
- Search does not appear. A Textview with the title replaces the search bar

**Comment by jesmrec** [comment]
Some agreements after today's meeting:

- Uploads: 
  - Show in the place of the Sort bar, a menu `Options` with all the actions to do: `Clear X` and `Refresh`. Icons with the options: trashbin for `Clear` options and another one for `Retry`

  - Let the `Upload` label as is. Replace the three-dot-menu with the avatar. 

- Avatar at the right of the `Search`. It leads to the `Manage accounts` view
- Avatar only in the root folder. If folder is not root, back arrow + label with the name of the folder + Lens to search

- Refresh account must be removed from three-dot.menu on the file list. Different options:

  1) Move it to the manage account. Pending to check how it works from such view.
  2) Remove it temporally. Make it automatically in the future -> requires additional development in all stages

- In pickers view, Toolbar will show the `ownCloud` label, the lens, but the avatar (more ideas welcome)

- In "Share with oC" view, Toolbar will show the `ownCloud` label, but the avatar (more ideas welcome)

**Comment by CarolinaCst** [comment]
- Figma Mockups link:

https://www.figma.com/file/FGfiuKPrlLYzIrFL1mXsh9/Android-2?node-id=0%3A1

**Comment by jesmrec** [comment]
1. Search bar is OK from my side

2. Uploads/Options. I miss several options there, but i guess this is only a listing detail. In the Figma link, you set a chevron to show a dropdown list with different clearing options. I'd not go for that approach because the number of options to show is not too high to hide them directly. Of course, we can iterate and discuss to get better UX results.

3. Manage accounts OK from my side. Pending to know how feasible is syncing the account from that view.

**Comment by CarolinaCst** [comment]
Talking with @abelgardep  we have made some changes as followed:

1. Search bar: hamburger menu and avatar will be inside as in the example from Drive.
![image](https://user-images.githubusercontent.com/60343863/100236634-35a5ee00-2f2e-11eb-95a8-e53eaa4d574d.png)

2. No logo: for small devices including the ownCloud logo will be too much space so the new option is to remove it completely.
![image](https://user-images.githubusercontent.com/60343863/100237406-30956e80-2f2f-11eb-950a-bc629f7be01f.png)

3. New Icon: new icon for Clear failed
![image](https://user-images.githubusercontent.com/60343863/100237576-68041b00-2f2f-11eb-8430-7c5f29114342.png)

**Comment by jesmrec** [comment]
i like all. Awesome!

**Comment by CarolinaCst** [comment]
3. Uploads changes:

- On the "Failed" section users now have the option to "Clear" or "Retry" all the data and 
still have the possibility to delete every single file.  

- On "Uploaded" users can clear all the files

![image](https://user-images.githubusercontent.com/60343863/101164831-ecdcec00-3635-11eb-95f7-3caeded0e11c.png)

**Comment by CarolinaCst** [comment]
### 3. New Uploads improvements

-  New CTA buttons
-  Figma link:
    https://www.figma.com/file/FGfiuKPrlLYzIrFL1mXsh9/Android-2?node-id=0%3A1

![image](https://user-images.githubusercontent.com/60343863/102919471-35473700-4489-11eb-88bb-8c04f3e14bbb.png)

**Comment by abelgardep** [comment]
Current status, two options for the moment.

| White background | Keep background color |
|---------|---------|
| ![Screenshot_1611917501](https://user-images.githubusercontent.com/47524927/106741465-055c8900-661c-11eb-9930-aee4c5efb1a5.png) | ![Screenshot_1611917621](https://user-images.githubusercontent.com/47524927/106741448-fece1180-661b-11eb-9e8d-9aeba0d98771.png) |

**Comment by michaelstingl** [comment]
> BTW, I need to add a lens icon.

👍 

@tbsbdr What is your preference? Left or right?

**Comment by jesmrec** [comment]
Right one seems to be more consistent with the current theme. White gap inside the toolbar is not nice, IMHO.

**Comment by michaelstingl** [comment]
> Right one seems to be more consistent with the current theme.

Yes, right one is more appealing. 👍 

Proposal from @diocas was, to make the input field more visible by highlighting it by ~20% or so. My proposal would be, to switch background to white when in search mode, but no idea if this is too fancy…

**Comment by tbsbdr** [comment]
Option 1 (preferred)
- **right one** + icon does the job and is nice! 👍

Option 2
> switch background to white when in search mode (@michaelstingl )
e.g. box does it kinda this way - to me this appears to be visually disruptive, therefore wouldn't switch to white when in search mode. ❌

Option 3 (n2h)
> highlighting it by ~20% 
onedrive, dropbox and google drive do it this way. n2h imho. only do it if you have some time to spare 🌈

**Comment by michaelstingl** [comment]
@tbsbdr thanks for the feedback 👍  Excited to see it in action in the next reviews…
