### ISSUE TITLE
[New Arch] Get Quota

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2850]
Related with #2849, there are some missing operations in new architecture.
First of them is Get Quota Operation.

### TASKS

- [x] Research (if needed)
- [x] Create branch new_arch/get_quota
- [x] Development tasks
  - [x] Create GetQuotaForAccountUseCase
  - [x] Add getQuotaForAccount functions to UserRepository, UserDatasources and UserService
  - [x] Migrate RemoteOperation to kotlin
  - [x] Call GetQuotaForAccountUseCase instead of GetRemoteUserQuotaOperation
  - [x] Add unit tests
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch new_arch/get_quota into master

### PR

- App #2880
- Library (if needed) https://github.com/owncloud/android-library/pull/320
