### ISSUE TITLE
[New Arch] Get Avatar

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2851]
Related with #2849, there are some missing operations in new architecture.
First is Get Quota Operation(#2850), next is this one(Get Avatar).

### TASKS

- [x] Research (if needed)
- [x] Create branch new_arch/avatar
- [x] Development tasks
  - [x] Create GetAvatarForAccountUseCase
  - [x] Add getAvatarForAccount functions to UserRepository, UserDatasources and UserService
  - [x] Migrate RemoteOperation to kotlin
  - [x] Perform cleanup
  - [x] Call GetAvatarForAccountUseCase instead of GetRemoteUserAvatarOperation
  - [x] Remove GetUserProfileOperation if possible. Call usecases instead. (Intermediate step: Created a SyncProfileOperation)
  - [x] Add unit tests
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch new_arch/avatar into master

### PR

- App https://github.com/owncloud/android/pull/2893
- Library (if needed) https://github.com/owncloud/android-library/pull/324

**Comment by abelgardep** [comment]
We are fetching Avatar each time we perform a refresh root folder operation.

Depending on user's avatar, it would be more or less data transferred. Let's set 29kb of image for example. That's like 29kb each time we refresh root folder.

How important is to keep avatar updated on each refresh?

**Comment by jesmrec** [comment]
Not much. For me, it'd be enough to check every time you enter the account.

**Comment by abelgardep** [comment]
BTW on each root folder refresh, oC performs next operations:
Is it needed a full profile sync on every root folder refresh? It take time and data

### Get User info(GetRemoteUserInfoOperation)
- Endpoint: /ocs/v2.php/cloud/user?format=json
- Size: ± 150B
### Get Avatar (GetRemoteUserAvatarOperation)
- Endpoint: /index.php/avatar/demo/448
- Size: Depending on avatar ± 20kb
### Get Quota (GetRemoteUserQuotaOperation)
- Endpoint: /remote.php/dav/files/demo/ (Same as refresh folder but with exclusive properties)
  - "quota-available-bytes"
  - "quota-used-bytes"
- Size: ±350B

### Refresh folder(ReadRemoteFolderOperation)
- Endpoint: /remote.php/dav/files/demo/ (Fetch all properties)
- Size: depending on files. Let's set 6Kb

### Fetch shares (GetRemoteSharesForFileOperation)
- Endpoint: /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2F&reshares=true&subfiles=true
- Size: depending on shares. Let's set 5Kb

### Fetch Capabilities (GetRemoteCapabilitiesOperation)
- Endpoint: /ocs/v2.php/cloud/capabilities?format=json
- Size: ± 1.5Kb

Info retrieved using AS profiler:
![refresh_folder_operation](https://user-images.githubusercontent.com/47524927/82558299-a8906f80-9b6d-11ea-8d9a-a5d7613e9252.png)
