### ISSUE TITLE
[FEATURE REQUEST] Add close button to "Edit permissions" view

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2852]
This is the current view for changing share permissions:

![Screenshot 2020-04-15 at 18 37 20](https://user-images.githubusercontent.com/14894746/79363562-580f6c00-7f48-11ea-9a6b-fa45fbad9ae0.png)

`Close` button is the best option in terms of material design

### TASKS

- [X] Research (if needed)
- [X] Create branch add_close_private_share_edit
- [X] Development tasks
  - [X] Add new button to edit_share_layout
  - [X] Add listener and dismiss dialog when clicked
  - [X] Add a test for that
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch add_close_private_share_edit into master

### PR

- App https://github.com/owncloud/android/pull/3018
- Library (if needed)
