### ISSUE TITLE
[New Arch] UploadListFragment isolation

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2858]
From a development point of view, it would be great to show a UploadListFragment within any activity. For example, with the current bottom navigation bar we need to create a new activity just to show the fragment. It would be great to simply replace one fragment with another.

At the moment, there are so many dependencies to open UploadListFragment:
- UploadListFragment extends ExpandableListFragment which extends ExtendedListFragment.

- UploadListFragment is created inside UploadListActivity which extends FileActivity which extends DrawerActivity

### TASKS

- [x] Research (if needed)
- [x] Create branch new_arch/uploads_screen
- [x] Development tasks
  - [x] Create a new fragment in kotlin with a recycler view
  - [x] Create a new adapter for the recycler view
  - [x] Use the ViewModel to retrieve the needed data from the usecases (all stored uploads) and store them in a livedata so the fragment can observe the changes
  - [x] Observe the livedata and update the adapter with the transfers
  - [x] At this point we should see something in the UI
  - [x] Update the domain and data layers to retrieve the stored uploads as live data so we can observe them in real time
  - [x] Create a new viewtype with its viewholder to show the headers (for example: `In Progress`, `n items in progress`, Cancel all)
  - [x] Modify the adapter to show the uploads by TransferStatus
  - [x] Show options Retry, Clear, Cancel depending on the transfer status group
  - [x] Implement all the calls to retry, cancel, etc..
  - [x] For the transfers in progress, retrieve the progress from Work manager and show a progress bar with its percentage
  - [x] (N2H) Add a DiffUtil
  - [x] (N2H) Generate thumbnails with Glide
- [x] Code review and apply changes requested
- [x] Merge branch new_arch/uploads_screen into new_arch/synchronization
