### ISSUE TITLE
[New Arch] Create folder operation

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2861]
Synchronization epic: https://github.com/owncloud/android/issues/2818

AC:

- Folder created in the current path
- Name must not be already used
- Characters "/" and "\\" are forbidden
- Other errors:
   - No connectivity
   - Server not reached
   - Maintenance mode...

### TASKS

- [x] Research (if needed)
- [x] Create branch new_sync/create_folder
- [x] Development tasks
  - [x] Create new usecase -> CreateFolderUseCase
  - [x] Add createFolder to repository
  - [x] Add createFolder to RemoteDataSource (Call CheckRemotePath before CreateRemoteFolderOperation to check if folder already exists?)
  - [x] Migrate CreateRemoteFolderOperation to kotlin
  - [x] Add operation to FileService
  - [x] Introduce folder into new database
  - [ ] Create local folder -> Not needed for the moment
  - [ ] Update DocumentsProvider -> Not done yet.
  - [ ] Error handling -> Needs UI issue to handle viewmodel
  - [x] Unit tests
- [x] Code review and apply changes requested
- [X] Design test plan -> moved to global EPIC
- [X] QA -> moved to global EPIC
- [x] Merge branch new_sync/create_folder into new_arch/sync

### PR

- App: https://github.com/owncloud/android/pull/2923
- Library: https://github.com/owncloud/android-library/pull/336
