### ISSUE TITLE
[New Arch] Rename file/folder Operation 

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2863]
Synchronization epic: https://github.com/owncloud/android/issues/2818

AC:

- Every item can be renamed
- Name must not be already used
- Characters "/" and "\\" are forbidden
- Other errors:
   - No connectivity
   - Server not reached
   - Maintenance mode...

### TASKS

- [x] Research (if needed)
- [x] Create branch new_sync/rename
- [x] Development tasks
  - [x] Create new usecase -> RenameFileUseCase
  - [x] Add renameFile to repository
  - [x] Add renameFile to RemoteDataSource (Call CheckRemotePath before RenameRemoteFileOperation to check if folder already exists?)
  - [x] Migrate RenameRemoteFileOperation to kotlin
  - [x] Migrate Rename dialog to kotlin
  - [x] Inject shared FilesViewModel into renamedialogfragment
  - [x] Call rename usecase inside FilesViewModel
  - [x] Observe rename result in FileDisplayActivity
  - [x] Update new database with an updated name and its descendants
  - [x] Update local file with an updated name and its descendants
  - [x] Update DocumentsProvider
  - [x] Error handling
  - [x] Unit tests
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [x] Merge branch new_sync/rename into new_arch/sync

### PR

- App https://github.com/owncloud/android/pull/3231
- Library (if needed) https://github.com/owncloud/android-library/pull/399

**Comment by abelgardep** [comment]
Blocked till https://github.com/owncloud/android/issues/2865 is merged because we need to perform a MOVE operation to rename local files and save them in the database.

**Comment by abelgardep** [comment]
Will be tested within the synchronization epic.
