### ISSUE TITLE
[New Arch] Remove file/folder operation

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2864]
Synchronization epic: https://github.com/owncloud/android/issues/2818

AC:

- Support removing the content in local (if downloaded), remote or both

### TASKS

- [x] Research (if needed)
- [x] Create branch new_sync/remove_file
- [ ] Development tasks
  - [x] Create new usecase -> RemoveFileUseCase
  - [x] Add removeFile to repository
  - [x] Implement removeFile
  - [x] Add removeFile to RemoteDataSource (Call CheckRemotePath before RemoveRemoteFileOperation to check if folder already exists?)
  - [x] Migrate RemoveRemoteFileOperation to kotlin
  - [x] Migrate RemoveRemoteChunksFolderOperation to kotlin
  - [x] Add removeFile to current FileService
  - [x] Create a new ChunkService to handle everything related to chunks
  - [x] Remove local file
  - [x] Remove file from database
  - [x] Update DocumentsProvider
  - [ ] Error handling
  - [x] Unit tests
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [x] Merge branch new_sync/remove_file into new_arch/sync

### PR

- App https://github.com/owncloud/android/pull/3214
- Library (if needed) https://github.com/owncloud/android-library/pull/394
