### ISSUE TITLE
[New Arch] Move file/folder Operation

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2865]
Synchronization epic: https://github.com/owncloud/android/issues/2818

### TASKS

- [x] Research (if needed)
- [x] Create branch new_sync/move
- [x] Development tasks
  - [x] Create new usecase -> MoveFileUseCase
  - [x] Add moveFile to repository
  - [x] Add moveFile to RemoteDataSource (Call CheckRemotePath before MoveRemoteFileOperation to check if folder already exists?)
  - [x] Migrate MoveRemoteFileOperation to kotlin
  - [x] Migrate MoveRemoteChunkFileOperation to kotlin
  - [x] Add move to FileService
  - [x] Add move to ChunkService
  - [x] Update database
  - [x] Move local files/folders
  - [x] Update DocumentsProvider
  - [x] Error handling
  - [x] Unit tests
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [x] Merge branch new_sync/move into new_arch/sync

### PR

- App https://github.com/owncloud/android/pull/3232
- Library (if needed) https://github.com/owncloud/android-library/pull/400

**Comment by abelgardep** [comment]
Pending:
- Check behaviour when moving Av. Offline or moving to a folder marked as Av. Offline
- Check performance when moving A LOT OF files

**Comment by abelgardep** [comment]
Will be tested within the synchronization epic.
