### ISSUE TITLE
[New Arch] Copy file/folder operation

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2866]
Synchronization epic: https://github.com/owncloud/android/issues/2818

AC:

- Copy remote in server.
- Local: check if file is downloaded to move to new location. Check if new version is available in case of file already downloaded.
- In case of copy folder: check if items inside are downloaded, if they have newer versions, update.
- Check if the copied file is downloaded, in case the source one is downloaded.
### QA Checks
https://github.com/owncloud/QA/blob/master/Mobile/Android/Sync/Copy.md

### TASKS

- [x] Research (if needed)
- [x] Create branch new_sync/copy
- [ ] Development tasks
  - [x] Create new usecase -> CopyFileUseCase
  - [x] Add copyFile to repository
  - [x] Add copyFile to RemoteDataSource (Call CheckRemotePath before CopyRemoteFileOperation to check if folder already exists?)
  - [x] Migrate CopyRemoteFileOperation to kotlin
  - [x] Update database
  - [ ] Copy local files/folders
  - [x] Update DocumentsProvider
  - [x] Error handling
  - [x] Unit tests
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [x] Merge branch new_sync/copy into new_arch/sync

### PR

- App https://github.com/owncloud/android/pull/3253
- Library (if needed) https://github.com/owncloud/android-library/pull/406

**Comment by abelgardep** [comment]
Related to AC:
> Copy remote in server.
> Local: check if file is downloaded to move to new location. Check if new version is available in case of file already downloaded.
In case of copy folder: check if items inside are downloaded, if they have newer versions, update.
Check if the copied file is downloaded, in case the source one is downloaded.

I think that it could be enough to copy files remotely and to update the database accordingly. We could avoid some problems that way instead of copying every downloaded file.

**Comment by abelgardep** [comment]
Will be tested within synchronization epic
