### ISSUE TITLE
[New arch] OCFileListFragment isolation

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2869]
Currently, there are several fragments to list files, it would be great to unify them and get rid of activities dependencies.

(Good to have) Adapter refactors, use a recycler view to show the list of files, use diff util to increase performance, use already created FilesViewModel, get files from DB as Flow and Pagination for better performance.

### Tasks 
- [X] Create branch new_arch/file_list_isolation
- [ ] Development tasks
  - [X] New fragment MainFileListFragment #3451 
  - [X] New ViewModel (?) #3451 
  - [X] Show a simple list of files (GetFolderContentUseCase it will be updated to LiveData-Flow) #3451 #3461 
  - [x] Footer with number of files and folders https://github.com/owncloud/android/pull/3457
  - [x] Empty files view (Could be modified -> https://github.com/owncloud/android/issues/3026) https://github.com/owncloud/android/pull/3460
  - [x] Swipe to refresh (call RefreshFolderFromServerAsyncUseCase) #3469 
  - [x] Different options: All files, Shared by link and Av Offline (FileListOption -> Check if we can improve it) ( GetFilesSharedByLinkUseCase) (AvOffline use case does not exist yet) -> https://github.com/owncloud/android/pull/3471
  - [x] Bottom navigation bar -> https://github.com/owncloud/android/pull/3476
  - [x] Grid view mode #3493 
  - [x] Floating action button handling (Only shown in All files option) -> https://github.com/owncloud/android/pull/3492
  - [x] Search files within the list (Check if a new use case is needed for this. It is searched locally and only for this folder) -> https://github.com/owncloud/android/pull/3494
  - [x] Sort by name, size, and date (Check if a new use case is needed for this) #3478
  - [x] Consider adding diff util to improve performance
  - [x] Display images correctly in the list #3495 
  - [ ] Multiselection
    - [x] Change toolbar
      - [x] Control items selected #3508 
      - [x] Control checkbox -> https://github.com/owncloud/android/pull/3545
      - [x] Control Drawer #3511 
      - [x] Refresh option -> https://github.com/owncloud/android/pull/3545
      - [x] Share option -> https://github.com/owncloud/android/pull/3545
    - [ ] Show Menu Dialog (Keep in mind that we may change the UI -> https://github.com/owncloud/android/issues/2885)
      - [x] Select all -> https://github.com/owncloud/android/pull/3545
      - [x] Select inverse -> https://github.com/owncloud/android/pull/3545
      - [ ] Set as Av. Offline
      - [x] Move -> https://github.com/owncloud/android/pull/3545
      - [x] Copy -> https://github.com/owncloud/android/pull/3545
      - [x] Rename -> https://github.com/owncloud/android/pull/3545
      - [x] Remove -> https://github.com/owncloud/android/pull/3545
    - [x] Hide FAB #3508 
    - [x] Manage actionMode after an operation is executed (in order to hide it)
   - [ ] Testing

Check if it would be feasible to use this fragment to show the file list in ReceiveExternalFilesActivity

- [x] Retrieve files in a flow or live data to get auto-updates (new usecase, add it to repository, dao, local datasource)
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### Bugs to fix:
- [x] Control popBackStack() when the user navigates inside the folder. https://github.com/owncloud/android/pull/3503
- [x] Avoid crash when the user uses the application in portrait or landscape mode and performs a search. #3501 
- [x] Avoid crash when the application is installed from scratch with the new architecture. #3504 
- [x] Display the correct list when the user navigates through the bottom menu. #3505 
- [x] Control filtering on all screens. #3502 
- [x] When a file or folder is shared, icon is not updated to show link
- [X] Manage click on files (not folders) to download them #3555 
- [x] All folders are empty, even if they contain data.
- [x] Change toolbar name
- [x] When user rotates the device, the folder root is reset
- [x] Back arrow button does not work correctly in the toolbar
- [x] Multiselection toolbar doesn't show correct icons
- [x] Footer is gone

**Comment by fesave** [comment]
https://user-images.githubusercontent.com/49989790/145961343-402b01fa-b94f-48f3-8093-d543926ea268.mp4

We want to propose a change of functionality taking advantage of the task of re-architecting the application. As you can see in the video, currently the type of view (List or Grid) is configured by folder and not globally. We believe that if it were configured globally it would be easier to use for the user, because right now he must go folder by folder configuring his desired view type. We have seen that other apps work this way and we think it is simpler and would help us to simplify the code. What do you think?

cc @michaelstingl @tbsbdr @hosy @jesmrec

**Comment by tbsbdr** [comment]
afaik ux-wise there is no "standard" expected behaviour if the view-setting should be set "per single folder" or "globally". both approaches are legit.
I would be fine with **setting it globally** and would then also implement it this way for the web ui.

**Comment by abelgardep** [comment]
### Known issues (8b38cb36b3295e8a19ebe9f3a3e6123209af814c)
- Duplicated items after uploads. Check if it is a new problem or a problem that will be fixed within the uploads issue #3004 
- Av. Offline and shared-by-link shortcuts don't work properly. To be done within #3246
