### ISSUE TITLE
[New arch] Fetch list of files of an specific path

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2873]
Synchronization epic: https://github.com/owncloud/android/issues/2818

- Once a folder is browsed, list of files is fetched. Important data:

  - File name
  - Extension (to set a thumbnail)
  - Size 
  - Date
  - Permissions?
  - Private/Universal link (if included in the response)
  - ...

### Improvement
- Remove individual Get Quota operation and use the quota retrieved in root propfind instead

### TASKS

- [x] Research (if needed)
- [x] Create branch new_arch/fetch_list_files
- [x] Development tasks
  - [x] Create new domain model OCFile
  - [x] Add refresh files usecase
  - [x] Migrate RemoteOperation to kotlin
  - [x] Add function to FilesRepository
  - [x] Implement FilesRemoteDatasource
  - [x] Implement FilesLocalDatasource
  - [x] Create OCFileEntity and Dao
  - [x] Add tests on domain module
  - [x] Add tests on data module [Not completed because it requires changes]
  - [x] Handle basic conflicts
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [x] Merge branch new_arch/fetch_list_files into master

### PR

- App: https://github.com/owncloud/android/pull/2918
- Library (if needed): https://github.com/owncloud/android-library/pull/335

**Comment by michaelstingl** [comment]
> * Extension (to set a thumbnail)

New iOS app just asks for thumbnail for EVERY file type… (plenty of 404)

This might help in the future: https://github.com/owncloud/core/issues/31267

I'd avoid hardcoded list of file types that support preview generation.

**Comment by jesmrec** [comment]
We will not forget it... right now, only asking for picture thumbnails.
