### ISSUE TITLE
[FEATURE REQUEST] Scoped Storage

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2877]
Place to discussion about the necessary feature in the close future 

Documentation: 

https://developer.android.com/preview/privacy/storage?hl=en
https://developer.android.com/training/data-storage

Scoped storage will provide a way to enclose user data related to an app. 

Research: https://github.com/owncloud/android/issues/2894

### TASKS

- [x] Research (if needed) -> SPIKE https://github.com/owncloud/android/issues/2894
- [x] Create branch feature/scoped_storage
- [ ] Development tasks
  - [ ] Recheck of the spike
  - [x] Update target to 30 (https://github.com/owncloud/android/issues/2920)
  - [x] Remove flag to opt-out the scoped storage
  - [x] Select a new location inside the sandbox
  - [x] Files downloaded stored in the scoped storage.
  - [x] Taking a photo within ownCloud is uploaded properly
  - [x] 'Open with' have enough permissions to open a file with other apps.
  - [x] 'Share with' have enough permissions to share a file with other apps.
  - [x] Camera uploads have enough permissions to access the camera folder and get pictures from there.
  - [x] Sharing files with ownCloud works as expected.
  - [x] `Chunk uploads` works as expected
  - [x] 'Upload files from local storage' works as expected
  - [x] Recheck permissions to access folders in setup, like camera folder in auto uploads... (check if native picker helps)
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/scoped_storage into master

### PR

- App #3269

This is part of Android 10 target: https://github.com/owncloud/android/issues/2576

**Comment by jesmrec** [comment]
Needed: upload targeting to API 29. Should we do in advance and test separately? or... is it not a problem to do in the same PR/PRs as scoped storage? @abelgardep @davigonz

**Comment by abelgardep** [comment]
> Needed: upload targeting to API 29. Should we do in advance and test separately? or... is it not a problem to do in the same PR/PRs as scoped storage? @abelgardep @davigonz

We could do it separately if we add the next attribute: [requestLegacyExternalStorage](https://developer.android.com/preview/privacy/storage#scoped-storage).

**Comment by jesmrec** [comment]
Some regards with this, after discussing (from https://github.com/owncloud/android/issues/2872#issuecomment-814848977 by @abelgardep ). 

The initial question is: how must be stored a file in the device after downloading??. There will be three kinds of download (by @abelgardep)

- Previews: They could be downloaded to the app-specific storage and maybe to the cached one. This way we could free some space when needed

- Av. Offline: They could be downloaded to the app-specific storage and it may have sense to store them in the persisted one

- Select and download: This behavior could be changed and make it download to the downloads folder if the user considers it important to persist it.

What i think about it:

- Previews: i like the idea they can be removed from cache, manually, or automatically (feasible as future improvement? iOS app implements this). That means, file is downloaded only to be previewed 

- Av. Offline: They must be persisted in scoped storage.

- Select and download: Would it make sense to get rid of this option? i mean, with Previews you can open and check a file by clicking on it. If this file is important for you, you will make it av. offline and will be always stored and synced in your device. Downloading a file and keep it in the device in a non-synced way does not offer advantages (doesn't it?). Indeed, we have to take care of the space limit. What do you think??

As @theScrabi , the "Download" option should have a different meaning (saving the file somewhere in the device storage, out of the scoped storage) and should have renamed to "Export" or something similar when it is implemented.

This discussion has some product and security concerns, that must be agreed before implementing.

CC @michaelstingl

**Comment by michaelstingl** [comment]
> - Select and download: Would it make sense to get rid of this option? i mean, with Previews you can open and check a file by clicking on it. If this file is important for you, you will make it av. offline and will be always stored and synced in your device. Downloading a file and keep it in the device in a non-synced way does not offer advantages (doesn't it?). Indeed, we have to take care of the space limit. What do you think??

I think export and safe somewhere on the storage is already possible with native Android feature. Then "Select and download" is no longer needed. If users really need it, they can set ab. offline.

**Comment by abelgardep** [comment]
We could check [this repo](https://github.com/google/modernstorage) when we decide to work on Scoped Storage. It could have interesting information.

**Comment by abelgardep** [comment]
### Migration from current storage to scoped storage.
For a common scenario: App installed and files are stored in external storage in the device.

**Case 1: Device API<29**
A device whose current API is lower than 29, could access the external storage after migrating to scoped storage. They keep read/write external storage permission. New files will be downloaded to scoped storage. Smooth transition.

![Screenshot 2021-07-21 at 09 52 56](https://user-images.githubusercontent.com/47524927/126452681-0c65e3f5-56aa-4047-a1e8-7a7da664653d.png)

**Case 2: Device API>=29**
A device whose current API is 29 or higher, will lose access to current downloaded files after moving to scoped storage.
![Screenshot 2021-07-21 at 10 09 55](https://user-images.githubusercontent.com/47524927/126454606-918b74e4-891a-4ec7-b187-df82d31806d6.png)
 It means that we will need to reset the field where the downloaded path is stored in the database. This way, files won't appear as downloaded and, sadly, they will need to be downloaded again. Additionally, we will need to ask the user for the removal of old files in the external storage. 
 
### Fresh install
Files are stored in scoped storage location as expected. Nothing to do here.

**Comment by abelgardep** [comment]
I think that we should resume the work in https://github.com/owncloud/android/issues/125 before moving to ScopedStorage.

Scoped storage is limited and we should free space after each account deletion.

As https://github.com/owncloud/android/issues/125#issuecomment-188351540 states, there are 2 different cases:
- Removing the account from the app -> Probably the most common case. Should not be so complex to include. Would be enough for a first iteration.
- Removing the account from Device settings -> Not so common and harder to manage.
