### ISSUE TITLE
[RELEASE] 2.15-beta2

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2879]
### TASKS:
 - [x] [COORDINATION] Get in touch with community/marketing team to publish a blog post, several days before releasing.
 - [x] [GIT] Create **release/1.0.5_beta.2** branch in owncloud/android-library from master
         - Update version code and name in build.gradle.
 - [x] [GIT] Create **release/2.15_beta.2** branch from master and:  
    - [x] Update version code and name in build.gradle.
    - [x] Update changelog file (< 500 chars)
 - [x] [QA] Perform some tests @jesmrec
 - [x] [GIT] Create and sign tag `1.0.5-beta.2` in HEAD commit of **release/1.0.5_beta.2** branch, in owncloud/android-library
 - [x] [GIT] Create and sign tag `oc-android-2.15-beta.2` in HEAD commit of **release/2.15_beta.2** branch, in owncloud/android
 - [x] [DIS] Generate test APKs files from `oc-android-2.15-beta.2` tag in owncloud/android 
- [x] [DOC] Include new changelog on Releases section of github android repo by drafting the new pre-release 2.15 beta
 - [x] [DIS] Generate final APK files from signed commit in owncloud/android and perform some basic operations
_____
### PLAY STORE:
 - [x] [DIS] Upload & publish beta release APK and changelog
_____
### F-DROID:
 - [x] [DEV] Create MR in F-Droid repo to include 2.15 beta build.
-  [x] [DEV] Merge MR into F-Droid
_____
### FINAL TASKS:
 - [x] [GIT] Merge **release/1.0.5_beta.2** branch in owncloud/android-library, into master, if needed
 - [x] [GIT] Merge **release/2.15_beta.2** branch into master in owncloud/android
 - [x] [SPREADTHEWORD] Publish central post and share new beta on social media.
_____

### PRs:
App: https://github.com/owncloud/android/pull/2881
Library: https://github.com/owncloud/android-library/pull/321
_____

### BUGS & IMPROVEMENTS:

- [x] Problem with basic auth: https://github.com/owncloud/android/issues/2878 [Ready to test @jesmrec]
- [x] Problem with trailing slash https://github.com/owncloud/android/issues/2813#issuecomment-624699764 [Ready to test @jesmrec]
- [x] Redirection stuff (customers) [moved to 2.16]
- [x] Chunking adaption to oCIS (https://github.com/owncloud/product/issues/39) [Ready to test @jesmrec]

**Comment by jesmrec** [comment]
QA:

**Installing beta2 from scratch:**

- [ ] Check trailing slash issue https://github.com/owncloud/android/issues/2813#issuecomment-624699764
- [ ] Add server with LDAP, and id = userid
- [ ] Add server with LDAP, and id != userid (UID, f. ex)
- [ ] Add OAuth2 server and let the token expire and renew
- [ ] Add oCIS/OIDC server and let the token expire and renew
- [ ] Check uploads (To define) 

**Upgrade from beta 1**

- [ ] Correct wizard slide

**Upgrade from 2.14.2**

- [ ] Check trailing slash issue https://github.com/owncloud/android/issues/2813#issuecomment-624699764
- [ ] In 2.14.2, add server with LDAP, and id = userid and then, upgrade to beta2
- [ ] In 2.14.2, add server with LDAP, and id != userid (UID, f. ex) and then, upgrade to beta2
- [ ] In 2.14.2, add OAuth2 server and let the token expire and renew and then, upgrade to beta2
- [ ] Check uploads (To define) 

**Common stuff**

- [ ] Smoke test
