### ISSUE TITLE
Replace the ownCloud file picker with the Android one

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2899]
As a continuation of #2436, where we replaced the ownCloud file picker with the Android one when uploading files, oC app should replace completely the file picker with the android one.

This oC file picker is still used to select the camera folder available for Camera Uploads in Preferences. Steps:
1- Open settings
2- Enable picture uploads
3- Choose camera folder
| oC Custom file picker | Storage Access Framework |
| ------------- | ------------- |
| ![custom-file-picker](https://user-images.githubusercontent.com/47524927/84506126-29e7a780-acbf-11ea-8d77-21938a096e74.jpg) | ![saf](https://user-images.githubusercontent.com/47524927/84506303-7632e780-acbf-11ea-95c6-27d134358add.jpg)| 

With this replacement, we will perform a big cleanup and it will be ready for Scoped Storage.
### TASKS

- [x] Research (if needed)
- [x] Create branch new_arch/camera_uploads
- [x] Development tasks
  - [x] Use SAF file picker
  - [x] decide weather to use SAF for accessing photos
  - [x] if yes: move accessing local storage to SAF.
  - [x] Create a new model in domain module for camera uploads config
  - [x] Add a new worker to perform camera uploads
  - [x] Add a new usecase to retrieve camera uploads configuration
  - [x] Add a new worker to perform single uploads with a content uri
  - [x] Add a constraint to perform uploads only when wifi is enabled
  - [x] Remove local file if behavior for camera uploads is move
  - [x] Show the uploads in the uploads list view
  - [x] Cancel uploads when removing the account
  - [x] Cancel uploads individually
  - [x] Notifications: Syncing camera uploads and uploading file individually (Check if needed)
  - [x] Improve error handling: Add new errors cases
  - [x] Check problems when upgrading: Previous uri is not valid
  - [x] Clean legacy code
  - [x] Fix unit tests
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch new_arch/camera_uploads into master

### PR

- App #3293
- Library (if needed) https://github.com/owncloud/android-library/pull/414

### QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.18.1/Camera%20uploads%20%2B%20picker.md

Bugs / improvements

**Comment by jesmrec** [comment]
Add another case: share with ownCloud

Case 1:

1. Open "Photos". 
2. Select one or more pictures.
3. Select "Share with"  -> ownCloud

Case 2:

1. Open browser, any web
2. Select some text
3. Select "Share" -> ownCloud

**Comment by abelgardep** [comment]
> Add another case: share with ownCloud
> 
> Case 1:
> 
>     1. Open "Photos".
> 
>     2. Select one or more pictures.
> 
>     3. Select "Share with"  -> ownCloud
> 
> 
> Case 2:
> 
>     1. Open browser, any web
> 
>     2. Select some text
> 
>     3. Select "Share" -> ownCloud

That's not the same case. Those cases uses the oC file picker to select where you want to store those files, but in the oC hierarchy. This issue is to select which folder you want to allow autouploads and uses system hierarchy, so we can use android one.

**Comment by jesmrec** [comment]
ok you meant the folder from the camera app (external from oC). I mistaked it with the camera upload folder

**Comment by theScrabi** [comment]
It is possible to use this file picker however it will return SAF URIs, which means we should then move the storage operations over to SAF as well.

**Comment by theScrabi** [comment]
It was proposed to make this work the same way as we made single file upload work. What we do there is copy the file from a `ContentProvider` to a `tmp` directory. This file in `tmp` is then uploaded:
in some way we are already using ContentResolvers here. Which is the right way to go:


https://github.com/owncloud/android/blob/e1c7b7028d0e6adedc771f420aef0fbf9c75af58/owncloudApp/src/main/java/com/owncloud/android/ui/asynctasks/CopyAndUploadContentUrisTask.java#L145-146

If we do it the same way for image/video upload however this would required to copy every image/video once before uploading. I'm concerned about the performance. I'd propose moving the dialog once we move to Scoped storrage.

**Comment by abelgardep** [comment]
We'll need to replace the ownCloud file picker with the SAF one in order to make the camera uploads work with [ScopedStorage](#2877)

**Comment by abelgardep** [comment]
The old camera uploads job has been replaced with a new worker
The old ownCloud picker has been replaced with the native picker to select the camera folder.

A notification with how many pictures and videos will be synced is shown now.
If there are any errors with the source path, a notification is shown now.

Updated several files to kotlin and new architecture.

### Pros:
- It will work before and after moving to Scoped Storage
- It is easier to add constraints like: trigger only when charging, trigger only when the battery is not low, etc

### Cons:
- Users will need to select the camera source path again
- Uploads triggered by camera uploads won't show progress (at least for the moment), but it should not be a big problem since they normally will be uploaded in the background.

### To discuss:
- Camera uploads repeat intervals. At the moment, it is triggered every 15 minutes. Maybe it is not needed to trigger them as often
- Camera uploads conditions: We can add some conditions like: `only when charging`, `only when the battery is not low` with no much effort if needed
- At the moment, camera uploads last sync timestamps are stored in the old database, and configuration(source path, behavior, account, etc) is stored in preferences. It could be an option to move both of them to a common place: new database. It would be easier to maintain, and we could take advantage of the needed reset in the next release.

@jesmrec @michaelstingl

**Comment by jesmrec** [comment]
> ### To discuss:
> * Camera uploads repeat intervals. At the moment, it is triggered every 15 minutes. Maybe it is not needed to trigger them as often

for me it's ok for the moment to keep 15 mins. Why should we set a longer scan frequency?

> * Camera uploads conditions: We can add some conditions like: `only when charging`, `only when the battery is not low` with no much effort if needed

interesting new features... for the future. 

> * At the moment, camera uploads last sync timestamps are stored in the old database, and configuration(source path, behavior, account, etc) is stored in preferences. It could be an option to move both of them to a common place: new database. It would be easier to maintain, and we could take advantage of the needed reset in the next release.

if that makes the code easier to mantain, no problem from my side. But the initial reset would be only the camera path. With this improvement, will we need a complete reset of the feature (like the 2.18 one)?

**Comment by abelgardep** [comment]
> for me it's ok for the moment to keep 15 mins. Why should we set a longer scan frequency?

Well, I think that maybe it is not needed to trigger camera uploads almost 100 times per day, but it is fine for me to keep the previous behavior.

> if that makes the code easier to maintain, no problem from my side. But the initial reset would be only the camera path. With this improvement, will we need a complete reset of the feature (like the 2.18 one)?

Yes, I think that camera path reset will be enough.

**Comment by jesmrec** [comment]
> Well, I think that maybe it is not needed to trigger camera uploads almost 100 times per day, but it is fine for me to keep the previous behavior.
 
Could this parameter be setup-able, or brandable? that means... giving users the choice to select the scan frequency (with the minimum of 15 mins, for sure)

**Comment by abelgardep** [comment]
> Could this parameter be setup-able, or brandable? that means... giving users the choice to select the scan frequency (with the minimum of 15 mins, for sure)

Yes, it could be brandable, or customizable. Probably in another issue 👍
