### ISSUE TITLE
[RELEASE] 2.15.1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2903]
### TASKS:

 - [ ] [GIT] Create branch release_1.0.6 in owncloud/android-library from master
 - [ ] [GIT] Create branch release_2.15.1 in owncloud/android from master
 - [ ] [DEV] Update version number and name in build.gradle in owncloudComLibrary module
 - [ ] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [ ] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [ ] [QA] Design Test plan
 - [ ] [QA] Regression Test plan
 - [ ] [DIS] Generate test APK file from `release_2.15.1` branch in owncloud/android
 - [ ] [GIT] Create and sign tag 'oc-android-2.15.1' in HEAD commit of stable master branch, in owncloud/android
 - [ ] [GIT] Create and sign tag '1.0.6' in HEAD commit of stable master branch, in owncloud/android-library
 - [ ] [DIS] Generate final APKs from signed commit in owncloud/android
 - [ ] [COM] inform `#release_coordination` and `#marketing` in internal chat
 - [ ] [GIT] Merge branch `release_1.0.6` in owncloud/android-library, into master
 - [ ] [GIT] Merge branch `release_2.15.1` in owncloud/android, into master
 - [ ] [DIS] Upload & publish release APK and changelog in Play Store
 - [ ] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [ ] [DIS] Upload release APK to internal owncloud instance
 - [ ] [GIT] merge master branch into stable, in owncloud/android-library
 - [ ] [GIT] merge master branch into stable, in owncloud/android
 - [ ] [DOC] Update owncloud.org/download version numbers (notify rocketchat #marketing)

_____
