### ISSUE TITLE
[RELEASE] 2.15.2

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2945]
### TASKS:

 - [x] [GIT] Create branch release/1.0.7 in owncloud/android-library from master
 - [x] [GIT] Create branch release/2.15.2 in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudComLibrary module
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [DIS] Generate test APK file from `release/2.15.2` branch in owncloud/android
 - [x] [GIT] Create and sign tag 'oc-android-2.15.2' in HEAD commit of stable master branch, in owncloud/android
 - [x] [GIT] Create and sign tag '1.0.7' in HEAD commit of stable master branch, in owncloud/android-library
 - [x] [DIS] Generate final APKs from signed commit in owncloud/android
 - [x] [COM] inform `#release_coordination` and `#marketing` in internal chat
 - [x] [GIT] Merge branch `release/1.0.7` in owncloud/android-library, into master
 - [x] [GIT] Merge branch `release/2.15.2` in owncloud/android, into master
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [DIS] Upload release APK to internal owncloud instance
 - [x] [GIT] merge master branch into stable, in owncloud/android-library
 - [x] [GIT] merge master branch into stable, in owncloud/android
 - [ ] [DOC] Update owncloud.org/download version numbers (notify rocketchat #marketing)

### PR
App: #2949 
Library: https://github.com/owncloud/android-library/pull/340
_____
