### ISSUE TITLE
[New Arch] Migrate OCFile to new database 

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2955]
To continue with the new architecture, we will need to migrate completely the old file database to the new one (Room).

This step will help us to develop the other synchronization issues faster, because we won't need to take care of two different databases and different ocfile models.

But this migration has different inconveniences since OCFile is present everywhere, and we will need to disable some functionalities until we finish completely the rearquitecture.

1. FileDataStorageManager handles every old database queries. So we will need to transform those operations to usecases. Some of them are currently planned, others may require new issues. Including:
- Get file by path, id.. #2957 
- Get folder content #2956 
- Get images from folder #2956 
- Save folder/file #2958
- Remove file/folder #2864 (includes local removal)
- Move file/folder #2865 (includes local move)
- Copy file/folder #2866 (includes local copy)
- Conflicts management
- Av. Offline management
- Shared by link management

2. Since the main idea is to release a version once we complete the rearquitecture, we could disable some features temporarely in the new_arch/synchronization branch, and work in different issues. For example:
- Camera Uploads
- Downloads #2872 
- Uploads
- Av. Offline synchronization
- DocumentsProvider integration

Once we have a compiling version, @jesmrec could start QA on each single functionality instead of waiting till the end of sync rearquitecture.

### Tasks

- [x] Transform RemoteFile to kotlin
- [x] Add old file attributes to new one. Needed to perform a proper migration
- [x] Use new create folder usecase instead of old database queries
- [x] Use new get file by id usecase instead of old database queries
- [x] Use new get file by path usecase instead of old database queries
- [x] Use new get folder content usecase instead of old database queries
- [x] Use new OCFile instead of old one on every file in the app
- [ ] Remove old OCFile [Deprecated for the moment. We may need to check its properties for pending new arch operations]
- [ ] Remove old database queries related to OCFile [Deprecated for the moment. We may need to check its properties for pending new arch operations]
- [ ] Try to perform attributes cleanup [Not possible at the moment. Let's check in next arch issues]
- [x] Add OCFile tests

### PR
- App #2995 
- Library (if needed) https://github.com/owncloud/android-library/pull/353

### Bugs and known issues after migration
- Av. Offline: Including get av.offline, toggle, sync, etc
- Uploads works partially: Files are uploaded properly to server but app shows an error
- Downloads works partially: Files are downloaded properly from server but app shows an error
- Shared by link
- Remove file
- Move local file
- Copy local file
- Conflicts

**Comment by jesmrec** [comment]
Migration done!
