### ISSUE TITLE
[New arch] Get folder content

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2956]
Related with #2955, we need to get the folder content from the local database in order to show the file list, so this should be one of the first issues to take care of after the migration.

For the moment, it would be enough to retrieve a list of files and keep the previous behaviour.

BTW, we can include GetImagesFromFolder use case since it is simply an aditional filter in the database.

In the future, we could use Flow or LiveData to improve the performance and error handling.

### TASKS

- [x] Research (if needed)
- [x] Create branch new_arch/get_folder_content
- [x] Development tasks
  - [x] Implement usecase for get folder content
  - [x] Implement usecase for get folder images
  - [x] Implement repository
  - [x] Implement localdatasource
  - [x] Implement dao
  - [x] Add tests for domain layer
  - [x] Add tests for data layer 
- [x] Code review and apply changes requested
- [x] Design test plan [no needed - after migration]
- [x] QA [no needed - after migration]
- [x] Merge branch new_arch/get_folder_content into new_arch/synchronization

### PR

- [app](https://github.com/owncloud/android/pull/2965)
- Library (if needed)

**Comment by abelgardep** [comment]
Merged into new_arch/synchronization. It will be tested there.
