### ISSUE TITLE
[New arch] Get file by id or path 

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2957]
Next step to new architecture, is to retrieve file/folder info from new database. Currently, files are retrieved by their id or path, so it would be enough to keep the current behaviour.

### TASKS

- [x] Research (if needed)
- [x] Create branch new_arch/get_file
- [x] Development tasks
  - [x] Implement usecase for get file by id
  - [x] Implement usecase for get file by remote path
  - [x] Implement repository
  - [x] Implement localdatasource
  - [x] Implement dao
  - [x] Add tests for domain layer
  - [x] Add tests for data layer 
- [x] Code review and apply changes requested
- [X] Design test plan [no needed - after migration]
- [X] QA  [no needed- after migration]
- [x] Merge branch new_arch/get_file into new_arch/synchronization

### PR

- App https://github.com/owncloud/android/pull/2962
- Library (if needed)

**Comment by abelgardep** [comment]
Will be tested in #2955
