### ISSUE TITLE
[New arch] Save file/folder in database 

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2958]
Currently there are some operations that need to save file info into the database. To achieve that, we can simply create a usecase to keep the current behaviour.

### TASKS

- [x] Research (if needed)
- [x] Create branch new_arch/save_file_in_db
- [x] Development tasks
  - [x] Create saveFileUseCase (add it to UseCaseModule)
  - [x] Add saveFile to FileRepository
  - [x] Add saveFile to FileLocalDataSource
  - [x] Add saveFile to FileDao if it is not added yet
  - [x] Add domain unit tests
  - [x] Add data unit tests
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [x] Merge branch new_arch/save_file_in_db into new_arch/synchronization

### PR

- App: https://github.com/owncloud/android/pull/2972

**Comment by abelgardep** [comment]
Will be tested in new_arch/synchronization branch
