### ISSUE TITLE
[FEATURE REQUEST] Integrate Sonarcloud

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2974]
[Sonarcloud](https://sonarcloud.io/) is a tool to check bugs, vulnerabilities, code smells etc... in the code of your app. Bow, we can take advantage of it and try to integrate with our repos to check how healthy they are.

### TASKS

- [ ] Research (if needed)
- [x] Create branch feature/feature_name
- [x] Development tasks
  - [X] Read about sonar
  - [x] Check how to integrate it
  - [x] Modify `build.gradle` to execute `sonar` task from the project
  - [x] Check if we can use jacoco for code coverage inside sonarcloud  [WONT DO IT NOW]
  - [x] CI integration
  - [x] Github reporting 
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
[WIP]

This was the process to integrate in the Android repo:

**1) `Github Actions` ❌** 

In order to split the jobs up and not to overload BitRise, i tried first to use `Github Actions` to trigger the SonarCloud analysis and decorations

After many tries, it was not posible due to any kind of problem related with the build process of the app. The execution of `./gradlew sonarqube --info` or simply an `./gradlew build --info` operation causes an error in the `owncloudData` layer:

```
Execution failed for task ':owncloudData:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
```

This error does not happen neither in other CI (BitRise) nor in the local execution. After researching about it, i could not find out which the problem is, so i discarded (ftm) using `Github Actions` to link the SonarCloud instance.

**2) `BitRise` ✅** 

BitRise allows to include a predefined step to connect with the SonarCloud instance:  `SonarQube Scanner` 

Set up is pretty easy and straightforward, so that it needs only a list of parameters.

[Here](https://docs.sonarqube.org/latest/analysis/analysis-parameters/) you'll find the documentation about the available parameters

This is the list i used:

```
sonar.sources=.
sonar.java.binaries=build/kotlin
sonar.login=$SONAR_TOKEN
sonar.projectKey=$SONAR_PROJECT
sonar.organization=$SONAR_ORGANIZATION
sonar.host.url=https://sonarcloud.io
sonar.report.export.path=sonar-report.json
sonar.pullrequest.provider=GitHub
sonar.pullrequest.github.repository=ownCloud/android
sonar.pullrequest.branch=$BITRISE_GIT_BRANCH
sonar.pullrequest.key=$BITRISE_PULL_REQUEST
```

setting the env variable `$SONAR_TOKEN` as secret and `$SONAR_PROJECT` & `$SONAR_ORGANIZATION` as env variables.

I set as trigger the pull request event for one reason. The parameters `sonar.pullrequest.branch` and `sonar.pullrequest.key` are mandatory for PR analysis, whereas the BitRise variable `$BITRISE_PULL_REQUEST` is only available for builds triggered from a PR event. 

That secret needs to be exposed for PR actions. Otherwise, the process will finish with an authorization error. I've researched about what does this exposition mean: in terms of logs, the secret is never printed (always [REDACTED]). The access to the steps is forbidden for non-members. A little explanation about this [here](https://blog.bitrise.io/post/anyone-even-prs-can-have-secrets).

With this setup, the PR will show the report generated from SonarCloud like [this test PR](https://github.com/owncloud/android/pull/3280). The steps to trigger the build have been placed in a different workflow called `Sonar` in BitRise's unit tests app.


**3) Local execution ✅** 

In the `build.gradle`  file of the project is included everything needed to trigger a build locally. It will be needed to export the token to connect the instance:

`export SONAR_TOKEN=xxxx`

by executing  `./gradlew sonarqube --info` the analysis will be triggered locally. 


**4) Code Coverage :heavy_minus_sign:**

SonarCloud is ready to be integrated with `JaCoCo` (java code coverage). After several tries i wasn't be able to integrate and make it work. The current status of the code (half Kotlin, half Java) leads to some confusion. When the app turns totally to Kotlin and the developed tests cover completely the app, we will try another look to the include the coverage.
