### ISSUE TITLE
Share ids should be moved to String

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2985]
By checking `ocs/v2.php/apps/files_sharing/api/v1/shares` ids are returned as:

- oC10: `<id>20</id>`
- oCIS: `<id>WekWkusWjURJIDD</id>`

they should be moved as string

AC:

- Transform int to String
- Use moshi to parse
- DB migration
- Update documentation

### TASKS

- [x] Research (if needed)
- [x] Create branch fix/parse_shareid_as_string
- [x] Development tasks
  - [x] Check documentation
  - [x] Implement datatype change
  - [x] Update tests
  - [x] Perform database migration and upgrade database version
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch fix/parse_shareid_as_string into master

### PR

- App: #3011 
- Library (if needed): https://github.com/owncloud/android-library/pull/355

**Comment by abelgardep** [comment]
I suggest using moshi to parse shares instead of a custom parsing of the XML

**Comment by abelgardep** [comment]
There are some fields that we don't use anywhere but we have them stored anyway (localName -> remoteName):

- `file_source` -> `file_source`
- `item_source` -> `item_source`
- `shared_date` -> `stime`
- `user_id` -> No remote

Should we remove them?

**Comment by abelgardep** [comment]
`file_source`, `item_source` and `user_id` were removed from OCShare model. They were not used in other platforms neither.

About moshi, i would suggest creating a new library issue to do it. This issue has enough complexity from my point of view. What do you think? @jesmrec @theScrabi

**Comment by jesmrec** [comment]
for me it is OK to move the moshi stuff to a new issue

**Comment by abelgardep** [comment]
Ok, i have created a new issue in the library (https://github.com/owncloud/android-library/issues/356). We will use it to parse shares using Moshi.

**Comment by jesmrec** [comment]
With testing purposes: check all migrations since 2.12.
