### ISSUE TITLE
[FEATURE REQUEST] New background image for the login screen

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/android#2991]
**Describe the solution you'd like**

With the ownCloud Server 10.5 release we said goodbye to the satellite that was visible in the login screen. In the Android app it is still visible. To be in sync the picture should be changed there as well.

**Steps taken**

I have already prepared the new images in the following branch:
https://github.com/owncloud/android/tree/new-ci-images

**Please note**

What should be considered is the fact that the positioning of the new image should start from the lower right edge. The new CI image has design elements only in the left and right corner. 

In portrait format you should see the following part of the design:

![image](https://user-images.githubusercontent.com/33026403/95328437-d882aa00-08a5-11eb-9ba2-ea5f3c43cc1d.png)

AC:

- Login view will include the new image
- Top drawer will include the new image

### TASKS

- [x] Research
- [x] Create branch feature/feature_name
- [ ] Development tasks
  - [x] Create util for matrix scaling
  - [x] apply matrix scaling util for login and drawer image
  - [x] add compatibility for whitelabel version
- [ ] Code review and apply changes requested
- [ ] Test background design with ownbranded version of the app
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR
- Old: https://github.com/owncloud/android/pull/2996
- New: https://github.com/owncloud/android/pull/3023

**Comment by jesmrec** [comment]
Will include in 2.16. 

Also, we have to change in the top side of the drawer where the satellite image is shown.

**Comment by ChrisEdS** [comment]
> Also, we have to change in the top side of the drawer where the satellite image is shown.

I'm one step ahead. 👍 

https://github.com/owncloud/android/blob/77e19f96c8bcd9d5dd65af4551bcf70666cb3888/owncloudApp/src/main/res/drawable-hdpi/drawer_header_background.png

But that image needs to be improved maybe.

**Comment by theScrabi** [comment]
Currently the app crashes on this branch. The stacktrace depics that the login button is null. Which can not be. This behaviour is not related to anything that the code does at the moment, which is weird and might required deeper investigation.

The scale view from bottom right is not working appropriately as well: https://github.com/owncloud/android/pull/2996/files#diff-64c334a87f1aea1fb0d3bcbc70d21e40d71ab4f51551665eec612117962f17b3

This function needs to be called every time the layout needs to be updated. This is required since we want the anchor point of the image to be on the bottom right of the screen and the image. Then we want to scale towards the top left. Either cropping the top part of the image or the left part of it. This needs to be done in order to ensure that 1. The image covers the whole screen, 2. the shapes on the bottom right are always visible.

However apart from crashing the this function is not even scaling appropriately. I'd like to test it on a device that allows to freely  size the app screen like resizing windows. This can be done with software like [android x86](https://www.android-x86.org/), or [anbox](https://anbox.io/) on ubuntu.

Additionally we need to distinguish between branded and the regular application. This needs to be done since branded apps do not use this image, and so the scaling must fall back to center crop.

I think the easiest way to go here is to keep center crop scaling but design a background image for portrait mode. This way we can ensure that the shapes are always visible without having to do complex matrix transformation.

**Comment by abelgardep** [comment]
> I think the easiest way to go here is to keep center crop scaling but design a background image for portrait mode. This way we can ensure that the shapes are always visible without having to do complex matrix transformation.

100% Agree. From my point of view we should not overcomplicate this issue. New images included in this [commit](https://github.com/owncloud/android/commit/77e19f96c8bcd9d5dd65af4551bcf70666cb3888?short_path=ddd24dd#diff-ddd24dd065231130fae2f1120968c60413e8ccfb64ce33789c8a902699867ca7) are pretty wide and when we try to center them, those shapes are missing. An image for portrait mode will be centered automatically fixing the problem we have when trying to scale it starting from bottom right.

**Comment by theScrabi** [comment]
@ChrisEdS Maybe you can directly send us the SVG versions these can be shown more crisp on phones ;)

**Comment by abelgardep** [comment]
> @ChrisEdS Maybe you can directly send us the SVG versions these can be shown more crisp on phones even with normal resolution ;)

Here the idea is to simply replace one image with the new one. If we change the format or rename the image, we will need to apply some changes in oB to support it. So, to keep it simple, i think that the best way to do it, is replacing the old one with a mobile version of the new ones.

**Comment by abelgardep** [comment]
| Drawer | Login Portrait |
| ------------- | ------------- |
| ![Screenshot_1606210005](https://user-images.githubusercontent.com/47524927/100075065-c6ea6700-2e3f-11eb-8d96-37e5d0538df3.png) | ![Screenshot_1606210015](https://user-images.githubusercontent.com/47524927/100075068-c8b42a80-2e3f-11eb-8919-ce70c505299d.png) |

| Login Landscape |
| ------------- |
| ![Screenshot_1606210023](https://user-images.githubusercontent.com/47524927/100075076-c94cc100-2e3f-11eb-8dab-3354151cb3e3.png) |

How important are the shapes in login landscape mode? At the moment we lose them. If we want to add a new background image exclusively for landscape, we probably will need to ask for an additional image in oB for landscape.

@ChrisEdS @michaelstingl @theScrabi @jesmrec

**Comment by ChrisEdS** [comment]
> How important are the shapes in login landscape mode? At the moment we lose them. If we want to add a new background image exclusively for landscape, we probably will need to ask for an additional image in oB for landscape.

I can provide the image. But what about branding? In ownBrander we only upload one picture.

**Comment by michaelstingl** [comment]
> I can provide the image. But what about branding? In ownBrander we only upload one picture.

Yes, single-image-only for branding customers please. Vanilla-oC can have some extra eyecandy, similar as we do with the new-features-wizard.
