### ISSUE TITLE
[RELEASE] 2.16

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2993]
### TASKS:

 - [x] [GIT] Create branch release_1.0.9 in owncloud/android-library from master
 - [x] [GIT] Create branch release_2.16 in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudComLibrary module
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DEV] Update wizard with most important changes
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [x] [DIS] Update screenshots in Google Play, because changes in UI (background image...)
 - [x] [DIS] Update screenshots in README, because changes in UI (background image...)
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan [WIP]
 - [x] [DIS] Generate test APK file from `release_2.16` branch in owncloud/android
 - [x] [GIT] Create and sign tag 'oc-android-2.16' in HEAD commit of stable master branch, in owncloud/android
 - [x] [GIT] Create and sign tag '1.0.9' in HEAD commit of stable master branch, in owncloud/android-library
 - [x] [DIS] Generate final APKs from signed commit in owncloud/android
 - [x] [COM] inform `#release_coordination` and `#marketing` in internal chat
 - [ ] [GIT] Merge branch `release_1.0.9` in owncloud/android-library, into master
 - [ ] [GIT] Merge branch `release_2.16` in owncloud/android, into master
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [DIS] Upload release APK to internal owncloud instance
 - [x] [DIS] Create post in central.owncloud.org
 - [ ] [GIT] merge master branch into stable, in owncloud/android-library
 - [ ] [GIT] merge master branch into stable, in owncloud/android
 - [ ] [DOC] Update owncloud.org/download version numbers (notify rocketchat #marketing)

### PR
App: https://github.com/owncloud/android/pull/3053
Library: https://github.com/owncloud/android-library/pull/365
_____

### QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.16/Regression_2.16.md

#### BUGS & IMPROVEMENTS

- [x] Check https://github.com/owncloud/android/issues/3029 [not reproducible]
- [X] (1) Remove '0' from version number https://github.com/owncloud/android/issues/2993#issuecomment-762726817 [FIXED]
- [X] (2) Crash after selection of sorting method https://github.com/owncloud/android/issues/2993#issuecomment-762831761 [FIXED]
- [x] (3) Lack of action after token revokal https://github.com/owncloud/android/issues/2993#issuecomment-763553847 [FIXED]

**Comment by abelgardep** [comment]
Update screenshots:
- Sort Menu
   - [ ] Play Store
   - [ ] ReadMe
   - [ ] F-Droid

**Comment by jesmrec** [comment]
### (1)

Current: 

release number: 2.16.0

Expected:

release number: 2.16  (no 0)

**Comment by jesmrec** [comment]
### (2)

1. Install 2.16 from scratch and add one account
2. Tap on Sorting type selector 

Current: crash. This is the stack trace:

```
2021-01-19 14:11:33.900 17492-17492/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.owncloud.android, PID: 17492
    java.lang.NullPointerException: null cannot be cast to non-null type android.view.View
        at java.util.Objects.requireNonNull(Objects.java:245)
        at com.owncloud.android.presentation.ui.files.SortBottomSheetFragment.onViewCreated(SortBottomSheetFragment.kt:52)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Expected: no crash

Pixel 2 Android 11
Nexus 6P Android 7
`a7e5fa5d`

**Comment by abelgardep** [comment]
(1) Ok, fixed
(2) Fixed, ready to test @jesmrec

**Comment by jesmrec** [comment]
### (3) 

1. Log in OAuth2 account
2. In web, revoke session (Settings -> Security -> OAuth2 -> Android -> Trashbin)
3. In app, browse or execute any action against server

Current: Nothing happens
Expected: Snackbar pointing to Sign In, as in 2.15.3

Pixel 2 Android 11
Nexus 6P Android 7
`a2e13155 `

**Comment by abelgardep** [comment]
Related to (3). I have been researching a little bit. Disabling the thumbnails for every file type, keeping just images, I didn't reproduce this issue. I think this is the best approach to release 2.16. We will enable them again once we replace appauth to check if this issue is fixed. So, we will try to include thumbnails for every file type in 2.17.

**Comment by jesmrec** [comment]
Workaround for (3) is correct.
