### ISSUE TITLE
[New Arch] Conflicts management

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3005]
Synchronization epic: #2818

Handle conflicts between local and remote files. Currently handled by SynchronizeFileOperation and SynchronizeFolderOperation. 

### TASKS

- [x] Research (if needed)
- [x] Create branch new_arch/conflicts_management
- [x] Development tasks
  - [x] Single item shows a red icon to show conflict
  - [x] Kotlinize `ConflictsResolveActivity.java`
  - [x] Kotlinize `ConflictsResolveDialog.java`
  - [x] Remove old `ConflictsResolveActivity.java` and `ConflictsResolveDialog.java`
  - [x] Show conflict dialog from the main file list
  - [x] Show conflict dialog from the file details view
  - [x] Folder shows a red icon if any descendants have conflicts [ADVANCED -> owncloud/android/pull/3766]
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch new_arch/conflicts_management into new_arch/synchronization

**Comment by jesmrec** [comment]
One clarification. In `master` version, when a conflict happens a notification is raised up. By clicking on it, conflict solving dialog is open in the app. Conflict could also happen in the background (new version of av. offline that collides with new version in server side)
