### ISSUE TITLE
[FEATURE REQUEST] Improvements in preview/thumbnails updates

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3024]
Current behaviour:

 - The preview of an txt file is updated only when it is not downloaded, and the containing folder is browsed back and forth. 

 - In case the file is downloaded, the preview is not updated because it is generated locally. That means, preview does not match with file content.

ACs

- When a file is updated in remote (web or other client), the preview will be updated in the following refresh.  (this behaviour is pretty similar to the av. offline files one)

- When a folder contains many files, requests should be scoped / reduced to avoid request-flooding in some way. -> Current behaviour: fetching previews of the files in the screen (pending to confirm)

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/improve_thumbnails
- [x] Development tasks
  - [x] Retrieve thumbnails even if the file is available locally
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/improve_thumbnails into master

### PR

- App #3035 
- Library (if needed)

**Comment by jesmrec** [comment]
Important topic: https://github.com/owncloud/android/issues/2926#issuecomment-725927475
