### ISSUE TITLE
[FEATURE REQUEST] Improve empty views

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3026]
I suggest adding a title, subtitle and image as server does.

Same for empty folders, shared by link, av. offline, uploads, log files

Good chance to align wording here.

Current empty views for server and android:
| Server | Android |
| ------ | ------ |
| ![Screenshot 2020-11-30 at 12 08 55](https://user-images.githubusercontent.com/47524927/100602974-d9174a00-3304-11eb-8493-0cf116be9633.png) | ![Screenshot 2020-11-30 at 12 05 47](https://user-images.githubusercontent.com/47524927/100602731-96ee0880-3304-11eb-8c8b-56c2e379644e.png) |

### TASKS

- [x] Research
- [x] Create branch feature/empty_views
- [x] Development tasks
  - [x] Improve empty folder view
  - [x] Improve empty folder file explorer view (sharing with ownCloud)
  - [x] Improve empty shared by link view
  - [x] Improve empty av. offline view
  - [x] Improve empty uploads view
  - [x] Improve empty log files view
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch feature/empty_views into master

**Comment by JohnKal** [comment]
Hello! Can i work on this feature?

**Comment by abelgardep** [comment]
Hello @JohnKal , thanks for your interest! We would like to align wording, icons, etc with other platforms when possible. Let me check if you have enough resources to work on it. @CarolinaCst may can help

**Comment by JohnKal** [comment]
I created this empty view for the files screen.

![Screenshot_1608569517](https://user-images.githubusercontent.com/1830777/102802633-a02c3b80-43bf-11eb-9dd9-aa10ef151726.png)

@abelgardep Are you ok with this? Also you have to provide me with the appropriate images (shared by link, av. offline, uploads) and strings.

**Comment by abelgardep** [comment]
I like it! What do you think @michaelstingl? Yes, we need to decide which images and strings fit better on each view. Thanks!

**Comment by jesmrec** [comment]
keep open to allign behaviour across the app.

**Comment by tbsbdr** [comment]
The screen should communicate the following:

1. Tell the user at a glimpse, that the folder is empty
2. Tell the user how to add files OR directly provide a add/upload button in-place.

Cross-app alignment would be nice, but I would prioritize it as p4.

**Comment by abelgardep** [comment]
Taking into account team suggestions, we have 2 options at the moment (any other suggestion is welcome). The first one would use the same colors as the top bar and bottom navigation bar, and the second one would keep the soft grey tones.

What do you think? @tbsbdr @michaelstingl @jesmrec @JuancaG05 @theScrabi 
### Topbar and bottom navigation bar colors
| All files | Available offline | Shared by link | Uploads | Logs |
| --- | --- | --- | --- | --- |
| ![empty_all_files](https://user-images.githubusercontent.com/47524927/184853776-938cae76-9c7d-49d6-a80a-433ce0929b7a.png) | ![empty_av_offline](https://user-images.githubusercontent.com/47524927/184853811-539c29dc-f2d3-4610-bc61-27e8aa20fa3f.png) | ![empty_shared_by_link](https://user-images.githubusercontent.com/47524927/184853907-cd1058d3-e2e2-449e-bcd8-d31476363cff.png) | ![empty_uploads](https://user-images.githubusercontent.com/47524927/185906625-76714bcb-4990-4ab8-a963-ab33b1222c95.png) | ![empty_logs](https://user-images.githubusercontent.com/47524927/185906659-f0795bdb-4e36-4222-a4a6-39ece344acba.png) |

____________________

### Grey tones
| All files | Available offline | Shared by link | Uploads | Logs |
| --- | --- | --- | --- | --- |
| ![empty_files](https://user-images.githubusercontent.com/47524927/187137189-00b4b1cd-f009-45e7-903b-9467dd774eef.png) |![empty_offline](https://user-images.githubusercontent.com/47524927/187137230-392d001a-4a76-4d79-a4d6-33df050b4769.png) | ![empty_shared](https://user-images.githubusercontent.com/47524927/187137329-5399ddbb-55f4-46cf-805b-191b39ca9b8a.png)| ![empty_uploads](https://user-images.githubusercontent.com/47524927/187137375-1a8d0844-23b5-4f2b-8b6d-12d87c07bb8d.png) | ![empty_logs](https://user-images.githubusercontent.com/47524927/187137420-7eea6e26-eaf3-4b03-86cc-3ef7137941c7.png)  |

**Comment by abelgardep** [comment]
Ok, let's try branded colors first. We can iterate..
