### ISSUE TITLE
Replace kotlin-android-extensions

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3028]
With latest update to kotlin 1.4.20, `kotlin-android-extensions` are deprecated. The most important thing here, is that we need to replace synthetics. ViewBinding? We need to use also the new `kotlin-parcelize` plugin

### TASKS

- [x] Research (if needed)
- [x] Create branch replace_kotlin_android_extensions
- [x] Development tasks
  - [x] Remove synthetics from DrawerActivity
  - [x] Remove synthetics from PreviewImageFragment
  - [x] Remove synthetics from ToolbarActivity
  - [x] Remove synthetics from FileDisplayActivity
  - [x] Remove synthetics from ShareFileFragment
  - [x] Remove synthetics from PublicShareDialogFragment
  - [x] Remove synthetics from SearchShareesFragment
  - [x] Remove synthetics from LoginActivity
  - [x] Remove synthetics from SharePublicLinkAdapter
  - [x] Remove synthetics from SortOptionsView
  - [x] Remove synthetics from EditPrivateShareFragment
  - [x] Remove synthetics from BottomSheetFragmentView
  - [x] Use kotlin-parcelize instead of old kotlin android extension
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA - UI Regressions
- [ ] Merge branch replace_kotlin_android_extensions into master

### PR

- App #3203 
- Library (if needed)

**Comment by jesmrec** [comment]
It will need to be changed medium - term.

Used in login view and shares.
