### ISSUE TITLE
Remove okHttpClient singleton from library

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android#3048]
Since we switched with the http library of the app to okhttp we use a singleton to represent the okHttpClient object. The OwnCloudClient objects are represented as instances yet contain always the same okHttpClient instance. This causes issues like the same cookiejar being used for every account, which requires us to delete the cookiejar manually.

### Tasks
- [x] Make okHttpClient nonsingleton
- [x] move library remoteoperations to nonsingleton 
- [x] move app remoteoperations to nonsingleton
- [ ] Add/fix Unit tests in library
- [ ] Add/fix Unit tests in app
- [ ] Test if application runs stable

### Implementation
App: https://github.com/owncloud/android/pull/3047
Library: https://github.com/owncloud/android-library/pull/364
