### ISSUE TITLE
[FEATURE REQUEST] OIDC Dynamic Client Registration support

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3054]
This issue tracks support for OIDC Dynamic Client Registration support 

Info about it:

- https://tools.ietf.org/html/rfc7591
- https://openid.net/specs/openid-connect-registration-1_0.html

New endpoint `register` is available to get the `client_id` and `secret_id` that will be used in the token request. The location of the endpoint is available on `.well-known`. The `secret_id` has its own validity time. 

OIDC Dynamic Client Registration is available on `ocis.owncloud.works`.

Other clients' stuff:

iOS-sdk commit: https://github.com/owncloud/ios-sdk/commit/85e09cbc1fa9fbd5ddab961787d98130c0b2f1f2
Desktop client PR: https://github.com/owncloud/client/pull/8350
Web: https://github.com/owncloud/web/pull/4286

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/oidc_dynamic_client_registration
- [x] Development tasks
  - [x] Create a new remote operation to register a new client (library)
  - [x] Create a new use case to register a new client
  - [x] Call new use case when needed
  - [x] Handle token renewal
  - [x] Add unit tests
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/oidc_dynamic_client_registration into master

### PR

- App https://github.com/owncloud/android/pull/3073
- Library https://github.com/owncloud/android-library/pull/367
