### ISSUE TITLE
[RELEASE] 2.16_oem

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3057]
### TASKS:

- [x] Check https://github.com/owncloud/ownbrander/pull/952
- [X] [QA] Test plan
- [x] [GIT] Create and sign tag `oc-android-2.16_oem` in HEAD commit of `release_2.16_oem` branch or 2.16 commit (depending on if there's new changes or not), in owncloud/android
- [X] Approve and merge changes in ownBrander
- [X] [DIS] Deploy and block button
- [x] [DIS] Generate final APKs files from signed commit in builder machine  and perform some basic operations 
- [x] [DIS] Enable button

_____

### PR
- App: https://github.com/owncloud/android/pull/3075

### BUGS & IMPROVEMENTS

- [X] (1) Background of sort bar https://github.com/owncloud/android/issues/3057#issuecomment-771613891 [FIXED]
- [x] (2) Custom background image of login view is missing https://github.com/owncloud/android/issues/3057#issuecomment-771850418 [FIXED]

**Comment by jesmrec** [comment]
### (1)

Sort bar is not tinted in the correct color. It is taking main color instead of the toolbar color:

![Screenshot 2021-02-02 at 13 52 06](https://user-images.githubusercontent.com/14894746/106602864-dbdd2800-655d-11eb-8fae-830609b5baee.png)

**Comment by abelgardep** [comment]
(1) Should be fixed now. Ready to test @jesmrec

**Comment by jesmrec** [comment]
### (2)

When a custom image is uploaded as login background to oB UI, the final result is the default image. 

Login background image is stored in `drawable` folder of `ownCloudApp` module. In themes, this image does not exist (weird?), but, at the end, this is the displayed image. Need to check with the final theme why this is happening.

**Comment by abelgardep** [comment]
About (2)

In https://github.com/owncloud/android/pull/3023 we replaced the previous png with a vector image. That way the shapes are properly displayed in the oC App. I think that the vector images are not removed in the scripts at the moment. So, Android will use the vector image instead of the theme image.

So, from my point of view, the script should remove the XML. That way, the custom App will use the custom image.

Images to delete in the scripts: [Portrait](https://github.com/owncloud/android/blob/master/owncloudApp/src/main/res/drawable/login_background_image.xml) and [Landscape](https://github.com/owncloud/android/blob/master/owncloudApp/src/main/res/drawable-land/login_background_image.xml)

**Comment by jesmrec** [comment]
(2)  was fixed in the build scripts, by removing the vector image when a custom one exists, and keep it in other case.

Fixed

**Comment by jesmrec** [comment]
Release done!!
