### ISSUE TITLE
Replace one-way mappers with kotlin extensions

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3091]
At the moment, we have some mappers to move a remote object from the library to a domain model. We could get rid of them and save some code just by replacing those mappers with private Kotlin extensions.

For example, we could delete [these mappers](https://github.com/owncloud/android/tree/master/owncloudData/src/main/java/com/owncloud/android/data/user/datasources/mapper) by adding like 20 lines to the remote datasource.
### TASKS

- [x] Research (if needed)
- [x] Create branch cleanup/one_way_mappers
- [x] Development tasks
  - [x] Replace oidc response mapper
  - [x] Replace token request mapper
  - [x] Replace token response mapper
  - [x] Replace remote user info mapper
  - [x] Replace remote user quota mapper
  - [x] Replace remote user avatar mapper
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch cleanup/one_way_mappers into master

### PR

- App #3112 
- Library (if needed)
