### ISSUE TITLE
[FEATURE REQUEST] Use Moshi to parse shares

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3097]
Issue to keep track of https://github.com/owncloud/android-library/issues/356

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/parse_shares
- [x] Development tasks
  - [x] Create GetRemoteShareOperation and ShareResponse and delete old GetRemoteShareOperation
  - [x] Modify CreateRemoteShareOperation and UpdateRemoteShareOperation
  - [x] Modify GetRemoteSharesForFileOperation
  - [x] Modify RemoveRemoteShareOperation
  - [x] Modify UpdateRemoteShareOperation
  - [x] Delete ShareUtils, ShareXMLParser and ShareToRemoteOperationResultParser
  - [ ] Implement Testing
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/parse_shares into master

### PR

- App #3366 
- Library (if needed) https://github.com/owncloud/android-library/pull/430
