### ISSUE TITLE
[RELEASE] 2.17

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3098]
### TASKS:

 - [x] [GIT] Create branch release/1.0.10 in owncloud/android-library from master
 - [x] [GIT] Create branch release/2.17 in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudComLibrary module
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [x] [DIS] Add step to wizard (if needed)
 - [x] [DIS] Update screenshots, if needed, in README.md
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [DIS] Generate test APK file from `release/2.17` branch in owncloud/android
 - [x] [GIT] Create and sign tag 'oc-android-2.17' in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Create and sign tag '1.0.10' in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Generate final APKs from signed commit in owncloud/android
 - [x] [COM] Inform `#release_coordination` and `#marketing` in internal chat
 - [x] [GIT] Merge branch `release/1.0.10` in owncloud/android-library, into master
 - [x] [GIT] Merge branch `release/2.17` in owncloud/android, into master
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [GIT] Publish a new release in owncloud/android
 - [x] [DIS] Upload release APK to internal owncloud instance
 - [x] [GIT] Merge master branch into stable, in owncloud/android-library
 - [x] [GIT] Merge master branch into stable, in owncloud/android
 - [x] [DOC] Update owncloud.org/download version numbers (notify rocketchat #marketing)

_____

### BUGS & IMPROVEMENTS

- [x] (1) Report from GP https://github.com/owncloud/android/issues/3098#issuecomment-799238022 [WONT FIX]
- [x] (2) Header in Logs view https://github.com/owncloud/android/issues/3098#issuecomment-800294279 [FIXED]
- [X] (3) Update wizard is missing https://github.com/owncloud/android/issues/3098#issuecomment-800399799 [FIXED]
- [X] (4) Clear button in `Current` section of uploads view https://github.com/owncloud/android/issues/3098#issuecomment-800936114 [FIXED]
- [x] (5) Share text https://github.com/owncloud/android/issues/3098#issuecomment-800966384 [Ready to test @jesmrec ]

**Comment by jesmrec** [comment]
### (1)

From GP:

```
java.lang.IllegalStateException: 
  at androidx.fragment.app.FragmentManager.checkStateLoss (FragmentManager.java:1832)
  at androidx.fragment.app.FragmentManager.enqueueAction (FragmentManager.java:1872)
  at androidx.fragment.app.BackStackRecord.commitInternal (BackStackRecord.java:329)
  at androidx.fragment.app.BackStackRecord.commit (BackStackRecord.java:294)
  at androidx.fragment.app.DialogFragment.dismissInternal (DialogFragment.java:352)
  at androidx.fragment.app.DialogFragment.dismiss (DialogFragment.java:304)
  at com.owncloud.android.ui.activity.BaseActivity.dismissLoadingDialog (BaseActivity.java:315)
  at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onTmpFilesCopied (ReceiveExternalFilesActivity.java:841)
  at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.onPostExecute (CopyAndUploadContentUrisTask.java:240)
  at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.onPostExecute (CopyAndUploadContentUrisTask.java:47)
  at android.os.AsyncTask.finish (AsyncTask.java:755)
  at android.os.AsyncTask.access$900 (AsyncTask.java:192)
  at android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:772)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7386)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:980)
```

**Comment by jesmrec** [comment]
### (2)

1. Tap 5 times in compilation number
2. Open Logs view

Current: Header is missing
Expected: Header is there

Pixel2 Android 11
`8905214d`

**Comment by jesmrec** [comment]
### (3)

1. Install 2.16
2. Update to current

Current: Update wizard is not displayed
Expected: Update wizard is displayed

Nexus 6P v7
`d3300e37 `

**Comment by jesmrec** [comment]
### (4)

A small glitch in the uploads view

1. Upload a bunch of files (so, you will have enough time to perform the following actions)
2. Open the Uploads view, where files have started to upload (`Current` section)
3. Scroll down to the `Uploaded` section where all the finished uploads are listed
4. Scroll up to the top again

Current: `Current` section shows the `Clear` button (in step 2, it didn't). `Clear` button does nothing
Expected: Either no `Current` button, or `Current` button with action  (f. ex, remove all pending)

Recording:


https://user-images.githubusercontent.com/14894746/111445714-f7fee800-870b-11eb-9bc0-5693bd6d1a61.mp4



Nexus 6P v7, Pixel 2v11
d3300e37

**Comment by jesmrec** [comment]
### (5)

1. Open a browser, any web with content
2. Select some text from the web
3. Share it with oC -> You will be asked for the account, location and file name
4. Tap on `UPLOAD`

Current: File with the text is uploaded, but file name dialog is not dismissed
Expected: File uploaded after dialog is dismissed (2.16)

Nexus 6P v7, Pixel 2v11
`d3300e3`

**Comment by abelgardep** [comment]
2.17 is already out!
