### ISSUE TITLE
[Android X Preference] Security section

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3099]
### AC

- It is placed in the same place, just below `Camera Uploads`

- Four cells, all of them always visible
  - Passcode: exclusive with Pattern
  - Pattern:  exclusive with Passcode
  - Biometric: only if one of the above is enabled. If not, greyed out
  - Touches: independent form the previous ones. Only a checkbox
  
- Names and definition keep, no needed new ones

- No new features, except for the removal of snackbars when passcode and pattern locks are set correctly. At the end it must work as before.

### TASKS

- [x] Research a little bit how settings are implemented and how we can include androidX ones.
- [x] Create branch settings/security
- [x] Development tasks
  - [x] Add [new dependency](https://developer.android.com/jetpack/androidx/releases/preference#declaring_dependencies) to owncloudApp build gradle.
  - [x] Create a new activity, a new fragment, and a new preferences XML. [Inflate them](https://developer.android.com/guide/topics/ui/settings#inflate_the_hierarchy)
  - [x] Create a new preference category for the security section
  - [x] Include 4 new checkbox preferences in the new preference category
  - [x] [Retrieve current values](https://developer.android.com/guide/topics/ui/settings/use-saved-values) to check or not those checkboxes
  - [x] Support navigation and back when passcode and pattern are clicked (onActivityResult)
  - [x] Disable biometric till pattern or passcode are enabled
  - [x] Remove snackbars when passcode and pattern locks are set correctly and add new ones when there is an error setting these locks
  - [x] Include UI tests / Unit tests
- [x] Code review and apply changes requested
- [x] Merge branch settings/security into settings/androidx

### PR

- App #3120 
- Library (if needed)

**Comment by JuancaG05** [comment]
New task added: "Remove snackbars when passcode and pattern locks are set correctly and add new ones when there is an error setting these locks"
