### ISSUE TITLE
[Android X Preference] More section

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3100]
### AC

- It is placed in the same place, last one in the settings view.

- Seven cells, six of them always visible and Imprint not visible (retrieve visibility from R.bool)
  - Help
  - Install DAVx
  - Recommend
  - Feedback
  - Privacy policy
  - Imprint
  - App version
  
- Names and definition keep, no needed new ones

- No new features, at the end it must work as before. But, do not include app version listener yet, since it will enable logs and it is not done yet. To be done in next issue.

### TASKS

- [x] Research a little bit about more section and how it works
- [x] Create branch settings/more
- [x] Development tasks
  - [x] Create a new preference category for the more section
  - [x] Include 7 new preferences in the new preference category
  - [x] Support navigation and back (if needed)
  - [x] Include UI tests / Unit tests
- [x] Code review and apply changes requested
- [x] Merge branch settings/more into settings/androidx

### PR

- App
- Library (if needed)
