### ISSUE TITLE
[Android X Preference] Logs section

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3101]
### AC

- The category is placed in the same place, below `security`, but now the preferences are displayed in another screen

- Two cells, visible only when logs are enabled.
  - HTTP Logs
  - Logs view
  
- Names and definition keep, no needed new ones

- New feature: 
  - DEBUG logic is removed: logs are not enabled by default although you use the debug version

### TASKS

- [x] Research a little bit how settings are implemented and how we can include androidX ones.
- [x] Create branch settings/logs
- [x] Development tasks(https://developer.android.com/guide/topics/ui/settings#inflate_the_hierarchy)
  - [x] Create a new preference screen for the logs section
  - [x] Include a new switch preference, a checkbox preference and a simple preference in the new preference screen
  - [x] [Retrieve current values](https://developer.android.com/guide/topics/ui/settings/use-saved-values) to check or not enable logging and HTTP logs.
  - [x] Support navigation and back when logs view is clicked (onActivityResult)
  - [x] Show logs settings only after enabling logging
  - [x] Remove DEBUG logic in the app (logs will start if you enable them from settings, no matter if you use the debug version or release version)
  - [x] Adapt LogHistoryActivity to the new toolbar and move it to presentation package
  - [x] Include UI tests / Unit tests
- [x] Code review and apply changes requested
- [x] Merge branch settings/logs into settings/androidx

### PR

- App
- Library (if needed)

**Comment by JuancaG05** [comment]
Hey, I have a proposal for this issue.
Looking forward to improve the section, I suggest to stop using the 5 clicks to enable the Logs section -maybe it's not as intuitive as it seems-, and instead of that, do something similar to what we are going to do in the [Camera uploads section](https://github.com/owncloud/android/issues/3130#issuecomment-789665455). The result might be something like this:

| Current implementation | Suggestion |
| ---------------------------------------------- | -------------------------------------------- |
| <img width="210" alt ="device-2021-03-11-122924" src="https://user-images.githubusercontent.com/57049315/110783339-969ccc00-8268-11eb-8ecc-bf241a66846b.png"> | <img width="210" alt="Captura de pantalla 2021-03-11 a las 12 43 33" src="https://user-images.githubusercontent.com/57049315/110783374-a87e6f00-8268-11eb-8673-e68c4e340086.png"> |

Then, going into the section, we'll have a new screen in which we can enable or not the logging settings, and which will be reflected from the settings main screen (previous screenshot). The specific settings will appear once logging is enabled:
| Disabled logging | Enabled logging |
| ---------------------------------------------- | -------------------------------------------- |
| <img width="210" alt="Captura de pantalla 2021-03-11 a las 12 45 11" src="https://user-images.githubusercontent.com/57049315/110784026-71f52400-8269-11eb-8fef-89d07678f741.png"> | <img width="210" alt="Captura de pantalla 2021-03-11 a las 12 47 53" src="https://user-images.githubusercontent.com/57049315/110784045-78839b80-8269-11eb-9333-cd08478571bb.png"> |

That way we can create a base for https://github.com/owncloud/android/issues/2887, and also make it look similar to iOS app, so that it's more homogeneous and easier to use for users who work with both apps.

What do you think @michaelstingl @tbsbdr ?

**Comment by jesmrec** [comment]
It's very cool, and IMHO, it's better and more intuitive than the 5-clicks.

The only thing i'd change is the switch in the "Suggestion" screenshot. I'd remove it, so in the next view you will have another one to enable/disable the feature.

**Comment by michaelstingl** [comment]
Nice improvement 👍

**Comment by tbsbdr** [comment]
well tidied 😍

**Comment by JuancaG05** [comment]
Update on the issue: the DEBUG logic for launching logs (they start automatically if you are using the debug version) has been removed. Now, due to the structure change, there's a similar behaviour in the debug and release versions: if you want to enable logging, just turn on the switch in the "Enable logging" settings subsection.
