### ISSUE TITLE
[New arch] Replace old capability operation with use cases

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3108]
**Is your feature request related to a problem? Please describe.**
[SyncCapabilitiesOperation](https://github.com/owncloud/android/blob/7e276f344e0a41fd9547889976e39ed064c5dd99/owncloudApp/src/main/java/com/owncloud/android/operations/SyncCapabilitiesOperation.java) is still used to retrieve capabilities. Those capabilities are stored in the old database. Capabilities were moved to the new architecture, so we should remove this duplicated code and use the new one exclusively.

**Describe the solution you'd like**
Stop using the old operation to retrieve and store capabilities. And use the new use cases as the exclusive source of information.

**Additional context**
We can see in our [FileDataStorageManager](https://github.com/owncloud/android/blob/b8d87d54bad7074b809c2a0767cfd27cf0dbf2c7/owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.kt#L1353) that there are still uses of the old `getCapability` that we should try to replace definitively with new architecture use cases.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Task1...
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)
