### ISSUE TITLE
[FEATURE REQUEST] Lens icon in music player

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3113]
Music player shows the lens icon, that does nothing. I think this has to be removed:

![Screenshot 2021-02-23 at 13 23 54](https://user-images.githubusercontent.com/14894746/108843318-cf874080-75da-11eb-8674-bb6a8d5defc5.png)

### TASKS

- [X] Research (if needed)
- [X] Create branch fix/lens_icon_music_player
- [X] Development tasks
  - [X] Hide search item in menu
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch fix/lens_icon_music_player into master

### PR

- App #3128 
- Library (if needed)
