### ISSUE TITLE
Blank view in music player

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3121]
While the music is reproduced, something should be shown to replace the white background: artwork, cover, a placeholder image...

As first improvement, setting an music icon on the background is enough. Then, we will iterate to improve.

![device-2021-02-23-132712](https://user-images.githubusercontent.com/14894746/108843443-fcd3ee80-75da-11eb-8b66-b9b4d43e3ff5.png)

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/feature_name
- [x] Development tasks
  - [x] Implement icon design
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

PR: https://github.com/owncloud/android/pull/3182

**Comment by theScrabi** [comment]
1, 2, 3 what will it be?

| 1 | 2 | 3|
|-|-|-|
|![1](https://user-images.githubusercontent.com/1891273/110804632-a6c0a580-8280-11eb-8f4e-b99d97f06900.png) |![2](https://user-images.githubusercontent.com/1891273/110804636-a7593c00-8280-11eb-8d96-c28013315212.png) |![3](https://user-images.githubusercontent.com/1891273/110804639-a7593c00-8280-11eb-87ff-b02e09083fd0.png) |

**Comment by michaelstingl** [comment]
@tbsbdr ⬆️

**Comment by jesmrec** [comment]
i like the 2

**Comment by theScrabi** [comment]
Second it is then :)

**Comment by theScrabi** [comment]
Ok so I found out we can already handle coverart. Though it looks a bit weird. The web frontend tries to make coverart rectangular while we just show what we get.
With our permission I would change this to.

| current state | my suggestion |
| ---- | ---- |
| ![Bild_fix](https://user-images.githubusercontent.com/1891273/113008291-34542e80-9177-11eb-8f43-9a086f37cd42.png) |  ![cover_small](https://user-images.githubusercontent.com/1891273/113008323-3a4a0f80-9177-11eb-8521-35e340ffc19d.png) |

What web frontend shows: 
![grafik](https://user-images.githubusercontent.com/1891273/113008534-66fe2700-9177-11eb-8831-a16cf6f5f1d5.png)

**Comment by theScrabi** [comment]
Just a design peak for a possible future solution. This could be implemented with simple draw able overlay and gradients:
![new_art](https://user-images.githubusercontent.com/1891273/113012820-6a93ad00-917b-11eb-9679-cdc16307f191.png)
![new_art_pure](https://user-images.githubusercontent.com/1891273/113012825-6b2c4380-917b-11eb-88d2-a8d84c3dec7a.png)

**Comment by theScrabi** [comment]
I need yet another decisions

| 1 | 2 | 3|
|---|---|---|
|![Clipboard - 7  April 2021 12_41-0](https://user-images.githubusercontent.com/1891273/113854802-92989700-979f-11eb-8a99-288e80958ca5.png) | ![Clipboard - 7  April 2021 12_41-1](https://user-images.githubusercontent.com/1891273/113854803-93312d80-979f-11eb-861e-c19df8f75bc7.png) | ![Clipboard - 7  April 2021 12_41-2](https://user-images.githubusercontent.com/1891273/113854804-93c9c400-979f-11eb-9291-191a430cedfa.png) |

**Comment by LukasHirt** [comment]
> I need yet another decisions

I love the 4th one! 🚀

**Comment by kulmann** [comment]
Agreeing with @LukasHirt on the 4th one! 💪

**Comment by theScrabi** [comment]
Ok I made this. It is 4. But without the overlay and the shadow gradient behind:
![asdf](https://user-images.githubusercontent.com/1891273/113865011-e1e4c480-97ab-11eb-9145-be323291d40e.png)

**Comment by pascalwengerter** [comment]
I don't dislike option 4 too much, but it reminds me of OC10 and we're not using black as a prominent color in owncloud.design - how about something like this?

<img width="357" alt="Screenshot 2021-04-07 at 13 31 05" src="https://user-images.githubusercontent.com/16822008/113866686-844d7980-97a5-11eb-9ee2-fb478ce87673.png">

**Comment by theScrabi** [comment]
Ok here the design with primary color:
![asdf-0](https://user-images.githubusercontent.com/1891273/113873755-61c35c80-97b5-11eb-8c4e-b2b527d68ff1.png)
