### ISSUE TITLE
Kotlinize PrivacyPolicyActivity

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3129]
Since we are refactoring Settings and this activity is pretty related, we can convert it to kotlin, move it to the presentation package, and update the test to `ActivityScenario` (Currently we use `ActivityTestRule`, which is deprecated)

### TASKS

- [x] Research (if needed)
- [x] Create branch settings/privacypolicyactivity
- [x] Development tasks
  - [x] Rename `PrivacyPolicyActivity` so that we can create a new Kotlin class called like that
  - [x] Move Java code to Kotlin code
  - [x] Update references to the activities (intents, imports...)
  - [x] Update UI tests
- [x] Code review and apply changes requested
- [x] Merge branch settings/privacypolicyactivity into settings/androidx

### PR

- App
- Library (if needed)

**Comment by JuancaG05** [comment]
Finally instead of moving from `ActivityTestRule` to `ActivityScenario`, we moved to `ActivityScenarioRule`, which is simpler but enough for the tests here
