### ISSUE TITLE
[Android X Preference] Camera uploads section

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3130]
### AC

- It is placed  just below the `Logging` section

- Two different sections: one for photos, another one for videos. They can be enabled/disabled by separate

- Every section will have four settings related:
   - Picture/Video upload path: the target folder where the pictures/videos will be uploaded
   - Upload pictures/videos via wifi only: check to decide whether... 
   - Camera folder (required): the place where the pictures/videos will be caught
   - Original file will be: two options here: kept or moved to app folder
   
- Those subsection will be always visible. If they are disabled, will be appear as greyed out

- Enabling camera uploads will show an alert to warn users about the camera folder and the delay

- Disabling camera uploads will ask for confirmation

### TASKS

- [x] Create branch settings/camera_uploads
- [x] Development tasks
  - [x] Create structure and navigation in XML files
  - [x] Adapt functionality to the new "Picture uploads" subsection
  - [x] Adapt functionality to the new "Video uploads" subsection
  - [x] Create new preferences to distinguish the common preferences ("camera folder" and "original file will be" preferences)
  - [x] Try to unify wording with the iOS app
  - [x] Unit tests
  - [x] UI tests
- [x] Code review and apply changes requested
- [x] Merge branch settings/camera_uploads into settings/androidx

### PR

- App
- Library (if needed)

**Comment by abelgardep** [comment]
About this one, we can discuss it a little bit.

When camera uploads are enabled there are a lot of options and they could be confusing. We could add a new view for each option to choose the configuration separately. I think it will be easier to understand what's going on.

| Current implementation | Suggestion |
| ---------------------------------------------- | -------------------------------------------- |
| ![Screenshot 2021-03-03 at 12 53 48](https://user-images.githubusercontent.com/47524927/109802269-e1429680-7c1f-11eb-9b0a-157a41351160.png) | ![Screenshot 2021-03-03 at 12 48 45](https://user-images.githubusercontent.com/47524927/109802335-f5869380-7c1f-11eb-91f3-2cc14b5c9b67.png) |

**Comment by michaelstingl** [comment]
@tbsbdr opinion? ⬆️

**Comment by JuancaG05** [comment]
Update on the issue: regarding the old settings version, in the new one the common options until now (that is, "Camera folder" and "Original file will be" preferences) will be differentiated, so that Picture uploads has its own and Video uploads too. Also, when the main preference in this case (Picture uploads or Video uploads) is not enabled, the related settings will be greyed-out instead of hidden as it happened in the old version.

**Comment by abelgardep** [comment]
> Update on the issue: regarding the old settings version, in the new one the common options until now (that is, "Camera folder" and "Original file will be" preferences) will be differentiated, so that Picture uploads has its own and Video uploads too. Also, when the main preference in this case (Picture uploads or Video uploads) is not enabled, the related settings will be greyed-out instead of hidden as it happened in the old version.

Taking this into account, we need to discuss the expected behaviour. Should we reset the camera upload configuration in the next version? 

Pros: Easier for us to develop and users will configure the new camera uploads properly.
Cons: Users will need to enable and configure camera uploads again.

This could be linked to https://github.com/owncloud/android/issues/3199 If we reset the camera uploads configuration, the users will need to configure it again (including a new option to select the account that enabled them). If not, we will need to decide what to do with it.

**Comment by michaelstingl** [comment]
> Should we reset the camera upload configuration in the next version?

I think it's okay, if we don't require it too often. Doing it with #3199 together would make sense.
