### ISSUE TITLE
[RELEASE] 2.17_oem

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3133]
### TASKS:

- [x] [GIT] Create and sign tag `oc-android-2.17_oem` in HEAD commit of `release_2.17_oem` branch or 2.17 commit (depending on if there's new changes or not), in owncloud/android
- [x] Approve and merge changes in ownBrander (upgrade version)
- [x] [DIS] Deploy and block button
- [x] [QA] Generate final APKs files from signed commit in builder machine  and perform some basic operations 
- [x] [DIS] Enable button

_____

### PR
- App: 

### BUGS & IMPROVEMENTS
