### ISSUE TITLE
[FEATURE REQUEST] Use new extensions in the whole project

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3138]
New Activity extensions were added in https://github.com/owncloud/android/pull/3136 to avoid code repetition. We realized these extensions could be used in some other parts of the project and that way get a more consistent code, so that's the aim of this issue.

### TASKS

- [ ] Research (if needed)
- [ ] Create new branch
- [ ] Development tasks
  - [ ] Search for replaceable code with these extensions, and adapt it
- [ ] Make sure all the tests keep passing
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by JuancaG05** [comment]
The objective here is to replace in the whole code some Intents creations by a call to these new extensions, so that everything is more unified. We might have to add some other simple extensions, depending on the way Intents are created and which properties are set, but doesn't seem too complex at first sight

**Comment by jesmrec** [comment]
QA -> open web views in browsers. open mail app ...

**Comment by jesmrec** [comment]
QA checks

- [x] OAuth2 auth
- [x] OIDC auth
- [x] Settings > More > Help
- [x] Settings > More > Davx5
- [x] Settings > More > Feedback
- [x] Settings > More > Recommend
- [x] Settings > More > Privacy policy

**Comment by jesmrec** [comment]
Approved on my side
