### ISSUE TITLE
[FEATURE REQUEST] Refactor tests for More and Security settings sections

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3148]
### EPIC: https://github.com/owncloud/android/issues/2867

Tests currently pass, but there are some improvements that can be applied to the code.

### TASKS

- [x] Create branch settings/refactortests
- [x] Development tasks
  - [x] Check if current flaky tests for "More" section pass in bitrise with the delay added (they do!!)
  - [x] Use `verifyPreference` extension created in Logs section issue (https://github.com/owncloud/android/issues/3101) to simplify tests code
  - [x] Try to use `mockIntent` utils function in More section tests, the same way as in Security section tests
  - [x] Adapt the `(setting)NotEnabledView` test methods, right now they're useless. Create a getter and test whether they are actually displayed or not
  - [x] Remove `mockk(relaxed = true)` and use `mockk(relaxUnitFun = true)` instead when possible
- [x] Code review and apply changes requested
- [x] Merge branch settings/refactortests into settings/androidx

### PR

- App
- Library (if needed)
