### ISSUE TITLE
[FEATURE REQUEST] Organize settings by subsections

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3153]
### EPIC: https://github.com/owncloud/android/issues/2867

Based on other apps' design, we propose some changes to the whole Settings menu. All settings are currently being updated to AndroidX (https://github.com/owncloud/android/issues/2867), so it would be suitable to address this issue now.

The idea is to group the different preferences by subsections that drives the user to other screens/fragments. This would make navigation through settings easier, since the users would find whatever they're looking for in a simpler and hierarchical way. Moreover, it makes it easily expansible if we want to add more settings in the future. Code would look cleaner and tests would be easier too.

Here's a prototype of the final result:

![device-2021-03-18-132323](https://user-images.githubusercontent.com/57049315/111625491-302a2780-87ed-11eb-956a-ad48b089eb7e.png)

Then, each item would go to a screen with its respective preferences, respecting the original ones (such in this issue https://github.com/owncloud/android/issues/3101#issuecomment-796688422, we move preference items to a new screen).

It's an open discussion, you can give your opinion and please discuss the following points:
- Would you place a divider line between "Picture uploads" and "Video uploads"? Currently it's not placed as they belong to the same category, but it may create confusion. Other option is to delete all those lines, please let me know what do you think about it.
- The "Enable logging" (now always visible) could maybe be moved to the end, just below "More", as it is something that only a certain segment of users will use. What do you think?

### TASKS

- [x] Create branch settings/subsections
- [x] Development tasks
  - [x] Make "Enable logging" section items disable instead of hide when the switch is off 
  - [x] Move "Security" section preferences to a new fragment
  - [x] Move "More" section preferences to a new fragment
  - [x] Move "App version" item to the general settings menu, and make it copy-able by a simple tap
  - [x] Try to unify wording with the iOS app
  - [x] Adapt existent UI tests (now they belong to different fragments)
  - [x] Create UI tests for the general settings screen
- [x] Code review and apply changes requested
- [x] Merge branch settings/subsections into settings/androidx

### PR

- App
- Library (if needed)

**Comment by JuancaG05** [comment]
@abelgardep @jesmrec @theScrabi @michaelstingl @tbsbdr opinion on this?

**Comment by abelgardep** [comment]
I like it. I would try to unify some common wording with iOS by the way. 👍

**Comment by michaelstingl** [comment]
> @abelgardep @jesmrec @theScrabi @michaelstingl @tbsbdr opinion on this?

Nice 👍 

Yes, if possible, align sections and naming with iOS team /cc @hosy Look & feel can stay Android-like of course.

**Comment by hosy** [comment]
Yeah, very cool! Yes, would be cool to have a same structure like in the iOS app, but please with Android-like look and feel.

**Comment by tbsbdr** [comment]
nice! 

if "more" expands like in the latests Android 11 settings, then I would suggest a caret-down icon (screenshot) so that it is not misunderstood with "add" iconography. but i guess this is not the point here ;-)
  
![Screenshot_20210318-151305_2](https://user-images.githubusercontent.com/26610733/111640952-f8c37700-87fc-11eb-9c8d-25eb111c2d57.png)

**Comment by JuancaG05** [comment]
> nice!
> 
> if "more" expands like in the latests Android 11 settings, then I would suggest a caret-down icon (screenshot) so that it is not misunderstood with "add" iconography. but i guess this is not the point here ;-)
> 
> ![Screenshot_20210318-151305_2](https://user-images.githubusercontent.com/26610733/111640952-f8c37700-87fc-11eb-9c8d-25eb111c2d57.png)

Well, the idea is not that it expands, but drives to another screen. Anyway, we can look for another and maybe more suitable icon 😁 .

**Comment by JuancaG05** [comment]
Update in the issue: the "About app" item, previously located in the "More" section, now will be in the main settings screen together with the subsections, at the bottom. Moreover, now with a long tap we'll have the summary of the preference (which contains app name, variant, version and commit) copied in clipboard.
