### ISSUE TITLE
Set a fixed account to execute "Camera Uploads" (fix current behaviour && add new UI options)

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3166]
Actually, camera uploads store the taken pictures in the active account. In case there are more that one account in the app, every upload will be stored in the active account at this moment, causing a fragmentation. 

then, this would be the new expected behaviour:

- When picture/video camera uploads are enabled, user will have to select an account as target. If user has only one, we can skip this step and select automatically that one. It should be shown in the Camera upload section as a new cell/row to select.

- The account can be switched to any other one in any moment, as every setting

- If the user removes the selected account from account manager:
   - If there is no remaining accounts in the device -> Camera uploads disabled and all fields reset. Camera uploads hidden.
   - If there are more remaining accounts in the device -> Camera uploads disabled and all fields reset. Camera uploads visible. N2H: let user know that the account is the Camera upload to make a decision before removing. This is open to discussion.

- Migration: users that upgrade from previous version and have the camera uploads enabled, should keep the feature enabled and set as target account the current active (feasible?). Also, open to discussion -> No migration!! settings from scratch-> WARN MARKETING/COMMUNICATION TEAM!! IMPORTANT!!!!

- https://github.com/owncloud/android/issues/3199

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/camera_uploads_fixed_account
- [x] Development tasks
  - [x] Add a new list preference to select account in picture upload subsection
  - [x] Add a new list preference to select account in video upload subsection
  - [x] Reset fixed account and upload path after disabling picture uploads
  - [x] Reset fixed account and upload path after disabling video uploads
  - [x] Use the saved account in picture and video upload
  - [x] Show a dialog to warn user that removing the account will disable camera uploads
  - [x] Reset camera uploads after removing the fixed account
  - [x] Adapt UI tests
  - [x] Adapt unit tests
- [x] Code review and apply changes requested
- [ ] Design test plan [WIP]
- [ ] QA
- [ ] Merge branch feature/camera_uploads_fixed_account into master

### PR

- App https://github.com/owncloud/android/pull/3226
- Library (if needed)

**Comment by abelgardep** [comment]
At the moment we try to use a fixed account that will trigger the camera uploads. The point here is that we should use the fixed account instead of the current one. https://github.com/owncloud/android/blob/498aff7c223bb7e0cf5246a9e56f0d1238d2aa36/owncloudApp/src/main/java/com/owncloud/android/db/PreferenceManager.java#L110-L115

**Comment by jesmrec** [comment]
so, with such implementation we could go ahead without changing the Settings implementation perspective (to settings for account, as discussed).

**Comment by abelgardep** [comment]
We could just add a new preference to show the account that enabled the camera uploads.
