### ISSUE TITLE
[FEATURE REQUEST] Divide SettingsViewModel into several ViewModels

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3175]
Now that we have several screens/fragments for the settings with the new structure by subsections, we should divide as well the ViewModel that all of them still use, `SettingsViewModel`, into several ViewModels (one per subsection), so that we reduce dependencies and we only have in each class the functions of the ViewModel that we want.

### TASKS

- [x] Create branch settings/divide_viewmodels
- [x] Development tasks
  - [x] Create new ViewModels classes, one for each current subsection: `SettingsSecurityViewModel`, `SettingsLogsViewModel` and `SettingsMoreViewModel`
  - [x] See which dependencies (logsProvider, preferencesProvider...) each of them need and add them to the constructor of the corresponding ViewModels
  - [x] Move methods from `SettingsViewModel` to the new ViewModels
  - [x] Make fragments reference the new corresponding ViewModels instead of the old `SettingsViewModel` and delete the old one
  - [x] Manage dependency injection for the new ViewModels
  - [x] Adapt unit tests
  - [x] Adapt UI tests (ViewModel was mocked)
- [x] Code review and apply changes requested
- [x] Merge branch settings/divide_viewmodels into settings/androidx

### PR

- App #3178 
- Library (if needed)

**Comment by abelgardep** [comment]
Merged via #3178
