### ISSUE TITLE
[RELEASE] 2.18

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3197]
### TASKS:

 - [x] [DIS] Warn marketing about camera uploads reset in new version
 - [x] [DEV] Add wording to new wizard, in order to be translated [#3227]
 - [x] [GIT] Create branch release/1.0.11 in owncloud/android-library from master
 - [x] [GIT] Create branch release/2.18 in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudComLibrary module
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create a folder for the new version 2.18.0_2021-05-18
 - [x] [DIS] Move all changelog files from the unreleased folder to the new version folder
 - [x] [DIS] Update screenshots, if needed, in README.md [Not needed]
 - [X] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [DIS] Generate test APK file from `release/2.18` branch in owncloud/android
 - [x] [GIT] Create and sign tag 'oc-android-2.18' in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Create and sign tag '1.0.11' in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Generate final APKs from signed commit in owncloud/android
 - [ ] [COM] Inform `#release_coordination` and `#marketing` in internal chat
 - [ ] [GIT] Merge branch `release/1.0.11` in owncloud/android-library, into master
 - [ ] [GIT] Merge branch `release/2.18` in owncloud/android, into master
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [ ] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [ ] [GIT] Publish a new release in owncloud/android
 - [x] [DIS] Upload release APK to internal owncloud instance
 - [ ] [GIT] Merge master branch into stable, in owncloud/android-library
 - [ ] [GIT] Merge master branch into stable, in owncloud/android
 - [ ] [DOC] Update owncloud.org/download version numbers (notify rocketchat #marketing)

_____
### PR
App: #3243 
Library: https://github.com/owncloud/android-library/pull/405
_____

### QA

Regression test: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.18/Regression.md

BUGS & IMPROVEMENTS:

**Comment by jesmrec** [comment]
Last-hour bug to be fixed.

**Comment by jesmrec** [comment]
Fix for the [last reported bug](https://github.com/owncloud/enterprise/issues/4579), affecting only streaming feature, that works fine after checking the fix
