### ISSUE TITLE
[FEATURE REQUEST] Error handling for pattern lock

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3215]
Due to the recent change in error handling for passcode lock (https://github.com/owncloud/android/issues/2722), in which we replaced the snackbars that displayed the error message with a new TextView with the error message (https://github.com/owncloud/android/issues/2722#issuecomment-826552591), it would be suitable to perform the same changes for pattern lock altough we don't have those visibility problems here, since they are analogous preferences. The cases are the same than for passcode lock:

#### Case 1
1. Open Settings > Pattern lock
2. Enter pattern
3. In the 2nd try, enter a different pattern

#### Case 2
1. Register a pattern correctly
2. Close the app
3. Open the app and enter an incorrect pattern

#### Case 3
1. Register a pattern correctly
2. Go to Pattern lock to try to remove the current pattern
3. Enter an incorrect pattern

### TASKS

- [x] Create branch feature/pattern_errors
- [x] Development tasks
  - [x] Add a new TextView to the XML file
  - [x] Replace Snackbar creation by printing a message in the TextView
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch fix/pattern_errors into master

### PR

- App #3221 
- Library (if needed)
