### ISSUE TITLE
[Improvement] Hide biometrical if device does not support it

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3217]
Current behaviour: If the device does not support biometrical lock, the Setting is displayed and when it is clicked, an snackbar appears with the proper error

Desired behaviour: If the device does not support biometrical lock, the Setting is hidden.

### TASKS

- [x] Create branch feature/hide_biometrics
- [x] Development tasks
  - [x] Change Snackbar with error by hiding directly the biometrics preference
  - [x] Adapt UI tests if there are some related with this
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/hide_biometrics into master

### PR

- App #3230 
- Library (if needed)
