### ISSUE TITLE
[TECHNICAL] Upgrade min SDK to Android 6 (v23)

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3245]
**Additional context**
At the moment our min SDK version is Android **5** (v21) and I think that it could be time to upgrade to Android **6** (v23) taking into account that Android **12** (v31) will be released this year, and it is already in beta.

According to AS, this is the current distribution (it may not be updated since Android11 is not there 🤔 ):

![Current android distribution](https://user-images.githubusercontent.com/47524927/118771814-44d57b00-b883-11eb-9b95-5a39ac78da2c.png)

### TASKS

- [x] Research (if needed)
- [x] Create branch technical/min_sdk_23
- [x] Development tasks
  - [x] Update `sdkMinVersion` to 23
  - [x] Make necessary changes in code and remove deprecated one
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch technical/min_sdk_23 into master

**Comment by jesmrec** [comment]
April 2022

https://gs.statcounter.com/os-version-market-share/android

Android 5 under 2% of global users.
