### ISSUE TITLE
[RELEASE] 2.18_oem

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3249]
### TASKS:

- [X] [GIT] Create branch `oc-android-2.18_oem` in HEAD commit of `release_2.18_oem` branch or 2.18 commit (depending on if there's new changes or not), in owncloud/android
- [x] Approve and merge changes in ownBrander (upgrade version)
- [x] [DIS] Deploy and block button
- [x] [GIT] Sign tag `oc-android-2.18_oem`
- [x] [QA] Generate final APKs files from signed commit in builder machine  and perform some basic operations 
- [x] Checks to do in ownBrander:
   - Music player note icon gets the main color of the app -> https://github.com/owncloud/android/issues/3249#issuecomment-852009193
   - `Settings` link on login view gets the font color of the URL field ✅ 
   - Settings view branded fields:
        - help_enabled    ✅ 
        - url_help ✅ 
        - imprint_enabled ✅ 
        - url_imprint ✅ 
        - recommend_enabled ✅ 
        - feedback_enabled ✅ 
        - mail_feedback ✅ 
        - privacy_policy_enabled ✅ 
        - url policy  ✅ 
- [x] [DIS] Enable button

_____

### PR
- App: 

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
Two small issues to comment:

1. When all the items inside the `More` section are branding-disabled (help, feedback, recommend, privacy policy, imprint), a blank screen is displayed. In that case, the `More` section should be hidden

2. The placeholder image in the music player is now brandable, but not under any parameter in oB. It was branded [here](https://github.com/owncloud/android/tree/master/owncloudApp/src/main/res/drawable/ic_place_holder_music_cover_art.xml) (let me know if i'm wrong). It is set as a `@color` but the list of colors is not brandable itself, it should be used under a parameter of `setup,xml`, the brandable file (i guess `primary_button_background_color` )

Both issues are not blockers and will not affect the app (only esthetic). If you agree, we can address in new tickets to be fixed in the following release CC @michaelstingl @abelgardep  

OTOH, basic checks done and passed

**Comment by michaelstingl** [comment]
> Both issues are not blockers and will not affect the app (only esthetic). If you agree, we can address in new tickets to be fixed in the following release CC @michaelstingl @abelgardep

Works for me 👍

**Comment by jesmrec** [comment]
approved on my side. Will create the issues.

**Comment by jesmrec** [comment]
Release done
