### ISSUE TITLE
[FEATURE REQUEST] Move bitrise.yml to here, so that it could be checked externally

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3252]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Push bitrise.yml here
  - [ ] Make actions in bitrise to use the GH yml file
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)
