### ISSUE TITLE
[RELEASE] 2.18.1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3282]
This release is intended to fix a problem related with the folder picker for the camera source in auto uploads, affecting users with specific vendor/model devices.

The issue is https://github.com/owncloud/android/issues/2899

By the way, that feature needed to complete the [Scope Storage implementation](https://github.com/owncloud/android/issues/2877), expected for following releases

### TASKS:

 - [x] [GIT] Create branch release/1.0.12 in owncloud/android-library from master
 - [x] [GIT] Create branch release/2.18.1 in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudComLibrary module
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create a folder for the new version like 2.18.1_2021-07-20
 - [x] [DIS] Move all changelog files from the unreleased folder to the new version folder
 - [x] [DIS] Update screenshots, if needed, in README.md
 - [x] [QA] Design Test plan
 - [x] [QA] Regression checklist
 - [x] [DIS] Generate test APK file from `release/2.18.1` branch in owncloud/android
 - [x] [GIT] Create and sign tag 'oc-android-2.18.1' in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Create and sign tag '1.0.12' in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Generate final APKs from signed commit in owncloud/android
 - [ ] [COM] Inform `#release_coordination` and `#marketing` in internal chat
 - [ ] [GIT] Merge branch `release/1.0.12` in owncloud/android-library, into master
 - [ ] [GIT] Merge branch `release/2.18.1` in owncloud/android, into master
 - [ ] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [ ] [GIT] Publish a new release in owncloud/android
 - [ ] [DIS] Upload release APK to internal owncloud instance
 - [ ] [GIT] Merge master branch into stable, in owncloud/android-library
 - [ ] [GIT] Merge master branch into stable, in owncloud/android
 - [ ] [DOC] Update owncloud.org/download version numbers (notify rocketchat #marketing)

_____
### PR
App: https://github.com/owncloud/android/pull/3312
Library: https://github.com/owncloud/android-library/pull/420
_____

### BUGS & IMPROVEMENTS

- [X] (1) Crash sharing just after attaching account https://github.com/owncloud/android/issues/3282#issuecomment-881237583  [FIXED]

**Comment by jesmrec** [comment]
### QA

Short release, the whole regression test will not be executed.

The following checklist to be executed as QA for 2.18.1

- [X] OAuth2 create session and renewal
- [X] OIDC create session
- [X] PKCE connections -> https://github.com/owncloud/enterprise/issues/4668#issuecomment-879753951
- [ ] Welcome text  
- [ ] Camera uploads sanity test
- [ ] Videostreaming (exoplayer bump)
- [ ] Automatic tests E2E
- [ ] Upgrade test from 2.18 -> check welcome text & camera uploads setup

**Comment by jesmrec** [comment]
### (1)

1. Install 2.18.1 from scratch
2. Add an account
3. Select an item and `Share` option

Current: app crashes with the following stacktrace. It only happens if the item is shared just after attaching the account (something is being initialized?). By waiting some seconds, crash not happens. 

```
2021-07-16 09:15:07.662 20580-20580/com.owncloud.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.owncloud.android.debug, PID: 20580
    java.lang.NullPointerException: ocCapabilityEntity must not be null
        at com.owncloud.android.data.capabilities.datasources.implementation.OCLocalCapabilitiesDataSource.getCapabilitiesForAccountAsLiveData$lambda-0(OCLocalCapabilitiesDataSource.kt:37)
        at com.owncloud.android.data.capabilities.datasources.implementation.OCLocalCapabilitiesDataSource.lambda$yzDD0aPXNwsE-cMu7Cm1HYoMC8Q(Unknown Source:0)
        at com.owncloud.android.data.capabilities.datasources.implementation.-$$Lambda$OCLocalCapabilitiesDataSource$yzDD0aPXNwsE-cMu7Cm1HYoMC8Q.apply(Unknown Source:2)
        at androidx.lifecycle.Transformations$1.onChanged(Transformations.java:76)
        at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Expected: no crash


Pixel2 v11
Nexus 6P v7
`1f57fd060`

**Comment by jesmrec** [comment]
Version is approved on my side.

Approved commits: 

app: `1ac962cf`
library: `7b5c0701`

IDE version: Android Studio 4.2.2

Devices: Pixel2 Android11, Nexus6P Android 7
