### ISSUE TITLE
[RELEASE] 2.18.1_oem

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3313]
### TASKS:

- [x] [GIT] Create and sign tag `oc-android-2.18.1_oem` in HEAD commit of `release_2.18.1_oem` branch or 2.18 commit (depending on if there's new changes or not), in owncloud/android
- [x] Approve and merge changes in ownBrander
  - [x] Upgrade version 
  - [x] https://github.com/owncloud/ownbrander/issues/985
  - [x] https://github.com/owncloud/ownbrander/issues/987
- [x] [DIS] Deploy and block button
- [x] [QA] Generate final APKs files from signed commit in builder machine  and perform some basic operations 
- [x] [QA] Check that bundle is correctly generated and apk family could be installed in device from bundle
- [x] [DIS] Enable button

_____

**Comment by jesmrec** [comment]
Release done
