### ISSUE TITLE
[RELEASE] 2.19

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3325]
### TASKS:

 - [x] [GIT] Create branch release/1.0.13 in owncloud/android-library from master
 - [x] [GIT] Create branch release/2.19 in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudComLibrary module
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create a folder for the new version like 2.19.0_YYYY-MM-DD
 - [x] [DIS] Move all changelog files from the unreleased folder to the new version folder
 - [x] [DIS] Update screenshots, if needed, in README.md
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [QA] Test pending stuff with Scoped Storage -> https://github.com/owncloud/android/pull/3336#issuecomment-894075798
 - [x] [DIS] Generate test bundle from `release/2.19` branch in owncloud/android
 - [x] [GIT] Create and sign tag 'oc-android-2.19' in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Create and sign tag '1.0.13' in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [ ] [COM] Inform `#release_coordination` and `#marketing` in internal chat
 - [ ] [GIT] Merge branch `release/1.0.13` in owncloud/android-library, into master
 - [ ] [GIT] Merge branch `release/2.19` in owncloud/android, into master
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [GIT] Publish a new release in owncloud/android
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - [ ] [GIT] Merge master branch into stable, in owncloud/android-library
 - [ ] [GIT] Merge master branch into stable, in owncloud/android
 - [ ] [DOC] Update owncloud.org/download version numbers (notify rocketchat #marketing)

_____

### QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.19/Regression%202.19.md

BUGS & IMPROVEMENTS:

- [x] https://github.com/owncloud/android/issues/3362 (regression)
- [x] (1) Change wording in wizard https://github.com/owncloud/android/issues/3325#issuecomment-960656573 [DONE]
- [x] (2) Progress bar in wizard https://github.com/owncloud/android/issues/3325#issuecomment-960657681 [WONT FIX]
- [x] (3) More section can be empty https://github.com/owncloud/android/issues/3325#issuecomment-961874379 [FIXED]
- [x] (4) Button is cut off in welcome wizard https://github.com/owncloud/android/issues/3325#issuecomment-961878713. [FIXED]
- [x] (5) Logs collected with option disabled https://github.com/owncloud/android/issues/3325#issuecomment-961903205 [FIXED]
- [x] (6) Leftovers when migration is done when file is copied to /tmp https://github.com/owncloud/android/issues/3325#issuecomment-963111202 [FIXED]
- [X] (7) Migration with reduced space https://github.com/owncloud/android/issues/3325#issuecomment-965619583 [FIXED]

### PR
App: #3436
Library: https://github.com/owncloud/android-library/pull/441

**Comment by jesmrec** [comment]
### (1)

Scoped Storage Wizard: in last slide, using `Access your files` instead of `Close`

**Comment by jesmrec** [comment]
### (2)

Scoped Storage Wizard: check if adding a meaningful progress bar is feasible

**Comment by jesmrec** [comment]
### (3)

1. Set the following values in `setup.xml`:

```
    <bool name="help_enabled">false</bool>
    <bool name="sync_calendar_contacts_enabled">false</bool>
    <bool name="imprint_enabled">false</bool>
    <bool name="recommend_enabled">false</bool>
    <bool name="feedback_enabled">false</bool>
```
2. Open the app > Settings > More

Current: Empty

Expected: `More` section is hidden because al its content is hidden. After moving the privacy policy link from there, it should be removed from the `More` visibility condition as well

Pixel2 Android11
`214c3800c`

**Comment by jesmrec** [comment]
### (4)

This one comes from https://github.com/owncloud/android/issues/3351

In landscape mode, the new button is cut off:

![device-2021-11-05-140237](https://user-images.githubusercontent.com/14894746/140514616-20f20f5a-0ef2-4c49-a71d-f54fcf5ea49a.png)

**Comment by jesmrec** [comment]
### (5)

1. Go to `Settings` > `Logging` > `Enable Logging`
2. Perform some actions in the app, so that the log file will have content
3. Go to `Settings` > `Log files` and remember the log file size
4. Disable Logging
5. Perform more actions in the app
6. Go to `Settings` > `Log files` and check the log file size

Current: file size in 6. is higher that in 3.  That means that logs are being collected.

Expected: file size in 6. should be the same as in 3.  Logs are disabled, so no new logs should be collected 

Pixel2 Android11
`214c3800`

**Comment by jesmrec** [comment]
### (6)

Check this scenario out:

1. Select a big file with oC, using the sharing sheet
2. While the file is being copied to /tmp before performing the upload, migration is executed

Current: /tmp folder is copied to scoped storage, including part of the copied file that was interrupted by the migration. But, the primary action (share with oC) is not resumed.

Things to consider:

- Is it correct that such action or other similars (pending to copy local files to `owncloud`) are not done as uploads?
- Any way to wipe the lost piece of files?

Pixel2 Android11
`214c3800`

**Comment by jesmrec** [comment]
about (6), three cases checked:

- [X] Sharing a big file + migration = tmp clean
- [X] Sharing a big file + uploads ongoing = tmp with uploads + tmp with no shared file fragments
- [x] Sharing a files + upload in different accounts + migration = uploads OK + tmp cleaned of pending shares

**Comment by jesmrec** [comment]
### (7)

I stumbled upon this problem, similar to one we faced some days ago

With 9 GB space free in device:

1. Install 2.18.3
2. Downloaded a files of 5GB and 5 files of 100MB (~5.5 GB) -> ~4.5GB left in device
3. Migration

Current: Migration ends but nothing is downloaded

Expected: All 100MB files are dowloaded. 5GB file is not dowloaded because there is no space left to copy it

`fec4585e`
Nexus 6P v7

**Comment by jesmrec** [comment]
Release 2.19 is approved and ready to go:

Approved commits:

- App: `c1ea0594`
- Library: `20efe90e`
- IDE version (Android Studio): `Arctic Fox 2020.3.1 Patch 1`
- Devices: Pixel2 (Android11), Nexus 6 (Android7), Huawei P20L (Android9) 
- E2E tests report: 
[2.19.zip](https://github.com/owncloud/android/files/7519911/2.19.zip)
[scenarios](https://github.com/owncloud/android-scenario-testing/tree/master/src/test/resources/io/cucumber)

Other comments:

- About Scoped Storage migration:

    - If migration happens meanwhile an upload is running, upload stops and stays in the uploads view. It will have to be retried manually in the uploads view by using the retrying actions. At the end, file is pushed to the server and local copy exists inside the scoped storage.

    - If migration happens meanwhile a file is being shared with oC before starting the upload, it will not be retried, and it will be cleaned up from temporary internal folder. Sharing action will have to be done again after the updating process. For this reason, is totally recommended not to have pending actions like this one just before doing this update. Recommended to forward this to customers.

    - Files are migrated from legacy storage to scoped storage one by one. Once one file is copied to the scoped storage, then is removed from legacy storage. That means, if the free space in the device is less than a file size, this file will not be migrated. It will have to be downloaded again manually by the user, once the device has enough free space to host it.

    - We were suggested to replace the flashing bar for a progress bar that shows the user the current % of migration done and left (check [report (2)](https://github.com/owncloud/android/issues/3325#issuecomment-960657681)). We discard this option because the migration process is the sum of different subprocesses (not only copying files). We can not control all of them in the same progress bar without including an extra complexity that leads to extra testing. Given the migration does not take very long (Pixel2 of 2017 takes less than 2 minutes to move 10GB), users will not have to wait long times till the process finishes, so the process will not require much patience to be calmed down with an explicit progress bar.

Thanks a lot for the great effort team!!!
