### ISSUE TITLE
[FEATURE REQUEST] Scoped Storage Migration from legacy storage

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3327]
**Is your feature request related to a problem? Please describe.**

What to do when users will upgrade to Scoped Storage. 

**Describe the solution you'd like**

A Wizard will guide them through the process.
Finally, they will decide if they want to remove the old folder by themselves, or the app will do it.
Pending uploads to be migrated

**Describe alternatives you've considered**

**Additional context**

- When user upgrades to 2.19, stuff to migrate:
  - Pending uploads migration: Sharing with oC, manual uploads, Document provider (over temporal folder).
  - Check one for one pending uploads, whether they are on external storage. 
  - Move files to ScSt and queue them (are they directly uploaded?) 

Create Wizard with some slides. NO SKIP OPTION
   - What ScSt is, quick description for users to understand what is it about
   - Advantages of Scoped Storage
   - Warning: all av offline stuff will be directly downloaded in some seconds. Not sure if tell user this... he/she can do nothing.
   - Migration

Check when and where, the options will be displayed to let user decide.

Ask user whether legacy storage is deleted or not. Be clear with the consequences of every option
   - If "yes" -> owncloud legacy removed from device
   - If "not"  -> owncloud legacy folder remains. Let him know what happens there...

### TASKS

- [x] Research (if needed)
- [x] Create branch scoped_storage_migration
- [ ] Development tasks
  - [x] Implement the designs for the migration
  - [x] Create logic to show or not the migration wizard
  - [x] Implement the viewmodel logic
  - [x] Implement the navigation inside the wizard
  - [x] Show how many files and Gb are going to be migrated and a time estimation
  - [x] Migrate files from legacy storage to scoped storage
  - [ ] Update database with the new path for already downloaded files
- [ ] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch scoped_storage_migration into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
Suggestion for the slides:

1. A new way for storing your files in Android
2. All your files locally stored will be locked up and no longer available from outside the app.
3. They will be only accessed by the Android system, no by other apps.
4. You will be asked what to do with the legacy storage
5. You can choose: remove automatically (we will take care), or do it by yourself
6. This new feature will add more security to your files locally stored.

**Comment by jesmrec** [comment]
QA checks

- [ ] Upgrade from 2.18.1 -> wizard displayed, no skip option, user asked to remove the legacy
- [ ] Upgrade from 2.18.1 -> user selects to remove the legacy automatically. owncloud folder removed
- [ ] Upgrade from 2.18.1 -> user selects to remove the legacy manually. nothing happens
- [ ] Upgrade from 2.18.1 -> pending uploads are migrated and finish correctly
- [ ] Upgrade from 2.18.1 -> no pending uploads -> nothing to migrate
- [ ] Fresh install -> no wizard, no asking user for migration

**Comment by michaelstingl** [comment]
Examples:
https://www.samsung.com/global/galaxy/apps/smart-switch/
https://mobiletrans.wondershare.com/app/wondershare-wutsapper.html

![IMG_5090](https://user-images.githubusercontent.com/214010/129860890-4921923b-4a6c-4334-9bc8-ba3de0692432.PNG)

**Comment by tbsbdr** [comment]
## Context
- Users of the ownCloud Android App >= v. 2.19 must perform a migration from legacy storage to scoped storage.
- the user must have the freedom to decide, when the migration should take place (no forced migration at app-start, there is always an exit option)
- if the migration had not been done, the user must be reminded to perfom the migration
- the user must be informed about the pros and cons of the migration
- the user must be informed about how long the migration will take time (round about - expecation management). 
- the migration promt is only shown, if there if the battery is charged enough (at xx% ) - maybe needs also to be explained.


## Starting Points
- After update (last slide on the "whats new" wizard)
- After 24 hours
- from within the settings

## Userflow draft (no design!)
https://www.figma.com/file/PscVEHRqfmVcQck7BiLbhu/Scoped-Storage-Assistant?node-id=0%3A1

**Comment by tbsbdr** [comment]
## Outcome of our discussion today

We have 2 choices how to proceed ( but don't know yet what is the best for the user and in terms of cost-effectiveness)

1. **No dismiss:** Automatically start the migration at first run after the update
2. **Dismiss:** give the user a choice, when the migration should be done

## Next steps
=> We'll implement the migration and  will check in a min stresstest how long it takes for a 5G Motorola mid-low-end device to migrate 8GB. If it takes < 2 mins, we'll go with option 1 "no dismiss" from above (we then accept, that we force users to wait until migration is done and block them from using the app)

## Note
- If we go with option 2 "Dismiss", then we should discuss the wording of the primary call-to-action. Current proposal is "Add extra security" but as @theScrabi pointed out, we could be more precise with the wording. tbd

**Comment by jesmrec** [comment]
Some thoughts, also open to discussion:

- In the first slide, i'd add something not to frighten the user. Something like: `You will be guided through this process. It can take some minutes but don't worry`.  or similar... 

- Also, in first slide, i'd clarify a bit what's going on. This is: `Your files will be more secure now. They will be moved to a new location inside your device, so they will be moved.`. 

- I'd put more value, defining it in the first slide as `more secure and safer` instead of `more secure`. Powerful feature.

- The concept `scoped storage` should not appear. It is a technical name that can lead to confusion if we don't refer to it before. "New storage" or "safer storage" could sound better. Less accurate technically, but clearer for plain users.

- In the second slide, you are leading users to choose. I'd add some explanation about the second option, letting user know that 2,6 GB will remain in the device and must be removed manually. Also, i'd avoid using "we", using the files or data as subject.

- I know this is only a draft. But, colours and icon are brandable?

thanks for the proposal!!

**Comment by abelgardep** [comment]
I know that the wording could be improved. That's not hard to change 👍 

About the brand-ability, yes, I'll try to make it brandable. But it is not as easy as anyone could think because we have not updated the app to the [material design color system](https://material.io/design/color/the-color-system.html#color-theme-creation) yet.

Updating the app to the material design color system would make brand-ability sooooo much easier. We would need to update just the palette with the custom colors, and the whole app will be updated with the custom palette.

At the moment it is a little messy because we need to check which colors are used on each view. It makes it pretty hard to determine which colors the branded version will have.

**Comment by tbsbdr** [comment]
nice! thanks for the draft @abelgardep !

I tried a refinement based on your draft - what do you think?
- added colored Icons
- text refinements
- link: https://www.figma.com/proto/PscVEHRqfmVcQck7BiLbhu/Scoped-Storage-Assistant?page-id=25%3A13&node-id=25%3A297&viewport=479%2C48%2C0.76&scaling=min-zoom&starting-point-node-id=25%3A297

... or just as images:
![image](https://user-images.githubusercontent.com/26610733/131552318-3694b628-3502-4532-aa69-79e7a92945a0.png)

**Comment by tbsbdr** [comment]
@theScrabi and I just had a kitchen-discussion that I want to share:

- **Always clean up:** The option to keep the old "unplugged" files in the legacy storage after the migration feels  inconsistent in terms of security (and doubles space usage). On one hand we try to add more security by moving files to the scoped storage, on the other hand, we provide a way to keep the old files in an as unsecure declared location. And: Chances to forget those old "unplugged" files in the legacy storage are big which makes them even more unsecure. therefore I would not provide this option.
- **Aknowledge the need for a transition period** But there might be usecases, where one needs to access eg. ownCloud-synced pdf files with her favorit fancy pdf-app directly from the legacy storage as your option @jesmrec "Migrate and keep old data" addresses.  For those people, who really need the legacy storage-option for a longer transition period (until all apps migrate to the scoped storage) we should provide an option for them to **postpone the migration** to a convenient later time. I think we should be polite with our wizard and show it eg. only every 7 days (and also have the opportunity to start it directly form the settings). So the basic idea is: With postponing the migration a little bit, we buy some time for those people who still rely on legacy storage and eg. wait for soped-storage-upades for their eg. fancy pdf viewer.
- **Inform about Scoped storage** The "learn more" link should (eg. expand and) show more text about:
  - what is scoped storage?
  - why do we need to migrate
  - what could be drawbacks if I migrate to scoped storage
  - what are advantages of scoped storage
  - (link to android.com ?)

@theScrabi please add if i forgot something or if I understood something different

**Comment by jesmrec** [comment]
Done!!!
