### ISSUE TITLE
[FEATURE REQUEST] Logs removal

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3328]
**Is your feature request related to a problem? Please describe.**

Scoped Storage will enclose all files in a SandBox. We must remove logs files to avoid exhausting device memory as time goes by

**Describe the solution you'd like**

a Worker will remove the old logs every 10 days

**Describe alternatives you've considered**

**Additional context**

AC:

- A worker will remove the logs in the background
- It will work every 10 days (parameter)
- Worker enqueued. Not network required.
- Create "Logs" folder and store logs inside, instead of the ownCloud root folder inside the ownCloud folder

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/logs_collector
- [x] Development tasks
  - [x] Create logs inside "Logs" folder instead of the ownCloud root one.
  - [x] Create a new worker to enqueue the logs collector
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/logs_collector into master

### PR

- App #3337 
- Library (if needed)

**Comment by abelgardep** [comment]
Logs collector worker will be triggered every 7 days, and it will delete logs older than 7 days.

A new logs folder has been created to store the logs files: "Logs"

When moving to scoped storage, we just need to change the LocalStorageProvider from `LegacyStorageProvider` to `ScopedStorageProvider`. Logs stored in Legacy storage will be removed in the migration to ScopedStorage, so we don't need to worry about them.

**Comment by jesmrec** [comment]
Question here... worker is executed no matter if the `Logs` switch is on/off?
