### ISSUE TITLE
Passcode input misbehaving

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android#3342]
### Actual behaviour
Pin code input behaves janki when one of the EditText fields is selected and its Value gets deleted.

### Expected behaviour
EditText field should not be select at all. They should only indicate how much of the pin code was entered so far. The delete button should only delete the last entered digit. 
 
### Steps to reproduce
1. enable Pin code
2. open Pin Code Acitivity
3. enter half of the pin code
4. select one of the input fields
5. hit the delete button

### Additional information

https://user-images.githubusercontent.com/1891273/128844041-ec76917d-2979-49bf-a566-085aa7a5221a.mp4

### Proposed fix

Maybe it is useful if we wrote our own [custom view](https://developer.android.com/guide/topics/ui/custom-components) for the pin input. It should not be hard as no input must be processed by it.
Here a possible mock up:
![Screenshot_1628587277](https://user-images.githubusercontent.com/1891273/128844313-a180da2a-159b-4912-bb16-f7ef447a165a.png)

### TASKS

- [x] Create branch fix/select_passcode_fields
- [x] Development tasks
  - [x] Make passcode fields not selectable
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch fix/select_passcode_fields into master

**Comment by jesmrec** [comment]
Some device/vendor dependency here. I tested with:

Pixel2 Android11
Huawei P20 Android9
Nexus6P Android7

and not reproducible. In any case, the custom view implementation could be productive and interesting.

**Comment by theScrabi** [comment]
I tested again, I can reproduce this on any device.

**Comment by jesmrec** [comment]
Now reproduced correctly with all devices. Touches must not be allowed in the passcode gaps.

**Comment by theScrabi** [comment]
Maybe we should talk about redesigning the whole passcode activity in general. @michaelstingl what do you think?

**Comment by michaelstingl** [comment]
> Maybe we should talk about redesigning the whole passcode activity in general. @michaelstingl what do you think?

Why? Currently it's not an urgency? Let's check Monday morning…

**Comment by JuancaG05** [comment]
For the moment, I will fix this by making the fields not selectable. A redesign of this activity could be addressed in another issue.

**Comment by abelgardep** [comment]
Already merged into #3361 so it will be tested as part of #3354 PR
