### ISSUE TITLE
[FEATURE REQUEST] Lock delay for app

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3344]
Actually, if the app is protected with passcode/biometrical, it is not posible to access the accounts using doc provider apps:

![Screenshot 2021-08-11 at 09 07 33](https://user-images.githubusercontent.com/14894746/128984909-5f89c61a-db0e-4008-a655-ae403bf7fae8.png)

This is an expected behaviour after the first iteration of document provider implementation. 

The idea is researching/implementing a solution in order not to make users to decide between document provider or passcode/pattern protection.

### PROPOSED FIX

As in the iOS app, a lock delay will be implemented with its respective preference:

![CleanShot 2021-09-07 at 13 46 56@2x](https://user-images.githubusercontent.com/57049315/132375835-407ec893-5bbc-4ee4-a738-dd6c8e5a00b0.png)

As we're implementing here the lock delay but it won't solve the document provider's problem (https://github.com/owncloud/android/issues/3344#issuecomment-918152437), it will be addressed in another issue: https://github.com/owncloud/android/issues/3379

### TASKS

- [x] Research about the best option on how to implement the lock delay
- [x] Create branch feature/lock_delay
- [x] Development tasks
  - [x] Implement lock delay with a default time in app's lock with passcode
  - [x] Implement lock delay with a default time in app's lock with pattern
  - [x] Implement lock delay with a default time in app's lock with biometric
  - [x] Implement preference of lock delay time chooser
  - [x] Update UI tests
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/lock_delay into master

### PR

- App #3375
- Library (if needed)

**Comment by michaelstingl** [comment]
Lock delay a simple approach on Android?

**Comment by jesmrec** [comment]
> Lock delay a simple approach on Android?

yes, it could be an approach (like iOS before).

**Comment by abelgardep** [comment]
Lock delay could be an option. 

IMHO, it could be easier for the user to include a new security option. It would be permanent, if the user wants to disallow, he needs to uncheck it again. 

New checkbox -> "Allow access from DocumentsProvider" Disabled by default

**Comment by michaelstingl** [comment]
> It would be permanent, if the user wants to disallow, he needs to uncheck it again.

Probably not what big organisations want. Users can forget to lock again.

System shows "Lock with pattern". Is there a method to trigger unlock UI there? (no requirement for first implementation)

**Comment by abelgardep** [comment]
> Probably not what big organisations want. Users can forget to lock again.

Ok, I saw that as a normal user. And it could be easier for me just to enable it once, instead of every time I need to access the documents provider, open the ownCloud App, unlock the ownCloud App, go to the security section and trigger a delay and then come back to the action I wanted to trigger

> System shows "Lock with pattern". Is there a method to trigger unlock UI there? (no requirement for first implementation)

No way to trigger the unlock UI there.

**Comment by JuancaG05** [comment]
We'll implement a lock delay approach to solve this problem

**Comment by michaelstingl** [comment]
> * If any lock is activated for the app, don't allow access to files by default but **create a preference for allowing access from document provider**, with some warnings for the user, similarly to "Touches with other visible windows" or "Enable logging" preferences.

Yes, this is the best we can do. Go for it 👍 

> IMHO, the best approach would be to keep the lock delay for the app, as it is a new feature that could be cool and comfortable for users which open the app frequently

Yes, that's a nice enhancement.
