### ISSUE TITLE
[New arch] File synchronization

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3350]
### Steps to sync a file
1. propfind remote server
1.1 Not found -> remove local file (db and storage)

2. if not downloaded -> Download

3. if downloaded, check if local has changed
3.1 Only remote changes -> Download new version
3.2 Only local changes -> Upload new version
3.3 Both changed -> Save conflict
3.4 None changed -> Do nothing

### UI
1.1 -> In details view, skip details view and go back to the file list
1.1 -> In the file list, update file list according to it, update multiselection, turn off multiselection in case all files removed.
2 -> We cant synchronize without download. Nothing to do
3.1 -> Update badge next to thumbnail and notification(if feasible) and update file with new files. In details view, show progressbar
3.2 -> Update badge next to thumbnail and notification(if feasible) and update file with new files. In details view, show progressbar
3.3 -> Details -> show conflict dialog  
3.3 -> File list -> Show badges with conflicts and user will choose one by one when entering preview or details view.
3.3 -> Documents provider -> show badge in file list
3.4 -> snackbar -> file already synchronized

### TASKS

- [ ] Research (if needed)
- [x] Create branch new_arch/update_file_list
- [ ] Development tasks
  - [ ] Implement whatever
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App https://github.com/owncloud/android/pull/3704
- Library (if needed) https://github.com/owncloud/android-library/pull/495

**Comment by abelgardep** [comment]
After the first steps, I got some known issues that should be fixed in upcoming PRs.

### Known issues
1. Preview for not downloaded files are not working properly. File synchronization is triggered within the main thread and it does not download the file to open it.
2. Preview not refreshed after sync file with changes in remote file. Previews need a full revamp.
3. Added some snackbars to debug the current behavior. Download enqueued and upload enqueued messages will be improved/removed in upcoming PRs.
4. Sync in progress state is gone atm. Not shown in the file list nor in the toolbar. So the file sync cant be canceled atm.

**Comment by abelgardep** [comment]
Will be tested within the #2934 PR
