### ISSUE TITLE
[New arch] Passcode activity

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android#3354]
[Passcode Activity](https://github.com/owncloud/android/blob/e6194afd35e533e08adecbd78a5aff3d66fe4871/owncloudApp/src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java#L50) is still written in the old architecture. Recently I changed the [the code of this activity](https://github.com/owncloud/enterprise/issues/4696), however I was not able to write proper tests for it since the code is not in MVVM architecture yet.
In order to be able to test the activity properly and align it with our new architecture we should convert it to MVVM.

### TASKS

- [x] Create branch new_arch/passcode
- [x] Development tasks
  - [x] Create new PassCodeViewModel
  - [x] Move logic from PassCodeActivity to PassCodeViewModel
  - [x] Save and remove passcode in PassCodeActivity instead of SettingsSecurityFragment
  - [x] Include unit tests
  - [x] Incude UI tests
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch new_arch/passcode into master
