### ISSUE TITLE
[New arch] Shared by link 

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3355]
At the moment, shared by link tab shows an empty list when there are current shared by link files.
We have the shared by link attribute stored in the database. We can see that the function to show every single shared by link file from this account is [commented](https://github.com/owncloud/android/blob/new_arch%2Fsynchronization/owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.kt#L218) on at the moment. This should be fixed within this issue. The shared by link tab should show the shared files within this account.

### TASKS

- [x] Research (if needed)
- [x] Create branch new_arch/shared_by_link
- [x] Development tasks
  - [x] Create Query to retrieve data from DB
  - [x] Create new method in Local Data Source
  - [x] Create new method in File Repository
  - [x] Create UseCase
  - [x] Implement Testing
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch new_arch/shared_by_link into new_arch/synchronization

### PR

- App:  #3359

**Comment by abelgardep** [comment]
Done, shared by link files are now displayed in the Links tab.
