### ISSUE TITLE
Lack of "Back" button in Logs view

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3357]
### Steps to reproduce
1. Open `Settings` 
2. Enable Logging
3. `Open logs view`

### Actual behaviour

This view lacks of a return button to go back to `Settings`:

![Screenshot 2021-08-20 at 10 12 41](https://user-images.githubusercontent.com/14894746/130202590-e138d4ee-e97e-4a73-9ddf-cd59c734ee1f.png)

it'd be handy to include a back arrow or similar. 

Android12(beta), Pixel5
Android11, Pixel2
 
### TASKS

- [x] Create branch fix/back_arrow_logs
- [x] Development tasks
  - [x] Include back arrow in logs screen
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch fix/back_arrow_log into master

### PR
App: #3363
