### ISSUE TITLE
[FEATURE REQUEST] Passcode digits brandable

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3358]
- add int to `setup.xml` to switch between different number of digits. Branding will allow to choose 4 or 6 ftm.
- make 4 digits default and minimum
- Migration 4 -> 6 (iOS PR: https://github.com/owncloud/ios-app/pull/1000)

### TASKS

- [x] Create branch feature/brandable_passcode
- [x] Development tasks
  - [x] Implement 4 to 6 digits migration
  - [x] Implement (ViewModel) tests (may require to mock resources)
- [ ] Trigger ownBrander devs to adopt the new flag
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/brandable_passcode into master

### PR

- App #3369 

### QA

Test plan:

Reports

- [X] (1) Minimum is not 4 https://github.com/owncloud/android/issues/3358#issuecomment-924643645 [FIXED]
- [X] (2) (enhancement) Title in migration https://github.com/owncloud/android/issues/3358#issuecomment-924707826 [DONE]
- [X] (3) New passcode delayed to biometrical dismisshttps://github.com/owncloud/android/issues/3358#issuecomment-924751859 [DONE]
- [x] (4) New passcode view is cancellable https://github.com/owncloud/android/issues/3358#issuecomment-927790900 [DONE]
- [x] (5) Killing app in migration deletes the passcode https://github.com/owncloud/android/issues/3358#issuecomment-927889847 [DONE]

**Comment by jesmrec** [comment]
### (1)

4 digits is not the minimum

Current:

By setting `<integer name="passcode_digits">2</integer>`,  passcode is asked with only 2 digits. Also, if `0` or negative value is set, app crashes

Expected:

if the value is >= 4, that value applies
If the value is <4, 4 digits are asked

Pixel2 Android11
`54e070a4`

**Comment by jesmrec** [comment]
### (2)

1. Enable passcode with 4 digits
2. In `setup.xml` set `passcode_digits` = 8
3. Close the app and open again
4. Enter 4-digit passcode to unlock

Current: 8-digit passcode is asked, but the title message is `Enter a new 6-digit passcode`

Expected: 8-digit passcode is asked, and the title message is `Enter a new 8-digit passcode`. Number of digits should be correctly shown in the title message depending on the setup value.

Pixel2 Android11
`54e070a4`

**Comment by jesmrec** [comment]
### (3) (to discuss)

1. Enable passcode with 4 digits
2. Enable biometrical
3. In `setup.xml` set `passcode_digits` = 6
4. Close the app and open again

Current: Biometrical is asked to unlock the app. By entering the correct biometrical, app is unlocked without asking new passcode. New passcode is asked after dismissing the biometrical activity to enter the code.

Expected: After entering correct biometrical, app is unlocked and new passcode is asked (current iOS behaviour). 

Anyway, the current behaviour is not totally incorrect, but it can lead to some confusion in case user is asked for new code after much time being set, because only biometrical was used. What do you think? @michaelstingl @hosy @fesave @abelgardep @JuancaG05 @theScrabi 

Pixel2 Android11
`54e070a4`

**Comment by JuancaG05** [comment]
> Anyway, the current behaviour is not totally incorrect, but it can lead to some confusion in case user is asked for new code after much time being set, because only biometrical was used. What do you think? @michaelstingl @hosy @fesave @abelgardep @JuancaG05 @theScrabi

Yes, I think the behaviour you propose is more suitable. But on the other hand, it's true that with the current behaviour, the migration for the passcode is performed only if the passcode is going to be used. So, maybe both sides could make sense. Let's listen to more opinions 👍 .

**Comment by tbsbdr** [comment]
I would favor your proposed ios behavior because:

If the admin says "you must use 6 digits" users shouldn't drive around with 4 digits for some time. so they should be forced to migrate from 4 to 6 digits from a CISO perspective. and if ux has proofed to be good in ios, i see only little risk to mess up the ux with the new behavior.

**Comment by jesmrec** [comment]
### (4)

1. Enable passcode with 4 digits
2. Migrate to 6 (or any other value)

Current:

New passcode view is cancellable:

![Screenshot 2021-09-27 at 13 30 33](https://user-images.githubusercontent.com/14894746/134900325-0ccbdf58-54b3-479d-9d90-f849957ed3f7.png)

Expected:

New passcode view must not be cancellable. Otherwise, passcode will be disabled without explicit authorization of the user.


Pixel2 Android11
`119a7c7c0`

**Comment by jesmrec** [comment]
(4) is fixed itself, but it has broken the `Cancel` button in the regular passcode. When you enable the passcode for the first time, the `Cancel` does nothing. Could you take a look @JuancaG05 ?

**Comment by JuancaG05** [comment]
I think it should be fixed completely now, without breaking other parts of the code! 😅  @jesmrec

**Comment by jesmrec** [comment]
Thanks! any way to cover that scenario with UI test?

**Comment by jesmrec** [comment]
### (5)

1. Enable passcode with 4 digits
2. Migrate to 6 (or any other value)
3. Reopen the app and enter old passcode to unlock
4. Before entering the new passcode, kill the app and open it again

Current: 

Passcode is gone. Not asked and disabled

Expected:

New passcode must be asked till it is entered.

Pixel2 Android11
`346e6723`
