### ISSUE TITLE
[TECHNICAL] Kotlinize PassCodeManager

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3371]
To finish with the rearchitecture of the passcode, the class `PassCodeManager` should be moved from Java to Kotlin and placed in the `presentation.ui.security` package so that all the stuff related with passcode is located there.

Other recent issues related with passcode: https://github.com/owncloud/android/issues/3354, https://github.com/owncloud/android/issues/3342, https://github.com/owncloud/android/issues/3358

### TASKS

- [x] Create branch technical/kotlinize_passcode_manager
- [x] Development tasks
  - [x] Move PassCodeManager to the `presentation.ui.security` package
  - [x] Move PassCodeManager from Java to Kotlin
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch technical/kotlinize_passcode_manager into new_arch/passcode

### PR

- App
- Library (if needed)

**Comment by abelgardep** [comment]
This was merged into #3361

It will be tested within #3361 PR, so we can close this issue.
