### ISSUE TITLE
[New arch] Pattern activity

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3373]
Pattern activity is written in Java in the old architecture. The aim of this issue is to move the pattern activity and all its related stuff to `presentation.ui.security` package and rewrite the class in Kotlin.

### TASKS

- [x] Create branch new_arch/pattern
- [x] Development tasks
  - [x] Move all the classes to `presentation.ui.security` package
  - [x] Kotlinize PatternActivity
  - [x] Create new PatternViewModel
  - [x] Move logic from PatternActivity to PatternViewModel
  - [x] Save and remove pattern in PatternActivity instead of SettingsSecurityFragment
  - [x] Kotlinize PatternManager
  - [x] Include unit tests
  - [x] Include UI tests
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch new_arch/pattern into master
