### ISSUE TITLE
[New arch] Biometric activity

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3377]
Biometric activity is written in Java in the old architecture. The aim of this issue is to move the biometric activity and all its related stuff to `presentation.ui.security` package and rewrite the class in Kotlin.

### TASKS

- [x] Create branch new_arch/biometric
- [ ] Development tasks
  - [x] Move all the classes to `presentation.ui.security` package
  - [x] Kotlinize BiometricActivity
  - [x] Create new BiometricViewModel
  - [x] Move logic from BiometricActivity to BiometricViewModel
  - [x] Kotlinize BiometricManager
  - [x] Include unit tests
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch new_arch/biometric into master

**Comment by abelgardep** [comment]
It would be great if you could bump the biometric dependency from 1.0.1 to 1.1.0

I'm not sure whether it requires so many changes

**Comment by abelgardep** [comment]
It will be tested within https://github.com/owncloud/android/pull/3389

Great job @JuancaG05
