### ISSUE TITLE
[FEATURE REQUEST] Allow access from document provider preference

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3379]
[QA pending - #3344]

Actually, if the app is protected with passcode/biometrical, it is not posible to access the accounts using doc provider apps:

![Screenshot 2021-08-11 at 09 07 33](https://user-images.githubusercontent.com/14894746/128984909-5f89c61a-db0e-4008-a655-ae403bf7fae8.png)

The idea is to implement a new preference in "Security" section which lets the user choose between allowing access from document provider or not, disabled by default so that it is more secure.

### TASKS

- [x] Create branch feature/access_from_document_provider
- [x] Development tasks
  - [x] Implement preference "Allow access from document provider"
  - [x] Put some security warnings for the user when enabling this preference
  - [x] Update unit tests
  - [x] Update UI tests
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/access_from_document_provider into master

### PR

- App
- Library (if needed)

**Comment by hannesa2** [comment]
I strongly vote for this feature. With this restriction the app is almost useless for my purpose

**Comment by JuancaG05** [comment]
@hannesa2 which feature do you refer to? This was already implemented and closed.

**Comment by hannesa2** [comment]
sorry, I wrote to wrong issue

**Comment by 3oooo0** [comment]
> [QA pending - [#3344](https://github.com/owncloud/android/issues/3344)]
> 
> Actually, if the app is protected with passcode/biometrical, it is not posible to access the accounts using doc provider apps:
> 
> ![Screenshot 2021-08-11 at 09 07 33](https://user-images.githubusercontent.com/14894746/128984909-5f89c61a-db0e-4008-a655-ae403bf7fae8.png)
> 
> The idea is to implement a new preference in "Security" section which lets the user choose between allowing access from document provider or not, disabled by default so that it is more secure.
> 
> ### TASKS
> * [x]  Create branch feature/access_from_document_provider* [x]  Development tasks
>     
>     * [x]  Implement preference "Allow access from document provider"* [x]  Put some security warnings for the user when enabling this preference* [x]  Update unit tests* [x]  Update UI tests[x]  Code review and apply changes requested[x]  Design test plan[x]  QA[x]  Merge branch feature/access_from_document_provider into master
> 
> ### PR
> * App
> * Library (if needed)
