### ISSUE TITLE
[RELEASE] 2.19 beta1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3397]
### TASKS:

 - [x] [GIT] Create branch release/1.0.13_beta.1 in owncloud/android-library from master
 - [x] [GIT] Create branch release/2.19_beta.1 in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudComLibrary module
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD [No needed for beta version]
 - [x] [DIS] Move all changelog files from the unreleased folder to the new version folder [No needed for beta version]
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [DIS] Generate test bundle from `release/2.19_beta.1` branch in owncloud/android
 - [x] [GIT] Create and sign tag 'oc-android-2.19-beta.1 ' in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Create and sign tag '1.0.13-beta.1' in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [x] [COM] Inform `#release_coordination` and `#marketing` in internal chat
 - [x] [GIT] Merge branch `release/1.0.13_beta.1` in owncloud/android-library, into master
 - [x] [GIT] Merge branch `release/2.19_beta.1` in owncloud/android, into master
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [x] [GIT] Publish a new release in owncloud/android
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - [ ] [GIT] Merge master branch into stable, in owncloud/android-library
 - [ ] [GIT] Merge master branch into stable, in owncloud/android
 - [ ] [DOC] Update documentation with new stuff (notify rocketchat #documentation-internal in advance!)

_____

### PR
App: #3433 
Library: https://github.com/owncloud/android-library/pull/440
