### ISSUE TITLE
[Epic] MDM integration

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3398]
MDM (mobile device management) is a software to check, admin and make safer mobile devices by remote control.

We have to integrate MDM support inside the Android app, by using the [AppConfig](https://www.appconfig.org/) protocol, already supported by several MDM vendors. The main target is setting up the app by pushing the config file from MDM server to the enrolled devices.

This issue is an epic to gather ideas, handle a checklist with the tasks and deal with discussions about the topic.

First goal: set up one parameter. We decided to choose **server URL** and **server URL input visibility** so that we check the complexity of combining different managed configurations.

Rough list of tasks to do:

- [x] [SPIKE] how to integrate app with MDM: how to enroll device? do we need Android Enterprise? ...  -> https://github.com/owncloud/android/issues/3399
- [x] Develop MDM support in the app for the first parameters -> https://github.com/owncloud/android/issues/3415
- [x] Set up a test platform to check if it works from a remote administration console -> https://github.com/owncloud/android/issues/3416
- [x] Send feedback from the app to the EMM console about the configurations applied -> https://github.com/owncloud/android/issues/3420
- [x] Check how to prioritize the value from MDM in comparison with the value from branding

After this first goal, more tasks to do:

- [ ] Decide which parameters must be branded via MDM to implement
- [ ] Create a Metadata mechanism that helps to document 
- [ ] Create a validator for data values that don't match the requirements
- [ ] ...

Please, share additional ideas to include in the list, as well as discussions about the existing ones or alternative ways to do.

This will require effort from all team in some way

@abelgardep @fesave @JuancaG05 @theScrabi @michaelstingl @hosy
