### ISSUE TITLE
[FEATURE REQUEST] Security enforced

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3400]
This is a feature that could be used in branding/MDM.

ACs

- App is always covered by one of the locking methods: passcode or pattern.
- Only affected passcode and pattern, not biometrical. 
- New branding/MDM option called `passcode_enforced` or similar. Boolean.
   - If the value is true, in the next opening of the app (or first opening, if the app was just installed), user is asked if prefers passcode or pattern lock
   - If the value is false, nothing happens
- After entering the passcode/pattern correctly twice, those fields will be hidden (and enabled) in Settings view. Only available the biometrical lock feature.
- If the `passcode_enforced` turns on after app is already installed
  - Next opening of the app will ask for the lock 
- If the `passcode_enforced` turns off after app is already installed
  - Lock fields become visible in Settings, so that user can decide to keep or disable.

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/security_enforced
- [x] Development tasks
  - [x] Create a temporal setup variable
  - [x] Check if dialog should be visible
  - [x] Hide passcode/pattern in settings
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/security_enforced into master

### PR

- App #3434
