### ISSUE TITLE
[RELEASE] 2.18.2

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3401]
### TASKS:

 - [x] [GIT] Create branch release/2.18.2 in owncloud/android from  `oc-android-2.18.1`
 - [x] [DEV] Update privacy policy link to https://owncloud.com/privacy-statement/
 - [ ] [DEV] Update version number and name in build.gradle in owncloudComLibrary module [Not needed]
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [ ] [DIS] Create a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD [Not needed]
 - [x] [QA] Check new privacy policy link in Settings
 - [x] [DIS] Generate test bundle from `release/2.18.2` branch in owncloud/android
 - [x] [GIT] Create and sign tag 'oc-android-2.18.2' in HEAD commit of release branch, in owncloud/android
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [ ] [GIT] Merge branch `release/2.18.2` in owncloud/android, into master ¿?
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [x] [GIT] Publish a new release in owncloud/android
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - [ ] [GIT] Merge master branch into stable, in owncloud/android ¿?

_____
