### ISSUE TITLE
[MDM] Integrate Android Enterprise in the app

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3415]
[EPIC] -> https://github.com/owncloud/android/issues/3398
[SPIKE] -> https://github.com/owncloud/android/issues/3399

The very first step to be able to manage the app via MDM is to introduce Android Enterprise in the app.
In this video playlist they show how to begin with Android Enterprise: https://www.youtube.com/playlist?list=PLWz5rJ2EKKc-nnQcMIVqAM9_CNmbGu12O
Guide about managed configurations in Android documentation: https://developer.android.com/work/managed-configurations

In our case, it'll be necessary to manage in some way the code that will have to be executed ONLY in the branded apps which use MDM. We discussed 2 different approaches:
- Create a flag variable in `setup.xml` to indicate whether that instance of the app is going to be managed via MDM
- Create a new product flavor so that this code is only executed if the app is built for that variant

For the moment, we are taking the second approach, but more opinions and suggestions are welcome.

### TASKS

- [x] Research
- [x] Create branch feature/mdm
- [x] Development tasks
  - [x] Create new product flavors "mdmDebug" and "mdmRelease"
  - [x] Include the `APP_RESTRICTIONS` meta-data node in the Android manifest 
  - [x] Create a new `managed_configurations.xml` resource file with a `restriction` node for test.
  - [x] Instantiate a `RestrictionsManager` and retrieve the restriction set previously **on app launch**
  - [x] Use the restriction value to do whatever it implies
  - [x] Test it with Test DPC
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Fdroid integration
- [ ] Merge branch feature/mdm into master
- [ ] Adapt BitRise workflow for tests

### CHANGES IN BITRISE WORKFLOWS
Since we introduced new flavors in the "owncloudApp" module in this issue, it is necessary to adapt workflows in BitRise so that they continue working after merging this into master. The changes performed are summarised in the next points:
- The old workflows "primary" (UI and unit tests) are now "**new_arch**". As new architecture is being developed in a separate branch, it will be necessary to keep these workflows until a rebase against master is done.
- The new "**primary**" workflow is a copy of the old "primary", but with some adaptations:
  - In the UI tests workflow, now the apk is assembled for the "originalDebug" flavor
  - In the unit tests workflow, now the unit tests in the "owncloudApp" module are executed for the "originalDebug" flavor, and the "owncloudApp" module is assembled for the "originalDebug" flavor
- Also, the trigger pattern for the workflows has been changed so that the "**new_arch**" workflows are triggered only in branches starting by `new_arch/...`, and "**primary**" workflows are triggered in the rest of branches ([here](https://discuss.bitrise.io/t/exclude-one-branch-from-workflow-trigger-pattern/1244) is how to do this). This will be changed once the branch for new architecture rebases against master.

### IMPORTANT POINTS
- For users to be able to use ownCloud app and all its features, they should have some apps installed in the work profile of their devices that are not by default, so that some intents that are launched can be handled by a suitable app (otherwise ownCloud app crashes). This may be responsibility of MDM console administrators (they can usually distribute these apps via the MDM console). The needed apps are:
  - A browser
  - An email client

**Comment by jesmrec** [comment]
Pending: Fdroid integration.

**Comment by abelgardep** [comment]
### Fdroid Integration
We need to send a PR [updating the yml](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.owncloud.android.yml)

The way to use the new flavor is introducing it in the Gradle section. The new version should go with something like this:
```
  - versionName: 2.21
    versionCode: 22100000
    commit: 439399770a1d1aaad7fd029a06fd8482fc689634
    subdir: owncloudApp
    submodules: true
    gradle:
      - original
    rm:
      - user_manual
```

Of course, the name and code may differ, and the commit hash must be the signed one.

New beta release -> https://github.com/owncloud/android/issues/3597
