### ISSUE TITLE
[MDM] Provide app feedback to MDM admins

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3420]
[EPIC] -> https://github.com/owncloud/android/issues/3398
[SPIKE] -> https://github.com/owncloud/android/issues/3399

Once implemented the basics in Android Enterprise for getting a MDM solution, it is very important to notify EMM (enterprise mobile management) admins about the result of the policy change requested. The app feedback can act as confirmation that managed configurations have been set successfully or it can include an error message if the app failed to apply the specified changes.

The next guide can be followed to achieve this: https://developer.android.com/work/app-feedback/overview

Previous issues related with MDM:
- https://github.com/owncloud/android/issues/3415
- https://github.com/owncloud/android/issues/3416

### TASKS

- [x] Research
- [x] Create branch feature/mdm_feedback
- [x] Development tasks
  - [x] Add keyed app state to give feedback
- [x] Test it with Test DPC
- [x] Test it with a MDM platform (such as IBM MaaS360)
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch feature/mdm_feedback into feature/mdm

**Comment by JuancaG05** [comment]
To get the feedback in IBM MaaS360 platform, it can be found following:

Devices > Inventory > Device being managed > App Distributions > View feedback (in column App Configuration Status)

![Captura de pantalla 2021-12-23 a las 13 03 05](https://user-images.githubusercontent.com/57049315/147238943-9be4997d-d78e-424b-99a9-e5f1308af0fc.png)

It seems that there are some minutes of delay until the feedback appears.
