### ISSUE TITLE
[FEATURE REQUEST] Upload a single file using new architecture

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3424]
This flow to accomplish:

1. User opens FAB and select upload file
2. Show the user the document provider (SAF), to select a file from there. Only one file for the moment. multiselection, a N2H.
3. Fetch the selected file
4. Send to the server, inside the correct location updating DB
5. New file is visible in the server (check in web or other client)

errors, notifications and upload view to be done in the following issues.

### TASKS

- [x] Research (if needed)
- [x] Create branch new_arch/upload_single_file
- [ ] Development tasks
  - [x] New usecase to upload files from everywhere.
  - [x] Implement force overwrite then uploading files
  - [x] Define exactly what is the LOCAL_BEHAVIOR, document, and rename them to a more understandable KEY
  - [x] Remove legacy create remote folder key, since it is not used anymore.
  - [ ] Generate a new ocfile to upload
  - [ ] Check if chunking is allowed or not and prepare the code to trigger a chunked upload
  - [x] Generate OCUpload and store it in the database
  - [ ] Add a listener and update the upload progress similar to downloads
  - [ ] Check if we can automatize upload retries when connection fails
  - [x] Use new usecase to upload files from camera uploads
  - [x] Use new usecase to upload files from manual uploads
  - [x] Use new usecase to upload files after receiving external files
  - [x] Use new usecase to upload files from documentsprovider
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch new_arch/upload_single_file into master

### PR

- App : Resolve #3686 
- Library (if needed): Resolve android-library/pull#462

**Comment by abelgardep** [comment]
### Known issues
- We create a cached file just when sharing with ownCloud. Other cases will try to upload the file directly.
- Upload from conflicts is prepared but needs some tweaks when #3005 is done
- Upload progress is not shown atm. Needs a rework during https://github.com/owncloud/android/issues/3426

**Comment by abelgardep** [comment]
We can close this at the moment. Already merged into the synchronization branch. We will keep improving the uploads behavior in upcoming PRs
