### ISSUE TITLE
[New arch] Migrate OCUpload to new database

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3426]
To keep working on our way to new architecture, we need to migrate the upload list to the room database.

To keep an eye on how it could be done, we can check OCFile Migration: https://github.com/owncloud/android/issues/2955

**New table name**: `transfers`

Initially, we will use it only for uploads, keeping the legacy behaviour. It will be ready to be used by other transfers (downloads)

**Fields from the SQLite table to migrate to new table:**

__id_	-> incremental row id
_local_path_ -> content URI from device
_remote_path_ -> path to store in server 
_account_name_ -> user@serverURI
_file_size_ -> in bytes
_status_ -> (0, 1, 2, 3) -> QUEUED, IN_PROGRESS, FAILED, SUCCEEDED
_local_behaviour_ -> (0, 1) -> COPY, MOVE
_force_overwrite_ -> (0, 1) -> false, true
_upload_end_timestamp_ -> when did it finish -> nullable
_last_result_ -> nullable
_created_by_ -> kind of upload
_transfer_id_ -> nowadays not used, but could be used for worker id -> nullable

**Fields to be removed:** 

_upload_time_
_is_create_remote_folder_

### TASKS

- [x] Research (if needed)
- [x] Create branch new_arch/migrate_uploads_database
- [x] Development tasks
  - [x] Create a new TransferStatus in domain layer
  - [x] Create a new TransferResult in domain layer
  - [x] Create a new OCTransfer in domain layer
  - [x] Create a new TransferRepository interface in domain layer
  - [x] Create a new OCTransferEntity in data layer
  - [x] Create a new TransferDao in data layer with CRUD operations
  - [x] Add new entity and new Dao to Room database
  - [x] Create a new LocalTransferDataSource interface in data layer
  - [x] Create a new OCLocalTransferDataSource implementation in data layer
  - [x] Create a new OCTransferRepository implementation in data layer
  - [x] Add dependency injection of the new components
  - [x] Deprecate old OCUpload datamodel
  - [x] Replace old model uses with the new one and use of UploadsStorageManager
  - [x] Remove unnecessary methods from old UploadsStorageManager
- [x] Code review and apply changes requested
- [x] Merge branch new_arch/migrate_uploads_database into new_arch/synchronization

**Comment by abelgardep** [comment]
Currently the uploads pending are stored in the old database.

Uploads are stored, retrieved, updated etc via UploadsStorageManager

Uploads data is in filelist database in list_of_uploads table. We need to migrate the data to the owncloud_database and create a new table there.

## Domain
### Model
Current class to represent an upload is [OCUpload](https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/datamodel/OCUpload.java) in the datamodel package in the ownCloudApp module.

We need to create a new data class in the domain layer in kotlin that represent those uploads.

Also, we need to move the [UploadResult](https://github.com/owncloud/android/blob/a311e16ccd298bd9acceda62161d09dde22efae2/owncloudApp/src/main/java/com/owncloud/android/db/UploadResult.java) to the domain layer, which is basically the way to persist the result. Also, we should consider adding a way to persist not only a code, but also a message or something to show why. For example, when a virus is [detected](https://github.com/owncloud/android/issues/3115)

### Usecases
Use cases represent all the actions we can do with the app. In this case, we need to create a new usecase for each potential use for the uploads feature.

We can check the [UploadsStorageManager](https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java) and see which are the expected and useful usecases:
- Save upload
- Update upload
- Remove upload by id
- Remove upload by account
- Get uploads
### Repository interface
The repository interface belongs to the domain layer and its just a facade that conects with the data layer

## Data layer
In the data layer, we will add all the classes related with the datasources.
In this case, we won't have a remote datasource since the uploads is something internal. So we will focus on the local datasource.

### Entity
We need to create a new entity that encapsulates all the data we want to store about an upload. Normally, it would be pretty similar to the domain model, but with basic types: Strings, booleans, ints...

### Dao
It will basically have the CRUD operations needed to st

### Room Database
Also, we need to update [the room database](https://github.com/owncloud/android/blob/master/owncloudData/src/main/java/com/owncloud/android/data/OwncloudDatabase.kt) introducing the new entity and also the new dao.

Normally, we would create a new MIGRATION file [here](https://github.com/owncloud/android/tree/new_arch/synchronization/owncloudData/src/main/java/com/owncloud/android/data/migrations) but, in this case, we would use the same migration file as the[ OCFile migration](https://github.com/owncloud/android/issues/2955) one: [Migration 37](https://github.com/owncloud/android/blob/new_arch/synchronization/owncloudData/src/main/java/com/owncloud/android/data/migrations/Migration_37.kt)

To fill that migration, we can take advantage of the autogenerated file based on the entities. If we did the previous steps correctly, a new asset should be autogenerated in the [assets folder](https://github.com/owncloud/android/tree/new_arch/synchronization/owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase). If we check the latest one, we should find the info for the new table, and we could use the "createSql" sentence to fill the migration.

### Local Datasource
The local datasource will link the repository with the dao and also it will map the domain to the entity, and the entity to the model.

We can check [this local datasource as example](https://github.com/owncloud/android/blob/new_arch/synchronization/owncloudData/src/main/java/com/owncloud/android/data/folderbackup/datasources/implementation/FolderBackupLocalDataSourceImpl.kt)

### Repository implementation
Normally, the repository links and synchronizes the local and remote datasources. But in this case, we don't have a remote datasource, so it will communicate directly with the local datasource.

## App layer
Now that we have finished with the domain and data layer implementation, we can go back to the app layer. 

We need to add every new component to the dependency injection. https://github.com/owncloud/android/tree/new_arch/synchronization/owncloudApp/src/main/java/com/owncloud/android/dependecyinjection

To begin with, we could annotate the old datamodel with @deprecated. That way, we can identify easily where we are using the old model and where we are not.

Let's use the new usecases that we have created. For each call to UploadsStorageManager, we would replace with the new usecase.

For example, storeUpload function:

It is used in the [camera uploads worker](https://github.com/owncloud/android/blob/new_arch/synchronization/owncloudApp/src/main/java/com/owncloud/android/workers/CameraUploadsWorker.kt)
Let's use the new domain model and the new storeUpload usecase in that file.

Repeat that for each storeUpload use from UploadsStorageManager.

Check that new items are being added to the new database. (App inspection in AS)

Repeat this for each function in UploadStorageManager.

Once we finished, the uploads view should show the data from the new database. Probably not 100% accurate, but most of it. UI improvements and progress and so on will be done in another issue.

## Migrate old database data
Now that we use the new database to persist the uploads, we can migrate the data we had in the old database to the new one.

The logic we need to update is in the [FileContentProvider](https://github.com/owncloud/android/blob/new_arch/synchronization/owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.kt#L1040)

If we increased the database version in the process, we would  need to introduce a new if to check the new and old version and migrate the data accordingly.

In this case, we didn't increased the version, since we are migrating the files and the uploads at the same time. so we can use that to migrate all together.

We will retrieve all the uploads from the old database, and introduce them into the new one.
