### ISSUE TITLE
[FEATURE REQUEST] 2.19_oem

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3427]
### TASKS:

- [x] [GIT] Create and sign tag `oc-android-2.19_oem` in HEAD commit of `release_2.19_oem` branch or 2.19 commit (depending on if there's new changes or not), in owncloud/android
- [x] Approve and merge changes in ownBrander
  - [x] Add `passcode_digits` to the setup.xml template 
  - [x] Upgrade version 
  - [x] Check migration wizard with branding
- [x] [DIS] Deploy and block button
- [x] [QA] Generate final APKs files from signed commit in builder machine  and perform some basic operations 
- [x] [QA] Check that bundle is correctly generated and apk family could be installed in device from bundle
- [x] [DIS] Enable button

_____

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
All stuff done. 2.19 completed!
