### ISSUE TITLE
[FEATURE REQUEST] Lock delay enforced

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3440]
Continues from https://github.com/owncloud/android/issues/3344

At this point, user decides a gap in which the lock method is not asked (1min, 5min, 30min). 

Next step is including a new setup to force one of these values.

AC:

- Name is `lockdelay_enforced` (or similar)
- In terms of visibility, it will work in the same way as the `Lock application` option: only available if pattern|passcode are enabled. Otherwise, greyed out.
- If `lockdelay_enforced` does not contain any value, behaviour is the current one. User is free to decide about it in the `Settings`
- If `lockdelay_enforced` contains 1, 5 or 30:
   - No way to select other value in the app
   - Selected value in setup is shown.

### TASKS

- [X] Create branch feature/lock_delay_enforced
- [X] Development tasks
  - [X] Implement the possibility of locking the application through branding/MDM
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App: #3547

**Comment by fesave** [comment]
I developed this idea concept:

- `lock_delay_enforced` will be `integer` with four different values
  - `0` -> Not forced (default)
  - `1` -> Immediately 
  - `2` -> One minute
  - `3` -> Five minutes
  - `4` -> Thirty minutes
  
- When passcode/pattern is enabled
   - If `lock_delay_enforced == 0` -> User is free to decide about it in the `Settings`
   - If `lock_delay_enforced == 1`,
   - If `lock_delay_enforced == 2`,
   - If `lock_delay_enforced == 3` -> No way to select other value in the app and selected value in setup is shown.


What do you think? @jesmrec @abelgardep @JuancaG05
