### ISSUE TITLE
Replace update wizard with release notes

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3442]
Actually, when a new amazing feature is released, an update wizard with slides and images is created to illustrate it. This is something very visual and nice to see but not very practical because:

- It takes longer to be done
- Some features are not easy to be represented with some shapes and colors
- It is not complete

So, i suggest to use a release notes report that is previewed just after the upgrading, in which all the changelog items are listed. Many apps go for this approach. iOS app could be a reference. This is how iOS shows the release notes:

![Screen Shot 2022-02-08 at 10 44 16](https://user-images.githubusercontent.com/14894746/152961531-cd64df19-79ed-4809-b105-b08377392681.png)

Kind of proposal:

- Create and maintain a data structure that contains the news for every release. iOS example: https://github.com/owncloud/ios-app/blob/master/ownCloud/Release%20Notes/ReleaseNotes.plist
- Every feature developed, adding a new entry to the correspondent (not necesary) 
-  Updates will show the list, not fresh installs.
- Brandable option to show/hidden. Always open for Google Play, hidden for customers?

Opinions, ideas... welcome. 

Maybe @hosy could give some light about the internal mechanism to handle the information to be included in the release notes.

### TASKS
- [x] Research (if needed)
- [x] Create branch feature/release_notes
- [x] Development tasks
  - [x] Create a new activity: ReleaseNotesActivity
  - [x] Apply a similar design to the iOS screenshot: Title, RecyclerView, Footer, and proceed button using ConstraintLayout
  - [x] Create a new viewModel for the activity
  - [x] Create a new class ReleaseNote(similar to [FeatureItem](https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/features/FeatureList.java#L82)) that will store the title, subtitle and type. (type could be an enum with a toDrawableRes function that returns the actual image to display)
  - [x] Create a new dummy list with some sample notes just to test that the notes are retrieved from the ViewModel
  - [x] Print the dummy list retrieved from the ViewModel in the recycler view (Adapter, ViewHolder, LayoutManager..)
  - [x] Check current logic to [display or not the initial wizard](https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java#L140) and modify it to show the initial wizard on fresh installments and the release notes on updates from previous versions (only show the release notes if the list is not empty)
  - [x] Clear the dummy list -> emptyList() and leave it prepared to add the release notes for the specific version.
  - [x] Create new `setup.xml` option to handle visibility, similar to current `wizard_enabled`
  - [x] Add UI tests
  - [x] Add calens item
  - [x] Add a new step in the release template to fill the release notes for that version.
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/release_notes into master

### PR

- App
- Library (if needed)

**Comment by tbsbdr** [comment]
very nice 👍
one remark regardng accessibility

Please be sure to have enough contrast for the small text on blue / white background (even if a more accentuated textcolor could mean, that the screen looks more "crowded"  - but visually impaired people will thank us for being accessible :) )
"enough" contrast means: WCAG 2.0 level AA requires a contrast ratio of at least **4.5:1** for normal text 

![image](https://user-images.githubusercontent.com/26610733/159486187-108ef6b4-519f-463f-bab7-7b9d7a254996.png)

in case your not familiar with contrast check: enter text-color and background color here: https://webaim.org/resources/contrastchecker/https://webaim.org/resources/contrastchecker/

Chrome has also a very nice build-in contrast checker in dev-tools (https://webdesign.tutsplus.com/articles/how-to-use-the-contrast-checker-in-chrome-devtools--cms-31504)
![image](https://user-images.githubusercontent.com/26610733/159488471-1ec06a0b-982a-4ebc-949d-9987ba56ed4a.png)

**Comment by davcres** [comment]
Thank you @tbsbdr. 
About the contrast, the dark blue background is from the iOS app, in the Android one we are trying to put black and gray text on white background, but thanks for the information, it is very useful. 
I leave you a screenshot of the Android design.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/78238260/159456489-6c755326-3287-4039-9f84-5dd89545c838.png">
