### ISSUE TITLE
[TECHNICAL] Review SonarCloud output

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3443]
Right now, when the SonarCloud analysis is triggered, it says we have several issues in the output report. **Vulnerabilities** and **Security hotspots** will be our priority now, as they are the most critical.

Also, we detected SonarCloud analysis is not triggered correctly in master and in branches whose origin is master. A little research about this could also be done here.

### TASKS

- [ ] Look for the security vulnerabilities and hotspots location in the SonarCloud analysis
- [ ] Create branch technical/sonar_issues
- [ ] Development tasks
  - [ ] Solve vulnerabilities
  - [ ] Solve security hotspots
- [ ] Research about why is SonarCloud not correctly triggered in some branches 
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch technical/sonar_issues into master

**Comment by JuancaG05** [comment]
Moved to enterprise repository
