### ISSUE TITLE
[FEATURE REQUEST] Open with action trigger an edit action

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3475]
At the moment the `open with` action triggers an [ACTION_VIEW](https://developer.android.com/reference/android/content/Intent#ACTION_VIEW).

Let's check if `open with` could trigger an `EDIT` action so users don't need to open the files only via documents provider but also within the ownCloud app.

### TASKS

- [x] Research 
- [x] Create branch feature/edit_action
- [x] Development tasks
  - [x] Check if `open with` could trigger an `EDIT` action -> Not necessary, `ACTION_VIEW` also allows to edit the document. `ACTION_EDIT` limits the different apps that the document can be opened with
  - [x] Adapt SynchronizeFileOperation to check always for local changes
  - [x] Adapt SynchronizeFolderOperation to sync not only av. offline files but all downloaded files
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/edit_action into master
