### ISSUE TITLE
Bump target SDK to Android 12 (31)

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3485]
We should bump the compileSdk and targetSdk to 31 since there are some dependencies that require those versions.

To do it, we need to verify that the ownCloud App supports each point in https://developer.android.com/about/versions/12/behavior-changes-12

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/feature_name
- [x] Research which Android12 features must be checked inside the app, due to feasible changes.
- [x] Development tasks
  - [x] Develop changes
  - [x] ...
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Check if in is installable from Internal testing track in Android 12
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by hannesa2** [comment]
This is my attempt https://github.com/owncloud/android/pull/3512

**Comment by fesave** [comment]
## Apps targeting API 31+

[Behaviour changes](https://developer.android.com/about/versions/12/behavior-changes-12)

### [User experience](https://developer.android.com/about/versions/12/behavior-changes-12#ux)

- [ ] Custom notifications
- [ ] Android App Links verification changes
- [ ] PiP Mode
- [ ] Toast redesign

### [Security and privacy](https://developer.android.com/about/versions/12/behavior-changes-12#security-privacy)

- [ ] Approximate location
- [ ] Modern SameSite cookies in WebView
  - [ ] Test SameSite behaviors in your app
- [ ] Motion sensors are rate-limited
- [ ] App hibernation
- [ ] Attribution declaration in data access auditing
- [ ] ADB backup restriction
- [ ] Safer component exporting
- [ ] Messages in Android Studio
- [ ] Pending intents mutability
  - [ ]  Test the pending intent mutability change
  - [ ] Unsafe intent launches

### [Performance](https://developer.android.com/about/versions/12/behavior-changes-12#performance)

- [ ] Foreground service launch restrictions
- [ ] Exact alarm permission
- [ ] Disable the behavior change
- [ ] Notification trampoline restrictions
   - [ ] Identify which app components act as notification trampolines
   - [ ] Update your app
   - [ ] Toggle the behavior

### [Backup and restore](https://developer.android.com/about/versions/12/behavior-changes-12#backup-restore)

- [ ] D2D transfer functionality changes
- [ ] New include and exclude format
- [ ] XML format changes
- [ ] Manifest flag for apps

### [Connectivity](https://developer.android.com/about/versions/12/behavior-changes-12#connectivity)

- [ ] Concurrent Peer-to-Peer + Internet Connection
- [ ] Compatibility
- [ ] mDNSResponder native API

### [Vendor libraries](https://developer.android.com/about/versions/12/behavior-changes-12#vendor-libraries)

- [ ] Vendor-supplied native shared libraries

### [Vendor libraries](https://developer.android.com/about/versions/12/behavior-changes-12#non-sdk-restrictions)

**Comment by fesave** [comment]
After performing an examination of the .apk with the [tool provided by Google](https://developer.android.com/guide/app-compatibility/restrictions-non-sdk-interfaces#test-veridex-tool) to check how many non-SDK interfaces are currently in the project, this is the result:

65 hidden API(s) used: 10 linked against, 55 through reflection:

     - 48 in unsupported
     - 2 in blocked
     - 1 in max-target-o
     - 11 in max-target-p
     - 3 in max-target-q
     - 0 in max-target-r

By consulting the table that Google published from API 29, we can deduce that:

![non-sdk table](https://user-images.githubusercontent.com/49989790/158761114-1b000c1d-7c1e-45e9-86a6-d072e7e885b9.png)

Most of our APIs are not supported, but currently, they are not restricted and our application can use them, we have to be careful with them in case they change and make the app not work properly.

**Comment by jesmrec** [comment]
Will check the impacting new features with API 31 and older to assure nothing is broken

||Android 12 | Android < 12
-|-|-
|Custom Notifications | | |
|Toast Redesign | | |
|Modern SameSite cookies in WebView | | 
|App hibernation| | |
|Safer component exporting | | | 
| Pending intents mutability | | | 
| Unsafe intent launches | | | 
| Foreground service launch restrictions | | | 
| Notification trampoline restrictions | | 
| Tests | | |
