### ISSUE TITLE
[RELEASE] 2.20

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3497]
### TASKS:

 - [ ] [GIT] Create branch release/1.0.14 in owncloud/android-library from master
 - [ ] [GIT] Create branch release/2.20 in owncloud/android from master
 - [ ] [DEV] Update version number and name in build.gradle in owncloudComLibrary module
 - [ ] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [ ] [DIS] Create a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD
 - [ ] [DIS] Move all changelog files from the unreleased folder to the new version folder
 - [ ] [DIS] Update screenshots, if needed, in README.md
 - [ ] [QA] Design Test plan
 - [ ] [QA] Regression Test plan
 - [ ] [DIS] Generate test bundle from `release/2.20` branch in owncloud/android
 - [ ] [GIT] Create and sign tag 'oc-android-2.20' in HEAD commit of release branch, in owncloud/android
 - [ ] [GIT] Create and sign tag '1.0.14' in HEAD commit of release branch, in owncloud/android-library
 - [ ] [DIS] Generate final bundle from signed commit in owncloud/android
 - [ ] [COM] Inform `#release_coordination` and `#marketing` in internal chat
 - [ ] [GIT] Merge branch `release/1.0.14` in owncloud/android-library, into master
 - [ ] [GIT] Merge branch `release/2.20` in owncloud/android, into master
 - [ ] [DIS] Upload & publish release bundle and changelog in Play Store
 - [ ] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [ ] [GIT] Publish a new release in owncloud/android
 - [ ] [DIS] Create post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))
 - [ ] [DIS] Upload release APK and bundle to internal owncloud instance
 - [ ] [GIT] Merge master branch into stable, in owncloud/android-library
 - [ ] [GIT] Merge master branch into stable, in owncloud/android
 - [ ] [DOC] Update documentation with new stuff (notify rocketchat #documentation-internal in advance!)

_____

**Comment by fesave** [comment]
ownCloud's logo does not appear in [F-Droid's store](https://f-droid.org/en/packages/com.owncloud.android/) and we have two identical images of the login view, Should we check them for this release or create a new issue to fix in the future?

**Comment by jesmrec** [comment]
updates are automatic in F.droid but this problem is weird. We have to take a look.

**Comment by fesave** [comment]
After taking a look at [f-droid's doc](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/) I have added the icon to the specific folder, I think it will fix the icon bug.

![Captura de pantalla 2022-02-10 a las 9 35 08](https://user-images.githubusercontent.com/49989790/153371879-98efcd48-78ca-4330-a845-31ec5f34ae2a.png)

**Comment by jesmrec** [comment]
### (2)

1. Select a non-empty folder
2. Click on sync (circle arrow icon on the top)

Current: content inside is not synced
Expected: content synced

Pixel2 v11, Nexus6P v7
`afae250f`

**Comment by jesmrec** [comment]
`2.20` is approved on my side.

Regression test: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.20/Regression.md
Automatic tests report: https://reports.cucumber.io/reports/9cf723f4-486c-44a2-8cee-c9fe598d401e

Approved commits:

app: `1d4d17d`
library: `a9a6ca6d`

Devices:

Nexus 6P, Android 7
Huawei 6P, Android 9
Pixel2, Android 11

IDE version: `Android Studio Bumblebee | 2021.1.1 Patch1`

Good job, team!!!
