### ISSUE TITLE
[FEATURE REQUEST] Improve UI design for passcode screen

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3516]
The passcode screen is a bit outdated in UI terms, so it would be great to perform a design improvement on it. Some mockups will be created so that we can compare among the current design and several proposals, also trying to align design with iOS.

### TASKS

- [x] Research (if needed)
- [ ] Create mockups
- [x] Create branch feature/passcode_screen
- [x] Development tasks
  - [x] Constraint layout
  - [x] Implement numeric keyboard
  - [x] Change passcode from Array<String> to String
  - [x] Remove attributes setters
  - [x] Fit keyboard for all screen sizes
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/passcode_screen into master

### PR
App: #3582 
Library (if needed): Not needed for this issue

**Comment by tripplehay** [comment]
Sounds like a really good idea to me the passcode screen is outdated in aspect of designing.

**Comment by jesmrec** [comment]
Some examples of different existing styles:

|iOS oC app| nC | Dropbox |
|:-:|:-:|:-:|
![Screen Shot 2022-02-21 at 14 13 35](https://user-images.githubusercontent.com/14894746/154968850-af7e9e66-d70c-49c9-bbe4-5b3ad851b56f.png)|![Screenshot_20220221_145034](https://user-images.githubusercontent.com/14894746/154968871-92e2df93-4f83-447b-94c9-86a85ac6b567.png)|![Screenshot_20220221_145537](https://user-images.githubusercontent.com/14894746/154968880-a8d5b9bf-f3f2-4621-9746-8dd893f4c8e6.png)|
