### ISSUE TITLE
[FEATURE REQUEST] Make document provider visibility independent from locking methods

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3520]
Actually, the feature is tied to the passcode/pattern.

Option will be independent from locking/methods with the same behaviour

### TASKS

- [x] Research
- [x] Create branch feature/doc_provider_visibility
- [x] Development tasks
  - [x] Change visibility condition in document provider
  - [x] Make preference available even with no lock method enabled
  - [x] Adapt unit tests
  - [x] Adapt UI test
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/doc_provider_visibility into master
