### ISSUE TITLE
[FEATURE REQUEST] Extend lock enforcing methods to make them more flexible 

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3543]
New behaviour:

- `lock_enforced` will be `integer` with four different values:
  - `0` -> not forced (default)
  - `1` -> dialog (current behaviour). User will decide whether pattern/passcode
  - `2` -> passcode enforced
  - `3` -> pattern enforced

- If the app is installed from scratch, the option set in `lock_enforced` will be applied.

- Upgrades. When user upgrades from previous version. Here we have two options:

    - App was unlocked before. No locking method set. In this case, the expected behaviour will be the same as the clean installation.

   - App was locked before. A locking method was set in the previous version:

       - When passcode was set in the previous version:
             - If `lock_enforced == 0` -> nothing happens in the start. Option visible in settings (not enforced anymore)
             - If `lock_enforced == 1` -> nothing happens in the app start. Option hidden in settings (enforced, not switchable)
             - If `lock_enforced == 2` -> nothing happens in the app start. Option hidden in settings (enforced, not switchable)
             - If `lock_enforced == 3`: 
             · After unlocking the app with the existing passcode, a pattern is asked in a mandatory way (not skippable). From now on, only pattern will be used to unlock. 
             · Biometrical will be also reset, but asked to be enabled after entering the correct pattern
             · Option hidden in settings (enforced, not switchable)

       - When pattern was set in the previous version:
             - If `lock_enforced == 0` -> nothing happens in the start. Option visible in settings (not enforced anymore)
             - If `lock_enforced == 1` -> nothing happens in the app start. Option hidden in settings (enforced, not switchable)
             - If `lock_enforced == 2` -> 
             · After unlocking the app with the existing passcode, a pattern is asked in a mandatory way (not skippable). From now on, only pattern will be used to unlock. 
             · Biometrical will be also reset, but asked to be enabled after entering the correct passcode
             · Option hidden in settings (enforced, not switchable)
             - If `lock_enforced == 3` -> nothing happens in the app start. Option hidden in settings (enforced, not switchable)

### TASKS

- [X] Create branch feature/custom_lock_enforced
- [X] Development tasks
  - [X] Implement new options due to new AC
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/custom_lock_enforced into master

### PR

- App #3544
