### ISSUE TITLE
[RELEASE] 2.20_oem

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3550]
### TASKS:

- [ ] Approve and merge changes in ownBrander
  - [ ] Passcode digits -> https://github.com/owncloud/ownbrander/issues/998
  - [ ] Upgrade version to 2.20
  - [ ] New path of apks/bundles -> https://github.com/owncloud/ownbrander/issues/1018
- [ ] [DIS] Deploy and block button
- [ ] [QA] Generate final APKs files from signed commit in builder machine  and perform some basic operations 
- [ ] [QA] Check that bundle is correctly generated and apk family could be installed in device from bundle
- [ ] [GIT] Create and sign tag `oc-android-2.20_oem` in HEAD commit of `release_2.20_oem` branch or 2.20 commit (depending on if there's new changes or not), in owncloud/android
- [ ] [DIS] Enable button

_____

**Comment by jesmrec** [comment]
Done!
