### ISSUE TITLE
[MDM] Making code more scalable

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3553]
[EPIC] -> https://github.com/owncloud/android/issues/3398

Currently, every MDM configuration is handled in the place the code is written for. 

For example, in the [current MDM branch](https://github.com/owncloud/android/pull/3419):

https://github.com/owncloud/android/blob/0f5e4cba3875f32d321758850bb104344679ccfe/owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt#L656

The idea is creating a specific provider to handle all stuff requiring MDM, like setting priorities together with `setup.xml` and provide the value that the code needs in every place.
 
Other ideas to improve are welcome.

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/mdm_scalable
- [x] Development tasks
  - [x] Create a new provider for MDM
  - [x] Retrieve the MDM restrictions from the new provider
  - [x] Cache the MDM restrictions in the new provider
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/mdm_scalable into feature/mdm

**Comment by abelgardep** [comment]
Already merged into https://github.com/owncloud/android/pull/3419
