### ISSUE TITLE
[FEATURE REQUEST] Improvements for the UI in the file details screen

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3557]
The view for the file details is currently a bit outdated in terms of design. It's very improvable, and we can also add or remove some of the information we show currently:

![Screenshot_20220216_125504](https://user-images.githubusercontent.com/57049315/154271385-c62aba2d-3c50-42d1-835b-33e40548f9fa.png)

### TASKS

- [ ] Research
- [ ] Create branch feature/improve_ui_file_details
- [ ] Development tasks
  - [ ] Substitute the RelativeLayout by a ConstraintLayout
  - [ ] Make "Type:", "Size:" and "Modified:" bold
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/improve_ui_file_details into master

**Comment by jesmrec** [comment]
Some other approaches

|iOS app| BOX | Google Drive |
|:-:|:-:|:-:|
<img width="340" alt="Screenshot 2022-02-16 at 14 19 18" src="https://user-images.githubusercontent.com/14894746/154275223-d97395e5-fee4-4aae-8743-084d4e0ae398.png">|![Screenshot 2022-02-16 at 14 23 37](https://user-images.githubusercontent.com/14894746/154275702-d2cf7a64-6b99-4106-b81c-a147f6cadd5c.png)|![Screenshot 2022-02-16 at 14 21 47](https://user-images.githubusercontent.com/14894746/154275820-9d643fa3-7d8f-4de0-9f6e-e5b751fb53ae.png)|

**Comment by jesmrec** [comment]
- let code in Java
- No tests (ftm)
- Mockups to be approved

**Comment by tbsbdr** [comment]
Hey, jep - agree - there should happen some polishing 👨‍🎨

One remark that seems important to me, because it lowers complexity and makes it easier to perceive table-information:
In our usecases the infos are presented in `key`:`value` pairs like `Date`: `Yesterday`. Regardless of the alignment, the following examples show a "visual emphasis" of the `value` by making the value bolde, giving it more contrast or making it bigger. That is imo a good approach to lower visual complexity in tables.

### What I mean:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/26610733/155149736-c47eedb1-849b-4514-bcb3-70973be4c681.png">

### Example 1:
![IMG_08654CECB3DF-1](https://user-images.githubusercontent.com/26610733/155147344-d771e4c0-4606-4d85-9b37-bad49f87f805.jpeg)

### Example 2:
![IMG_A0D9A14A0116-1](https://user-images.githubusercontent.com/26610733/155147355-0addd4d9-1b46-4214-9b5e-bb74e32bc5d2.jpeg)

### Example 3:
![IMG_6BBB5D1142A1-1](https://user-images.githubusercontent.com/26610733/155147361-cef66fbd-8168-4353-b849-80ac68fb005e.jpeg)

### Example 4:
![IMG_65EDBDCAB9EB-1](https://user-images.githubusercontent.com/26610733/155147370-4099b364-71bc-45bb-9bcc-1879a3649c90.jpeg)

### Example 5:
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/26610733/155147411-4eb956dc-53d2-4a62-bef7-2b841443374b.png">

### Example 6:
![image](https://user-images.githubusercontent.com/26610733/155147605-9f53cc00-b737-4f17-8d80-40d115996fd5.png)
