### ISSUE TITLE
[FEATURE REQUEST] Improve UI design for pattern screen

### ISSUE THREAD

**Issue by fesave** [owncloud/android#3580]
The passcode screen is a bit outdated in UI terms, so it would be great to perform a design improvement on it. Some mockups will be created so that we can compare among the current design and several proposals.

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/improve_pattern_screen
- [x] Development tasks
  - [x] Add a back arrow to cancel in the toolbar
  - [x] Align the design with the new passcode's design
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by davcres** [comment]
Hello @tbsbdr.
We are redesigning the pattern screen, and we want to ask you which option is better for tablets.
| Old design | First option | Second option |
|:-:|:-:|:-:|
| <img width="300" alt="Captura de pantalla 2022-03-25 a las 9 17 48" src="https://user-images.githubusercontent.com/78238260/160095204-65f39b8b-3ff2-4b90-a602-35bc152f693b.png"> | <img width="300" alt="Captura de pantalla 2022-03-25 a las 9 17 48" src="https://user-images.githubusercontent.com/78238260/160095275-7de37edd-010d-4e6e-a3ac-02f5163ee0b8.png"> | <img width="300" alt="Captura de pantalla 2022-03-25 a las 9 33 54" src="https://user-images.githubusercontent.com/78238260/160095296-00bfd131-6d75-4dac-bb89-ffb84164b605.png"> |

The first option is very similar to the old one but the second one leaves more space between the text and the pattern.
Maybe a third option could be join the text with the pattern of the second option.

Thank you.

**Comment by tbsbdr** [comment]
I would prefer the first option, because "Place Related Elements near Each Other" (https://www.nngroup.com/articles/gestalt-proximity/) and the whitespace around looks to me more noble 👑

I agree on removing "Cancel" as the primary action in this screen is imo also a good idea as this is obviously not the primary action here ;-)
