### ISSUE TITLE
[TECHNICAL] Bump target SDK to Android 13

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3617]
**Deadlines**
New apps: August 1, 2023
Updates: November 1, 2023

Source: https://support.google.com/googleplay/android-developer/answer/11926878

Android 13 overview: https://developer.android.com/about/versions/13/overview

All apps: https://developer.android.com/about/versions/13/behavior-changes-all
Target 33: https://developer.android.com/about/versions/13/behavior-changes-13

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App https://github.com/owncloud/android/pull/3972
- Library (if needed) https://github.com/owncloud/android-library/pull/550

**Comment by abelgardep** [comment]
In Android 13, the notifications are off by default. And once we target Android 13 #3617 the app will have complete control over when the permission dialog is displayed. 

AFAIK, this is the only runtime permission we request that involves core functionality. But in the future could be more. So, it could be an option to ask for it within wizard #3955  explaining to the user why we need to request this permission. 
https://developer.android.com/develop/ui/views/notifications/notification-permission#new-apps

Also, there are some recommendations about permission requests:
https://developer.android.com/develop/ui/views/notifications/notification-permission#best-practices

**Comment by abelgardep** [comment]
[Behavior changes: Apps targeting Android 13 or higher](https://developer.android.com/about/versions/13/behavior-changes-13)
## Privacy
- [X] Notification permission affects foreground service appearance (Notification dialog is shown and manage notification row added in Settings screen)
- [ ] ~~New runtime permission for nearby Wi-Fi devices~~ oC does not need that permission
- [ ] ~~Granular media permissions~~ We get files via SAF
- [ ] ~~Use of body sensors in the background requires new permission~~ oC does not need that permission
## Performance and battery
- [X] Battery Resource Utilization should have no impact in the current app
## User experience
- [ ] Media controls derived from PlaybackState No real impact atm
- [ ] ~~App color theme applied automatically to WebView content~~ No dark theme (yet), so should have no impact
## Google Play services
- [ ] ~~Permission required for advertising ID~~ no ads
## Updated non-SDK restrictions
No impact
