### ISSUE TITLE
[FEATURE REQUEST] Open Privacy Policy in Chrome Custom Tabs

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3658]
Privacy policy statement is opened inside the app by using a webView. In case the privacy policy statement is not in web format (f. ex. PDF), it is not previewed.

So, moving that to CCTs could be a solution. 

### TASKS

- [x] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by fesave** [comment]
It is possible to implement CustomChromeTabs on the device, but there are a number of points to keep in mind.

The first one is that the functionality is different depending on the version of the operating system, I have tested on Android 10 and Android 12. In the first one, the [test URL](http://www.africau.edu/images/default/sample.pdf) is displayed inside a Google PDF viewer (which I have not seen installed on the device) but in Android 12 the functionality is different, as it directly asks you to download the .pdf file. And if the user cancels, they are left with a blank screen. 

Android 10  | Android 12
------------- | -------------  |
<video src="https://user-images.githubusercontent.com/49989790/167085893-55e8caad-bac0-45b6-8730-b8f90b633139.mp4" /> | <video src="https://user-images.githubusercontent.com/49989790/167085946-f6ca6e74-dce0-47f3-ad86-81bc74407e6f.mov" />

I've found a workaround to avoid this in Android 12, but I'm not convinced, it would be to add the following piece of code in front of the URL of the privacy policy:

`https://docs.google.com/gview?embedded=true&url=`

and the result would be the following:

https://user-images.githubusercontent.com/49989790/167087726-e35d8efe-6d9f-4c4a-997a-0b1ce3b4ba94.mov

You have to keep in mind that it is **MANDATORY** to have Google Chrome installed on the phone, and if not when trying to open the privacy policy, the application will crash. To avoid this, we should control by making that in case of not having Google Chrome installed opens in a Webview as we have right now with its drawbacks.
