### ISSUE TITLE
[RELEASE] 2.21

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3662]
### TASKS:

 - [ ] [GIT] Create branch release/1.0.15 in owncloud/android-library from master
 - [x] [GIT] Create branch release/2.21 in owncloud/android from master
 - [ ] [DEV] Update version number and name in build.gradle in owncloudComLibrary module
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create a folder for the new version like 2.21.0_YYYY-MM-DD
 - [x] [DIS] Move all changelog files from the unreleased folder to the new version folder
 - [x] [DIS] Update screenshots, if needed, in README.md
 - [x] [DIS] Add ReleaseNotes replacing `emptyList` with `listOf` and adding inside `ReleaseNote()` with String resources
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [DIS] Generate test bundle from `release/2.21` branch in owncloud/android
 - [x] [GIT] Create and sign tag 'oc-android-2.21.0' in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Create and sign tag '1.0.5' in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [x] [GIT] Merge branch `release/2.21` in owncloud/android-library, into master
 - [x] [GIT] Merge branch `release/1.0.15` in owncloud/android, into master
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [ ] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [GIT] Publish a new release in owncloud/android
 - [x] [DIS] Create post in central.owncloud.org ([`Category:Android + Tag:news`](https://central.owncloud.org/tags/c/news/5/android))
 - [x] [COM] Inform `#updates` and `#marketing` in internal chat
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - [x] [GIT] Merge master branch into stable, in owncloud/android-library
 - [x] [GIT] Merge master branch into stable, in owncloud/android
 - [x] [DOC] Update documentation with new stuff (notify rocketchat #documentation-internal in advance!)

_____

### BUGS & IMPROVEMENTS

- [x] (1) Sharing icon twice in Details view after downloading https://github.com/owncloud/android/issues/3662#issuecomment-1144541905 [FIXED]
- [x] (2) Sharing icon twice in Video Streaming https://github.com/owncloud/android/issues/3662#issuecomment-1144580069 [FIXED]
- [x] (3) Scrollbar in Release Notes view https://github.com/owncloud/android/issues/3662#issuecomment-1144608652
- [X] (4) Lack of empty folder message after removing all the items inside a folder https://github.com/owncloud/android/issues/3662#issuecomment-1144716669 [FIXED]
- [X] (5) Items in `More` section in Settings do not work in Android 12 https://github.com/owncloud/android/issues/3662#issuecomment-1145744903 [FIXED]

**Comment by jesmrec** [comment]
### (3) (improvement)

It'd be interesting that the new `Release Notes` view includes a tiny scroll bar, just to let know that there are more items that the ones on the screen

(no blocker, it could be addressed to new ticket)

**Comment by jesmrec** [comment]
### (4)

1. In an empty folder, upload a file
2. Remove the file, so that the folder is empty again

Current: blank view
Expected (2.20): Message `Nothing in here. Upload something`

Pixel5 Android12
Nexus 6P Android7
`a9c50986 `

**Comment by abelgardep** [comment]
> ### (1)
> 1. Click on a pdf file to download (or any other non openable inside the app)
> 
> Current:
> 
> Details view is displayed to track the download. In the top bar, the share icon appears twice:

> ### (2)
> (1) is also reproducible in the video streaming view

Both should be fixed now. Also fixed an issue with navigation when sharing current folder and come back

**Comment by jesmrec** [comment]
### (5)

By installing the app in a Android 12 device, some of the options do no work, returning an error `No app found for this section`:

https://user-images.githubusercontent.com/14894746/171821610-8637fa63-c9c5-426d-99df-f924e6b7033d.mp4

Also happens with the items in the sidebar.

Pixel5 Android12
Samsung Galaxy S10+
`8a8c700c4c`

**Comment by jesmrec** [comment]
`2.21` is approved on my side.

Regression test: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.21/Regression.md
Automatic tests report: https://reports.cucumber.io/reports/a4b74352-f2bb-4579-baa6-45c77fc744ff

Approved commits:

app: `7d16585`
library: `2dc6f30a`

Devices:

Nexus 6P, Android 7
Huawei 6P, Android 9
Pixel5, Android 12

IDE version: `Android Studio Chipmunk | 2021.2.1 Patch 1`

Good job, team!!! Ready to go.

**Comment by abelgardep** [comment]
Release out! Everything done!
