### ISSUE TITLE
[RELEASE] 2.21.1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3699]
### TASKS:

 - [ ] [GIT] Create branch release/Y.Y.Y in owncloud/android-library from master [NOT NEEDED]
 - [x] [GIT] Create branch release/2.21.1 in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create a folder for the new version like 2.21.1_2022-06-15
 - [x] [DIS] Move all changelog files from the unreleased folder to the new version folder
 - [ ] [DIS] Update screenshots, if needed, in README.md [NOT NEEDED]
 - [x] [DIS] Add ReleaseNotes replacing `emptyList` with `listOf` and adding inside `ReleaseNote()` with String resources
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [ ] [DIS] Generate test bundle from `release/X.X.X` branch in owncloud/android
 - [x] [GIT] Create and sign tag 'oc-android-2.21.1' in HEAD commit of release branch, in owncloud/android
 - [ ] [GIT] Create and sign tag 'Y.Y.Y' in HEAD commit of release branch, in owncloud/android-library [NOT NEEDED]
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [ ] [GIT] Merge branch `release/Y.Y.Y` in owncloud/android-library, into master [NOT NEEDED]
 - [ ] [GIT] Merge branch `release/2.21.1` in owncloud/android, into master
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [ ] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [GIT] Publish a new release in owncloud/android
 - [ ] [DIS] Create post in central.owncloud.org ([`Category:Android + Tag:news`](https://central.owncloud.org/tags/c/news/5/android))
 - [ ] [COM] Inform `#updates` and `#marketing` in internal chat
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - [ ] [GIT] Merge master branch into stable, in owncloud/android-library
 - [ ] [GIT] Merge master branch into stable, in owncloud/android
 - [ ] [DOC] Update documentation with new stuff (notify rocketchat #documentation-internal in advance!)

_____

**Comment by jesmrec** [comment]
Basic checks performed because minor changes were done. It's ready to go.

Automatic tests report: https://reports.cucumber.io/reports/5642fc54-ba39-4e42-8a53-fb8833ad3210

Approved commits:

app: `53e4dee3`
library: `2dc6f30a`

Devices:

Nexus 6P, Android 7
Huawei P20, Android 9

IDE version: `Android Studio Chipmunk | 2021.2.1 Patch 1`

**Comment by jesmrec** [comment]
In this release, the targetSDK was downgraded to 30 to avoid a crash related with foreground services in Android 12. Some dependencies were bumped by dependabot to new versions that are only available for targetSDK. In order to avoid  building problem, targetSDK was set to 30 and compileSDK to 31. Here some links provided by @abelgardep to clarify

https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd
https://stackoverflow.com/questions/24510219/what-is-the-difference-between-min-sdk-version-target-sdk-version-vs-compile-sd
