### ISSUE TITLE
[New arch] Migrate pending uploads to new database

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3717]
Since https://github.com/owncloud/android/issues/3426 uploads are stored in the new database.
Since https://github.com/owncloud/android/issues/2858 uploads view uses the new database to retrieve the queued, in progress, succeeded, and failed uploads.

This one should be the last issue for the uploads. We need to migrate the pending uploads to the new database, and then enqueue them, so they can be uploaded with the workers. I think that Camera Uploads don't need to be enqueued again, The workers should be enqueued yet, but needs some research.

Also, we need to check that the migration to scoped storage enqueues the pending uploads.

### TASKS
- [x] Research (if needed)
- [x] Create branch new_arch/migrate_pending_uploads
- [x] Development tasks
  - [x] Implement a new function to generate an entity from a cursor
  - [x] Next to the [migration of the files to the new database](https://github.com/owncloud/android/blob/new_arch/synchronization/owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.kt#L1040), migrate also the uploads
  - [x] Check every use of ``UploadsStorageManager`` and refactor it to eventually remove it
  - [x] Remove ``UploadBehavior.fromLegacyLocalBehavior()`` from ``RetryUploadFrom***UseCase``s
- [x] Code review and apply changes requested
- [x] Merge branch new_arch/migrate_pending_uploads into new_arch/synchronization
