### ISSUE TITLE
[RELEASE] 3.0

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3724]
Synchronization engine with [new architecture ](https://github.com/owncloud/android/milestone/43)

### TASKS:

 - [x] [GIT] Create branch release/3.0 in owncloud/android from new_arch/synchronization
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD
 - [x] [DIS] Move all changelog files from the unreleased folder to the new version folder
 - [x] [DIS] Update screenshots, if needed, in README.md
 - [x] [DIS] Add ReleaseNotes replacing `emptyList` with `listOf` and adding inside `ReleaseNote()` with String resources
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [GIT] Create and sign tag 'oc-android-3.0' in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Create and sign tag '2.0' in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [x] [GIT] Merge branch `release/3.0` in owncloud/android, into master
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [GIT] Publish a new release in owncloud/android
 - [x] [DIS] Create post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))
 - [x] [COM] Inform `#updates` and `#marketing` in internal chat
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - [x] [GIT] Merge new_arch/synchronization branch into master, in owncloud/android-library
 - [x] [GIT] Merge new_arch/synchronization branch into master, in owncloud/android
 - [x] [GIT] Merge master branch into stable, in owncloud/android-library
 - [x] [GIT] Merge master branch into stable, in owncloud/android
 - [x] [DOC] Update documentation with new stuff (notify rocketchat #documentation-internal in advance!)

_____

### QA (pending reports)

S1:

- [x] (1) Refresh new content in previews https://github.com/owncloud/android/issues/3724#issuecomment-1302054391 [FIXED]
- [x] (2) Smooth authentication process https://github.com/owncloud/android/issues/3724#issuecomment-1302057437 [WONT FIX ftm]
- [X] (35) Crash copying using document provider to root folder https://github.com/owncloud/android/issues/3724#issuecomment-1310174023 [FIXED]
- [X] (36) App does not behave correctly in certificate change https://github.com/owncloud/android/issues/3724#issuecomment-1317084182 [FIXED]

S2:

- [X] (3)  Clickable snackbar after revoking token https://github.com/owncloud/android/issues/3724#issuecomment-1302060258 [FIXED - file/folder sync]
- [x] (4) Sync badge is gone https://github.com/owncloud/android/issues/3724#issuecomment-1302062566 [FIXED]
- [x] (6) Download cancelling in file list's toolbar https://github.com/owncloud/android/issues/3724#issuecomment-1302067033 
- [ ] (16) Failed authentication in OAuth2 https://github.com/owncloud/android/issues/3724#issuecomment-1302098265
- [x] https://github.com/owncloud/android/pull/3788
- [X] (18) Uploaded files out of line are not listed till connection is recovered https://github.com/owncloud/android/issues/3724#issuecomment-1305627194 [OUT OF SCOPE]
- [ ] (20) Unknown error in oCIS when big file is uploaded https://github.com/owncloud/android/issues/3724#issuecomment-1306779506
- [X] (21) Cancelled uploads with oCIS in file list https://github.com/owncloud/android/issues/3724#issuecomment-1306807397 [NOT REGRESSION -> CREATE NEW ISSUE]
- [ ] (24) Public link not in the list if item is not in root folder https://github.com/owncloud/android/issues/3724#issuecomment-1307104937 [MAYBE SERVER RELATED] -> https://github.com/owncloud/ocis/issues/5139
- [X] (25) Remove public link in oCIS https://github.com/owncloud/android/issues/3724#issuecomment-1307116456 [FIXED]
- [x] (30) Download bar in image preview https://github.com/owncloud/android/issues/3724#issuecomment-1308375458 [NOT REP]
- [ ] (31) Ugly error when copying https://github.com/owncloud/android/issues/3724#issuecomment-1308406767 [MAYBE SERVER RELATED] -> https://github.com/owncloud/ocis/issues/5039
- [ ] (32) Conflict when moving file https://github.com/owncloud/android/issues/3724#issuecomment-1308474779
- [ ] (34) No way to cancel folder sync / av. offline https://github.com/owncloud/android/issues/3724#issuecomment-1308994548 [TO IMPROVE]
- [X] (37) Download stuff is always synced https://github.com/owncloud/android/issues/3724#issuecomment-1317374160 [wont fix now]
- [ ] [38] Sync action with folders triggers spinner / progress bar https://github.com/owncloud/android/issues/3724#issuecomment-1323685412
- [X] (40) Crash resuming upload with credentials error https://github.com/owncloud/android/issues/3724#issuecomment-1330857147 [FIXED]
- [x] (41) Conflicted file not opened https://github.com/owncloud/android/issues/3724#issuecomment-1331746326 [FIXED]

S3:

- [ ] (5) Upload stucked after running sc. st. wizard  https://github.com/owncloud/android/issues/3724#issuecomment-1302064261
- [ ] (7) Glitch in toolbar when navigating https://github.com/owncloud/android/issues/3724#issuecomment-1302073068
- [ ] (8) Bad browsing - toolbar https://github.com/owncloud/android/issues/3724#issuecomment-1302076947
- [ ] (9) Long message in copy error https://github.com/owncloud/android/issues/3724#issuecomment-1302079350
- [ ] (10) Folder recreated after being removed https://github.com/owncloud/android/issues/3724#issuecomment-1302081278
- [ ] (11) Uploads very fast https://github.com/owncloud/android/issues/3724#issuecomment-1302083472
- [ ] (12) New status for enqueued https://github.com/owncloud/android/issues/3724#issuecomment-1302085816
- [ ] (13) Clear button for enqueued list in upload https://github.com/owncloud/android/issues/3724#issuecomment-1302088619
- [ ] (14) Unav. offline option in top bar https://github.com/owncloud/android/issues/3724#issuecomment-1302090817
- [ ] (15) Disable FAB if folder lacks of writing permission https://github.com/owncloud/android/issues/3724#issuecomment-1302093300
- [ ] (17) Way to display quota in oCIS https://github.com/owncloud/android/issues/3724#issuecomment-1305597368
- [ ] (19) Downloading offline image https://github.com/owncloud/android/issues/3724#issuecomment-1305637729
- [x] (22) App closed while uploading shows `Unknown error` https://github.com/owncloud/android/issues/3724#issuecomment-1306830218
- [ ] (23) Behaviour after non-allowed streaming https://github.com/owncloud/android/issues/3724#issuecomment-1307052202
- [ ] (26) Error incorrect when sharing with existing recipient https://github.com/owncloud/android/issues/3724#issuecomment-1307162695 
- [ ] (27) Error incorrect when resharing without permissions https://github.com/owncloud/android/issues/3724#issuecomment-1307179119 [MAYBE SERVER RELATED]
- [ ] (28) Error incorrect when editing file without permissions https://github.com/owncloud/android/issues/3724#issuecomment-1307206520
- [ ] (29) Error incorrect when uploading stuff to non-permission folder https://github.com/owncloud/android/issues/3724#issuecomment-1307240881
- [ ] (33) Syncing removed file in details view does not lead to list of files https://github.com/owncloud/android/issues/3724#issuecomment-1308509276
- [ ] (39) Navigation to a non-existent folder after rejecting "Open with" or "Send" https://github.com/owncloud/android/issues/3724#issuecomment-1324908406

**Comment by jesmrec** [comment]
### (1) [P1]

1. Download a text file, or set it as av. offline
2. Go back to the list of files
3. In server, modify the text file
4. Open txt file in app

Current: download enqueued but old content displayed. By reopening the file, content is correct.
Expected: download done and new content displayed

**Comment by jesmrec** [comment]
### (2) [S1]

(unfortunately, not always reproducible)

1. Install app from scratch
2. Add basic auth account

Current: After entering credentials, app is frozen. Reopening the app not always fix the problem. 
Expected: Smooth authentication and file list process

Samsung A51 Android 12
`d470bd968`

**Comment by jesmrec** [comment]
### (3) [S2]

1. Enter in an OAuth2 account
2. In the server, remove the token
4. In the app, download a file

Current: notification not clickable in snackbar
Expected: notification clickable to redirect to login view

|master|3.0-beta.2|
|:-:|:-:|
|![Screenshot_20221004_165248](https://user-images.githubusercontent.com/14894746/193853167-8ac08124-45c9-474f-b11f-4437f53d0000.png)|![Screenshot_20221004_164946](https://user-images.githubusercontent.com/14894746/193853201-174e7478-526b-43ce-af9c-a78e9d0f5878.png)|

**Comment by jesmrec** [comment]
### (4) [S2]

1. Select a file in file list
2. Click on download or select av. offline option

Current: Sync badge is gone
Expected: Sync badge displayed

**Comment by jesmrec** [comment]
### (5) [S2]

1. Install v2.18.3 (or any version before Scoped Storage release)
2. Add account
3. Upload a very big file 
4. Before the upload ends, upgrade to current and run wizard
5. Open uploads view

Current: upload stucked and never ends.
Expected: upload resumed and finished

**Comment by jesmrec** [comment]
### (6) [S2]

1. Select a big file from the file list
2. Click on the down arrow on the toolbar to download it

File starts to download (badge is gone as [(14)](https://github.com/owncloud/android/issues/3771#issuecomment-1267163450)), the way to check it is the `Details` view.

By cancelling the selection mode, and selecting the file again, the (x) to cancel is in the toolbar. By clicking the (x), the download is cancelled but the (x) remains in the toolbar.

Expected: Download and cancel buttons should be handled dinamically in toolbar, as in `master`. That means:

- If user clicks on down arrow, the down arrow turns in (x) to cancel
- If the download is running and user clicks on (x), (x) turns into down arrow again.

Sometimes, by clicking several times in (x) after cancelling, app crashes

Behaviour is correctly implemented in `Details` view

**Comment by jesmrec** [comment]
### (7) [S3] 

Related to https://github.com/owncloud/android/issues/3498

1. Create a link on a pdf file
2. Open Links tab
3. Clink on the pdf file -> open details view
4. Select  `Open with` and open the file with an external app
5. Go back to oC app

Current: Toolbar shows `Shared by link` in the details view

**Comment by jesmrec** [comment]
### (8) [S2]

1. Open `Details` view of any file in the root folder
2. Click on Share icon on the top
3. Click on back arrow

Current: toolbar is not correct. It includes items of root folder instead of Details view
Expected: Details view items

**Comment by jesmrec** [comment]
### (9) [S3]

1. Select a folder
2. Select `Copy` 
3. Select as target folder, same folder as 1.

Current: error message is too long, and could not be read completely:

<img width="346" alt="Screenshot 2022-08-19 at 13 45 51" src="https://user-images.githubusercontent.com/14894746/185611695-c424abc9-1029-4707-b294-ef4e37ee90b8.png">

Expected (`master`): message is reduced: `It is not possible to copy a folder into a descendant`

NOTE: same for move

**Comment by jesmrec** [comment]
### (10) [S3]

1. Browse to folder `Photos`
2. Select a file to upload inside
3. Before submitting, remove the folder `Photos` in another client
4. Submit the upload

Current: `Photos` folder is created again with the picture inside
Expected: Folder was deleted, so it should trigger a `Folder error`. Maybe the current behaviour is not too evil, open to discussion

**Comment by jesmrec** [comment]
### (11) [S3]

Open to discussion: when a bunch of files is uploaded and uploads run fast. it's difficult to check what's going on in the uploads view because items move up and down very fast in a non-readable way:

https://user-images.githubusercontent.com/14894746/185399118-6aaded4a-d1e9-46bc-9146-4a6bd88870bd.mp4

**Comment by jesmrec** [comment]
### (12) [S3] 

1. Set to upload a very big file
2. When file is uploading, set to upload other files

Current: Pending files with the status `Uploading`, same as the file that is really being uploaded:

<img width="337" alt="Screenshot 2022-08-29 at 13 51 04" src="https://user-images.githubusercontent.com/14894746/187195356-8e952e4f-37b3-4ee8-82f4-fe1893b255e4.png">

Expected: different status. File uploading with `Uploading` and others with `Waiting` or similar

**Comment by jesmrec** [comment]
### (13) [S3] (improvement)

1. Upload many files manually
2. Remove device connection

Current: it may happen that the amount of enqueued files is very big. For example:

![Screenshot 2022-08-31 at 15 07 51](https://user-images.githubusercontent.com/14894746/187685959-763f9be7-bc15-4ca6-aca7-85c2bc9a0fc6.png)

Do you think it'd be interesting to add a `Clear` button to the enqueued? is it feasible to cancel works at that point?

**Comment by jesmrec** [comment]
### (15) [S3]

Comes from https://github.com/owncloud/android/issues/2653

When a folder lacks of writing permission, FAB button could be hidden/disabled. In that way, we will avoid users to perform actions that will be banned.

Permissions available in property `<oc:permissions>` with the following values:

https://github.com/owncloud/client/blob/cedf72825bc0db8e3c147958a9382ee5b411d9ea/src/common/remotepermissions.h#L42-L54

Samsung A52
`8f2d519d`

**Comment by jesmrec** [comment]
### (16)

1. Log in a OAuth2 server

Current: after first authentication, a credentials error is returned. By re-signing, everything OK
Expected: No error after first authentication

Some logs were caught over `cloud.damken.com`:

[owncloud.2022-11-03.log](https://github.com/owncloud/android/files/9929465/owncloud.2022-11-03.log)

`d470bd9685`

**Comment by jesmrec** [comment]
### (17) [S3]

1. In oCIS user dashboard, set any user's quota to 1GB
2. Open app drawer of such user

Current: xMB of 982.2 MB used
Expected: xMB of 1 GB used

Maybe not a client issue, maybe yes... open to discussion

Samsung A51, Android 12
`f14caeff2`

**Comment by jesmrec** [comment]
### (18) [S2]

1. Set several files to upload. I used 20, to have tome to perform the following steps
2. While files are uploading, remove connection. Some of them have finished, the rest will fail
3. Switch to the containing folder

Current: none of the uploaded (finished) files are there
Expected: the uploaded files are there

Samsung A51, Android 12
`f14caeff2`

**Comment by jesmrec** [comment]
### (20) [S2]

1. Upload a big file to oCIS (i used a 2GB one)
2. Wait till upload ends

Current: in uploads view, it shows `Unknown error`, but file is uploaded and listed in the list view
Expected: Finished in uploads view

Samsung A51, Android 12
`f14caeff2`

**Comment by jesmrec** [comment]
### (21) [S2]

1. in oCIS, upload several big files (to have time to perform next steps). For this example, upload 5 files
2. Cancel some of them, for example 3, in uploads view

Current: All 5 files appear in the target folder. The cancelled ones with 0B size
Expected: Cancelled files not appearing in the file list

Samsung A51, Android 12
`f14caeff2`

**Comment by jesmrec** [comment]
### (22) [S3]

1. in oCIS, upload a big file (to have time to perform next steps)
2. Before file finishes, kill the app
3. Reopen the app and check the uploads view

Current: upload with `Unknown error`
Expected (msater): upload with `App was terminated`

Samsung A51, Android 12
`f14caeff2`

**Comment by jesmrec** [comment]
### (23) [S3]

in a  https with self-signed certificate server, try to stream a video  (no matter if oCIS or oC10)

Current: message `Streaming cannot be initialized because your server certificate is untrusted. File download will start automatically`. But, file does not start to download

Expected: Two options, both work for me:
1) Change the error message, by removing the last statement.
2) Make the file download after the error is displayed 

Samsung A51, Android 12
`f14caeff2`

**Comment by jesmrec** [comment]
[24] [S2]

1. In oCIS server, create a public link over an item that is NOT in root folder

Current: link does not appear in the list till containing folder is refreshed. That does not happen in oC10. 
Expected: After creating the link, link is in the list and item is marked in the file list

Samsung A51, Android 12
`f14caeff2`

**Comment by jesmrec** [comment]
### (25) [S2]

1. In oCIS, create a public link
2. Delete the public link using the trashbin icon

Current: `It was not posible to unshare this file or folder because server could not be reached`. Server return `200` to the `DELETE` request. Link is removed finally
Expected: No error message

Samsung A51, Android 12
`f14caeff2`

**Comment by jesmrec** [comment]
(26) [S3] [No regression]

1. Share item with user
2. Try to share the same item with same user

Current: Error displayed: `It was not posible to unshare this file or folder because server could not be reached`
Expected: More accurate error

Samsung A51, Android 12
`f14caeff2`

**Comment by jesmrec** [comment]
### (27) [S3] [No regression]

1. Share item with user without sharing permission
2. Recipient shares the item with another user

Current: Error displayed: `It was not posible to share this file or folder because it was not found`
Expected: More accurate error

Samsung A51, Android 12
`f14caeff2`

**Comment by jesmrec** [comment]
### (28) [S3]

1. User1 shares txt file with User2 without edit permission
2. User2 receives the file and try to edit it
3. User2 saves changes

Current: `Unknown error` in uploads view
Expected (master): `Permission error`

Samsung A51, Android 12
`f14caeff2`

**Comment by jesmrec** [comment]
(29) [S3] [No regression]

1. User1 shares a folder with User2, with no create permission
2. User2 tries to upload something inside

Current: Unknown error in uploads view
Expected: More accurate error

Samsung A51, Android 12
`f14caeff2`

**Comment by jesmrec** [comment]
### (30) [S2]

1. Set a large image to download
2. Cancel the download in the preview 

Current: Download progress bar is not continuos, so, cancelling sometimes comes later and the cancelled image is finally downloaded:

https://user-images.githubusercontent.com/14894746/200775703-0dee1241-0f3e-48bf-a918-915ba89f79ef.mp4

Expected: Download progress bar with progress information

Samsung A51, Android 12
`f14caeff2`

Happens in:

- [X] oCIS
- [X] oC10

**Comment by jesmrec** [comment]
### (32) 

1. In app, download a txt file
2. In server, modify the txt file
3. In app, move the file to another location

Current: file is shown as conflicted
Expected: file was always remote-modified, no local modification. So, no conflict should happen.

Samsung A51, Android 12
`f14caeff2`

Happens in:

- [X] oCIS
- [X] oC10

**Comment by jesmrec** [comment]
### (33) [S3]

1. Open details view of any file
2. Click on sync -> OK
3. In server, remove the file
4. Click again on sync

current: nothing happens
expected: move back to the list of files

Samsung A51, Android 12
`f14caeff2`

Happens in:

- [X] oCIS
- [ ] oC10

**Comment by jesmrec** [comment]
### (34) 

There is no way to cancel a folder sync / av. offline. 

Samsung A51, Android 12
f14caeff2

Happens in:

- [X] oCIS
- [X] oC10

**Comment by jesmrec** [comment]
### (35) [S1]

1. Create a new document using a 3rd-party-app compatible with document provider
2. Save it in a oC account's root folder

Current: app crashes. File is always save in the parent folder. That means, by selecting A/B/C to save the file, it is saved in A/B instead. So, root folder does not have parent and make the app crash

Expected: No crash

Samsung A51, Android 12
https://github.com/owncloud/android/commit/f14caeff2afc4481ff7115058db34a801d901223

Happens in:

 -[x] oCIS
- [X] oC10

**Comment by jesmrec** [comment]
### (37) [S2]

Take a look together with (1)

1. Download any file to the device
2. Using web or any other client, modify the file
3. In app, pull to refresh

Current: new version of the file is automatically downloaded.
Expected: new version of the file not downloaded. It should be downloaded when file is opened. Automatic download when refreshing/syncing folder is for available offline stuff.

This is not a bad behaviour, but could lead to confusion for scenarios with lots of modifications and/or av. offline files. All downloaded and av. offline will behave in the same way, breaking any difference between them. Since [Download status is intended to be removed ](https://github.com/owncloud/android/issues/3289), this problem should not make us to spend a lot of time. Need to discuss.

Samsung A51 Android 12
`f14caeff2a`

Happens in:

 - [X] oCIS 
 - [X] oC10

**Comment by jesmrec** [comment]
### (38) [S2]

1. Select a folder with much content
2. Select to sync / Av. offline (no matter which one)

Current: Progress bar on the top and spinner in the screen till the sync action finishes
Expected: Progress bar and spinner only displayed in pull to refresh action. For syncing, just setting status badge should be enough

Samsung A51 Android 12
`492645dcf`

Happens in:

- [X] oCIS
- [X] oC10

**Comment by JuancaG05** [comment]
### (39) [S3]

1. In a non-downloaded file, select "Open with" or "Send"
2. Before it finishes downloading, navigate to its details view (or a preview of any file that is already downloaded)
3. Go back to the main file list before it finishes downloading
4. When it finishes downloading, close the bottom sheet

Current: After closing the bottom sheet, the app navigates to a non-existent file with the name of the file whose details (or whose preview) has been seen in step 2
Expected: No navigation, staying in the same folder

Samsung Galaxy S9 Android 9
`7d6fb80`

Happens in:

- [X] oCIS
- [X] oC10

Notes:
It happens due to the property `file` of FileActivity, from where many activities extend. When navigating to a preview or to a details view, the variable `file` is overwritten with the current file being previewed or whose details are being seen, and when closing the bottom sheet, the method `onResume` of FileDisplayActivity tries to navigate to `file` expecting it as a folder.

**Comment by jesmrec** [comment]
### (40) 

1. In a OAuth2 account, upload a big file
2. While the upload is being done, remove session from admin dashboard -> Upload will fail with `Credentials error`
3. Tap on the failed upload in the uploads view

Current: crash
Expected: moved to login view

Stack trace:

```
FATAL EXCEPTION: main
Process: com.owncloud.android, PID: 9479
java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.  at androidx.room.RoomDatabase.assertNotMainThread(RoomDatabase.java:469)
at androidx.room.RoomDatabase.query(RoomDatabase.java:525)
at androidx.room.util.DBUtil.query(DBUtil.java:86)
at com.owncloud.android.data.transfers.db.TransferDao_Impl.getTransfersWithStatus(TransferDao_Impl.java:504)
at com.owncloud.android.data.transfers.datasources.implementation.OCLocalTransferDataSource.getFailedTransfers(OCLocalTransferDataSource.kt:127)
at com.owncloud.android.data.transfers.repository.OCTransferRepository.getFailedTransfers(OCTransferRepository.kt:99)
at com.owncloud.android.usecases.transfers.uploads.RetryFailedUploadsForAccountUseCase.run(RetryFailedUploadsForAccountUseCase.kt:40)
at com.owncloud.android.usecases.transfers.uploads.RetryFailedUploadsForAccountUseCase.run(RetryFailedUploadsForAccountUseCase.kt:32)
at com.owncloud.android.domain.BaseUseCase.execute(BaseUseCase.kt:30)
at com.owncloud.android.ui.activity.UploadListActivity.onRemoteOperationFinish(UploadListActivity.java:156)
at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:398)
at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(Unknown Source:6)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8663)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

Samsung A51, Android 12
`b15316ff7`

Happens in:

- [X] oCIS
- [X] oC10

**Comment by jesmrec** [comment]
### (41) [S2]

1. Cause a conflict in a file (i used txt file)
2. Tap on the file to fix the conflict

Current: File is not opened 
Expected: File opened to fix the conflict

Samsung A51, Android 12
`b15316ff7`

Happens in:

- [X] oCIS
- [X] oC10

**Comment by JuancaG05** [comment]
Before 3.0, we are releasing a 3.0 beta.3 with the following fixes:
- (1) Refresh new content in previews https://github.com/owncloud/android/issues/3724#issuecomment-1302054391 [FIXED]
- (35) Crash copying using document provider to root folder https://github.com/owncloud/android/issues/3724#issuecomment-1310174023 [FIXED]
- (36) App does not behave correctly in certificate change https://github.com/owncloud/android/issues/3724#issuecomment-1317084182 [FIXED]
- (3) Clickable snackbar after revoking token https://github.com/owncloud/android/issues/3724#issuecomment-1302060258 [FIXED - file/folder sync]
- (4) Sync badge is gone https://github.com/owncloud/android/issues/3724#issuecomment-1302062566 [FIXED]
- (25) Remove public link in oCIS https://github.com/owncloud/android/issues/3724#issuecomment-1307116456 [FIXED]
- (40) Crash resuming upload with credentials error https://github.com/owncloud/android/issues/3724#issuecomment-1330857147 [FIXED]
- (41) Conflicted file not opened https://github.com/owncloud/android/issues/3724#issuecomment-1331746326 [FIXED]
