### ISSUE TITLE
[New arch] Remove account

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3730]
Removing an account from the app should:
- Clean the files database for that account (related to [Report 7](https://github.com/owncloud/android/issues/2818#issuecomment-1198961987)) [TO DO]
- Clean the downloaded files for that account [DONE]
- Clean the uploads database for that account [DONE]
- Clean the pending uploads in the workmanager [DONE]
- Clean the pending downloads in the workmanager [DONE]
- Reset camera uploads (picture or videos) if that account is the attached one [DONE]
- Clean capabilities for account [TO DO]
- Clean shares for account [TO DO]
- Clean quotas for account [TO DO]
- Clean cached, temporals or any other files in the local storage for that account [TO DO] (Files under `com.owncloud.android.debug > files > tmp` are not removed)
- Notify the removal to the documents provider [DONE]

Set same behaviour when removing the account from device settings (out of app).

### TASKS

- [x] Research which of the previous are already done
- [x] Create branch new_arch/remove_account
- [x] Development tasks
  - [x] Remove account from device
  - [x] Clean the files database for that account
  - [x] Clean the downloaded files for that account
  - [x] Clean the uploads database for that account
  - [x] Clean the pending uploads in the workmanager
  - [x] Clean the pending downloads in the workmanager
  - [x] Reset camera uploads (picture or videos) if that account is the attached one
  - [x] Clean capabilities for account
  - [x] Clean shares for account
  - [x] Clean quotas for account
  - [x] Clean cached, temporals or any other files in the local storage for that account
  - [x] Notify the removal to the document provider
  - [x] Set same behaviour when removing the account from device settings
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch new_arch/remove_account into new_arch/synchronization
