### ISSUE TITLE
[FEATURE REQUEST] [oCIS] Respect Capability "privateLinks": false

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#3732]
**Is your feature request related to a problem? Please describe.**

oCIS doesn't have the oC10-style private links. It's also announced as false in the capabilities:

```
% cat ocis.capabilities | jq .ocs.data.capabilities.files
{
  "privateLinks": false,
  "bigfilechunking": false,
  "undelete": true,
  "versioning": true,
  "favorites": false,
  "blacklisted_files": [],
  "tus_support": {
    "version": "1.0.0",
    "resumable": "1.0.0",
    "extension": "creation,creation-with-upload",
    "max_chunk_size": 100000000,
    "http_method_override": ""
  },
  "archivers": [
    {
      "enabled": true,
      "version": "2.0.0",
      "formats": [
        "tar",
        "zip"
      ],
      "archiver_url": "/archiver",
      "max_num_files": "10000",
      "max_size": "1073741824"
    }
  ],
  "app_providers": [
    {
      "enabled": true,
      "version": "1.0.0",
      "apps_url": "/app/list",
      "open_url": "/app/open",
      "new_url": "/app/new"
    }
  ]
}
```

**Describe the solution you'd like**

Android app should respect the capability, and hide the private link entries on all screens.

**Additional context**

Desktop issues:

- https://github.com/owncloud/client/issues/9573
- https://github.com/owncloud/client/issues/8998

iOS issue:
- https://github.com/owncloud/ios-app/issues/1138

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/private_link_capability
- [x] Development tasks
  - [x] Add a new field in capabilities response
  - [x] Add a new field in capabilities domain model
  - [x] Add a new field in capabilities entity
  - [x] Show or hide the private link button when sharing depending on the capability
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/private_link_capability into master

### PR

- App https://github.com/owncloud/android/pull/3738
- Library (if needed) https://github.com/owncloud/android-library/pull/505

**Comment by michaelstingl** [comment]
> Silly question came to my mind: private link means link like `http://<url>/f/<file-id>` , right?

Yes exactly. `http://<url>/f/<file-id>` or `http://<url>/index.php/f/<file-id>`

**Comment by abelgardep** [comment]
With current behavior, we don't show the private link if it is not in the files propfind.

In case the capability is false, the server shouldn't send the private link in the propfind, right?

**Comment by michaelstingl** [comment]
> With current behavior, we don't show the private link if it is not in the files propfind.
> 
> In case the capability is false, the server shouldn't send the private link in the propfind, right?

Yes, oCIS doesn't include the private links in the `PROPFIND` response.
