### ISSUE TITLE
[RELEASE] 3.0 Beta1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3743]
### TASKS:

 - [x] [GIT] Create branch release/Y.Y.Y in owncloud/android-library from master
 - [x] [GIT] Create branch release/X.X.X in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Add ReleaseNotes replacing `emptyList` with `listOf` and adding inside `ReleaseNote()` with String resources
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [DIS] Generate test bundle from `release/X.X.X` branch in owncloud/android
 - [x] [GIT] Create and sign tag 'oc-android-X.X.X' in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Create and sign tag 'Y.Y.Y' in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [x] [GIT] Merge branch `release/X.X.X` in owncloud/android, into master
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [GIT] Publish a new release in owncloud/android
 - [x] [DIS] Create post in central.owncloud.org ([`Category:Android + Tag:news`](https://central.owncloud.org/tags/c/news/5/android))
 - [x] [COM] Inform `#updates` and `#marketing` in internal chat
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance

_____
