### ISSUE TITLE
[RELEASE] 2.21.2 + 2.21.2_oem

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3744]
Short release that will include:

- Open in web https://github.com/owncloud/android/issues/3672
- Support for `privateLinks` capability https://github.com/owncloud/android/issues/3732
- Last translations, including estonian.

### TASKS:

 - [x] [GIT] Create branch release/Y.Y.Y in owncloud/android-library from master
 - [x] [GIT] Create branch release/X.X.X in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD
 - [x] [DIS] Move all changelog files from the unreleased folder to the new version folder
 - [x] [DIS] Update screenshots, if needed, in README.md
 - [x] [DIS] Add ReleaseNotes replacing `emptyList` with `listOf` and adding inside `ReleaseNote()` with String resources
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [DIS] Generate test bundle from `release/X.X.X` branch in owncloud/android
 - [x] [GIT] Create and sign tag 'oc-android-X.X.X' in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Create and sign tag 'Y.Y.Y' in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [x] [GIT] Merge branch `release/Y.Y.Y` in owncloud/android-library, into master
 - [x] [GIT] Merge branch `release/X.X.X` in owncloud/android, into master
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [GIT] Publish a new release in owncloud/android
 - [x] [DIS] Create post in central.owncloud.org ([`Category:Android + Tag:news`](https://central.owncloud.org/tags/c/news/5/android))
 - [x] [COM] Inform `#updates` and `#marketing` in internal chat
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - [x] [GIT] Merge master branch into stable, in owncloud/android-library
 - [x] [GIT] Merge master branch into stable, in owncloud/android
 - [x] [DOC] Update documentation with new stuff (notify rocketchat #documentation-internal in advance!)

_____

**Comment by jesmrec** [comment]
QA checks

- [X] Install from scratch
- [X] Transfers (uploads/downloads)
- [X] Security checks
- [X] Private link capability
- [X] Open in web
- [X] Shares in propfind
- [X] Upgrade from 2.21.1

**Comment by jesmrec** [comment]
2.21 .2 is approved on my side.

Approved commits:

app: `07e757b42`
library: `0be462c9a`

Devices:

Samsung A51 Android 12

Automatic tests report: https://reports.cucumber.io/reports/6f67f7df-803c-45f7-95b2-d37aaa035633

IDE version: Android Studio Chipmunk | 2021.2.1 Patch 1

**Comment by jesmrec** [comment]
# 2.21.2_oem

Check list

- [X] Create oB PR -> https://github.com/owncloud/ownbrander/pull/1040
- [ ] Fix building scripts
- [ ] Disable button
- [ ] Sign and push new tag `oc-android-2.21.2_oem`
- [ ] Merge ownBrander stuff -> https://github.com/owncloud/ownbrander/pull/1040
- [ ] Merge scripts PR
- [ ] Deploy ownBrander
- [ ] Test builds
- [ ] Enable button
- [ ] Ping https://github.com/owncloud/enterprise/issues/5346

**Comment by jesmrec** [comment]
All checks passed. Ready to go
