### ISSUE TITLE
[RELEASE] 3.0 Beta.2

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3771]
Will be released with P2 and P3 pending reports from Beta.1 as well as new reports and feedback. 

List of issues, ordered by priority:

**P1 (must in Beta.2)**

- [ ] (10) Refresh new content in previews https://github.com/owncloud/android/issues/3771#issuecomment-1267152234 [postponed]
- [X] (11) Crash when moving av. offline folder https://github.com/owncloud/android/issues/3771#issuecomment-1267154586 [FIXED]
- [x] (17) ANR when selecting many files https://github.com/owncloud/android/issues/3771#issuecomment-1267192824 [FIXED]
- [X] (23) Logs disappearing https://github.com/owncloud/android/issues/3771#issuecomment-1293179269 [FIXED]

**P2 (must in oficial release)**

- [x] (1) Remove action blocks the UI https://github.com/owncloud/android/issues/3771#issuecomment-1266978389 [FIXED]
- [x] (2) Bad local remove behaviour https://github.com/owncloud/android/issues/3771#issuecomment-1266980128 [FIXED]
- [ ] (8) Clickable snackbar after revoking token https://github.com/owncloud/android/issues/3771#issuecomment-1267137556 [postponed]
- [x] (9) Download bar progress missing in image preview https://github.com/owncloud/android/issues/3771#issuecomment-1267147451 [FIXED]
- [ ] (14) Sync badge is gone https://github.com/owncloud/android/issues/3771#issuecomment-1267163450 [postponed]
- [ ] (16) Upload stucked after running sc. st. wizard https://github.com/owncloud/android/issues/3771#issuecomment-1267177353 [postponed]
- [X] (18) Share icon missing https://github.com/owncloud/android/issues/3771#issuecomment-1267214898 [FIXED]
- [ ] (19) Download cancelling in file list's toolbar https://github.com/owncloud/android/issues/3771#issuecomment-1267227389 [postponed]
- [X] (20) Incorrect message in notification https://github.com/owncloud/android/issues/3771#issuecomment-1278698710 [FIXED]
- [X] (22) Wrong gallery mode sorting method https://github.com/owncloud/android/issues/3771#issuecomment-1293163934 [FIXED]

**P3 (nice to have)**

- [ ] (13) Glitch in toolbar when navigating https://github.com/owncloud/android/issues/3771#issuecomment-1267159426
- [ ] (15) Bad browsing - toolbar https://github.com/owncloud/android/issues/3771#issuecomment-1267168594
- [ ] (3) Long message in copy error https://github.com/owncloud/android/issues/3771#issuecomment-1266982020
- [ ] (4) Folder recreated after being removed https://github.com/owncloud/android/issues/3771#issuecomment-1266984669
- [ ] (5) Uploads view run very fast https://github.com/owncloud/android/issues/3771#issuecomment-1266989466
- [ ] (6) New status for enqueued https://github.com/owncloud/android/issues/3771#issuecomment-1267111778
- [ ] (7) Clear button for enqueued list in upload https://github.com/owncloud/android/issues/3771#issuecomment-1267119797
- [ ] (12) Unav. offline option in top bar https://github.com/owncloud/android/issues/3771#issuecomment-1267155889
- [ ] https://github.com/owncloud/android/issues/3016
- [ ] (21) Disable FAB if folder lacks of writing permission https://github.com/owncloud/android/issues/3771#issuecomment-1278704800

**To verify**
- https://github.com/owncloud/android/issues/129 [FIXED]
- https://github.com/owncloud/android/issues/382
- https://github.com/owncloud/android/issues/1135 [IMPROVEMENT]
- https://github.com/owncloud/android/issues/2137 [NO REGRESSION]
- https://github.com/owncloud/android/issues/2376  [FIXED]
- https://github.com/owncloud/android/issues/2653 [FIXED WITH PLACE FOR IMPROVEMENT]
- https://github.com/owncloud/android/issues/3039
- https://github.com/owncloud/android/issues/3164 [TINY IMPROVEMENTS]
- https://github.com/owncloud/android/issues/3439 [FIXED]

### TASKS:

 - [x] [GIT] Create branch release/X.X.X in owncloud/android from new_arch/synchronization
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Add ReleaseNotes replacing `emptyList` with `listOf` and adding inside `ReleaseNote()` with String resources
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [DIS] Generate test bundle from `release/X.X.X` branch in owncloud/android
 - [x] [GIT] Create and sign tag 'oc-android-X.X.X' in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Create and sign tag 'Y.Y.Y' in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [x] [GIT] Merge branch `release/X.X.X` in owncloud/android, into master
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [GIT] Publish a new release in owncloud/android
 - [x] [DIS] Create post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))
 - [x] [COM] Inform `#updates` and `#marketing` in internal chat
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance

_____

**Comment by jesmrec** [comment]
### (2) [P2]

1. Download a txt file
2. Select it in the list of files -> `Remove` -> `Local only`

Current: List of files is cleaned up and file name is set on the tool bar
Expected: File loses the green bagde of dowloaded and list of files in the screen

**Comment by jesmrec** [comment]
### (3) [P3]

1. Select a folder
2. Select `Copy` 
3. Select as target folder, same folder as 1.

Current: error message is too long, and could not be read completely:

<img width="346" alt="Screenshot 2022-08-19 at 13 45 51" src="https://user-images.githubusercontent.com/14894746/185611695-c424abc9-1029-4707-b294-ef4e37ee90b8.png">

Expected (`master`): message is reduced: `It is not possible to copy a folder into a descendant`

NOTE: same for move

**Comment by jesmrec** [comment]
### (5) [P2]

Open to discussion: when a bunch of files is uploaded and uploads run fast. it's difficult to check what's going on in the uploads view because items move up and down very fast in a non-readable way:

https://user-images.githubusercontent.com/14894746/185399118-6aaded4a-d1e9-46bc-9146-4a6bd88870bd.mp4

**Comment by jesmrec** [comment]
### (6) [P3] 

1. Set to upload a very big file
2. When file is uploading, set to upload other files

Current: Pending files with the status `Uploading`, same as the file that is really being uploaded:

<img width="337" alt="Screenshot 2022-08-29 at 13 51 04" src="https://user-images.githubusercontent.com/14894746/187195356-8e952e4f-37b3-4ee8-82f4-fe1893b255e4.png">

Expected: different status. File uploading with `Uploading` and others with `Waiting` or similar

**Comment by jesmrec** [comment]
### (7) [p3] (improvement)

1. Upload many files manually
2. Remove device connection

Current: it may happen that the amount of enqueued files is very big. For example:

![Screenshot 2022-08-31 at 15 07 51](https://user-images.githubusercontent.com/14894746/187685959-763f9be7-bc15-4ca6-aca7-85c2bc9a0fc6.png)

Do you think it'd be interesting to add a `Clear` button to the enqueued? is it feasible to cancel works at that point?

**Comment by jesmrec** [comment]
### (8) [P1]

1. Enter in an OAuth2 account
2. In the server, remove the token
4. In the app, download a file

Current: notification not clickable in snackbar
Expected: notification clickable to redirect to login view

|master|3.0-beta.1|
|:-:|:-:|
|![Screenshot_20221004_165248](https://user-images.githubusercontent.com/14894746/193853167-8ac08124-45c9-474f-b11f-4437f53d0000.png)|![Screenshot_20221004_164946](https://user-images.githubusercontent.com/14894746/193853201-174e7478-526b-43ce-af9c-a78e9d0f5878.png)|

**Comment by jesmrec** [comment]
### (9) [P2]

1. Click on a big previewable file (for example, a 30M big image)

Current: Progress bar is missing
Expected: Progress bar works

**Comment by jesmrec** [comment]
### (10) [P1]

1. Download a text file, or set it as av. offline
2. Go back to the list of files
3. In server, modify the text file
4. Open txt file in app

Current: download enqueued but old content displayed. By reopening the file, content is correct.
Expected: download done and new content displayed

**Comment by jesmrec** [comment]
### (11) [P1]

1. Set a folder with subfolders in root as av. offline
2. Move the folder to any other location
3. Browse into the new location to see the av. offline folder

Current: app crashes:

```
2022-07-29 10:02:25.768 30687-30687/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.owncloud.android.debug, PID: 30687
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.domain.files.model.OCFile.getStoragePath()' on a null object reference
        at com.owncloud.android.operations.SynchronizeFolderOperation.getFolderPath(SynchronizeFolderOperation.java:533)
        at com.owncloud.android.ui.errorhandling.ErrorMessageAdapter$Companion.getResultMessage(ErrorMessageAdapter.kt:183)
        at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:275)
        at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:487)
        at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
Expected: no crash 

NOTE: same behaviour by moving a subfolder from av. offline folder.

**Comment by jesmrec** [comment]
### (12) (improvement) [P3]

1. Set a folder with many items inside as av. offline (so, the sync operation will take more time)

Current: The option `Unset as av. offline` is available in three dot menu while the folder is being synced.
Expected (current `master`): while folder is being synced, the option to  `Unset as av. offline` is available on the top bar, so only one click is required to cancel sync:

![Screenshot 2022-07-29 at 10 48 32](https://user-images.githubusercontent.com/14894746/181721841-bdaed965-0639-41ff-a053-1615a0a70af8.png)

**Comment by jesmrec** [comment]
### (14) [P2]

1. Select a file in file list
2. Click on download or select av. offline option

Current: Sync badge is gone
Expected: Sync badge displayed

**Comment by jesmrec** [comment]
### (15) [P2]

1. Open `Details` view of any file in the root folder
2. Click on Share icon on the top
3. Click on back arrow

Current: toolbar is not correct. It includes items of root folder instead of Details view
Expected: Details view items

**Comment by jesmrec** [comment]
### (16) [P2]

1. Install v2.18.3 (or any version before Scoped Storage release)
2. Add account
3. Upload a very big file 
4. Before the upload ends, upgrade to current and run wizard
5. Open uploads view

Current: upload stucked and never ends.
Expected: upload resumed and finished

**Comment by jesmrec** [comment]
### (17)

1. Create a folder that contains 1000 files
2. 3-dot-button -> `Select All`

Current: App stucked causing ANR
Expected: App not stucked

**Comment by jesmrec** [comment]
### (18)

1. User A shares an item with User B
2. User B opens list of files

Current: User B sees the item in the list, but the sharing icon on the right is missing.
Expected: User B sees the item in the list and the sharing icon on the right.

**Comment by jesmrec** [comment]
### (21) [P3]

Comes from https://github.com/owncloud/android/issues/2653

When a folder lacks of writing permission, FAB button could be hidden/disabled. In that way, we will avoid users to perform actions that will be banned.

Permissions available in property `<oc:permissions>` with the following values:

https://github.com/owncloud/client/blob/cedf72825bc0db8e3c147958a9382ee5b411d9ea/src/common/remotepermissions.h#L42-L54

Samsung A52
`8f2d519d`

**Comment by abelgardep** [comment]
### (22) [P2]

Current behavior:
When we change the sort method in the file list, and enter into images gallery mode, the images shown do not respect the file list sorting.

Expected behavior:
Gallery mode uses the same sorting method as the user selected for file list

**Comment by jesmrec** [comment]
### (23) [P1]

1. Install app from scratch in debug mode
2. Click on Settings -> logging to check that logging feature is enabled and log file was created
3. Go again to login view and login in a browser account (OAuth2 / OIDC). 
4. When login is completed, go to Settings -> Logging -> Log files

Current: empty
Expected: log file with logs there

Samsung A51 Android 12
`7c8f2fef7`

**Comment by jesmrec** [comment]
Moving forward to 3.0 -> https://github.com/owncloud/android/issues/3724
