### ISSUE TITLE
[New arch] Check 3.0 migration status

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3783]
3.0 is intended to work with only one DB, by removing the old one. Tasks:

- [ ] Check if all tables are already migrated
- [ ] Migrate those ones that are not migrated yet

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by abelgardep** [comment]
Nothing to do here. Everything migrated to new database.
