### ISSUE TITLE
[TECHNICAL] Kotlinize ManageAccountsActivity

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3789]
The activity which manages the accounts on the app is still in Java, so we're moving it and all the stuff related to Kotlin.

### TASKS

- [x] Research (if needed)
- [x] Create branch enhancement/manage_accounts_activity
- [x] Development tasks
  - [x] Create a new `account_item.xml` which represents each of the accounts in the list, keeping the same appearance as the current one but using `ConstraintLayout` instead of `RelativeLayout`
  - [x] Use it in `AccountListAdapter.java` to check the behaviour is the same as before
  - [x] Create a new `accounts_layout.xml` which hosts the dynamic list of the accounts, keeping the same appearance as the current one but using `RecyclerView` instead of `ListView`
  - [x] Kotlinize `ManageAccountsActivity.java` in a new file called `ManageAccountsActivity.kt` which will be located in a new package `com.owncloud.android.presentation.ui.accounts`
    - First, make sure accounts are shown in the new activity, with no functionality
    - Then, give functionality to each of the buttons
  - [x] Use it with `AccountListAdapter.java` to check the behaviour is the same as before
  - [x] Kotlinize `AccountListAdapter.java` in a new file called `AccountListAdapter.kt` which will be located in a new package `com.owncloud.android.presentation.adapters.accounts`
  - [x] When everything is working, delete legacy classes and keep only the new ones
  - [x] UI tests
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch enhancement/manage_accounts_activity into new_arch/synchronization
