### ISSUE TITLE
[SPACES] Save account type and display new tab for spaces

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3803]
After adding a new account to the device, detection of spaces / non-spaces account should be done. Way to do it: checking in the capabilities end point the existence of `spaces` node:

```
 "spaces": {
                    "version": "1.0.0",
                    "enabled": true,
                    "projects": true,
                    "share_jail": true
}
```

In case `spaces` is available and enabled, value to be persisted in DB (capabilities table). Initially, the new field in the table is `NULL` for all the existing rows (no spaces before this release). It will be updated every time capabilities are checked.

In case `spaces` node is enabled, bottom bar will show a new item `spaces`. Icon should be similar to the one in web:

![Screenshot 2022-12-12 at 09 12 33](https://user-images.githubusercontent.com/14894746/206994486-1d72c7d8-dcd3-4d2e-8115-9093727b0214.png)

At this point, this new item in the bottom bar will do nothing when clicking on it.

### TASKS

- [x] Research (if needed)
- [x] Create branch spaces/tab_in_bottom_bar
- [x] Development tasks
  - [x] Create new field in `capabilities` table and initialize with `NULL`
  - [x] Update capabilities logic to detect new node and save its value in DB's new field
  - [x] Add new option to bottom bar as hidden with the proper icon
  - [x] Add logic to show/hide the spaces option
- [x] Code review and apply changes requested
- [X] Design test plan
- [X] QA
- [x] Merge branch spaces/tab_in_bottom_bar into spaces/main

### QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_4.0/Save%20Account%20%26%20Tab.md

**Comment by JuancaG05** [comment]
At the moment, the new tab for spaces looks like this after the development of this issue:

![spaces_empty_view](https://user-images.githubusercontent.com/57049315/209347169-0c11a929-d4b0-45dc-84ed-2a0c9f7df636.png)

@michaelstingl @tbsbdr 
Comments and suggestions are welcome of course!

**Comment by JuancaG05** [comment]
We won't do unit tests and UI tests for spaces for the moment, will have to discuss about UI tests in some time

**Comment by jesmrec** [comment]
> We won't do unit tests and UI tests for spaces for the moment, will have to discuss about UI tests in some time

UI tests delay, not a problem. But, if unit tests are required, they should be done in same PR. Delaying unit tests is an error from my POV.

**Comment by jesmrec** [comment]
Done.
