### ISSUE TITLE
[SPACES] Create new "Spaces" view

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3805]
It will be needed a new table in DB to support spaces. Much info comes from `drives` endpoint and should be persisted for Android app's use. Below, you'll find a sample JSON object with all the retrieved info.

At least, we should save:

- Space id
- Account id
- Description (subtitle)
- Name
- Last Modification date
- WebDavURL
- Etag
- Image (URL, name, etag...): not sure which fields will be compulsory here.
- Status (active/disabled)

(any other?)

Description is also interesting but, ftm, we are not handling markdown files. Future feature.
Permissions to be handled in a separate issue

Also, new activity to show list of available spaces will be created like 

![206656429-3944af86-c123-4d5a-9270-faf9f56409ed](https://user-images.githubusercontent.com/14894746/207038987-5530ebb9-e13e-4bc7-acea-d0f97d2a8dca.jpeg)

showing image, title and subtitle

If no spaces are available, a view with `No spaces` will be displayed instead.

Show only enabled spaces. If the space is disabled, it is not displayed.

Items in the list of spaces will not handle any operation. Just showing the list ftm.

This view could be refreshable. Good feature.

### TASKS

- [x] Research (if needed)
- [x] Create branch spaces/fetch_spaces
- [x] Development tasks
  - [x] Create new table
  - [x] Add logic to populate it when spaces account is added
  - [x] Create new usecase to fetch the spaces
  - [x] Call the new usecase when opening the spaces tab (we may refresh spaces from another place too, but keep it simple at the moment :))
  - [x] Create new usecase to retrieve spaces from database as flow
  - [x] Populate new fragment with the spaces retrieved from database(recycler grid, adapter etc)
  - [x] Display title and subtitle (name and description from space)
  - [x] Display image using the specials from space
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [X] Merge branch spaces/fetch_spaces into spaces/main

Example of JSON space object:

```
{
         "description" : "Subtitle",
         "driveAlias" : "project/space1",
         "driveType" : "project",
         "id" : "aeda45a3-9aae-408e-b050-4f1ea6258f5e$3ae8361b-51f0-4e3a-be77-17bf29fbbfe8",
         "lastModifiedDateTime" : "2022-12-09T13:57:08.380088722Z",
         "name" : "Space1",
         "owner" : {
            "user" : {
               "id" : "3ae8361b-51f0-4e3a-be77-17bf29fbbfe8"
            }
         },
         "quota" : {
            "remaining" : 999089265,
            "state" : "normal",
            "total" : 1000000000,
            "used" : 910735
         },
         "root" : {
            "eTag" : "\"33492caaafb97df067f651d71d2ec70b\"",
            "id" : "aeda45a3-9aae-408e-b050-4f1ea6258f5e$3ae8361b-51f0-4e3a-be77-17bf29fbbfe8",
            "permissions" : [
               {
                  "grantedTo" : [
                     {
                        "user" : {
                           "id" : "33e4fecc-b8c0-4aa2-b563-e0582ef9475c"
                        }
                     }
                  ],
                  "roles" : [
                     "manager"
                  ]
               },
               {
                  "grantedTo" : [
                     {
                        "user" : {
                           "id" : "fc20ad85-0600-4aa0-9de8-7411faf5114d"
                        }
                     }
                  ],
                  "roles" : [
                     "viewer"
                  ]
               }
            ],
            "webDavUrl" : "https://127.0.0.1:9200/dav/spaces/aeda45a3-9aae-408e-b050-4f1ea6258f5e$3ae8361b-51f0-4e3a-be77-17bf29fbbfe8"
         },
         "special" : [
            {
               "eTag" : "\"61b7bd07a72435578cea0ade9bdf6f25\"",
               "file" : {
                  "mimeType" : "image/jpeg"
               },
               "id" : "aeda45a3-9aae-408e-b050-4f1ea6258f5e$3ae8361b-51f0-4e3a-be77-17bf29fbbfe8!522078a2-6ec7-4b05-91c8-af0c38573aea",
               "lastModifiedDateTime" : "2015-12-31T09:29:26Z",
               "name" : "Ca.jpg",
               "size" : 910681,
               "specialFolder" : {
                  "name" : "image"
               },
               "webDavUrl" : "https://127.0.0.1:9200/dav/spaces/aeda45a3-9aae-408e-b050-4f1ea6258f5e$3ae8361b-51f0-4e3a-be77-17bf29fbbfe8%213ae8361b-51f0-4e3a-be77-17bf29fbbfe8/.space/Ca.jpg"
            },
            {
               "eTag" : "\"5b20d1b17c8c933751e3ad6a97e4ec03\"",
               "file" : {
                  "mimeType" : "text/markdown"
               },
               "id" : "aeda45a3-9aae-408e-b050-4f1ea6258f5e$3ae8361b-51f0-4e3a-be77-17bf29fbbfe8!fa2702d4-308e-4622-a5eb-4785540af4cb",
               "lastModifiedDateTime" : "2022-12-09T13:57:08.379060043Z",
               "name" : "readme.md",
               "size" : 54,
               "specialFolder" : {
                  "name" : "readme"
               },
               "webDavUrl" : "https://127.0.0.1:9200/dav/spaces/aeda45a3-9aae-408e-b050-4f1ea6258f5e$3ae8361b-51f0-4e3a-be77-17bf29fbbfe8%213ae8361b-51f0-4e3a-be77-17bf29fbbfe8/.space/readme.md"
            }
         ],
         "webUrl" : "https://127.0.0.1:9200/f/aeda45a3-9aae-408e-b050-4f1ea6258f5e$3ae8361b-51f0-4e3a-be77-17bf29fbbfe8"
      }
```

## QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_4.0/Spaces%20View.md

- [x] (1) Images not updated by pull to refreshing https://github.com/owncloud/android/pull/3843#issuecomment-1378643548 [WONT FIX NOW]
- [x] (2) Blank view with disabled spaces https://github.com/owncloud/android/issues/3805#issuecomment-1378704787 [FIXED]
- [x] (3) Crash after updating https://github.com/owncloud/android/issues/3805#issuecomment-1378765463 [WONT FIX NOW]

**Comment by JuancaG05** [comment]
This is the appearance we developed for the spaces list view:

![Screenshot_20230110_182627](https://user-images.githubusercontent.com/57049315/211620573-93243f8f-f097-482a-bf5f-4b4f806206c1.png)

In contrast with the web client:

![Captura de pantalla 2023-01-10 a las 18 31 49](https://user-images.githubusercontent.com/57049315/211621674-a8906659-8c30-40fd-8698-9582023be7b0.png)

I used the same color for the background of each space card as in the web, but we are not sure if we should make this color brandable or even keep it always white with a border to make it non-brandable?
Also, I set rounded corners to the card to keep it more Material-styled, but currently the app doesn't follow Material Design system (planned for the next months).

Any opinions, suggestions and comments are always welcome 😀 @michaelstingl @tbsbdr

**Comment by jesmrec** [comment]
### (1)

Steps:

1. In web, create space with image
2. Open app > Spaces. Space with the image correctly shown
3. In web, edit image, setting a new one for the space
4. In app, pull to refresh in Spaces view

Current: image not refreshed. Required to browse through tabs to get an update
Expected: Pull to refresh, refreshing image as the title and subtitle do

Samsung A51, Android12
`bb0260d3`

**Comment by jesmrec** [comment]
### (2)

1. In web, create space (or reuse an existing one)
2. Open app > Spaces. Space correctly shown
3. In web,  disable space
4. In app, pull to refresh in Spaces view

Current: Blank view. Space is still existing but not listed. 
Expected: `No spaces view`  displayed 

Samsung A51, Android12
`bb0260d3`

**Comment by jesmrec** [comment]
### (3) 

1. Install previous version 3.0.1
2. Add any account (no matter if oCIS or oC10)
3. Update to current

Current: app crashes
Expected: no crash and correct update

Samsung A51, Android12
`bb0260d3`

**Comment by jesmrec** [comment]
Done!
