### ISSUE TITLE
[SPACES] Adapt Scoped Storage to Space's folder structure. Check Download action

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3808]
New spaces accounts will have another level of storage in Scoped Storage. From the account level will hang the space level. Inside it, the downloaded files and folders will be stored.

user1@myserver.com
|_ Personal
&emsp; |_ Folder1
&emsp; |_ Folder2
|_ Shares
|_ Space1
&emsp; |_ ...
|_ Space2
&emsp; |_ ...

Existing oCIS accounts should move to /Personal the existing stuff.

After migrating the content to the new location, we will need to update the database(storagePath field) accordingly.

Download action to add here, as check for the new locations.

Add space id to DB if space is personal ¿?

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Modify the path to save files
  - [ ] Migrate DB to include the new path.
  - [ ] Migrate existing ones to new location.
  - [ ] Unit tests
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App  https://github.com/owncloud/android/pull/3891
- Library (if needed)  https://github.com/owncloud/android-library/pull/537

**Comment by abelgardep** [comment]
I've been checking how to introduce the hierarchy of the spaces on android storage, and I got some questions.

First, we thought about the "ideal" solution with space's name:

```
user1@myserver.com
|_ Personal
  |_ Folder1
  |_ Folder2
|_ Shares
|_ Space1
  |_ ...
|_ Space2
  |_ ...
```
The main issue here comes when we have several spaces with the same name.

Apparently, the only unique key to identify a space is the `id` so, the proper hierarchy would be like that:

```
user1@myserver.com
|_ space_id_151294u12
  |_ Folder1
  |_ Folder2
|_ space_id_2519284
|_ space_id_3184912
  |_ ...
|_ space_id_41u24124
  |_ ...
```
This is not human-readable. At the moment, we store the files on scoped storage, so users won't see the actual hierarchy, and we would be able to identify each space internally. So we could use the spaceId in the hierarchy (AFAIK).

The only issue I can think of at the moment is if we decide to open the storage in the future (somehow), users won't be able to identify the spaces by the space id in the hierarchy.

**Comment by jesmrec** [comment]
a mixture would be posible? for example:

space name: `maths`
space id:  `345345baf54454....`

space name in storage: `maths-345345baf54454`  (truncking somehow the  long id)

How would this affect to space renames?

**Comment by abelgardep** [comment]
Hierarchy options:
### Option 1: Based on space ids
```
user1@myserver.com
|_ space_id_151294u12
  |_ Folder1
  |_ Folder2
|_ space_id_2519284
|_ space_id_3184912
  |_ File1
|_ space_id_41u24124
  |_ Folder1
```
PRO: Hierarchy based on space_id, which is unique
CON: Not human-readable, currently on scoped storage so not visible anyway. Could become an issue if the storage becomes public in the future.

### Option 2: Based on space name or drive alias or something like that
```
user1@myserver.com
|_ Shares
  |_ Folder1
  |_ Folder2
|_ Personal
|_ University
  |_ File1
|_ Family
  |_ Folder1
```
PRO: Human-readable but currently on scoped storage so not visible. Easy for the user to identify the spaces if the storage becomes public in the future.
CON(CRITICAL): Not unique key, can cause issues with several spaces with the same name/Alias

### Option 3: Based on space name or drive alias + _ + trunked spaceId
```
user1@myserver.com
|_ Shares_spaceId123123
  |_ Folder1
  |_ Folder2
|_ Personal_spaceId123124
|_ University_spaceId123456
  |_ File1
|_ Family_spaceId123457
  |_ Folder1
```
PRO: Human-readable but currently on scoped storage so not visible. Kind of easy for the user to identify the spaces if the storage becomes public in the future.
CON: Renaming could cause issues. Depending on the trunked digits we could have collisions. Spaces with same name will be confusing for the user anyway (`University_space123123` and `University_space312312`)

### Conclusion
From my point of view, the way to go is Option 1. The easy path for us. No need to take care about renamings. Unique key. Invisible for the user in scoped storage. Real con appears for the user if the storage becomes public in the future.
Alternatively, we could go with option 3 composing the folder name with enough digits from space Id to avoid collisions, but still with some cons.

**Comment by michaelstingl** [comment]
> From my point of view, the way to go is Option 1. The easy path for us. No need to take care about renamings. Unique key. Invisible for the user in scoped storage.

I think Option 1 is a good start 👍

**Comment by jesmrec** [comment]
### (1)

1. Download some images in any account's personal space
2. Go to an space with images stored inside
3. Click on the image to download preview

Current: Preview is not correct, showing the image of 1.
Expected: Correct image previewed

Samsung A51, Android 12
`2c221c103`

**Comment by abelgardep** [comment]
(1) Should be fixed now: d8ed3a414751d67a7f9b234ae9f2485afb3ab110

**Comment by jesmrec** [comment]
Related: https://github.com/owncloud/android/issues/3901 (reproducible in `master`)

**Comment by jesmrec** [comment]
### (2)

1. Open a space that contain images
2. Download a big image
3. Before download finishes, cancel the download
4. Click again in the same image to download

Current: `Download failed` , but the file starts to download and finishes correctly 
Expected: Download correct, without errors

https://user-images.githubusercontent.com/14894746/217807382-4935596c-6721-47ab-8d8a-1f8fa7f25a70.mp4

Samsung A51, Android 12
`d8ed3a414`

**Comment by jesmrec** [comment]
(2) is also reproducible in `master`, so i will approve this one and move the report to a separate issue
