### ISSUE TITLE
[SPACES] Document Provider showing available Spaces

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3809]
Document provider feature will show the available spaces for an specific account.

By selecting an account in document provider, a list of spaces is displayed, every of them as a folder. Then, user will browse through it as usual. 

No changes for non-spaces accounts.

Article with info about DocumentsProvider: https://medium.com/androiddevelopers/building-a-documentsprovider-f7f2fb38e86a

### TASKS

- [x] Research
- [x] Create branch spaces/document_provider
- [x] Development tasks
  - [x] Create new `SpaceCursor` to show spaces
  - [x] Modify logic in `RootCursor` to set correct directory to `COLUMN_DOCUMENT_ID` depending on whether it's a spaces or non-spaces account
  - [x] Adapt logic in `DocumentsStorageProvider` to show the list of spaces
  - [x] Adapt logic to be able to browse through the hierarchy of spaces as if they were folders
  - [x] Check that create folder, rename and remove operations work properly
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch spaces/document_provider into spaces/main
