### ISSUE TITLE
[TECHNICAL] Some refactoring after 3.0

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3812]
During the long process of the rearchitecture of the app, there have been several points that we detected could be refactored to improve the code understandability and to unify it following some conventions. These points are:

- Prefix `OC-` in implementations: should we continue using it? Replacing with `-Impl` suffix or similar?
- Prefix `OC-` in domain classes: should we keep it? Maybe confusing with implementations?
- Make DAOs interfaces and not abstract classes where possible?
- Update SQL queries from "query" to """query"""?
- Align names of operations in database: `store-` or `save-` (in DataSources)? `insert` or `insertSomething` (in DAOs)? `delete-` or `remove-`? `deleteSomethingWithId` or `deleteSomethingById` (in Repositories, DataSources and DAOs)?
- Rearrange package structure (i.e. in the `presentation` package, arrange it by features, and each of the features contains standard packages `fragments`, `viewmodels`, etc.)
- Can we remove `DownloadReceiver` from `FileDisplayActivity.kt`?
- Can we remove `SquareImageView.java`?
- Can we remove `RemoteFileMapper.kt`?
- Anything else we can remove?
- Take a look at flaky tests, sometimes they prevent BitRise from passing at the first attempt and make work slower
- Update dependencies that we couldn't update all this time
- Check Sonar status of the code
- When Room 2.5 is stable, change the inserts with replace strategy and updates by `@Upsert`

This is all open to discussion, I will post in a comment the decisions we eventually take for each of the points above.

### TASKS

- [x] Create branch technical/some_refactoring
- [x] Development tasks
  - [x] Do what was decided with `OC-` prefixes
  - [x] Do what was decided with DAOs as interfaces and not abstract classes
  - [x] Do what was decided with format of SQL queries
  - [x] Do what was decided with names of DB operations
  - [x] Do what was decided with package structure
  - [x] Remove unnecessary stuff (@JuancaG05)
  - [x] Remove unnecessary stuff (@abelgardep)
  - [x] Update dependencies -> https://github.com/owncloud/android/pull/3810
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch technical/some_refactoring into master

**Comment by JuancaG05** [comment]
**- Prefix `OC-` in implementations: should we continue using it? Replacing with `-Impl` suffix or similar?**
Let's keep implementations with `OC-` prefix.

**- Make DAOs interfaces and not abstract classes where possible?**
Let's do it.

**- Update SQL queries from "query" to """query"""?**
Let's try it (resarch).

**- Align names of operations in database: `store-` or `save-` (in DataSources)? `insert` or `insertSomething` (in DAOs)? `delete-` or `remove-`? `deleteSomethingWithId` or `deleteSomethingById` (in Repositories, DataSources and DAOs)?**
To put something in DB we'll use `save-`.
The insert methods will be `insert` followed by the strategy of the insert operation.
To get rid of data we'll use `delete-`, and for the attribute we use to delete we'll use `deleteSomethingById`.
`-asStream` will become `-asFlow` or `-asLiveData` to specify more.

**- Rearrange package structure (i.e. in the `presentation` package, arrange it by features, and each of the features contains standard packages `fragments`, `viewmodels`, etc.)**
All the content under `presentation` should be moved to a feature-based package structure.

**- Can we remove `DownloadReceiver` from `FileDisplayActivity.kt`?**
@abelgardep will check the previous uses and will decide if this is finally removed.

**- Can we remove `SquareImageView.java`?**
Yes!

**- Anything else we can remove?**
We'll have to check more deeply in a future.

**- Take a look at flaky tests, sometimes they prevent BitRise from passing at the first attempt and make work slower**
We'll deal with this in another moment.

**- Update dependencies that we couldn't update all this time**
A PR will be made with this.

**- Check Sonar status of the code**
A PR will be made with this.

**- When Room 2.5 is stable, change the inserts with replace strategy and updates by `@Upsert`**
This will be done when Room 2.5 is available. Also, we'll have to do a complete DB migration, since names of columns should be written with snake_case instead of camelCase.

**Comment by JuancaG05** [comment]
To do in the future:
- Prefix `OC-` in domain classes
- Second iteration of package restructuring
- Take a look at flaky tests
- Update Room to 2.5 when it is stable
- Check Sonar status of the code
- Reformat of the whole code (automatically by Android Studio)
