### ISSUE TITLE
[RELEASE] 3.0.1_oem

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3835]
### TASKS:

- [x] Approve and merge changes in ownBrander
  - [x] Version number 
  - [x] Webfinger https://github.com/owncloud/ownbrander/pull/1048
- [x] [OPS] Block oB button
- [x] [GIT] Create and sign tag `oc-android-3.x_oem` in HEAD commit of `release_3.0_oem` branch or 3.0  commit  
- [x] [OPS] Deploy oB
- [x] [QA] Generate final APKs files from signed commit in builder machine  and perform some basic operations 
- [x] [QA] Check that bundle is correctly generated and apk family could be installed in device from bundle
(depending on if there's new changes or not), in owncloud/android
- [ ] [OPS] Enable button

_____

**Comment by jesmrec** [comment]
Checks done:

- [x ] Build with URL and no webfinger
- [x] Build with URL and webfinger
- [X] Build with webfinger and no URL (makes no sense, but a feasible case)
- [X] Check aab installs correctly

**Comment by abelgardep** [comment]
Working on 3.0.2 already, so the button will be enabled with it
