### ISSUE TITLE
[RELEASE] 3.0.1

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3839]
### TASKS:

 - [x] [GIT] Create branch release/3.0.1 in owncloud/android from tag oc-android-3.0
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [ ] [DIS] Create a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD inside the `changelog` folder
 - [ ] [DIS] Move all changelog files from the unreleased folder to the new version folder
 - [x] [DIS] Add ReleaseNotes replacing `emptyList` with `listOf` and adding inside `ReleaseNote()` with String resources
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [GIT] Create and sign tag 'oc-android-3.0.1' in HEAD commit of release branch, in owncloud/android
 - [ ] [GIT] Create and sign tag '2.0.1' in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [ ] [GIT] Merge branch `release/3.0.1` in owncloud/android, into master
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [x] [GIT] Publish a new release in owncloud/android
 - [ ] [COM] Inform `#updates` in internal chat
 - [ ] [DIS] Upload release APK and bundle to internal owncloud instance
 - [ ] [GIT] Merge master branch into stable, in owncloud/android-library
 - [ ] [GIT] Merge master branch into stable, in owncloud/android

Fixes included:

- https://github.com/owncloud/android/pull/3837
- https://github.com/owncloud/android/pull/3841
- https://github.com/owncloud/android/pull/3831
- Code guards to avoid some crashes detected in Google Play Developer Console
_____

**Comment by jesmrec** [comment]
QA checks

- [ ] Update from 2.18
- [X] Update from 2.21.2 with failed uploads (manual uploads and share text)
- [ ] Update from 3.0.0
- [X] Check unsharing
- [ ] Basic testing (authentication, security, transfers)

**Comment by jesmrec** [comment]
Approved.

Commits:

app: `5e553f07`
library: `0e11f0d4`
