### ISSUE TITLE
[FEATURE REQUEST] Create "Open in web" option in main file list

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3860]
[First iteration](https://github.com/owncloud/android/pull/3737). `Open in web` available from Details view. 

- Create option in main list of files
- Keep option in Details 
- List available app providers for every file (https://owncloud.dev/services/app-registry/apps/#app-registry). 
- Out of multiselection
- Refactor of class

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/open_in_web_main_list
- [x] Development tasks
  - [x] Move "Open in web" to a new extension
  - [x] Use this new extension in the main file list
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/open_in_web_main_list into master

**Comment by abelgardep** [comment]
What should be the label here for each provider?

```
Open in "Provider"
Open in web ("Provider")
Open in "Provider" (web)
```

Other considerations are also welcome @michaelstingl

**Comment by michaelstingl** [comment]
`Open in "Provider"` works for me 👍
