### ISSUE TITLE
[SPACES] Copy and move operations

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3863]
Copy and move operations have storage regards, so, this one should be implemented after https://github.com/owncloud/android/issues/3808

- Copy files and folders available in the same space and to other spaces
- Move only in the current space

Behaviour will be the same as current:

- If file is downloaded, local copy to be moved to final location
- If two files have same name, (2) added to the filename
- Folder picker will differ a little bit: spaces browsing is posible only for copying, and with camera uploads only personal space will be shown
- Folder not copied/moved into itself or its descendants
- Error when copying/moving into inexistent location
- Errors with no connection, maintenance mode...

Initially, we will not check permissions, so, if the target space lacks of writing permission, we should show an error (to improve)

More ideas... welcome

### TASKS

- [x] Research (if needed)
- [x] Create branch spaces/copy_and_move
- [x] Development tasks
  - [x] Kotlinize `FolderPickerActivity.java`
  - [x] Adapt picker to CAMERA_FOLDER option: it should show just personal space
  - [x] Adapt picker to MOVE option: it should show just the space where the files come from
  - [x] Adapt picker to COPY option: it should show the list of spaces
  - [x] Adapt network operations for move action
  - [x] Adapt network operations for copy action
  - [x] Assert in move file or folder usecase that the destination space is the same as the original
  - [x] Check that scoped storage works fine with downloaded files
- [x] Code review and apply changes requested
- [X] Design test plan
- [x] QA
- [ ] Merge branch spaces/copy_and_move into spaces/main

## QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_4.0/Copy%20Move%20Picker.md

Reports

- [x] (1) Some items to be removed from folder picker https://github.com/owncloud/android/issues/3863#issuecomment-1427963594
- [x] (2) oC10 with no spaces to select https://github.com/owncloud/android/issues/3863#issuecomment-1429311261
- [x] (3) Copy folder with content in personal, list empty copied folder https://github.com/owncloud/android/issues/3863#issuecomment-1429425859
- [x] (4) Different behaviour when copying to the same location https://github.com/owncloud/android/issues/3863#issuecomment-1429477179
- [x] (5) Copy from custom to personal does not work https://github.com/owncloud/android/issues/3863#issuecomment-1429562735 [WONT FIX HERE]
- [x] (6) Copy to disabled space https://github.com/owncloud/android/issues/3863#issuecomment-1429650036 [FIXED]

**Comment by JuancaG05** [comment]
Since files belonging to the Personal space don't have currently its `spaceId` (at the moment they are treated as if they were legacy), the copy operation between Personal space and other spaces is not working right now. Hardconding it, it works, so we'll only have to wait until files are associated to the Personal space

**Comment by jesmrec** [comment]
### (1)

Folder picker in spaces list contain:

- Share item on the top bar. Useless there
- Lens icon (we could keep it thinking in https://github.com/owncloud/android/issues/3865)
- `Copy here` option. Useless there. `Cancel` makes sense and should keep

![Screenshot 2023-02-13 at 14 23 51](https://user-images.githubusercontent.com/14894746/218471039-76dfa44e-4681-43de-8bb9-e8213ce6c89f.png)

Samsung A51, Android 12
`618c39c1e`

**Comment by jesmrec** [comment]
### (2)

1. Open oC10 account
2. Select any item to copy

Current: Spaces list (empty) displayed
Expected: oC10 does not support spaces, so root folder should be displayed

Samsung A51, Android 12
`618c39c1e`

**Comment by jesmrec** [comment]
### (3)

1. Open personal space in a oCIS account
2. Select a folder that contains files and Copy operation
3. Select Personal as target space
4. Select any location inside Personal to copy
5. Browse into the new folder

Current: folder empty. Copy request returns 200 (step 4), and propfind (step 5) return the list of items inside the folder. kind of weird
Expected: folder's content displayed

Samsung A51, Android 12
`c0f8e649f1`

**Comment by jesmrec** [comment]
### (4)

- In a custom space, copy a file to the same location -> Snackbar with `The file exists already in the folder`
- In personal space, copy a file to the same location -> File duplicated with (2)

Behaviour of same operation should be consistent across the platform. 

Web gives user the chance of keeping both or replace. This is not implemented in our side yet, so, we have to choose a default behaviour for any space.

Samsung A51, Android 12
`c0f8e649f1`

**Comment by jesmrec** [comment]
### (5)

1. In a custom space, select a file and then, Copy operation
2. Select Personal as target folder
3. Select any location inside Personal

Current: `Server could not be reached`. Copying to another custom space works fine
Expected: Correctly copied

Samsung A51, Android 12
`c0f8e649f1`

**Comment by jesmrec** [comment]
### (6)

1. In a custom space, select a file, then copy
2. Select another custom space, without submitting
3. In web, disable the target space
4. In app, submit the copy operation

Current: no feedback for the user. Copy request returns `409` 
Expected: since this is a non-allowed operation, some error message should be displayed somehow

Samsung A51, Android 12
`c0f8e649f1`

**Comment by JuancaG05** [comment]
@jesmrec (2) is solved but a little tingling has been introduced when showing the list of spaces in the folder picker activity, at the moment I think it's unavoidable, will take a look anyway

**Comment by JuancaG05** [comment]
@jesmrec I'm not able to reproduce (3), could you check if it is still reproducible in the fixes branch (`spaces/fixes_copy_and_move`)?

**Comment by JuancaG05** [comment]
@jesmrec ready for second QA round! 🚀 You can find the fixes in `spaces/fixes_copy_and_move` branch -> https://github.com/owncloud/android/pull/3924

(5) is already fixed as well in this branch since it contains the commits from https://github.com/owncloud/android/issues/3919.

**Comment by jesmrec** [comment]
Approved on my side

**Comment by abelgardep** [comment]
Done. We are a step closer to the first beta with Spaces support 🚀
