### ISSUE TITLE
[RELEASE] 3.0.2

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3870]
To include:

- Authentication fixes
- Scope/Prompt parameterization in OIDC

### TASKS:

 - [x] [GIT] Create branch release/3.0.2 in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD inside the `changelog` folder
 - [x] [DIS] Move all changelog files from the unreleased folder to the new version folder
 - [x] [DIS] Update screenshots, if needed, in README.md
 - [x] [DIS] Add ReleaseNotes replacing `emptyList` with `listOf` and adding inside `ReleaseNote()` with String resources
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [GIT] Create and sign tag 'oc-android-3.0.2' in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Create and sign tag '2.0.2' in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [ ] [GIT] Merge branch `release/3.0.2` in owncloud/android, into master
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [GIT] Publish a new release in owncloud/android
 - [x] [DIS] Create post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))
 - [x] [COM] Inform `#updates` and `#marketing` in internal chat
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - [ ] [GIT] Merge master branch into stable, in owncloud/android-library
 - [ ] [GIT] Merge master branch into stable, in owncloud/android
 - [x] [DOC] Update documentation with new stuff (notify rocketchat #documentation-internal in advance!)

_____

**Comment by jesmrec** [comment]
QA checks

- [ ] Install from scratch
- [ ] Check fix auth problem https://github.com/owncloud/android-library/pull/534
- [ ] Basic testing (authentication, security, transfers)
- [ ] Update from 2.12
- [ ] Update from 2.21.2 with failed uploads (manual uploads and share text)
- [ ] Update from 3.0.0
- [ ] Update from 3.0.1
- [ ] Check generated aab

**Comment by jesmrec** [comment]
short `3.0.2` is approved on my side

Approved commits:

app: `61113a8f8`
library: `8132baa1`
