### ISSUE TITLE
[SPACES] Get Personal spaces quota from GraphAPI

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3874]
Quota is displayed at the bottom of the side menu. Legacy and current behaviour is showing the personal space quota. So, we should always show the personal space quota in the drawer (the general quota for oC10).

Now, this value should be fetched from GraphAPI's drives endpoint in case of oCIS, and keeping the current behaviour for 0C10.

```
"quota" : {
            "remaining" : 2655551488,
            "state" : "normal",
            "total" : 0,
            "used" : 66351210
},
```

Docs: https://owncloud.dev/libre-graph-api/#/me.drives/ListMyDrives

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/personal_space_quota
- [x] Development tasks
  - [x] Implement logic for oC10
  - [x] Implement logic for oCIS
  - [x] Implement unit tests (if needed)
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

**Comment by abelgardep** [comment]
I understand the idea, but oCIS has compatibility with this AFAIT: 
Propfind Request`https://server/remote.php/dav/files/user`
```
<?xml version='1.0' encoding='UTF-8' ?>
<propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav" xmlns:SABRE="http://sabredav.org/ns" xmlns:OC="http://owncloud.org/ns">
    <prop>
        <quota-used-bytes />
        <quota-available-bytes />
    </prop>
</propfind>
```
Response:
```
<d:multistatus xmlns:s="http://sabredav.org/ns" xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
    <d:response>
        <d:href>/remote.php/dav/files/user/</d:href>
        <d:propstat>
            <d:prop>
                <d:quota-used-bytes>16996007</d:quota-used-bytes>
                <d:quota-available-bytes>-2</d:quota-available-bytes>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
</d:multistatus>
```

Is it planned to remove the compatibility?
Do we need to show something different here?

**Comment by michaelstingl** [comment]
Spaces have quota information in the Graph endpoint. Better align quota handling across Personal Space and Project Spaces?
