### ISSUE TITLE
[RELEASE] 3.0.3_oem

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3877]
### TASKS:

- [x] Approve and merge changes in ownBrander
  - [x] Version number 
  - [x] OIDC Scope https://github.com/owncloud/ownbrander/pull/1051
- [x] [OPS] Block oB button
- [X] [GIT] Create and sign tag `oc-android-3.0.3_oem` in HEAD commit of `release_3.0.3_oem` branch or 3.0.3  commit  
- [x] [OPS] Deploy oB
- [X] [QA] Generate final APKs files from signed commit in builder machine  and perform some basic operations 
    - [X] Right webfinger flow 
    - [X] Scope in OIDC/Oauth2 requests 
    - [X] OAuth2 -> Webfinger update
    - [X] App update from 2.21.2_oem
- [x] [QA] Check that bundle is correctly generated and apk family could be installed in device from bundle
(depending on if there's new changes or not), in owncloud/android
- [x] [OPS] Enable button

_____

### BUGS & IMPROVEMENTS

**Comment by ZSJsts** [comment]
The APK still does not work. There is no response to selecting the open method.
(ownCloud release version 3.0.2)  on (Android 11 oneplus Oxygen OS 11.0.8.1)

**Comment by jesmrec** [comment]
> The APK still does not work. There is no response to selecting the open method.
(ownCloud release version 3.0.2) on (Android 11 oneplus Oxygen OS 11.0.8.1)

which apk? from where did you get it?

**Comment by michaelstingl** [comment]
@ZSJsts please open a new, separate issue for your problem
