### ISSUE TITLE
[SPACES] Upload content to spaces

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3879]
Adapt the existing upload feature to the new paths given by spaces, so that new files can be uploaded (when permissions granted to)

Cases covered:
- FAB -> Upload -> Files
- Camera autouploads
- FAB -> Upload -> Picture from camera
- Share files with ownCloud **[only Personal space]**
- Share plain text with ownCloud **[only Personal space]**
- Conflict - keep both
- Conflict - keep local
- Synchronization when file has changed locally (similar to Conflict - keep local, but triggered automatically)

### TASKS

- [x] Research (if needed)
- [x] Create branch spaces/uploads
- [x] Development tasks
  - [x] Add column `spaceId` to transfers table and adapt all the OCTransfers creations with space ID needed
  - [x] Adapt workers and network operations to upload correctly content to spaces
  - [x] Adapt UI in transfers tab to show name of the space of the file being uploaded
  - [x] Check if documents provider works fine with uploads
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch spaces/uploads into spaces/main

**Comment by JuancaG05** [comment]
The new appearance of the Uploads tab is like this:

![transfers_space_name2](https://user-images.githubusercontent.com/57049315/219604223-4ef67cc3-7e0e-458a-9a9f-5b7330606b37.png)

The space name where the upload belongs is shown, followed by the path where it is located inside this space. Previously, the first chunk of the path was the name of the app (`/ownCloud...`), but this was removed to avoid confusions with the introduction of spaces.

Also, the idea is that in oC10 servers the path is shown as before (without the space name before).

In this case, in the third transfer of the image, the name of the space doesn't appear because it belongs to Personal, which is not being treated as a space yet (@abelgardep currently working on that in https://github.com/owncloud/android/issues/3919). This is how the transfers will look like in oC10, while in oCIS servers, the uploads to Personal space will appear like this:

<img width="314" alt="" src="https://user-images.githubusercontent.com/57049315/219633610-41e2b773-b1de-4669-86ba-22c3d4a9b04f.png">

Any comment or suggestion accepted 😀

**Comment by JuancaG05** [comment]
> It seems that when uploading to Personal space from the FAB in the app, the destination space doesn't appear in the corresponding transfer row in the Uploads tab (as shown in the previous comment). However, when uploading from the documents provider, it does appear. I didn't research a lot about this unexpected behaviour, but won't spend so much time on it since when Personal is used as a space (when #3919 is merged) this shouldn't happen anymore. FYI @jesmrec 👍.

As this branch was rebased with the branch where #3919 is being developed, this restriction should not exist anymore 🎉 @jesmrec
