### ISSUE TITLE
[SPACES] Support file and folders operations with Spaces in DocumentsProvider

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3881]
After adapting DocumentsProvider to show and browse available spaces with basic operations (create folder, remove folder/file and rename folder/file) in https://github.com/owncloud/android/issues/3809, we have to support the other operations with files and folders: upload, download, copy and move.

### TASKS

- [x] Research (if needed)
- [x] Create branch spaces/doc_provider_operations
- [x] Development tasks
  - [x] Support upload operation
  - [x] Support download operation
  - [x] Support copy operation
  - [x] Support move operation
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch spaces/doc_provider_operations into spaces/main

**Comment by abelgardep** [comment]
Done, will be available on v4.0
