### ISSUE TITLE
[RELEASE] 3.0.3

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3898]
Fixes for

- Account util reports (Google Play) https://github.com/owncloud/android/pull/3889
- Bad navigation https://github.com/owncloud/android/issues/3866 https://github.com/owncloud/enterprise/issues/5550
- Long error message in copy operation https://github.com/owncloud/android/issues/3820

### TASKS:

 - [x] [GIT] Create branch release/3.0.3 in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD inside the `changelog` folder
 - [x] [DIS] Move all changelog files from the unreleased folder to the new version folder
 - [x] [DIS] Update screenshots, if needed, in README.md
 - [x] [DIS] Add ReleaseNotes replacing `emptyList` with `listOf` and adding inside `ReleaseNote()` with String resources
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [GIT] Create and sign tag 'oc-android-3.0.3' in HEAD commit of release branch, in owncloud/android
 - [ ] ~[GIT] Create and sign tag 'Y.Y.Y' in HEAD commit of release branch, in owncloud/android-library~
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [ ] [GIT] Merge branch `release/3.0.3` in owncloud/android, into master
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [ ] ~[DIS] Update screenshots and store listing, if needed, in Play Store~
 - [x] [GIT] Publish a new release in owncloud/android
 - [ ] ~[DIS] Create post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))~
 - [x] [COM] Inform `#updates` and `#marketing` in internal chat
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - [ ] ~[GIT] Merge master branch into stable, in owncloud/android-library~
 - [ ] ~[GIT] Merge master branch into stable, in owncloud/android~
 - [ ] ~[DOC] Update documentation with new stuff (notify rocketchat #documentation-internal in advance!)~

_____

**Comment by jesmrec** [comment]
## QA

- [ ] Install from scratch
- [ ] Check Changelog items
- [ ] Basic testing (authentication, security, transfers)
- [ ] Update from 2.21
- [ ] Update from 3.0.0
- [ ] Update from 3.0.1
- [ ]  Update from 3.0.2
  - [ ] Check correct Release Notes
  - [ ] Check correct version in `Settings`
- [ ] Check generated aab

**Comment by jesmrec** [comment]
`3.0.3` is approved on my side

Approved commits:

app: `550e4ba9`
library: `8132baa17`

IDE version: `Android Studio Dolphin | 2021.3.1 Patch 1`

Device: Samsung A51, Android 12
