### ISSUE TITLE
[FEATURE REQUEST] Add link to drawer menu

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3907]
As some customers asked, we could add a brandable text with a brandable link in the drawer menu.

I have three proposals:

| Logo as an icon and text | Logo as before and text under | Logo as before and text under and centered |
|---|---|---|
| ![link_drawer_1](https://user-images.githubusercontent.com/57049315/218112421-54e6c970-f2b3-4de9-b2e7-910e84dbd309.png) | ![link_drawer_2](https://user-images.githubusercontent.com/57049315/218112496-41e48581-493b-47d8-819e-b11fdd64fcaf.png) | ![link_drawer_3](https://user-images.githubusercontent.com/57049315/218107896-5588b399-3002-4a2c-9d29-8dbe0fc865db.png) |

I would go with the second one since the drawer in the first one remains almost blank, and I think some logos could not fit well there being that small. Also, I don't like centering the text here, but could be another option. The text is totally customizable, so suggestions accepted.

When we do this, the whole area (logo + text) could be clickable, not only the text.

Let me know your thoughts! @michaelstingl @tbsbdr @abelgardep @jesmrec 

### TASKS

- [x] Create branch feature/drawer_link
- [x] Development tasks
  - [x] Add logo icon and text with link to drawer XML file
  - [x] Add click listener to logo icon and text
  - [x] Add parameters in `setup.xml` for logo icon, text and link
  - [x] Handle visibility of the new elements in the drawer menu (only visible when these 3 parameters have a value)
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/drawer_link into spaces/main

**Comment by michaelstingl** [comment]
> Logo as an icon and text

This would be my favourite

**Comment by JuancaG05** [comment]
Finally I went with the first option.

This drawer link is show only when the `drawer_link` and the `drawer_link_label` params both are not empty, FYI @jesmrec
