### ISSUE TITLE
[RELEASE] 4.0-beta.1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3934]
First beta release including spaces. To be done once all basic operations are completed

### TASKS:

 - ~~[DOC] Ping in #documentation-internal about the new release~~
 - [x] [GIT] Create branch `release/4.0-beta.1` in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - ~~[DIS] Create a folder for the new version like `M.m.p_YYYY-MM-DD` inside the `changelog` folder~~
 - ~~[DIS] Move all changelog files from the unreleased folder to the new version folder~~
 - [x] [DIS] Update screenshots, if needed, in README.md
 - [x] [DIS] Add ReleaseNotes replacing `emptyList` with `listOf` and adding inside `ReleaseNote()` with String resources
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [GIT] Create and sign tag `oc-android-4.0-beta.1` in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Create and sign tag `2.1-beta.1` in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [ ] [GIT] Merge branch `release/4.0-beta.1` in owncloud/android, into master
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [ ] [DIS] Update YAML file in F-droid
 - ~~[DIS] Update screenshots and store listing, if needed, in Play Store~~
 - [x] [GIT] Publish a new release in owncloud/android
 - [ ] [DIS] Create post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))
 - [ ] [COM] Inform `#updates` and `#marketing` in internal chat
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - [ ] [GIT] Merge master branch into stable, in owncloud/android-library
 - [ ] [GIT] Merge master branch into stable, in owncloud/android
 - ~~[DOC] Update documentation with new stuff by creating [issue](https://github.com/owncloud/docs-client-android/issues)~~

### IMPROVEMENTS
- Quotas properties won't be retrieved on regular propFinds. Will be asked on specific propFind to retrieve the quota of the root folder/Personal

**Comment by jesmrec** [comment]
## QA

- [X] Install from scratch
- [X] Check Changelog items
- [x] Basic testing (authentication, security, transfers)
- [X] Update from 2.21.2
- [X] Update from 3.0.3
- [x]  Update from 3.0.4
  - [X] Check correct Release Notes
  - [X] Check correct version in `Settings`
- [x] Check generated aab
