### ISSUE TITLE
[FEATURE REQUEST] Copy/move conflict solved by users

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3935]
Related with https://github.com/owncloud/android/issues/3946

**Current behaviour:**

Copy/Move a item to a target folder that contains another item with the same name ->  `(2)` is automatically added to the file name to fix the collision

**New behaviour (implemented in the oCIS web):**

Showing this kind of dialog:

![Screenshot 2023-02-24 at 09 52 14](https://user-images.githubusercontent.com/14894746/221135296-d6876a93-8d73-4152-a5e4-f3e6d0fac876.png)

Skip -> cancel operation
Replace -> that's it, put the new one over the existing one
Keep both -> current behaviour

This behaviour does not depend on the kind of backend (oCIS/oC10)

Conflict solving dialog could be reused for this

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/file_conflict_solving
- [x] Development tasks
  - [x] Look for the code that checks whether the file exists or not
  - [x] Instead of directly renaming it, return this information to the fragment
  - [x] Create a new dialog to let the user choose the way to solve the conflict
  - [x] Implement "Skip" option
  - [x] Implement "Replace" option
  - [x] Implement "Keep both" option
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/file_conflict_solving into master
