### ISSUE TITLE
[FEATURE REQUEST] Authenticated Webfinger

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3943]
Extend support for the WebFinger protocol

Authentication is necessary to prevent leaking information about existing users.
Basic auth is not supported.

**Additional context**
https://github.com/owncloud/ocis/tree/master/services/webfinger

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/authenticated_webfinger
- [x] Development tasks
  - [x] Retrieve the oidc issuer from webfinger
  - [x] Retrieve the oC instances from authenticated webfinger
  - [x] Check compatibility with old webfinger implementation
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch feature/authenticated_webfinger into spaces/main

### PR

- App https://github.com/owncloud/android/pull/3945
- Library (if needed) https://github.com/owncloud/android-library/pull/545
