### ISSUE TITLE
[FEATURE REQUEST] File name conflict starting by (1)

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3946]
Related with https://github.com/owncloud/android/issues/3935

Copying a file or folder into a location that contains another item with the same name. 

Conflict should be fixed by adding (1) to the new item, if new conflict then (2), (3) etc... Now is (2), then (2) (2), then (2) (2) (2) etc...

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/file_conflict_naming
- [x] Development tasks
  - [x] Start by `MainFileListFragment` and look for the copy action until we arrive at the suitable use case
  - [x] From the use case, navigate through the different layers of the architecture until we find the conflict naming algorithm
  - [x] Change the algorithm
  - [x] Add unit tests
- [ ] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/file_conflict_naming into master
