### ISSUE TITLE
[SPACES] Available offline

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3947]
In #3879 we introduced a new way to distinguish between uploads to different spaces.

We could extend that to available offline files to distinguish them easily. Otherwise, there is no way to distinguish them in the available offline section.

Options:
1. Add the space on the third row and show the entire path (including the name as it is atm)
2. Add the space on the third row and show the parent path (not including the name as it is in the uploads section)
3. Add a new row with the space.

| Uploads | Av Offline |
| --- | --- |
| ![uploads_spaces_dif](https://user-images.githubusercontent.com/47524927/222433115-11c2b758-342b-463f-91fb-d15bd9000a6d.png) | ![available_offline_diff_spaces](https://user-images.githubusercontent.com/47524927/222433137-9d6a1096-fed2-4ec3-8cfd-6e6e5df652b5.png) |

### TASKS

- [x] Research (if needed)
- [x] Create branch spaces/available_offline
- [x] Development tasks
  - [x] Show only parent folder path instead of whole path
  - [x] Add space name label and icon
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch spaces/available_offline into master

**Comment by abelgardep** [comment]
I would go with option 2.

Option 1: space + full path is too long and we are already showing the name in the first row
Option 2: space + parent path will be kind of similar in length to the current row
Option 3: New row is too much from my point of view

**Comment by jesmrec** [comment]
Number 2 is most congruent with the current stuff
