### ISSUE TITLE
[TECHNICAL] [SPACES] Create entity for OCFile + OCFile sync info + OCSpace

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3971]
There are several cases in which we retrieve all the spaces from database just to be able to associate each file to its space. For example, `FileListAdapter` receives from `MainFileListFragment` a list with all the spaces, provided by `MainFileListViewModel`. The same happens with `TransfersAdapter`, `TransfersListFragment` and `TransfersViewModel`, respectively.

A better solution would consist in retrieve the space all together with the file, so that we don't have to call again the database and retrieve all the spaces we have saved for all accounts. This could be done by adding the space entity to `OCFileWithSyncInfo`, which would help removing the observable with the list of spaces in the previous mentioned ViewModels.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch spaces/entity_file_space
- [ ] Development tasks
  - [ ] Add space to `OCFileWithSyncInfo` (and all the layers behind)
  - [ ] Adapt code to the new entity that already contains the space
  - [ ] Remove observables with the list of spaces
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch spaces/entity_file_space into master
