### ISSUE TITLE
[FEATURE REQUEST] Open in Web showing all the providers

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3994]
As a user, I want to open a file directly with my favorite web app provider.

In the details view, instead of `Open in Web` we should show the different providers available to open the file in web:

```
Open in Collabora
Open in OnlyOffice
```
https://owncloud.dev/services/app-registry/apps/#app-registry

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App #3990 
- Library (if needed) owncloud/android-library#553

**Comment by jesmrec** [comment]
Testing done over https://ocis.ocis-wopi.latest.owncloud.works/app/list

With extension in app/list:

- [X] .pdf (OnlyOffice) 
- [X] .odt (OnlyOffice & Collabora) 
- [X] .ods (OnlyOffice & Collabora) 
- [X] .odt (OnlyOffice & Collabora) 
- [X] .docx (OnlyOffice & Collabora) 
- [X] .xlsx (OnlyOffice & Collabora) 
- [X] .pptx (OnlyOffice & Collabora) 

Without extension in app/list:

- [X] .txt (OnlyOffice & Collabora) 
- [X] .png (Collabora)
- [X] .htm (OnlyOffice)
- [X] .gif (Collabora)
- [X] .jpg (Collabora)
- [X] .tiff (Collabora)
- [X] .xml (OpenOffice)
- [X] .epub (OnlyOffice)
- [X] octet-stream file (OnlyOffice & Collabora) 
 
Without app provider:

- [X] .zip
- [X] .css
- [X] .sh
- [X] .xsl
- [X] .md
- [X] Source code (.php, .java, .js, .c, .h, .kt, .json...)
- [X] Media (.ogv, .wmv, .avi, .mov, .mpg, .mp3, .mp4...)
