### ISSUE TITLE
[FEATURE REQUEST] Create new file via Open in Web

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3995]
As a user, I want to create a new file and open it directly on the web.

On the floating action button, we need a new item for each available file we can create on the web.

https://owncloud.dev/services/app-registry/apps/#creating-a-file-with-the-app-provider

Create mini-fab if providers available for open
Set all options in bottom sheet
Ask for file name
Open in web
Refreshing list of files just after closing file in web

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/create_file_web
- [x] Development tasks
  - [x] Create network call to create file via app provider
  - [x] Create use case to create file via app provider
  - [x] Add new mini FAB and bottom sheet with the different available file options
  - [x] Hide mini FAB if there are no available file options to create
  - [x] When picking the document type in the bottom sheet, ask for file name and call use case
  - [x] Open file in web just after creating it
  - [x] Refresh list of files when closing file in web
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/create_file_web into master

**Comment by JuancaG05** [comment]
Not sure about which title show in the new mini floating button that will allow to create new files and then automatically open them in web.

The iOS app says "New document" as shown in the first screenshot. The other 2 are possible options for the floating button title:

| iOS title | Option 1 | Option 2 |
|---|---|---|
| ![new_file_ios](https://user-images.githubusercontent.com/57049315/232769158-9b736ab8-2039-485b-9b9c-ea90d27ca4ce.png) | ![new_file1](https://user-images.githubusercontent.com/57049315/232768919-fe2726b7-1e72-4eec-9256-96c0fcbf24ea.png) | ![new_file2](https://user-images.githubusercontent.com/57049315/232768975-295b0055-a66d-46bf-a1fc-762836ada91c.png) |

The difference here is that in iOS, the file is only created and not automatically opened in web, and in Android we do open it just after creating it, so it could be a bit weird for the user if the browser is opened with no previous warn. For this, the Option 2 would be more suitable, but we can also set Option 1 and let the user discover it the first time they create a new document.

Also open to other suggestions!

What do you think? @michaelstingl @tbsbdr @jesmrec

**Comment by michaelstingl** [comment]
Let's try option 1, and we'll iterate on it…

**Comment by JuancaG05** [comment]
This is how the document type selector looks like at the moment (just visually, no action linked yet):

![Screenshot_20230420_134056](https://user-images.githubusercontent.com/57049315/233355571-485992db-5bae-47f9-b4a8-e9881226b4e0.png)

**Comment by JuancaG05** [comment]
Pending for these bugs in the server to be addressed:

- [ ] https://github.com/owncloud/ocis/issues/6140
- [ ] https://github.com/owncloud/ocis/issues/6141
