### ISSUE TITLE
[FEATURE REQUEST] Update WebFinger flow

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3998]
Adapt WebFinger flow to the latest updates.

Now, WebFinger will be requested first and will skip status.php in case the WebFinger call is a success

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/auth_webfinger_flow
- [x] Development tasks
  - [x] Ask WebFinger for the OIDC Issuer
  - [x] In case WebFinger call returns a 2xx, request the OIDC configuration
  - [x] In case WebFinger call returns anything else. start with regular status.php
  - [x] Move this logic to the OCServerInfoRepository
  - [x] Add tests to this new logic in the repo
  - [x] Update LoginActivity tests to match the new behavior
  - [x] Update ViewModel tests to match the new behavior
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/auth_webfinger_flow into master

### PR

- App https://github.com/owncloud/android/pull/4000
- Library (if needed) https://github.com/owncloud/android-library/pull/555

**Comment by michaelstingl** [comment]
> Now, WebFinger will be requested first and will skip status.php in case the WebFinger call is a success

Only for account setup, not regular start of the app with account configured?
