### ISSUE TITLE
[TECHNICAL] Move available operations in file list to UseCase

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4009]
Let's move the legacy `FileMenuFilter.java` class to Kotlin and transform it to use case.

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/filter_menu_usecase
- [x] Development tasks
  - [x] Create new enum with the different menu options
  - [x] Move `FileMenuFilter` to use case
  - [x] Create Fragment extension to show or hide menu options
  - [x] Replace `FileMenuFilter` uses by the new use case
  - [x] Remove old `FileMenuFilter`
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/filter_menu_usecase into master

### QA

Test plan:

Reports & improvements

- [x] (1) Sharing missing in oC10 https://github.com/owncloud/android/issues/4009#issuecomment-1570497306  [FIXED]
- [x] (2) Links view does not allow to share in oC10 https://github.com/owncloud/android/issues/4009#issuecomment-1570526571  [FIXED]
- [x] (3) Sharing not available in Details view (oC10) https://github.com/owncloud/android/issues/4009#issuecomment-1570540502  [FIXED]

**Comment by michaelstingl** [comment]
Needed for:
- https://github.com/owncloud/android/issues/2885
- https://github.com/owncloud/android/issues/3860

**Comment by JuancaG05** [comment]
The old filter, and thus the new use case, is used in the next screens:
- Main file list (when selecting at least 1 file)
- Details screen
- Audio preview screen
- Image preview screen
- Text preview screen
- Video preview screen

The filter consists of various menu options and parameters to select which of them must be shown in each case:
- **SELECT ALL:** shown always in the main file list except when all the files in the screen are already selected.
- **SELECT INVERSE:** shown always in the main file list.
- **DOWNLOAD:** shown when none of the selected files is synchronizing, no videos are being previewed, we're not in the av. offline screen, we're not in the shared by link screen, there are no folders among the selected files and there are no downloaded files among the selected ones.
- **RENAME:** shown when none of the selected files is synchronizing, no videos are being previewed, we're not in the av. offline screen, we're not in the shared by link screen, it is a single file or folder and we do have permission to rename it.
- **MOVE:** shown when none of the selected files is synchronizing, no videos are being previewed, we're not in the av. offline screen, we're not in the shared by link screen and we do have permissions to move the selection.
- **COPY:** shown when none of the selected files is synchronizing, no videos are being previewed, we're not in the av. offline screen and we're not in the shared by link screen.
- **REMOVE:** shown when none of the selected files is synchronizing, we're not in the av. offline screen, we're not in the shared by link screen and we do have permissions to remove the selection.
- **OPEN WITH:** shown when none of the selected files is synchronizing and it is a single file.
- **SYNCHRONIZE:** shown when none of the selected files is synchronizing, we're not in the av. offline screen, we're not in the shared by link screen and in the selection there is at least one file downloaded or one folder.
- **CANCEL SYNC:** shown when at least one of the selected files is synchronizing, we're not in the av. offline screen, we're not in the shared by link screen and none of the selected files is available offline.
- **SHARE:** shown when we're not in the av. offline screen, share via link or with users is allowed, resharing is allowed, we're in the personal space and it is a single file or folder.
- **DETAILS:** shown when it is a single file.
- **SEND:**  shown when none of the selected files is synchronizing, no videos are streaming, we're not in the av. offline screen, there are no folders in the selection and all files in the selection are downloaded or it is a single file and send is allowed.
- **SET AS AVAILABLE OFFLINE:** shown when none of the selected files is synchronizing, there is at least one not-available offline file in the selection and no videos are streaming.
- **UNSET AS AVAILABLE OFFLINE:** shown when there is at least one available offline file in the selection and no videos are streaming.


In addition, the following screens have additional restrictions:
- Details screen: **DETAILS**, **MOVE** and **COPY** options are always removed.
- Audio preview screen: **RENAME**, **MOVE**, **COPY** and **SYNC** options are always removed.
- Image preview screen: **RENAME**, **MOVE**, **COPY** and **SYNC** options are always removed.
- Text preview screen: **RENAME**, **MOVE**, **COPY** and **SYNC** options are always removed.

**Comment by jesmrec** [comment]
Let's QA

**Comment by jesmrec** [comment]
### (1)

1. Open a oC10 account
2. Select any item in the list

Not reproducible in oCIS

Current: Share option is not available
Expected: Share option is available (sharing allowed via capability)

Pixel2, Android11 
`766480781`

**Comment by jesmrec** [comment]
### (2)

1. Open a oC10 account
2. Create a public link over any item
3. Open the `Links` view
4. Select any item in that list

Current: Share option is not available
Expected: Share option is available (sharing allowed via capability)

Pixel2, Android11
`766480781`

**Comment by jesmrec** [comment]
### (3) 

May be related with (1)

1. In oC10, open `Details` of any file

Current: Share option is not available
Expected: Share option is available (sharing allowed via capability)

Pixel2, Android11
`766480781`

**Comment by JuancaG05** [comment]
(1), (2) and (3) should be fixed now 👍 
About (4):
> * options `Select All` and `Select inverse` are part of the filter? they shouldn't since they are going to be static in the list of files, no matter selections and operations. Indeed, when all available operations will be moved to the new menu, `Select All` and `Select inverse` will keep in the top-bar 3-bot-button.

Yes, they are. They have a tiny dynamic behaviour since "Select all" is only shown when not every file is selected and we are in the main file list, and "Select inverse" only when we are in the main file list. We could separate them from the filter but then we would spread the menu options logic in several parts of the code...

> * New markdown support is inserted in txt preview right? it's not another kind of preview.
That's correct, it is the same preview but displayed differently if it's a `.md` file

**Comment by jesmrec** [comment]
This is the test matrix:


## Single selection

|| File List | Links (oC10) | Details | Av. Offline | Img preview| Video preview | Audio preview | Txt preview | While Sync |
|:-:| :-------: | :---: | :---------: | :---: | :--------: | :-----------: | :-----------: | :---------: | :-: |
| Download (only files) | Available<br>:white_check_mark: | Not available<br>:white_check_mark:| Available<br>:white_check_mark: | Not available<br>:white_check_mark: | Not available<br>:white_check_mark: | Not available<br>:white_check_mark: | Not available<br>:white_check_mark: | Not available<br>:white_check_mark: | Not available<br>:white_check_mark: |
| Rename |Available<br>:white_check_mark: | Not available<br>:white_check_mark: |Available<br>:white_check_mark: | Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:
| Move |Available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:
| Copy |Available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:
| Remove |Available<br>:white_check_mark:| Not available<br>:white_check_mark:|Available<br>:white_check_mark: | Not available<br>:white_check_mark:|Available<br>:white_check_mark:|Available<br>:white_check_mark:|Available<br>:white_check_mark:|Available<br>:white_check_mark:| Not available<br>:white_check_mark:
| Open with (only files) |Available<br>:white_check_mark:| Available<br>:white_check_mark:| Available<br>:white_check_mark:| Available<br>:white_check_mark:| Available<br>:white_check_mark:| Available<br>:white_check_mark:| Available<br>:white_check_mark:| Available<br>:white_check_mark:| Not available<br>:white_check_mark:| 
| Sync | Available<br>:white_check_mark:| Not available<br>:white_check_mark:| Available (downloaded files)<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:|Not available<br>:white_check_mark:
| Cancel sync | Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Available (downloaded files)<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark:| Available<br>:white_check_mark:| Not available<br>:white_check_mark:| Not available<br>:white_check_mark: | Available<br>:white_check_mark:
| Share | Available<br>:white_check_mark:| Available<br>:white_check_mark: | Available<br>:white_check_mark:| Not available<br>:white_check_mark: | Available<br>:white_check_mark:| Available<br>:white_check_mark:| Available<br>:white_check_mark:| Available<br>:white_check_mark:| Available<br>:white_check_mark:
| Details (only files) | Available<br>:white_check_mark: | Available<br>:white_check_mark: | Not available<br>:white_check_mark: | Available<br>:white_check_mark: | Available<br>:white_check_mark: | Available<br>:white_check_mark: | Available<br>:white_check_mark: | Available<br>:white_check_mark: | Available<br>:white_check_mark:
| Send (downloaded files) |Available<br>:white_check_mark: | Available<br>:white_check_mark: | Available<br>:white_check_mark: | Not Available<br>:white_check_mark: | Available<br>:white_check_mark:| Available<br>:white_check_mark: | Available<br>:white_check_mark: | Available<br>:white_check_mark: | Not available<br>:white_check_mark: 
| Set as av. off. |Available<br>:white_check_mark: | Available<br>:white_check_mark: | Available<br>:white_check_mark: | Not available<br>:white_check_mark: | Available<br>:white_check_mark:| Available (no streaming)<br>:white_check_mark: | Available<br>:white_check_mark: | Available<br>:white_check_mark: | Not available<br>:white_check_mark: 
| Unset as av. off. |Available<br>:white_check_mark: | Available<br>:white_check_mark: | Available<br>:white_check_mark: | Available<br>:white_check_mark: | Available<br>:white_check_mark:| Available (no streaming)<br>:white_check_mark: | Available<br>:white_check_mark: | Available<br>:white_check_mark: | Not available<br>:white_check_mark: 

## Multiple selection

|| File List | Links | Details | Av. Offline | Img preview| Video preview | Audio preview | Txt preview | While Sync |
|:-:| :-------: | :---: | :---------: | :---: | :--------: | :-----------: | :-----------: | :---------: | :-: |
| Download (not downloaded files)|Available<br>:white_check_mark:| Not available<br>:white_check_mark: | NA | Not available<br>:white_check_mark: | NA | NA | NA | NA | NA 
| Rename | Not available<br>:white_check_mark: |Not available<br>:white_check_mark: | NA |Not available<br>:white_check_mark: |NA |NA |NA |NA |Not available<br>:white_check_mark:
| Move |Available<br>:white_check_mark:|Not available<br>:white_check_mark: | NA | Not available<br>:white_check_mark: |NA |NA |NA |NA |Not available<br>:white_check_mark:
| Copy |Available<br>:white_check_mark:|Not available<br>:white_check_mark: | NA |Not available<br>:white_check_mark: |NA |NA |NA |NA |Not available<br>:white_check_mark:
| Remove |Available<br>:white_check_mark:|Not available<br>:white_check_mark: |  NA |Not available<br>:white_check_mark: |NA |NA |NA |NA |Not available<br>:white_check_mark:
| Open with | Not available<br>:white_check_mark: | Not available<br>:white_check_mark: | NA | Not available<br>:white_check_mark:|NA |NA |NA |NA | Not available<br>:white_check_mark:
| Sync | Available<br>:white_check_mark: | Not available<br>:white_check_mark: | NA | Not available<br>:white_check_mark: | NA|NA |NA |NA| Not available<br>:white_check_mark:
| Cancel sync | Not available<br>:white_check_mark:| Not available<br>:white_check_mark: | NA | Not available<br>:white_check_mark:|NA |NA |NA |NA | Available<br>:white_check_mark:
| Share | Not available<br>:white_check_mark: | Available<br>:white_check_mark: | NA | Not available<br>:white_check_mark: | NA |NA |NA |NA| Not available<br>:white_check_mark:
| Send (downloaded files) | Available<br>:white_check_mark: | Available<br>:white_check_mark:| NA | Not available<br>:white_check_mark:| NA |NA |NA |NA| Not available<br>:white_check_mark:
| Set as av. off. | Available<br>:white_check_mark: | Available<br>:white_check_mark:| NA | Not available<br>:white_check_mark:| NA |NA |NA| NA| Not available<br>:white_check_mark:
| Unset as av. off. | Available<br>:white_check_mark: | Available<br>:white_check_mark:| NA | Available<br>:white_check_mark:| NA |NA |NA| NA| Not available<br>:white_check_mark:
