### ISSUE TITLE
[RELEASE] 4.0

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4012]
### TASKS:

 - [x] [DOC] Ping in #documentation-internal about the new release
 - [x] [GIT] Create branch `release/4.0` in owncloud/android from master
 - [x] [DEV] Warn users with oCIS accounts that accounts must be removed and reattached
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create a folder for the new version like `M.m.p_YYYY-MM-DD` inside the `changelog` folder
 - [x] [DIS] Move all changelog files from the unreleased folder to the new version folder
 - [x] [DIS] Update screenshots, if needed, in README.md
 - [x] [DIS] Add ReleaseNotes replacing `emptyList` with `listOf` and adding inside `ReleaseNote()` with String resources
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [DOC] Ping in #documentation-internal to let them merge their PR before creating the tag
 - [x] [GIT] Create and sign tag `oc-android-4.0` in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Create and sign tag `2.1` in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [x] [GIT] Merge branch `release/4.0` in owncloud/android, into `stable`
 - [x] [GIT] Rebase with `master` in owncloud/android and merge into it
 - [x] [GIT] Merge branch `release/4.0` in owncloud/android-library, into `stable`
 - [x] [GIT] Rebase with `master` in owncloud/library and merge into it
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [GIT] Publish a new release in owncloud/android
 - [x] [DIS] Create post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))
 - [x] [COM] Inform `#updates` and `#marketing` in internal chat
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - [ ] [DOC] Update documentation with new stuff by creating [issue](https://github.com/owncloud/docs-client-android/issues)

### QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_4.0/Regression.md

Reports:

- [x] (1) Search bar not implemented in spaces view https://github.com/owncloud/android/issues/4012#issuecomment-1542128383 [FIXED]
- [x] (2) Thumbnails are refreshed only twice https://github.com/owncloud/android/issues/4012#issuecomment-1542175817 [FIXED]
- [X] (3) FAB visible in space with viewer permission the first time https://github.com/owncloud/android/issues/4012#issuecomment-1545369990 
- [X] (4) Edit public link with `upload only` https://github.com/owncloud/android/issues/4012#issuecomment-1547280983 [FIXED]
- [x] (5) Add new field to public link creation https://github.com/owncloud/android/issues/4012#issuecomment-1549228885 [WONT FIX HERE]

**Comment by jesmrec** [comment]
### (1)

1. Attach oCIS account with spaces
2. In Spaces view, click on the top bar

Current: `Search this folder`
Expected: Filter is not implemented, so the searching bar should not be displayed there. In the scope of https://github.com/owncloud/android/issues/3865, it is a nice feature

Pixel 2, Android 11
`007cbca44`

**Comment by jesmrec** [comment]
### (2)

maybe related with https://github.com/owncloud/android/issues/3865

1. In web, set an image to a space
2. In app, check that the image refreshes
3. In web, change the image again
4. In app, check that the image refreshes
5. Check again in app

After a couple of changes if the image in web, app does not refresh anymore.

Expected: App gets the image as many times as the server changes it

Pixel 2, Android 11
`007cbca44`

**Comment by JuancaG05** [comment]
(1) should be fixed now
I detected where the problem of (2) is coming, it's a bit more complex than that but not related with the issue you suggest. It's about how we store the spaces images in database, not about the images cache. I will take a look and let you know 👍.

**Comment by JuancaG05** [comment]
(2) should be fixed now as well 👍 @jesmrec

**Comment by jesmrec** [comment]
### (4)

This one, reproducible again, so reopened

https://github.com/owncloud/android/issues/3825

**Comment by JuancaG05** [comment]
About (3), it has a logical explanation: when we fetch spaces, we don't fetch their root folder (and so its permissions). In https://github.com/owncloud/android/pull/3978/files, what we did is creating a new root folder the first time we navigate to it (until we fetch it) with `CK` permissions by default (ability to write and add new subdirectories) thinking on the personal space. This also happens for the rest of spaces, and if the user doesn't have permissions, the first time will see the FAB anyway. If the user tries to add content to the space where they don't have permissions, errors will be handled by the server, so it's not a very wicked behaviour, it's just a glitch as you said. This behaviour can be changed in a future, but we have to take into account that if we fetch the root folders together with the spaces, this could produce lag when there are many spaces to fetch.
Will check (4) 👍

**Comment by jesmrec** [comment]
### (5)

Comes from https://github.com/owncloud/ocis/issues/5139

Issue is still reproducible, but, checking last comment, there is a fix in server side that should be added also in clients.

Public links has to add a new field in the payload `space` with the space reference in one of the mentioned formats, in order to build the correct path to the item and fix the described problem.

**Comment by JuancaG05** [comment]
A possible fix for (5) was pushed to `release/4.0_fix_public_share`, pending for a response from the backend team since it doesn't work as expected.

**Comment by jesmrec** [comment]
4.0 is QA approved

**App commit**: `26ccad5af`
**Library commit**: `e6937b42`

**Device**: Pixel2 Android 11

**Changelog:** https://github.com/owncloud/android/blob/master/CHANGELOG.md 

**Considerations**:

- No migration was done after last release (3.0.4) in regards of oCIS. In order to get a complete oCIS support in this new version (spaces included), all existing oCIS accounts in previous version must be removed from app and then, added again. A warning in the app will show this issue.

- Some features like:

    - Auto uploads
    - Sharing (with users and by link)
    - Sharing from a 3rd party app
	
	are available only for the “Personal” space of oCIS accounts.

-  `4.0` will be the last version with support for Android 5.x

- Known issue: Spaces’s thumbnails are not loaded the first time the spaces view is displayed, because a caching problem. https://github.com/owncloud/android/issues/3959

- Known issue: fix of https://github.com/owncloud/ocis/issues/5139 may need some tweak in the Android app. Check the message stream to get more info about this. List of public links is not refreshed after creation, need to re-open the share view to see it. First draft of the fix in `release/4.0_fix_public_share` branch

great job, team!
