### ISSUE TITLE
[FEATURE REQUEST] Improve grid mode

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4027]
Grid mode is currently not so good-looking, as we can see in the next screenshot:

![grid_mode](https://user-images.githubusercontent.com/57049315/234851422-d6dccf2d-48eb-47c2-95a2-ca0cb12abe8b.png)

Each cell is too separated from the others and there's much blank space in between. This view can be improved to offer a better user experience, for example, by increasing the size of the image thumbnails and reducing the margin between them.

Any ideas are welcome!

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/improve_grid_mode
- [ ] Development tasks
  - [ ] Make ONLY images thumbnails fill the whole space for the grid cell
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/improve_grid_mode into master

**Comment by ashu-sa** [comment]
Hii i'm new to open source, can i work on this feature

**Comment by AdityaJain09** [comment]
Hi @JuancaG05 ,, I hope you're doing well. I'm wondering if you could help me with something since I'm new to open source and thinking to work on this feature but when i build the app got this error. 
![owncloud_error](https://github.com/owncloud/android/assets/42073000/e52566de-e5a5-49dc-a24b-9266863e755a)

**Comment by JuancaG05** [comment]
Hi @AdityaJain09! Did you clone the project recursively? It is required so that you have the `owncloud-library` project locally as well, as a submodule of the main project. You can check in [SETUP.md](https://github.com/owncloud/android/blob/release/4.0/SETUP.md) how to do this step by step. If you follow this steps and it continues not working, just tell me and we'll keep searching for a solution 👍

**Comment by JuancaG05** [comment]
@AdityaJain09, I think @ashu-sa also wanted to work on this. Please, coordinate and let us know if any of you is going to work on this finally, so that you don't duplicate work. Since he posted first, @ashu-sa, do you want to work on this?
Don't worry if any of you don't work on this issue finally, we have lots of issues and we can create several more, similar to this one 😛.

**Comment by parneet-guraya** [comment]
> Hi @AdityaJain09! Did you clone the project recursively? It is required so that you have the `owncloud-library` project locally as well, as a submodule of the main project. You can check in [SETUP.md](https://github.com/owncloud/android/blob/release/4.0/SETUP.md) how to do this step by step. If you follow this steps and it continues not working, just tell me and we'll keep searching for a solution +1

I'm getting the same error. 
"Did you clone the project recursively?" I used this command from
[https://github.com/owncloud/android/blob/release/4.0/SETUP.md](url)
command -> git clone --recursive https://github.com/YOURGITHUBNAME/android.git
I think it is doing recursivley. Also followed the steps as mentioned.

**Comment by JuancaG05** [comment]
Hi @parneet-guraya! I just tried following the exact steps from [SETUP.md](https://github.com/owncloud/android/blob/release/4.0/SETUP.md) and could clone and build the project correctly. I can suggest a couple of things that may not be so clear in the setup docs:
- This should be done automatically, but in case it is not, try pressing "Sync Project with Gradle Files" in Android Studio (in the top bar, at the right) before trying to build.
- Also before trying to build, execute the `git submodule update` command in the terminal.
- Update Android Studio to the latest stable release. I guess you are not using a very old version, but if that's the case, each Android Studio version only supports up to a specific Gradle version, this could be the reason.

Try checking these points and let's see if we can solve your problem 👍

**Comment by parneet-guraya** [comment]
- [x]  This should be done automatically, but in case it is not, try pressing "Sync Project with Gradle Files" in Android Studio (in the top bar, at the right) before trying to build.

- [x] Also before trying to build, execute the git submodule update command in the terminal.


- Update Android Studio to the latest stable release. I guess you are not using a very old version, but if that's the case, each Android Studio version only supports up to a specific Gradle version, this could be the reason.

**Here are the details about Android Studio and gradle version.**

**Android Studio version -> Android Studio Flamingo | 2022.2.1 Patch 1**

**Gradle version(file:gradle-warpper.properties) --> distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip**

From google dev docs -> [Flamingo 2022.2.1 | Gradle version 3.2-8.0](https://developer.android.com/build/releases/gradle-plugin#android_gradle_plugin_and_android_studio_compatibility).

I have done the things you've mentioned.

**But it is giving the warning ->** 

![Screenshot from 2023-05-17 13-12-12](https://github.com/owncloud/android/assets/111801812/d3b9dc9d-2a34-432a-b8d1-f6ac9e9543ed)

**Comment by JuancaG05** [comment]
Hi again @parneet-guraya! Ok! So if you followed the steps I mentioned, is it building now properly? That warning is not important and we can ignore it, doesn't affect to the building process.

**Comment by parneet-guraya** [comment]
No it's not. Still getting the same error :-(

**Comment by JuancaG05** [comment]
😱 Ok, let's try another thing. In the message error that @AdityaJain09 posted, it says something related with the `mdmDebug` variant. Although we could do our work there, we're not interested in that variant for this. Let's try to build the `originalDebug` variant that we can choose from the sidebar menu in Android Studio:

<img width="293" src="https://github.com/owncloud/android/assets/57049315/40a97e3e-d10b-4af2-9249-c078e577ffed">

I guess the error will be the same but at least we can discard some reasons.
If you are still getting the same error with the `originalDebug` variant, please upload a new screenshot with the error (that I guess won't contain references to `mdmDebug` variant).

**Comment by parneet-guraya** [comment]
![Screenshot from 2023-05-17 18-29-37](https://github.com/owncloud/android/assets/111801812/e484ee33-b45f-4f09-9af3-d1aecfff4e39)

**Comment by JuancaG05** [comment]
Hi @parneet-guraya! This is weird!

I have uploaded a possible fix for this to a separate branch, `fix/building_app`. I'm going to ask you to try it and tell me whether it works or not. Before building the app, go to File > Invalidate Caches > Check every option and press "Invalidate and Restart". I hope we can fix this soon!

**Comment by JuancaG05** [comment]
I think it is stable now, you can try it 👍

**Comment by parneet-guraya** [comment]
**Git commands ->** 

- git fetch upstream
- git rebase upstream/master
- git checkout branch fix/building_app
- git submodule update

Tried building the project again but error still persists 
![Screenshot from 2023-05-18 17-19-21](https://github.com/owncloud/android/assets/111801812/12fe373c-6ffa-4c0d-946e-89f71d2bf432)

**Comment by parneet-guraya** [comment]
@AdityaJain09 Hi, Yes I've used the recursive flag while cloning. Now what should I do?

**Comment by JuancaG05** [comment]
> Hi @JuancaG05, @parneet-guraya it worked on my machine, the problem was i didn't use "--recursive" flag. command -> git clone --recursive https://github.com/YOURGITHUBNAME/android.git

Nice! I'm glad you solved your problem :-).

> @JuancaG05 but how to access main screen app says enter server name, do i have to configure owncloud server on my machine or is there any guide that i should follow ?

For testing purposes, you can access https://demo.owncloud.com/ for an ownCloud 10 server, and https://ocis.owncloud.com/ for an oCIS server. I recommend you use both since currently we support both versions of the backend. These instances are restarted every hour so that all the data inside them is removed, as well as the token generated when login (you will have to login again).
But of course, you can create your own server. In this case I recommend you to use the demo server, but if you feel like, try creating your own 😉.

**Comment by AdityaJain09** [comment]
Hi @JuancaG05, After digging into this problem, I have come up with an approach. However, since the image size is fixed, simply increasing the size of the image and reducing the margin might work for large screen devices .Conversely, image in small screen devices looks too big and  the folder name is either completely cut off or partially visible. This can be seen in the following example
![Screenshot_20230522-075929](https://github.com/owncloud/android/assets/42073000/883458cf-3b8c-4267-b39e-8328e30e17d4)

1. Create multiple layouts for supporting different screen sizes.
  Disadvantages of using this approach 
  -  Having multiple layout can increase the app size.
  - Maintaining separate layout for different devices can result in fragmented codebase. 

2. Adjust the image size and reduce the space between them
 Disadvantage of using this approach
 - In small devices, due to the large folder size, the text will be partially hidden or clipped. 
 - Thee UI doesn't look intuitive 

I'm seeking your advice. If my approach to the problem is incorrect, I would greatly appreciate your input.

**Comment by JuancaG05** [comment]
Hi @AdityaJain09! How are you doing?
Hey, are you still working on this issue or are you interested on keeping working on it? Let us know, please, otherwise we'll plan to address it in some other way, thank you! 😀

**Comment by JuancaG05** [comment]
Out new teammate @Aitorbp will work on this 😺

**Comment by Aitorbp** [comment]
Hi @michaelstingl,
In connection with this issue, I have made a new layout of the grid.
In the screenshot below you can see how the image occupies more size than before, eliminating the space of the text view, but maintaining some space between items.
![MicrosoftTeams-image](https://github.com/owncloud/android/assets/34248951/e6012944-905b-49c4-8a8c-ec9cec48d2c8)

In the version before the re-architecture, the spacing between items was much smaller, but honestly, I prefer the option that I show you above.
Here, is a screenshot before re-rearchitecture:
![Captura de pantalla 2023-06-30 113607](https://github.com/owncloud/android/assets/34248951/1f378aa9-e831-46e0-a9c7-be7c58549f18)

So I wanted to consult with you to know how to proceed: get a new option or do it equally than before re-architecture.

Regards

**Comment by JuancaG05** [comment]
IMO, I prefer the second option, so as it was before re-architecture 🤔 Let's collect some more opinions @jesmrec @manuelplazaspalacio @tbsbdr

**Comment by manuelplazaspalacio** [comment]
I prefer the second option too. I think with only two photos there isn't much difference. But in the case that there are more photos, the second option is much better.

**Comment by JuancaG05** [comment]
Thanks for your feedback @tbsbdr! We'll make image thumbnails bigger then. About showing 2 or 3 files per row instead of 4, let's discuss it in another issue if it proceeds, it would imply some more changes 😄.
