### ISSUE TITLE
[FEATURE REQUEST] Add suggested app to access document provider

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4028]
Add a new row in `More` section of `Settings` to suggest users an app to access document provider.

Title: `Access Document provider`
Subtitle: `Suggested app to browse the files of your device`
App: https://play.google.com/store/apps/details?id=com.marc.files 

Clicking the row should point to the link

We should add a new entry in `setup.xml` to show/hide the row in `Settings` as other options. It will be always true ftm.

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/settings_more_filesapp
- [x] Development tasks
  - [x] Add new row in "More" section of the app settings
  - [x] Add a new parameter to `setup.xml` to control visibility of this row
  - [x] Add unit tests
  - [x] Add UI tests
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/settings_more_filesapp into master

**Comment by JuancaG05** [comment]
The settings in the "More" section will be like in the next screenshot (new row was added just after the DAVx app):

![new_settings_option](https://user-images.githubusercontent.com/57049315/236193854-19cd6ea2-c3ae-4678-a4df-28ad667f073c.png)
