### ISSUE TITLE
[FEATURE REQUEST] Improve UX of creation dialog when forbidden characters are typed

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4031]
Comes from https://github.com/owncloud/android/pull/4023#issuecomment-1532672814

Using FAB, create a new document using a file name that already exists in the current folder

Currently, dialog closes and error message in snackbar: `File name contains at least one forbidden character`

This is a valid approach, but, i compared this with same error in dialog when sharing text from outside:

![Screenshot 2023-05-03 at 12 44 38](https://user-images.githubusercontent.com/14894746/235900627-e0c1964b-6115-4fd4-877b-783c653c9a49.png)

same approach in web. 

Advantage: user has the clue about what was wrong. With current approach, user must type again the whole name, guessing which one is the forbidden error. Likely, user could make another mistake.

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/feature_name
- [x] Development tasks
  - [x] Implement whatever
  - [x] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)
