### ISSUE TITLE
[RELEASE] 4.0-beta.4

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4033]
### TASKS:

 - [x] [GIT] Create branch `release/4.0-beta.4` in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Add ReleaseNotes replacing `emptyList` with `listOf` and adding inside `ReleaseNote()` with String resources
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [GIT] Create and sign tag `oc-android-4.0-beta.4` in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Create and sign tag `2.1-beta.4` in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [x] [GIT] Merge branch `release/4.0-beta.4` in owncloud/android, into master
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [x] [GIT] Publish a new release in owncloud/android
 - [x] [DIS] Modify post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))
 - [x] [COM] Inform `#updates` and `#marketing` in internal chat
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
