### ISSUE TITLE
[RELEASE] 4.0_oem

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4042]
### TASKS:

- [x] [GIT] Create a new branch `release/4.0_oem` (optional)
- [x] [DIS] Update release notes in app with the proper content for oem release
- [x] [GIT] Create and sign tag `oc-android-4.0_oem` in HEAD commit of `release/4.0_oem` branch
- [x] [DEV] Approve and merge changes in ownBrander
  - [x] https://github.com/owncloud/ownbrander/issues?q=is%3Aopen+is%3Aissue+label%3A%22android+4.0%22
  - [x] Update version number in ownBrander
- [x] [OPS] Block oB button
- [x] Merge changes in scripts: Merge PR to modify package names inside build.gradle (gitea#19) 
- [x] [OPS] Deploy oB
- [x] [QA] Generate final APKs files from signed commit in builder machine and perform some basic checks:
    - [x] Installation of apk/aab generated by builder machine
    - [x] [Check Features](https://github.com/owncloud/ownbrander/issues?q=is%3Aopen+is%3Aissue+label%3A%22android+4.0%22)
    - [x] App update from previous version (generated in advance)
- [x] [QA] Notify result in #ownbrander
- [x] [OPS] Enable button

**Comment by jesmrec** [comment]
Everything done.
