### ISSUE TITLE
[FEATURE REQUEST] Force security if device is not protected

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4061]
Passcode/Pattern are free to be enabled/disabled for users in `Settings`

- Driven for a new boolean branding option: `device_protection` (another name?).  `false` by default. 
   - `false` status will have no effect on the app
   - `true` status will trigger new behaviour

New behaviour

- If device is protected with passcode (or another method), nothing to do.
- if device is not protected with passcode or another method, security must be enforced with the value set in `lock_enforced` (check [here](https://github.com/owncloud/android/issues/3543) how it works). This will have branding regards because `0` value is forbidden.

Add it to the MDM option set.

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/feature_name
- [x] Development tasks
  - [x] Implement whatever
  - [x] ...
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
> New behaviour

> If device is protected with passcode (or another method), nothing to do.
> if device is not protected with passcode or another method, security must be enforced with the value set in lock_enforced (check https://github.com/owncloud/android/issues/3543 how it works). This will have branding regards because 0 value is forbidden.

New behaviour to be redefined:

Logic to execute every time the app is open:

- If device is protected, or app has already pattern/passcode, or both: nothing to do

- If neither device nor app are protected, user is prompt to security. App must not be usable till user types a new passcode/pattern. These ones are not enforced (this is the main difference with the behaviour described above). That means, user could go to the `Settings` and disable passcode/pattern. Not a problem because the next launch will ask again for it. Only in case `lock_enforced` is enabled, then security will be enforced (apart of enabled).

please let me know if you miss any other scenario

**Comment by jesmrec** [comment]
Other way:

1. Device with protection and app not protected

|| lock_enforced = 0 | lock_enforced !=0 |
|:-:|:-:|:-:|
| **device_protection = true** | When app is open, user must add a passcode or pattern. In Settings, it is allowed to be disabled | When app is open, user must add a passcode or pattern.  In Settings, it is NOT allowed to be disabled, because enforcement |
| **device_protection = false** | Passcode/Pattern not mandatory | When app is open, user must add a passcode or pattern.  In Settings, it is NOT allowed to be disabled, because enforcement  |

2. Device with no protection and app not protected

|| lock_enforced = 0 | lock_enforced !=0 |
|:-:|:-:|:-:|
| **device_protection = true** | When app is open, user must add a passcode or pattern. In Settings, it is NOT allowed to be disabled, because device is not protected | When app is open, user must add a passcode or pattern.  In Settings, it is NOT allowed to be disabled, because enforcement |
| **device_protection = false** | Passcode/Pattern not mandatory | When app is open, user must add a passcode or pattern.  In Settings, it is NOT allowed to be disabled, because enforcement  |

3. App already protected

|| lock_enforced = 0 | lock_enforced !=0 |
|:-:|:-:|:-:|
| **device_protection = true** | Passcode/Pattern is already set. In Settings, it is allowed to be disabled if device is also protected. If device is not protected, NOT allowed to be disabled | In Settings, it is NOT allowed to be disabled, because enforcement |
| **device_protection = false** | Passcode/Pattern is already set. In Settings, it is allowed to be disabled, no matter if device is protected or not  | In Settings, it is NOT allowed to be disabled, because enforcement   |

i hope it's more clear now
