### ISSUE TITLE
[FEATURE REQUEST] Prevent http traffic

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4066]
New branding option like `enforce_secure_connection` (boolean):

- `true` : http traffic not allowed, just https
- `false`: http traffic allowed

In case http is not allowed and URL under http is typed, a correct error will be shown like `non-secured traffic not allowed`

Only checked in login view, not dynamic (at least in first iteration)

Default value: `false` (traffic allowed in vanilla app)

Reference: https://github.com/owncloud/enterprise/issues/5769

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/feature_name
- [x] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by michaelstingl** [comment]
> New branding option like `prevent_http` (boolean):

Better name  `enforce_https` or `enforce_ssl`?

**Comment by jesmrec** [comment]
> Better name enforce_https or enforce_ssl?

yes, sounds more positive since `true` allows and `false` disallows.

**Comment by jesmrec** [comment]
Let's call it `enforce_secure_connection`
