### ISSUE TITLE
[FEATURE REQUEST] Stop authentication flow after account removal if URL is fixed

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4067]
Reference:
- ~~https://github.com/owncloud/enterprise/issues/5693~~
- https://github.com/owncloud/android/issues/4067

Current behaviour:

1. In `setup.xml` set the following fields:
   - `server_url` -> any valid URL of a server using browser authentication
   - `show_server_url_input` -> false 
2. Install app and type credentials to add the account
3. Open `Manage accounts` and remove account

Moved to login view and then, straight to browser

Expected: login view. Browser will be open when user clicks on `CHECK SERVER` (rename button?). Only if URL is fixed and hidden.

That feature was added in the first webfinger iteration (non-authenticated).

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/stop_auth_flow_url_fixed
- [x] Development tasks
  - [x] Set conditions to continue or not with the authentication flow
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/stop_auth_flow_url_fixed into master

**Comment by JuancaG05** [comment]
To solve this I tried to keep the current flow (browser opens automatically) in all cases except when coming from removing the only account logged in the app in the accounts management screen. However, it seems that all cases in which we launch the login screen use a same common method for it, and cannot distinguish if I come from one screen or another, which was my original idea.

So, a possible solution could be removing the automatic opening of the browser when there is a fixed URL, the behaviour we had some versions ago (automatic opening was introduced as an improvement to save 1 click and make the login process smoother). What do you think @michaelstingl?

**Comment by michaelstingl** [comment]
> So, a possible solution could be removing the automatic opening of the browser when there is a fixed URL, the behaviour we had some versions ago (automatic opening was introduced as an improvement to save 1 click and make the login process smoother). What do you think @michaelstingl?

Yes, should solve it 👍
