### ISSUE TITLE
[TECHNICAL] Unit tests for datasource classes - Part 1

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4070]
Epic: https://github.com/owncloud/android/issues/4063

In this issue we'll address the unit tests for the classes:
- OCLocalAppRegistryDataSource
- OCRemoteAppRegistryDataSource
- OCLocalAuthenticationDataSource
- OCRemoteAuthenticationDataSource
- OCLocalCapabilitiesDataSource
- OCRemoteCapabilitiesDataSource

Remember we want to create unit tests that **check that every method returns the expected result** and **verify that every method calls the corresponding methods of other classes**.

### TASKS

- [x] Research (if needed)
- [x] Create branch technical/testing_datasources_1
- [ ] Development tasks
  - [x] Create unit tests for `OCLocalAppRegistryDataSource`
  - [x] Create unit tests for `OCRemoteAppRegistryDataSource`
  - [x] Create unit tests for `OCLocalAuthenticationDataSource`
  - [x] Create unit tests for `OCRemoteAuthenticationDataSource`
  - [x] Create unit tests for `OCLocalCapabilitiesDataSource`
  - [x] Create unit tests for `OCRemoteCapabilitiesDataSource`
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch technical/testing_datasources_1 into master
