### ISSUE TITLE
[TECHNICAL] Unit tests for datasources classes - Part 2

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4071]
Epic: https://github.com/owncloud/android/issues/4063

In this issue we'll address the unit tests for the classes:
- OCLocalFileDataSource
- OCRemoteFileDataSource

Remember we want to create unit tests that **check that every method returns the expected result** and **verify that every method calls the corresponding methods of other classes**.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch technical/testing_datasources_2
- [ ] Development tasks
  - [ ] Create unit tests for `OCLocalAppRegistryDataSource`
  - [ ] Create unit tests for `OCRemoteAppRegistryDataSource`
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch technical/testing_datasources_2 into master
