### ISSUE TITLE
[TECHNICAL] Unit tests for datasources classes - Part 3

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4072]
Epic: https://github.com/owncloud/android/issues/4063

In this issue we'll address the unit tests for the classes:
- OCFolderBackupLocalDataSource
- OCRemoteOAuthDataSource
- OCRemoteShareeDataSource
- OCLocalShareDataSource
- OCRemoteShareDataSource
- OCLocalSpacesDataSource
- OCRemoteSpacesDataSource
- OCLocalTransferDataSource
- OCLocalUserDataSource
- OCRemoteUserDataSource
- OCRemoteWebFingerDatasource

Remember we want to create unit tests that **check that every method returns the expected result** and **verify that every method calls the corresponding methods of other classes**.

### TASKS

- [x] Research (if needed)
- [x] Create branch technical/testing_datasources_3
- [x] Development tasks
  - [x] Create unit tests for `OCFolderBackupLocalDataSource`
  - [x] Create unit tests for `OCRemoteOAuthDataSource`
  - [x] Create unit tests for `OCRemoteShareeDataSource`
  - [x] Create unit tests for `OCLocalShareDataSource`
  - [x] Create unit tests for `OCRemoteShareDataSource`
  - [x] Create unit tests for `OCLocalSpacesDataSource`
  - [x] Create unit tests for `OCRemoteSpacesDataSource`
  - [x] Create unit tests for `OCLocalTransferDataSource`
  - [x] Create unit tests for `OCLocalUserDataSource`
  - [x] Create unit tests for `OCRemoteUserDataSource`
  - [x] Create unit tests for `OCRemoteWebFingerDatasource`
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch technical/testing_datasources_3 into master
