### ISSUE TITLE
[TECHNICAL] Unit tests for datasources classes (providers) - Part 4

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4073]
Epic: https://github.com/owncloud/android/issues/4063

In this issue we'll address the unit tests for the classes:
- OCSharedPreferencesProvider
- ScopedStorageProvider

Remember we want to create unit tests that **check that every method returns the expected result** and **verify that every method calls the corresponding methods of other classes**.

In addition, in this case, we'll have to discuss if moving these providers to a new package `providers` inside the `owncloudData` module since these are special datasources.

### TASKS

- [x] Research (if needed)
- [x] Create branch technical/testing_datasources_4
- [x] Development tasks
  - [x] Create unit tests for `OCSharedPreferencesProvider`
  - [x] Create unit tests for `ScopedStorageProvider`
  - [x] Discuss if moving providers to a new package `providers`
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch technical/testing_datasources_4 into master
