### ISSUE TITLE
Respect app_provider values from capabilities

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#4075]
@DeepDiver1975 reported in https://github.com/owncloud/enterprise/issues/5747#issuecomment-1593139899, Android app doesn't respect the `app_provider` values from the capabilities

```
      "capabilities": {
        "files": {
          "app_providers": [
            {
              "enabled": true,
              "version": "1.1.0",
              "apps_url": "/app/list",
              "open_url": "/app/open",
              "open_web_url": "/app/open-with-web",
              "new_url": "/app/new"
            }
          ]
        }
      }
```

**Comment by DeepDiver1975** [comment]
Specifically: `apps_url` is not respected in my test. No matter what the server (owncloud 10) is returning as path - android app is still calling `/app/list`

**Comment by DeepDiver1975** [comment]
Testsystem: https://app-registry-demo.owncloud.works/index.php/settings/users
User demo:123456

**Comment by Aitorbp** [comment]
### TASKS

- [x] Research (if needed)
- [x] Create branch feature/respect_app_provider_values_from_capabilities
- [ ] Development tasks
  - [x] Create at least 2 design proposals for the details view
  - [x] With the chosen proposal, start to implement it just with the fields that we have right now
  - [x] Add last sync field with the new design
  - [x] Add info about status of the file with the new design
  - [ ] Add unit tests
  - [ ] Add UI tests
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/respect_app_provider_values_from_capabilities into master
