### ISSUE TITLE
[FEATURE REQUEST] Support "per app" language change on Android 13+

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#4082]
**Is your feature request related to a problem? Please describe.**

I'd like to easily see the ownCloud Android app in different languages, for example to contribute to the translations, or to capture screenshots for tutorials etc

**Describe the solution you'd like**

Android 13+ supports the change of the language for an individual app in your device settings.

**Describe alternatives you've considered**

Currently, I need to switch the device language, what causes more friction.

**Additional context**

- https://support.google.com/android/answer/12395118
- https://developer.android.com/guide/topics/resources/app-languages

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/feature_language_android13
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_language_android13 into master

### PR

- App
- Library (if needed)

**Comment by JuancaG05** [comment]
This shouldn't be so complex, it seems this feature can be included in the app by creating a new file specifying the languages we want to appear in this new device's settings menu, and then referencing it from the manifest. Let's say we could develop this in 2-3 days, taking into account QA?

**Comment by Aitorbp** [comment]
Hello @michaelstingl,
How many languages ​​do we put in the app? Right now I have included: English, Spanish, German, French ,Japanese and Chinese.
