### ISSUE TITLE
[FEATURE REQUEST] Improve details view

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4092]
Currently, our details view looks like this:

![](https://github.com/owncloud/android/assets/57049315/66cb9fee-9030-4df3-b50f-b31920d6dd93)

It looks a bit old-fashioned and empty, so let's add redesign it and add some new fields. The proposals here are:

- Create 2 or more proposals for the redesign of this screen
- Add last sync field (if it was synced previously, if it was not synced it can be hidden)
- Add info about status of the file (downloaded, syncing, available offline)
- OPTIONAL: Add info section for shares: who is this file shared with, who shared it with me, is it shared by public link...

More ideas welcome!

Some details view from other modern apps for inspiration:

| Google Drive | OneDrive |
|---|---|
| ![](https://github.com/owncloud/android/assets/57049315/ab17db31-5ff3-405a-bb91-fb2e32471d47) | ![](https://github.com/owncloud/android/assets/57049315/c6c0c23f-236c-47de-a8f1-88f304cb14b5) |

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/improve_details_view
- [ ] Development tasks
  - [x] Create at least 2 design proposals for the details view
  - [x] With the chosen proposal, start to implement it just with the fields that we have right now
  - [x] Add last sync field with the new design
  - [x] Add info about status of the file with the new design
  - [x] Add unit tests
  - [x] Add UI tests
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/improve_details_view into master

**Comment by Aitorbp** [comment]
Good morning,
I have done three designs for the detail view.
In the first design, we can see the items ordered in rows. It is a simple design, where you can see the items easily. I have added new properties like Created, Last Sync, and Status. In the Status property, I added an icon to be more representative.

**1 design:**

![Captura de pantalla 2023-07-10 103906](https://github.com/owncloud/android/assets/34248951/20ec6fc3-2cd7-42f1-bd14-ba1f8580420b)

In the second design, the items are ordered in a column. Also is a simple design and in my opinion, the items are more easily viewed than in the design one. The only thing I don't like is you have to scroll to see every item perfectly.

**2 design:**

![Captura de pantalla 2023-07-10 112309](https://github.com/owncloud/android/assets/34248951/2f4d68bc-c3f4-4e31-9c9c-226caa1e5801)

And then I show you the third design, which in my opinion is the most I like of all. The design is more complex and everything is more compact. The edges of the image are rounded, this is cool for me. In the same way, the items are separated from each other by dividers that make it easier to read the items. The name of the image is added in large below the image's center middle. For me, this is the most modern design of the three.

**3 design:**

![Captura de pantalla 2023-07-11 101032](https://github.com/owncloud/android/assets/34248951/d0709d0e-ef5a-412f-987f-47b0c6941f25)
![Captura de pantalla 2023-07-11 101108](https://github.com/owncloud/android/assets/34248951/336f21a1-3f11-4177-8ec0-55691a28209e)

Please @michaelstingl, @tbsbdr , @manuelplazaspalacio, and @jesmrec  could you give me feedback to choose one design?

Regards,

**Comment by michaelstingl** [comment]
ownCloud web for comparison:

![CleanShot 2023-07-12 at 09 20 32@2x](https://github.com/owncloud/android/assets/214010/f3bc3627-0967-490d-8e97-f268c4b2b368)

```
[Log]  ownCloud Web UI 6.0.0  (web-runtime-f0fd7d61.js, line 1)
[Log]  ownCloud 10.12.2 Enterprise  (web-runtime-f0fd7d61.js, line 1)
```

- Direct access for the **Private Link** could make sense on the details screen?
- `Status` and `Last sync` really needed? Will it live-update on the Details screen? Progress bar? Don't over-engineer it I'd say.
- I like the separator lines in 3rd design
- I don't need `Type` and `Size` side-by-side. Could be new line as well if it makes things easier
- Otherwise 👍

**Comment by tbsbdr** [comment]
Design 1 my clear favorite, because here I can capture the info the fastest.

**Comment by michaelstingl** [comment]
Please consider extremely long path names + and extremely long file names in your designs. Details page is the best way for users to review the full information.

**Comment by Aitorbp** [comment]
Hello,
I have added a new design according to the feedback. In this design, I put the items in blocks as @tbsbdr commented. Also, I have changed the text's color to Owncloud corporative colors like the web. I have kept the title in the middle of the screen and the division lines.

On the other hand, I have removed the text of the Status and I have kept the icon status in the thumbnail. The icon will change when the file changes status instantly.

Finally, I have added the path at the bottom of the screen. I have uploaded three designs so you can see how it would look if the text were long.

![Captura de pantalla 2023-07-12 105217](https://github.com/owncloud/android/assets/34248951/7312d098-d8a1-4eec-9ca9-12565ed609c2)
 
![Captura de pantalla 2023-07-12 111320](https://github.com/owncloud/android/assets/34248951/ee290eb0-2ce3-43d7-a801-be1e9e129c75)



What do you think about the new design? @michaelstingl @tbsbdr @jesmrec @manuelplazaspalacio

**Comment by tbsbdr** [comment]
good improvement 👍
one remark: font of the text on the right looks quite bold compared to the [1 design screenshot](https://github.com/owncloud/android/issues/4092#issuecomment-1630364235)

**Comment by Aitorbp** [comment]
Yes, It is bold @tbsbdr because I wanted to highlight the most important text in the screen.

**Comment by tbsbdr** [comment]
ah, in the first design right column was regular and the left column was just more decent. got it. If you ask me I'd not make it bold because it does not add to readability - bold is usually typographically harder to read in longer sentences. having the left column decent is perfect to shift focus to the right column (as it was in 1 design). so I'd stick to the style you had in 1 design.

**Comment by JuancaG05** [comment]
Nice improvement for this screen @Aitorbp! 💯
Some changes I would suggest following @tbsbdr advice, @michaelstingl suggestions and my personal ones:
- Right column shouldn't be bold. It's ok if it is set to the brandable color but with a regular font in order not to difficult readability
- `Last sync` row should be hidden when there has not been a sync in that file yet. It's very easy to check this case because the value of this field in 
- `Path` should be changes by `Location` and only show the path to the parent folder. Showing the file name is redundant and, in cases where the file name is so long, it takes a lot of space unnecessarily. Also, maybe setting more space between the title of the field (`Location:`) and its value (`/Mythings/...`)?
- The status badge at the corner of the image should be a bit bigger and partly out of the image so that it doesn't mix totally with its content. You can just move it slightly to the right and to the bottom
