### ISSUE TITLE
[FEATURE REQUEST] Align Sharing icons with other platforms

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#4101]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

<img width="1150" alt="CleanShot 2023-07-14 at 10 13 42@2x" src="https://github.com/owncloud/android/assets/214010/3079d376-fc5b-41a6-a1de-458a5599fe5c">

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/align_sharing_icons_with_other_platforms
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/align_sharing_icons_with_other_platforms into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
In the Android app, both "Share with Users" and "Share by Link" are handled in the same "Share" view which is represented but the current icon. Should we keep this and only change the icon in the list?

**Comment by michaelstingl** [comment]
I'd like to get rid of this icon for ownCloud user / group sharing:

![Sharing Icon](https://upload.wikimedia.org/wikipedia/commons/f/ff/Sharethis.svg)

It's used on the Android platform to send a copy of a file to another app. For this, it can stay.

Whenever we indicate ownCloud user / group sharing or have an action for ownCloud user / group sharing, I'd like to use the icon with the 2 people, as you can see in web and iOS.

**Comment by michaelstingl** [comment]
> In the Android app, both "Share with Users" and "Share by Link" are handled in the same "Share" view which is represented by the current icon. Should we keep this and only change the icon in the list?

iOS app uses 2-people icon for the share menu item for user / group + link:

![CleanShot 2023-07-14 at 10 57 09@2x](https://github.com/owncloud/android/assets/214010/bb86c772-e02b-497c-ac64-2026bf37adef)

**Comment by jesmrec** [comment]
Replace in:

- File list (second info line)
- Bottom operations sheet
- Multiselection mode

**Comment by michaelstingl** [comment]
![CleanShot 2023-07-17 at 10 26 34@2x](https://github.com/owncloud/android/assets/214010/ca0f6c0d-cd51-4915-b61e-bb10cc0fa9d2)
