### ISSUE TITLE
[FEATURE REQUEST] Auto-refresh when a file is uploaded

### ISSUE THREAD

**Issue by Aitorbp** [owncloud/android#4103]
**Is your feature request related to a problem? Please describe.**
When I create a file on the home screen after I've created it, this item doesn't appear in the feed. When a user uploads a file to the app, this item doesn't appear in the home screen feed in the first instance. You have to refresh the screen to see the new item. I think this functionality is not intuitive because when I come back from the upload file I don't see anything, so I think something is wrong or the file didn't upload.

**Describe the solution you'd like**
From my point of view, when the client returns to the main activity, the screen should refresh immediately. This way, users will see your download in the feed without the need to refresh the screen. It will improve the user experience.

**Additional context**
Next, I show you a video where you can see the current behavior. 

https://github.com/owncloud/android/assets/34248951/2ce8bb08-86c4-4bce-9750-51d214b9b7bd

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/refresh_after_upload
- [x] Development tasks
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/refresh_after_upload into master

**Comment by JuancaG05** [comment]
Some ideas here:
- Detect when the upload worker has finished and, if we continue in the same folder, refresh it so that the view is updated with the new file
- Add a badge in the uploads section of the bottom bar when there is something uploading (also when an upload has finished or failed)

More ideas welcome!

**Comment by abelgardep** [comment]
Maybe you can trigger a `SynchronizeFileUseCase` in the final step of the upload, so you save the new file info in the database within the upload and it should appear immediately when u are in the same folder.

Or adding a file to the database when the operation finishes. At that point you know some info of the upload: `path`, `owner`, `spaceId`, I think that u also know the `eTag`, maybe the `remoteId`. The file should appear and will be synchronized with all the info the next time the user refreshes the folder.

**Comment by michaelstingl** [comment]
For files being created and edited in web office now also trigger an auto refresh of the parent dir.
