### ISSUE TITLE
[FEATURE REQUEST] Show  app provider icon from endpoint

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4105]
After https://github.com/owncloud/android/issues/2885, all available options for a selection are shown in a bottom sheet.

In case of app providers to open a file in the browser, this is the current look:

![Screenshot 2023-07-17 at 11 08 04](https://github.com/owncloud/android/assets/14894746/4c953c6c-4fdc-4541-a10f-6100ab896638)

the `app/list` endpoint returns an icon for every specific provider together with the name.

It'd be nice to add the icon that comes from the server instead the static one, as other clients do

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/show_app_provider_icon_from_endpoint
- [x] Development tasks
  - [x] Create function to get drawable icon from url with Glide
  - [x] Add release notes
  - [x] Add calens
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master
