### ISSUE TITLE
[RELEASE] 4.1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4111]
### TASKS:

 - [x] [DOC] Ping in #documentation-internal about the new release
 - [x] [GIT] Create branch `release/4.1` in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create a folder for the new version like `4.1.0_YYYY-MM-DD` inside the `changelog` folder
 - [x] [DIS] Move all changelog files from the unreleased folder to the new version folder
 - [x] [DIS] Update screenshots, if needed, in README.md
 - [x] [DIS] Add ReleaseNotes replacing `emptyList` with `listOf` and adding inside `ReleaseNote()` with String resources
 - [x] [QA] Design Test plan
 - [x] [QA] Regression Test plan
 - [x] [DIS] Generate final bundle from signed commit in owncloud/android
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - [x] [GIT] Create and sign tag `v4.1.0` in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Create and sign tag `v2.2.0` in HEAD commit of release branch, in owncloud/android-library
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [x] [GIT] Publish a new release in [owncloud/android](https://github.com/owncloud/android/releases)
 - [x] [DIS] Release published in Google Play
 - [x] [DIS] Publish post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))
 - [x] [COM] Inform `#updates` and `#marketing` in internal chat
 - [x] [GIT] Merge `release/2.2` branch into stable, in owncloud/android-library
 - [x] [GIT] Merge `release/4.1` branch into stable, in owncloud/android
 - [x] [GIT] Merge `release/2.2` branch into master, in owncloud/android-library
 - [x] [GIT] Merge `release/4.1` branch into master, in owncloud/android
 - [x] [DOC] Update documentation with new stuff by creating [issue](https://github.com/owncloud/docs-client-android/issues)

### QA

Regression test: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_4.1/Regression.md

Bugs & improvements:

- [X] (1) Incorrect error in login view https://github.com/owncloud/android/issues/4111#issuecomment-1671085854 [FIXED]
- [X] (2) Incorrect share icon in log view https://github.com/owncloud/android/issues/4111#issuecomment-1673079176 [FIXED]
- [X] (3) Incorrect error when copying folder into itself https://github.com/owncloud/android/issues/4111#issuecomment-1688543181 [FIXED]
- [x] (4) Rename does not work https://github.com/owncloud/android/issues/4111#issuecomment-1689699442 [FIXED]
- [x] (5) Uploads broken https://github.com/owncloud/android/issues/4111#issuecomment-1690139565 [FIXED]
- [x] (6) Thubmnails as folders https://github.com/owncloud/android/issues/4111#issuecomment-1690269515 [FIXED]
- [x] (7) oC10 servers do not show conflict dialog https://github.com/owncloud/android/issues/4111#issuecomment-1690308525  [FIXED]
- [X] (8) Ugly error in copy with server down https://github.com/owncloud/android/issues/4111#issuecomment-1697264796 [FIXED]

**Comment by jesmrec** [comment]
### (1)

1. Set `<bool name="enforce_secure_connection">false</bool>`
2. Type an http url without http:// prefix

Current: `Connection is not secure, http traffic is not allowed`
Expected: `SSL initialization failed`, because an URL without prefix is guessed as https. 

Pixel 2 Android 11

**Comment by jesmrec** [comment]
### (2)

1. Open `Settings`-> `Logging` -> Log files

Current: Share icon is incorrect. Using the "share with users and groups" 

![Screenshot 2023-08-10 at 13 42 21](https://github.com/owncloud/android/assets/14894746/4dc07b61-99de-4352-86b4-951d2ab89e10)

Expected: "share with others" one instead

![Screenshot 2023-08-10 at 13 55 26](https://github.com/owncloud/android/assets/14894746/761b172d-e747-4368-8258-d85a133e0d4c)

Pixel 2 Android 11

**Comment by jesmrec** [comment]
### (3)

1. Create a folder inside another folder, f. ex /A/B
2. Select A and `Copy`
3. Select B as target folder

Current: error: `An error occurred when trying to copy this file or folder`
Expected (4.0): error:  `It is not possible to copy a folder into a descendant`

NOTE: same behaviour when copying folder into itself. 

You can check expected behaviour performing same steps with the `Move` option

Pixel 2 Android 11

**Comment by jesmrec** [comment]
### (4)

Try to rename any item in the list, using any name that's not used yet

Current: error `Rename could not be completed because file already exists`
Expected: item correctly renamed

Pixel 2 Android 11

**Comment by jesmrec** [comment]
### (5)

Uploads seem to be broken. They appear as queued forever.

Stacktrace i obseved:

```
android.view.WindowLeaked: Activity com.owncloud.android.ui.activity.FileDisplayActivity has leaked window DecorView@c2f46f0[FileDisplayActivity] that was originally added here
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:733)
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:717)
                                                                                                    	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:399)
                                                                                                    	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
                                                                                                    	at android.app.Dialog.show(Dialog.java:340)
                                                                                                    	at com.owncloud.android.presentation.files.filelist.MainFileListFragment.openBottomSheetToUploadFiles(MainFileListFragment.kt:766)
                                                                                                    	at com.owncloud.android.presentation.files.filelist.MainFileListFragment.registerFabUploadListener$lambda$7(MainFileListFragment.kt:713)
                                                                                                    	at com.owncloud.android.presentation.files.filelist.MainFileListFragment.$r8$lambda$p4LwSRqoxddS_yXHPAsop8FOeG8(Unknown Source:0)
                                                                                                    	at com.owncloud.android.presentation.files.filelist.MainFileListFragment$$ExternalSyntheticLambda8.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:7448)
                                                                                                    	at android.view.View.performClickInternal(View.java:7425)
                                                                                                    	at android.view.View.access$3600(View.java:810)
                                                                                                    	at android.view.View$PerformClick.run(View.java:28305)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Pixel 2 Android 11
`c6da843b`

**Comment by jesmrec** [comment]
### (6)

Not specific steps to reproduce, but i noticed that file thumbnails in the list turns into folder icon. Check the following video:

https://github.com/owncloud/android/assets/14894746/c09a3523-7509-4ba0-8de5-79ea2c7af588

some jpg files are shown as folders. I reproduce mainly with images but also i saw some other files.

Pixel 2 Android 11
`c6da843b`

**Comment by jesmrec** [comment]
### (7)

1. in oC10 account, select any item and `Copy`
2. Select the same folder as target folder

Current: nothing happens
Expected: conflict dialog should be shown. This behaviour is correct executing the steps above in oCIS server.

Pixel 2 Android 11
`c6da843b`

**Comment by jesmrec** [comment]
### (7)

[this item](https://github.com/owncloud/android/issues/4044) in the changelog is again reproducible. Fix is gone somehow.

Pixel 2 Android 11
`c6da843b`
