### ISSUE TITLE
[FEATURE REQUEST] Open in web - oC10 (app registry)

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4130]
Open in web is working over oCIS instances.

Now, it should be adapted to work over oC10.

Follow up: https://github.com/owncloud/enterprise/issues/5747

Changes to do

-
-
-
-

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/open_in_web_oc10
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/open_in_web_oc10 into master

**Comment by michaelstingl** [comment]
Can be tested witch oC `10.13.1` on demo.owncloud.com  and demo.owncloud.org

**Comment by JuancaG05** [comment]
Open in web is working on oC10 but on oCIS. Follow up here: https://github.com/owncloud/ocis/issues/7484
Closing this then 👍
