### ISSUE TITLE
[RELEASE] 4.1.0_oem

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4137]
### TASKS:

- [x] [GIT] Create a new branch `release/4.1.0_oem` (optional) from 4.1.0 tag
- [x] [DEV] Add content to the branch
- [x] [DIS] Update release notes in app with the proper content for oem release
- [x] [GIT] Create and sign tag `v4.1.0_oem` in HEAD commit of `release/4.1.0_oem` branch
- [x] [DEV] Approve and merge changes in ownBrander https://github.com/owncloud/ownbrander/issues/1074
  - [x] http traffic banned (hardcoded) 
  - [x] Device protection 
  - [x] Update version number in ownBrander
- [x] [OPS] Block oB button
- [x] [OPS] Deploy oB
- [x] [QA] Generate final APK/bundle files from signed commit in builder machine and perform some basic checks:
    - [x] Installation of apk/aab generated by builder machine
    - [x] Check http traffic banned
    - [x] Check device protection
    - [x] App update from previous version (generated in advance)
- [x] [QA] Notify result in #ownbrander
- [x] [OPS] Enable button

**Comment by jesmrec** [comment]
All done, `v4.1.0_oem` out
