### ISSUE TITLE
[FEATURE REQUEST] Thumbnail improvements in grid view

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4145]
**Current behaviour / Context:**

When browsing through folder structure, a request per item is sent:

`/remote.php/dav/files/<username>/<filename>?x=336&y=336&c=&preview=1`

response returns the thumbnail preview if exists, otherwise returns `404`

Usually, servers return thumbnails for images (not every format) and txt files, but it could change.

**Problem:**

In grid view, images use to show the thumbnail, but the name. But, not every image format is handled by the server. So, we have some items without thumbnail nor name, weird for the user:

![Screenshot 2023-08-30 at 18 20 37](https://github.com/owncloud/android/assets/14894746/38c70130-127c-41f1-b87d-01236ee20d5d)

**Solution (please, suggest other if this one is not OK):**

In grid view, if image is not previewable (request returns `404`), show the file name as any other kind of file. 

Also, change the thumbnail for another more descriptive one (anything in Android material??)

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/feature_name
- [x] Development tasks
  - [x] Implement whatever
  - [x] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by Aitorbp** [comment]
Related to change the thumbnails, honestly I wouldn´t change the current imagen default, but I have found this one in Material Design that could be more descriptive:
 
![Captura de pantalla 2023-11-28 a las 16 20 41](https://github.com/owncloud/android/assets/34248951/e18968e2-8a92-46ac-9566-4fd67b516d9d)


What do you think? More ideas or images are welcome @jesmrec @michaelstingl @tbsbdr @JuancaG05

**Comment by michaelstingl** [comment]
> What do you think? More ideas or images are welcome @jesmrec @michaelstingl @tbsbdr @JuancaG05

No change please. Nothing is broken, and I'd like to keep it consistent with the other platforms.
