### ISSUE TITLE
[FEATURE REQUEST] Improvements in "Manage accounts" view

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4148]
EPIC:
- https://github.com/owncloud/android/issues/4314

This is the current look of the `Manage accounts`:

![Screenshot 2023-08-31 at 09 17 03](https://github.com/owncloud/android/assets/14894746/d0401aab-22a0-46bf-82d9-db5ab6487cf3)

- Text field containing the username@url overflows the space and overlaps other icons on the right (check https://github.com/owncloud/enterprise/issues/5986#issuecomment-1693193046). 

- Round arrow icon will be removed -> https://github.com/owncloud/android/issues/4301

- Key icon could be removed (after research on https://github.com/owncloud/android/issues/4227). In case credentials are lost, Snackbar with `Sign In` option is in the file list. May need to check if removing the key icon could carry other side-effects

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/improvements_in_manage_accounts_view
- [x] Development tasks
  - [x] Avoid overlapping between the username and the icons
  - [x] Remove key icon
  - [x] Make lost-credentials Snackbar equal for every auth (with the `Sign in` option in basic auth too)
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/improvements_manage_accounts into master

**Comment by michaelstingl** [comment]
> But, if the account is basic auth and password changes in server, there is no way to get `Sign-in` snackbar because there are no available sessions (basic auth works with an authenticated header). Key icon is required to re-enter a new one.
> 
> So, i'd keep it for basic auth accounts and remove for token accounts (if feasible).
> 
> CC @michaelstingl

When passwords change on the server, clients receive `401`'s too. This should trigger re-login.

**Comment by jesmrec** [comment]
there is no `401` because server creates a new session (new cookie) that supports it without losing auth.  Making this work with basic auth will trigger probably deeper and tricky changes (needs research to accurate). This is the issue:

<img width="1107" alt="Screenshot 2023-09-04 at 13 00 47" src="https://github.com/owncloud/android/assets/14894746/4c244829-8921-4af6-8729-38a9f5205dd7">

**Comment by jesmrec** [comment]
Well, kept testing it and after some time, `401` is returned, but the snackbar is different:

![Screenshot 2023-09-04 at 13 09 37](https://github.com/owncloud/android/assets/14894746/57dc8856-6af7-4cc7-adcb-dc1c17c11b8f)

no way to regain auth, only to select another account.

**Comment by jesmrec** [comment]
iOS approach in account management:

| List of accounts | Options of every account | No access | Regain access |
|:-:|:-:|:-:|:-:|
|![screenshot-1695120524711](https://github.com/owncloud/android/assets/14894746/d75e4228-e8a9-4ed7-93f3-c9dc1fa2d8c1)|![screenshot-1695120678576](https://github.com/owncloud/android/assets/14894746/22c5f456-525d-458b-a780-d1d4636d1aca)|![screenshot-1695121067183](https://github.com/owncloud/android/assets/14894746/0ec11b56-12fe-4f5d-85d9-3100691ce3ba)|![screenshot-1695121079115](https://github.com/owncloud/android/assets/14894746/5564e2d2-b6a4-49da-bf19-6297eef25e54)|

Some inputs to move Android approach to the iOS one:

- Android app will remove sync option and make it automatic somehow (new issue)
- [`Change account`](https://github.com/owncloud/android/issues/4148#issuecomment-1705080267) in basic auth may need redefinition to be similar to browser auth. Then, it could be removed from account manager
- `Manage` in iOS removes all downloaded files from the account. New feature in Android with two options: manual and auto. Check how to integrate in the accounts manager view
- Android app lacks of a "log out" option.  https://github.com/owncloud/android/issues/3872. Out of scope of this issue, imho

more ideas?
