### ISSUE TITLE
[FEATURE REQUEST]  Streamlined Log File Upload Functionality

### ISSUE THREAD

**Issue by dpapac** [owncloud/android#4155]
**Is your feature request related to a problem? Please describe.**

When confronted with elevated security demands or a potential shortfall in technical proficiency, the act of log file uploading within the application may not prove as straightforward for the user.

**Describe the solution you'd like**

Develop a more intuitive and user-friendly interface that simplifies the log file upload process. Incorporate a clear visual cue to guide users through the procedure.

or...

Implement an automated log file collection feature that reduces user involvement to a minimum. The application could periodically collect and securely upload log files in the background without requiring any user action.

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/streamlined_log_file_upload_functionality
- [x] Development tasks
  - [x] Implement whatever
  - [x] ...
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
- Check why oC is not part of Share Sheet
- Check regards abour downloading to download folder

**Comment by michaelstingl** [comment]
> * Check why oC is not part of Share Sheet. If it appears, problems are fixed since there will be always to share with

Sounds more like
- https://github.com/owncloud/android/issues/4156

**Comment by jesmrec** [comment]
This issue will be used to fetch the log file, or saving to the device (`Downloads` folder, f. ex.)

Adding a download arrow in the `Logging` section of `Settings` (To ellaborate)
