### ISSUE TITLE
[RELEASE] 4.1.1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4165]
### TASKS:

 - ~~[DOC] Ping in #documentation-internal about the new release~~
 - [x] [GIT] Create branch `release/4.1.1` in owncloud/android from master
 - ~~[GIT] Rebase `release/4.1.1` against `stable` in owncloud/android~~
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DEV] Update [SBOM](https://cloud.owncloud.com/f/6072870)
 - [x] [DIS] Create a folder for the new version like `M.m.p_YYYY-MM-DD` inside the `changelog` folder
 - [x] [DIS] Move all changelog files from the unreleased folder to the new version folder
 - ~~[DIS] Update screenshots, if needed, in README.md~~
 - [x] [DEV] Add ReleaseNotes replacing `emptyList` with `listOf` and adding inside `ReleaseNote()` with String resources
 -  ~~[DIS] Prepare post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))~~
 - [x] [DIS] Generate final bundle from last commit in owncloud/android
 - [x] [QA] Design Test plan
 - [x] [DEV] Code Review
 - [x] [QA] Regression Test execution
 - [x] [QA] QA Approval
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - ~~[DOC] Ping in #documentation-internal that we are close to sign the new tags~~
 - [x] [GIT] Create and sign tag `v4.1.1` in HEAD commit of release branch, in owncloud/android
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - ~~[DIS] Update screenshots and store listing, if needed, in Play Store~~
 - [x] [GIT] Publish a new release in [owncloud/android](https://github.com/owncloud/android/releases)
 - [x] [DIS] Release published in Play Store
 - ~~[DIS] Publish post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))~~
 - [x] [COM] Inform `#updates` and `#marketing` in internal chat that release is out
 - [x] [GIT] Merge `release/4.1.1` branch into `stable`, in owncloud/android
 - [ ] [GIT] Merge `release/4.1.1` branch into `master`, in owncloud/android
 - ~~[DOC] Update documentation with new stuff by creating [issue](https://github.com/owncloud/docs-client-android/issues)~~

### QA

Regression test:

Bugs & improvements:

- [ ] (1) ...

**Comment by jesmrec** [comment]
## QA checks

Just bugfixing release, so basic checks

- [X] Release notes
- [X] Authentication: basic, OAuth2, OIDC
- [X] Transfers: uploads, downloads 
- [X] Settings > Security
- [X] Document provider
- [x] Thumbnails in accounts which username contains  `@`
- [X] Upgrade from 4.1.0
