### ISSUE TITLE
[FEATURE REQUEST] New field "last usage"

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4173]
Context: https://github.com/owncloud/android/issues/4002#issuecomment-1742856574

Adding and maintaining a new field in DB to control the last access' date. So, we can know how long was a file not used. 

- For every single file, folders not needed
- Updated when
  - File is opened/downloaded/previewed
  - File is renamed/moved
  - Cleaned up when local copy is removed (set lastUsage to null)
- Migration: empty for non-downloaded, current date for downloaded

It will be used for automatic removal.

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/new_field_last_usage
- [x] Development tasks
- [ ] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/new_field_last_usage into master
