### ISSUE TITLE
[FEATURE REQUEST] Manual removal of local storage

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4174]
EPIC:
- https://github.com/owncloud/android/issues/4314

This one may be done after https://github.com/owncloud/android/issues/4148

Context: https://github.com/owncloud/android/issues/4002#issuecomment-1742856574

New option in "Manage Accounts" to clean the account up. Will be removed:

- All downloaded files that are not av. offline
- ~`/tmp` folder~ -> not finally, since in the automatic removal we realised we cannot remove the temporal files
- failed uploads list

how to show to option in the UI? 

- Broom icon (available in material?) + warning about the behaviour like `All downloaded and temporal files and failed uploaded will be cleaned up`
- Gear to open a new view in which other options could be added (iOS style):

<img width="337" alt="Screenshot 2023-10-02 at 13 56 18" src="https://github.com/owncloud/android/assets/14894746/02c62e40-225d-4a34-bbcf-c32401db50e9">

- Other ideas ¿? @Aitorbp @manuelplazaspalacio @JuancaG05 

More ACs:

- During the process, an spinner or similar should be displayed to let users know that the process is running.
- When the downloaded files are removed, [the last usage date](https://github.com/owncloud/android/issues/4173) will be cleaned up 
- Lack of connection to internet or to the server will not affect

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/manual_removal_local_storage
- [x] Development tasks
  - [x] Create DAO with SELECT * files
  - [x] Create datasource and repository
  - [x] Create UseCase: deleteTemporal function, selectAllFiles repository and RemoveFile usecase.
  - [x] Add function in ViewModel: implement loading and usecase
  - [x] Create UI
  - [x] Add unit test if it is necessary
  - [x] Add release notes
  - [x] Add calens
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/manual_removal_local_storage into master
