### ISSUE TITLE
[FEATURE REQUEST] Automatic removal of downloaded files and local storage clean up

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4175]
EPIC:
- https://github.com/owncloud/android/issues/4314

Context: https://github.com/owncloud/android/issues/4002#issuecomment-1742856574

New option in `Settings` to remove automatically all the downloaded and temporal stuff from the local storage. Where to place? i'd go for the `Advanced` section. Option called `Delete local copies`, that will display the proper options.

Proposal:

- never
- 1 hour
- 12 hours
- 1 day
- 30 days

The way to display could be an slider like in iOS, but other options are also valid, f. ex. something similar to the `Security > Lock application` option.

A worker will run with the given frequency and will delete those files which `last_usage` date is older than the given time. This is only an approach (any ideas to improve?). Removing tmp and failed uploads as well.

- Check frequency of the worker (¿¿1 hour??)
- Check if feasible to check if file is being previewed (to avoid being deleted while previewing)

iOS style (right screenshot): https://github.com/owncloud/android/issues/4002#issuecomment-1495832098

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/automatic_removal_downloaded_files_local_storage_clean_up
- [x] Development tasks
  - [x] Retrieve files that need to be removed (from ALL the accounts)
  - [x] Create UseCase to retrieve files
  - [x] Implement logic to clean temporal folder
  - [x] Create worker to remove the previous retrieved files and check it works
  - [x] Create new preference "delete unused local copies"
  - [x] Manage changes of this preference (kill worker if necessary, create a new one, etc.)
  - [x] Create tests
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

**Comment by JuancaG05** [comment]
`/tmp` directory contains on the one hand temporal files related to uploads (which we shouldn't remove in case they're failed uploads, more info: https://github.com/owncloud/android/pull/4320#issuecomment-1978759686), and temporal files related to downloads. For this issue we'll just deal with downloaded files, not the `/tmp` directory, we'll research more about this in another issue
