### ISSUE TITLE
[FEATURE REQUEST]  Improve biometrical authentication security

### ISSUE THREAD

**Issue by manuelplazaspalacio** [owncloud/android#4180]
**Improve the biometrical authentication to solve posible security problems.**
Improve the mange of the onAuthenticationSucceeded result to prevent posible security leaks.
More info here: https://sec-consult.com/blog/detail/bypassing-android-biometric-authentication/

**Manage the CryptoObject**
Manage the CryptoObject obtained inside  the result of the onAuthenticationSucceeded. You can find more info here:
https://medium.com/androiddevelopers/using-biometricprompt-with-cryptoobject-how-and-why-aace500ccdb7
https://developer.android.com/training/sign-in/biometric-auth#crypto

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/improve_biometrical_security
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/improve_biometrical_security into master

### PR

- App
- Library (if needed)

**Comment by michaelstingl** [comment]
Worst case, maybe 4.2.1… 🤞
