### ISSUE TITLE
[FEATURE REQUEST]  Manage deep links and open the app correctly

### ISSUE THREAD

**Issue by manuelplazaspalacio** [owncloud/android#4181]
Things to do:
- Adapt AndroidManifest
- Handle intent
- Manage posible login errors
- Check Deep Link correct format.

Expected result: the app is open in login if no user logged and if there is any user logged go to FileDisplayActivity an show success message if correct format.
Spike related: https://github.com/owncloud/android/issues/4068

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/feature_name
- [x] Development tasks
  - [x] Open App
  - [x] Manage logged or not logged  user
  - [x] Check deep link
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Feature%20template/Other/Open%20DeepLinks.md

Bugs & improvements:

**Comment by jesmrec** [comment]
First draft of test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Feature%20template/Other/Open%20DeepLinks.md

let me know if you miss something there.
