### ISSUE TITLE
[FEATURE REQUEST]  Select correct user and navigate to the correct file when opening via deep link

### ISSUE THREAD

**Issue by manuelplazaspalacio** [owncloud/android#4194]
**Describe the solution you'd like**
Things to do:
- Select the user owner of the file between the logged users if the user is not logged show the login view.
- When the user is selected, navigate to the file with id contained in the deep link.
- Show error if no user for the file.
- Show error if file couldn't be finde in the user account.

**Additional context**
Spike related: https://github.com/owncloud/android/issues/4068

## oC10 link / fileid resolve

```
% curl -sI -u "test:test" "https://demo.owncloud.com/f/9" | grep "location"
location: /apps/files/?dir=/Photos
webdav-location: /remote.php/dav/files/test/Photos
```

- https://github.com/owncloud/core/pull/30383

## oCIS link / fileid resolve

`/remote.php/dav/meta/` could be used to get more information.

```
% curl -s 'https://ocis.ocis-traefik.latest.owncloud.works/remote.php/dav/meta/427a5e74-6921-4768-8d53-cd5e8b30f5b0%24534bb038-6f9d-4093-946f-133be61fa4e7!a130bbe3-5681-4193-9ab0-2a714934722a' \
-X 'PROPFIND' \
-H 'Authorization: Bearer REDACTED' \
-H 'Depth: 0' \
--data-binary $'<?xml version="1.0"?>\n<d:propfind  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">\n  <d:prop>\n    <oc:meta-path-for-user />\n  </d:prop>\n</d:propfind>' | xmllint --format -

<?xml version="1.0"?>
<d:multistatus xmlns:s="http://sabredav.org/ns" xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/remote.php/dav/meta/427a5e74-6921-4768-8d53-cd5e8b30f5b0$534bb038-6f9d-4093-946f-133be61fa4e7%21a130bbe3-5681-4193-9ab0-2a714934722a/</d:href>
    <d:propstat>
      <d:prop>
        <oc:meta-path-for-user>/Hacker-Songs</oc:meta-path-for-user>
        <oc:id>427a5e74-6921-4768-8d53-cd5e8b30f5b0$534bb038-6f9d-4093-946f-133be61fa4e7!a130bbe3-5681-4193-9ab0-2a714934722a</oc:id>
        <oc:fileid>427a5e74-6921-4768-8d53-cd5e8b30f5b0$534bb038-6f9d-4093-946f-133be61fa4e7!a130bbe3-5681-4193-9ab0-2a714934722a</oc:fileid>
        <oc:spaceid>427a5e74-6921-4768-8d53-cd5e8b30f5b0</oc:spaceid>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

- https://doc.owncloud.com/server/developer_manual/webdav_api/meta.html

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/select_user_navigate_file_deep_link
- [x] Development tasks
  - [x] Create the call to check the location of the file
  - [x] Manage the possible errors
  - [x] Navigate to the file
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/select_user_navigate_file_deep_link into master

**Comment by jesmrec** [comment]
This will be the test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Executions/Release_4.2/DeepLinks.md

**Comment by JuancaG05** [comment]
Finally, we'll ask the `/remote.php/dav/meta/` endpoint to resolve the fileId in oC10 as well:

## oC10 link / fileid resolve

```
% curl -s 'https://demo.owncloud.com/remote.php/dav/meta/56' \
-u 'demo:demo' \
-X 'PROPFIND' \
-H 'Depth: 0' \
--data-binary $'<?xml version="1.0"?>\n<d:propfind  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">\n<d:prop>\n<oc:meta-path-for-user />\n</d:prop>\n</d:propfind>' | xmllint --format -

<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/remote.php/dav/meta/56/</d:href>
    <d:propstat>
      <d:prop>
        <oc:meta-path-for-user>/Photos</oc:meta-path-for-user>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```
