### ISSUE TITLE
Remove all database

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4203]
Time ago, Android app used to store data in SQLite DB. Then, new architecture came and everything was moved to Room.

But, SQLite exists still in the app

To do:

- [ ] Check if something in SQLite DB is still used/useful
- [ ] In case it is, migrate it to Room
- [ ] Remove SQLite DB

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

**Comment by shalenMathew** [comment]
hey there is this issue still active ?

**Comment by jesmrec** [comment]
@shalenMathew yes, it's alive. If you are going to work on it, please be very careful.

In any case, it will target (minimum) 4.3, because the change carries some regards.

**Comment by Prakhar1701** [comment]
Hey I want to work on this issue, may I get started?

**Comment by JuancaG05** [comment]
Hey @Prakhar1701! Could be a good one, but this got was opened more than 1 year ago and the situation got more complex. Go for it if you want, but take into account that the PR will be reviewed thoroughly and has the risk to be rejected if there is anything left we consider it's important 👍

**Comment by Prakhar1701** [comment]
Okay
