### ISSUE TITLE
[FEATURE REQUEST] Improvements in "New content" refresh button

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4219]
Recently, we added a new clickable floating action button that we use to trigger a manual refresh of the folder:

![Screenshot_20231117_120331](https://github.com/owncloud/android/assets/57049315/5bfda8f9-b852-4e02-b1d8-387b7ae88bfc)

There was some feedback and we can improve it in several ways:

- [ ] Wording: change `New content` to `Refresh`, so that the user knows exactly this button triggers that action
- [ ] Not showing everything in uppercase (this is a Material default, but could investigate how to change it)

More ideas welcome: color, icon...

CC/ @tbsbdr 

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/improvements_refresh_fab
- [x] Development tasks
  - [x] Implement whatever
  - [x] ...
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [x] Merge branch feature/improvements_refresh_fab into master

**Comment by jesmrec** [comment]
@rishabh241 before developing, a proposal will help. This issue was created after getting some feedback after first iteration. Just to hit the correct thing, we could discuss about how will be the final look

**Comment by JuancaG05** [comment]
Hi @rishabh241! Cool, go for it! 🚀 
But as @jesmrec says, let's first post a proposal so that everyone can tell their thoughts, and also maybe some feedback from @tbsbdr which is an expert in UI/UX 😃

**Comment by rishabh241** [comment]
Instead of writing refresh or new content, we can just put a symbol for refresh which is more effective, and for color we should choose a color from the color palette of owncloud app

**Comment by tbsbdr** [comment]
thanks @rishabh241 for your idea!
yes, the color should be selected from the color palette 👍
> Wording: change New content to Refresh, so that the user knows exactly this button triggers that action
I'd stick to this approach (just rename to "refresh") since its more polite to add some text to labels - good read: https://www.nngroup.com/articles/icon-usability/

**Comment by JuancaG05** [comment]
Thanks a lot @tbsbdr! I also prefer some label in the button, so that the click area is bigger as well.

So now we can go for it, these are the changes required @rishabh241:

- [ ] Rename "New content" to "Refresh"
- [ ] Not showing everything in uppercase
- [X] The color being used is already the primary color from the palette

Let us know when you have your PR ready or if you have any question 💪. If you didn't, you can read [CONTRIBUTING.md](https://github.com/owncloud/android/blob/master/CONTRIBUTING.md) for a start 🤠.

**Comment by rishabh241** [comment]
can we do some work on its color?

**Comment by jesmrec** [comment]
> can we do some work on its color?

no please, because it's branded to the main color of the app. This field in brandable and we should maintain it.
