### ISSUE TITLE
[FEATURE REQUEST] Render the app in black in "Recents" view when security is enabled

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4220]
Currently, when we have some security lock enabled (passcode/pattern/biometric) and we lock the device or it goes to sleep, the app is closed to avoid revealing sensitive information in the "Recents" view. We could change that old behaviour to a modern one, not closing the app but rendering it in black in this view, just like some apps like the native Camera ones do:

![Screenshot_20231117_102202](https://github.com/owncloud/enterprise/assets/57049315/28894c09-6127-4651-abe3-89dadd00cbfe)

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/render_black_in_recents
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/render_black_in_recents into master
