### ISSUE TITLE
[TECHNICAL] Upgrade min SDK to Android 7.0 (v24)

### ISSUE THREAD

**Issue by Aitorbp** [owncloud/android#4230]
At the moment our min SDK version is Android 6 (v23) and I think that it could be time to upgrade to Android 7.0 (v24). This is needed to upgrade Kotlin version as well: 
- https://github.com/owncloud/android/pull/4216

Users will be warned in 4.2 and it will be effective in the next feature release.

### TASKS

- [x] Research (if needed)
- [x] Create branch technical/upgrade_min_sdk_to_android_7
- [x] Development tasks
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

**Comment by michaelstingl** [comment]
Post / link to the Android version marketshare chart?

**Comment by jesmrec** [comment]
official info shown by android studio that seems to be broken ftm. Will update as soon as is again available.

**Comment by JuancaG05** [comment]
Official information shown by Android Studio continues broken, so we can take as a reference the percentages in Play Store referred to our app:

![user_percentages](https://github.com/owncloud/android/assets/57049315/ab318be4-0510-47e6-a9d6-9d95ced17a4e)

As you can see here, the percentage of users using Android 6 (SDK 23) is <1%. We could even upgrade it to SDK 25 (Android 7.1), which is still <1%.

**Comment by michaelstingl** [comment]
Checked here:
https://www.appbrain.com/stats/top-android-sdk-versions

7.0+ works for me 👍

**Comment by JuancaG05** [comment]
Android Studio was updated to Android Studio Hedgehog version and now the window with this info seems to work:

<img width="543" alt="" src="https://github.com/owncloud/android/assets/57049315/79cc3e10-9dae-4071-b0f2-d63d6494f13f">

Numbers are more or less similar to the appbrain webpage, so we could keep the same decision 👍
