### ISSUE TITLE
[FEATURE REQUEST] Block UI when deleting files

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4231]
**Is your feature request related to a problem? Please describe.**
Currently, when performing operations like copy or move, the UI blocks until the operation is finished by showing a dialog on screen. This doesn't happen with the delete operation.

**Describe the solution you'd like**
Block the UI with the delete operation as well.

**Describe alternatives you've considered**
Showing the same dialog as in the copy and delete operations to block the screen.

**Additional context**
The dialog is the following:

![block_ui](https://github.com/owncloud/android/assets/57049315/2e361333-b51c-4455-bda2-ce96dbdbe36b)

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/block_ui_delete
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/block_ui_delete into master

**Comment by parneet-guraya** [comment]
I want to work on it.
