### ISSUE TITLE
[TECHNICAL] Unit tests for repository classes - Part 2

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4233]
Epic:
- https://github.com/owncloud/android/issues/4063

In this issue we'll address the unit tests for the class:
- OCFileRepository

Remember we want to create unit tests that **check that every method returns the expected result** and **verify that every method calls the corresponding methods of other classes**.

### TASKS

- [x] Research (if needed)
- [x] Create branch technical/testing_repositories_2
- [x] Development tasks
  - [x] Create unit tests for `OCFileRepository`
- [ ] Code review and apply changes requested
- [ ] Merge branch technical/testing_repositories_2 into master
