### ISSUE TITLE
[TECHNICAL] Unit tests for repository classes - Part 3

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4234]
Epic:
- https://github.com/owncloud/android/issues/4063

In this issue we'll address the unit tests for the classes:
- OCFolderBackupRepository
- OCOAuthRepository
- OCServerInfoRepository
- OCShareeRepository
- OCShareRepository

Remember we want to create unit tests that **check that every method returns the expected result** and **verify that every method calls the corresponding methods of other classes**.

### TASKS

- [x] Research (if needed)
- [x] Create branch technical/testing_repositories_classes_3
- [x] Development tasks
  - [x] Create unit tests for `OCFolderBackupRepository`
  - [x] Create unit tests for `OCOAuthRepository`
  - [x] Create unit tests for `OCServerInfoRepository`
  - [x] Create unit tests for `OCShareeRepository`
  - [x] Create unit tests for `OCShareRepository`
- [ ] Code review and apply changes requested
- [ ] Merge branch technical/testing_repositories_classes_3 into master
