### ISSUE TITLE
[TECHNICAL] Unit tests for repository classes - Part 4

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4235]
Epic:
- https://github.com/owncloud/android/issues/4063

In this issue we'll address the unit tests for the classes:
- OCSpacesRepository
- OCTransferRepository
- OCUserRepository
- OCWebFingerRepository

Remember we want to create unit tests that **check that every method returns the expected result** and **verify that every method calls the corresponding methods of other classes**.

### TASKS

- [x] Research (if needed)
- [x] Create branch technical/testing_repositories_4
- [x] Development tasks
  - [x] Create unit tests for `OCSpacesRepository`
  - [x] Create unit tests for `OCTransferRepository`
  - [x] Create unit tests for `OCUserRepository`
  - [x] Create unit tests for `OCWebFingerRepository`
- [x] Code review and apply changes requested
- [ ] Merge branch technical/testing_repositories_4 into master
