### ISSUE TITLE
[FEATURE REQUEST] Don't redact auth type HTTP request logging

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#4249]
**Describe the solution you'd like**

I'd like to log the auth method, and redact only the actual credentials.

**Additional context**

Desktop example:
```
        "header":
        {
            "Authorization": "Bearer [redacted]",
```

iOS example:
```
Authorization: Bearer [redacted:1]
```

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/reveal_redacted_info_logs
- [x] Development tasks
  - [x] Process the string to show just the authentication method
  - [x] Create a brandable parameter to show or hide redacted info
  - [x] Create a MDM parameter for the same
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/reveal_redacted_info_logs into master

**Comment by jesmrec** [comment]
New requirement:

Add new option to reveal `[redacted]` info with debugging purposes. Options:

- New branding/MDM option
- Reveal always in `debug` mode (not sure if this is the best option)

more options, welcome.
