### ISSUE TITLE
[RELEASE] 4.2.0-beta.2

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4253]
### TASKS:

 - ~~[DOC] Ping in #documentation-internal about the new release~~
 - [ ] [GIT] Create branch `release/4.2.0-beta.2` in owncloud/android from master
 - ~~[GIT] Rebase `release/4.2.0-beta.2` against `stable` in owncloud/android using the [`--rebase-merge` option](https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt---rebase-mergesrebase-cousinsno-rebase-cousins)~~
 - [ ] [DEV] Update version number and name in build.gradle in owncloudApp module
 - ~~[DEV] Update [SBOM](https://cloud.owncloud.com/f/6072870)~~
 - [ ] [DIS] Create a folder for the new version like `M.m.p_YYYY-MM-DD` inside the `changelog` folder
 - [ ] [DIS] Move all changelog files from the `unreleased` folder to the new version folder
 - ~~[DIS] Update screenshots, if needed, in README.md~~
 - [ ] [DEV] Add release notes replacing `emptyList` with `listOf` and adding inside `ReleaseNote()` with String resources, in `ReleaseNotesViewModel.kt`
 - [ ] [DIS] Prepare post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))
 - [ ] [DIS] Generate final bundle from last commit in owncloud/android
 - [ ] [QA] Design Test plan
 - [ ] [DEV] Code Review
 - [ ] [QA] Regression Test execution
 - [ ] [QA] QA Approval
 - [ ] [DIS] Upload release APK and bundle to internal owncloud instance
 - ~~[DOC] Ping in #documentation-internal that we are close to sign the new tags~~
 - [ ] [GIT] Create and sign tag `v4.2.0-beta.2` in HEAD commit of release branch, in owncloud/android
 - [ ] [DIS] Upload & publish release bundle and changelog in Play Store
 - ~~[DIS] Update screenshots and store listing, if needed, in Play Store~~
 - [ ] [GIT] Publish a new [release](https://github.com/owncloud/android/releases) in owncloud/android
 - [ ] [DIS] Release published in Play Store
 - [ ] [DIS] Publish post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))
 - [ ] [COM] Inform `#updates` ~~and `#marketing`~~ in internal chat that release is out
 - ~~[GIT] Merge `release/4.2.0-beta.2` branch into `stable`, in owncloud/android~~
 - [ ] [GIT] Merge `release/4.2.0-beta.2` branch into `master`, in owncloud/android
 - ~~[DOC] Update documentation with new stuff by creating [issue](https://github.com/owncloud/docs-client-android/issues)~~

### QA

Regression test:

Bugs & improvements:

- [ ] (1) ...
