### ISSUE TITLE
[RELEASE] 4.2.1_oem

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4292]
### TASKS:

- [x] [GIT] Create a new branch `release/4.2.1_oem` (optional)
- [x] [DIS] Update release notes in app with the proper content for oem release
- [x] [GIT] Create and sign tag `v4.2.1_oem` in HEAD commit of `release/4.2.1_oem` branch
- [x] [DEV] Approve and merge changes in ownBrander
  - [x] Links with a proper scheme
  - [x] Number of uploads to refresh
  - [x] Redact auth information in logs
  - [x] Add `login_hint` and `user` to the OIDC authentication request
  - [x] Update version number in ownBrander
- [x] [OPS] Block oB button
- [x] [OPS] Deploy oB
- [x] [DEV] Merge changes in scripts -> this is the first version without submodules
- [x] [QA] Generate final APKs files from signed commit in builder machine and perform some basic checks:
    - [x] Installation of apk/aab generated by builder machine
    - [x] Test links with a proper scheme
    - [x] Test number of uploads to refresh
    - [x] Test redact auth information in logs
    - [x] Test `login_hint` and `user` to the OIDC authentication request
    - [x] App update from previous version (generated in advance)
- [x] [QA] Notify result in #ownbrander
- [x] [OPS] Enable button

**Comment by jesmrec** [comment]
Everything done!
