### ISSUE TITLE
[FEATURE REQUEST] Make dialog more Android-alike

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4303]
**Is your feature request related to a problem? Please describe.**
I think the dialog shown when solving a name conflict in the copy or move operation is not very Android-alike, and is out of the style line of other dialogs in the app:

![dialog_not_cool](https://github.com/owncloud/android/assets/57049315/9311b0b7-bf2f-4bd9-a4dd-2ee709e362a6)

**Describe the solution you'd like**
I'd like to see new proposals for the dialog so that it looks more similar to others in the app.

**Describe alternatives you've considered**
We can make it more similar to other dialogs shown in the app such as:

![dialog_cool](https://github.com/owncloud/android/assets/57049315/f96103d1-d835-4d9d-9b14-dc8c70714478)

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/improve_name_conflicts_dialog
- [x] Development tasks
  - [x] Remove icon from title and make title bigger and black bold
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/improve_name_conflicts_dialog into master
