### ISSUE TITLE
[FEATURE REQUEST] Password generator for public links

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/android#4308]
**Is your feature request related to a problem? Please describe.**
Along with the password policy, the iOS client implements a password generator.

**Describe the solution you'd like**
The generator creates passwords that follow the policy and in general should have a higher entropy than a user generated password.
The implementation should be aligned with the iOS implementation.

**Additional context**
iOS code: https://github.com/owncloud/ios-sdk/blob/develop/ownCloudSDK/Password%20Policy/OCPasswordPolicy%2BGenerator.m#L24

Possible password policies to fulfill are the following (values are server-customizable):
 ```
 "password_policy": {
                    "max_characters": 72,
                    "min_characters": 8,
                    "min_digits": 1,
                    "min_lowercase_characters": 1,
                    "min_special_characters": 1,
                    "min_uppercase_characters": 1
}
```

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/password_generator_public_links
- [x] Development tasks
  - [x] Create password generator algorithm
  - [x] Add a button to generate password (only for oCIS)
  - [x] Add a button to copy password (only for oCIS)
  - [x] Implement unit tests (if needed)
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/password_generator_public_links into master

**Comment by jesmrec** [comment]
Needs research to check for available solutions in the Android world

**Comment by JuancaG05** [comment]
> Needs research to check for available solutions in the Android world

None of the available solutions was suitable (in addition to the fact that none of them is native).
Developing our own solution then 👨🏼‍💻
