### ISSUE TITLE
[FEATURE REQUEST] New UI for "Manage accounts" view

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4312]
EPIC:
- https://github.com/owncloud/android/issues/4314

Currently, the `Manage accounts` view looks like this:

<p align="center">
<img src="https://github.com/owncloud/android/assets/57049315/54ca1879-d8b6-47df-8b7d-0269bdfd08b2" width="300"/> 
</p>

This is a little bit outdated in terms of design, and shows a pretty empty screen unless you have several accounts. The aim here is to move this view to a dialog showing the same info, just like modern apps that follow the Material Design standards are doing lately:

| Play Store | Gmail | Maps |
| --- | --- | --- |
| ![play_store](https://github.com/owncloud/android/assets/57049315/699ba225-1a82-41e1-b749-61a0b4a2829c) | ![gmail](https://github.com/owncloud/android/assets/57049315/29ef9f51-9ddf-4001-babd-eed035bacc39) | ![maps](https://github.com/owncloud/android/assets/57049315/1713cfb2-72a8-4bdf-a136-26a50f961f34) |

This implies changing the click listener of the avatar in the top bar, that will open this new dialog instead of going to the current screen, which will be deleted.

In addition, we'll remove the second menu of the drawer menu, which shows redundant options for managing accounts (adding an account, a link to the manage accounts screen and the other accounts), so that everything related to managing accounts is centralized in just 1 place. The click listener of the avatar in the drawer menu could be changed as well to open the new dialog.

Past proposals:
- https://github.com/owncloud/android/issues/2849

More proposals welcome!

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/new_ui_manage_accounts
- [x] Development tasks
  - [x] Design mockups
  - [x] Switch between accounts
  - [x] Add a new account functionality
  - [x] Clean account local storage functionality
  - [x] `suscribeToViewModels` function
  - [x] Hide the main dialog when you click on the remove account button
  - [x] Refresh the file list when a new account is added
  - [x] Remove second menu of the drawer menu, mini avatars and all the related stuff
  - [x] Remove `AccountsManagementActivity` and its related tests
  - [x] Implement unit tests (if needed)
  - [x] Add feature to Release Notes (if required)
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/new_ui_manage_accounts into master

**Comment by jesmrec** [comment]
In case of multiaccount, the "clean" and "delete" options are not clearly attached to the account. The compacted version (on the right) likes me the most. I know that they are mockups to make ourselves an idea, but i miss some beautifiers there.

**Comment by JuancaG05** [comment]
For a first iteration, I'd go for the second option. That is, keeping the current design but in a dialog instead of a new screen. Technically, it will be easier as well 😄

**Comment by joragua** [comment]
After first iteration, I've redesigned the second option and that is the result:


<p align="center">
<img src="https://github.com/owncloud/android/assets/160487817/687f2fa5-b986-451d-b100-0ce21bc67755" width="300"/> 
</p>

**Comment by tbsbdr** [comment]
Thumbs up 👍 lets go, looks very good!

Summay of what we just discussed in addition:
Improvement **for the future**:
- Problem: the brush icon is not very intuitiv, its not self-explaining.
- Possible Solution:
  - show text next to the icon
  - maybe within an collapsible or dedicated dialog/drawer or alike

**Comment by joragua** [comment]
### WORK TO DO:

- Hide the main dialog when you click on `remove account` button. If you confirm, you have to see files of the remaining account. Also, if you click on cancel option the main dialog would appear again.
- Refresh the file list when a new account is added
- `suscribeToViewModels` function
