### ISSUE TITLE
[EPIC] New "Manage accounts" view

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4314]
We want to make several changes and improvements in the current `Manage accounts` view, so they will be collected in this epic to track the progress. The related issues are:

- [x] https://github.com/owncloud/android/issues/4227: checking and understanding how cookies are handled in the app, so that it is not an impediment removing the key icon in the `Manage accounts` view for both accounts with `Basic` or `Bearer` authentication
- [x] https://github.com/owncloud/android/issues/4301: doing an discovery of the whole account automatically when we login, so that we can remove the sync icon in the `Manage accounts` view
- [x] https://github.com/owncloud/android/issues/4148: removing the sync icon and the key icon safely after the previous issues are completed, fix a glitch for long usernames and unify the behaviour of the app when the cookies/tokens are invalid in `Basic` and `Bearer` auth accounts
- [x] https://github.com/owncloud/android/issues/4312: great improvement in the UI of this view
- [x] https://github.com/owncloud/android/issues/4174: a new icon to clean manually the local storage of the account will be added to the `Manage accounts` view
- [x] https://github.com/owncloud/android/issues/4175: to complement the previous issue, an automatic cleaning will be provided as well from settings
- [x] https://github.com/owncloud/android/issues/4309: once both ways of cleaning the app are developed, researching about why the `Clear data` option from the device settings is not working, and if possible remove this option since we'll already have an option to remove local storage manually
- [x] https://github.com/owncloud/android/issues/4335: problem with the temporary folder, containing uploads that, at least, failed once.

**Comment by jesmrec** [comment]
Everything done!!
