### ISSUE TITLE
List of shares in oCIS not visible in SAF

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4322]
apps with SAF access show first the list of available spaces to browse on oC accounts. But, if shares are available, the shares space is not listed in the first view.

Shares jail should be (at least) browsed. Now, operations over shared items are banned in the app, so we can follow that behaviour.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
  - [ ] Implement unit tests (if needed)
  - [ ] Add feature to Release Notes (if required)
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

**Comment by jesmrec** [comment]
Done in https://github.com/owncloud/android/issues/4515
