### ISSUE TITLE
[FEATURE REQUEST] Improvements in remove confirmation dialog

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4342]
**Is your feature request related to a problem? Please describe.**
The remove confirmation dialog is currently pretty simple, and could be improved by showing some valuable information (being aware of not overloading the dialog, that's not the aim).

**Describe the solution you'd like**
I think it would be nice to apply 2 different improvements:

1. When removing a file with thumbnail, it would be cool to show the thumbnail in the dialog to know exactly which file we are going to delete (also to avoid misclicks). Currently, we just show the title, which can be non-descriptive sometimes:

<img width="300" src="https://github.com/owncloud/android/assets/57049315/f76cc773-7fa2-4d30-9b54-4fcf47f89472">

2. When removing several files, it would be nice to show the number of elements selected. Currently, we show a common message for every case. It's true that there's a conflictive case, in which we select a folder: should we consider it as just 1 element or count recursively all the elements contained there? Right now it looks like this:

<img width="300" src="https://github.com/owncloud/android/assets/57049315/b9444c34-0e41-48bb-b28c-39e595bd7643">

**Describe alternatives you've considered**
Proposals are welcome, and more ideas or suggestions as well 🙂.

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/improvements_remove_dialog
- [x] Development tasks
  - [x] Add thumbnail in remove dialog, just for files with thumbnails
  - [x] Add number of elements in remove dialog when selecting several files to remove
  - [x] Implement unit tests (if needed)
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/improvements_remove_dialog into master

**Comment by jesmrec** [comment]
> When removing an image, it would be cool to show the thumbnail in the dialog to know exactly which image we are going to delete (also to avoid misclicks). Currently, we just show the title, which can be non-descriptive sometimes:

Should we show everything that contains a thumbnail? for example a txt file, not only an image. If we are ready for this, app will be ready to show any supported thumbnail in the future.

**Comment by JuancaG05** [comment]
> Should we show everything that contains a thumbnail? for example a txt file, not only an image. If we are ready for this, app will be ready to show any supported thumbnail in the future.

Sure! I didn't realise about them. I'll update the main comment, thanks 😄
