### ISSUE TITLE
[FEATURE REQUEST] Improve the `removed from original folder` option in Auto Uploads

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4357]
The option `removed from original folder` in auto uploads is potentially destructive

![Screenshot 2024-04-04 at 13 40 53](https://github.com/owncloud/android/assets/14894746/36a72a79-7da0-41b2-a871-b90846e4b6e6)

Removing the local file when worker moves the taken pictures to the scoped storage forces the uploads to work in order not to lose the pictures/videos. If upload fails for X reason and is not recoverable, the file is lost: it is neither in server, nor in local

Some solutions:

- Adding a warning when option is clicked: `The pictures/videos taken by the camera will not be available in your device anymore. This could be potentially dangerous in case of failure in the uploads because external reasons`. In that way, problem is not solved but user is warned about the existing perils.

- Removing the local file only when the upload is finished. Not sure how to control this, unless different kinds of uploads are distinguishable.

- Other ideas...

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/feature_name
- [x] Development tasks
  - [x] Create Work to remove local file
  - [x] Enqueued two works: `uploadFileFromContentUriWorker` and `removeLocalFileWorker`.
  - [x] Removed code relate to remove local file in UploadFileFromContentUriWorker
  - [x] Implement unit tests (if needed)
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

**Comment by JuancaG05** [comment]
Could be that auto-uploads are removed instantly because permissions are removed by Android over the files after a while... Needs to be checked
