### ISSUE TITLE
[RELEASE] 4.3.0

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4359]
### TASKS:

 - [x] [DOC] Ping in #android-dev-internal to warn that new release is incoming (@mmattel)
 - [x] [GIT] Create branch `release/4.3.0` in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DEV] Update [SBOM](https://cloud.owncloud.com/f/6072870)
 - [x] [DIS] Create a folder for the new version like `M.m.p_YYYY-MM-DD` inside the `changelog` folder
 - [x] [DIS] Move all changelog files from the `unreleased` folder to the new version folder
 - [x] [DEV] Check release notes in `ReleaseNotesViewModel.kt` to assure nothing important is missing there
 - [x] [DIS] Prepare post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))
 - [x] [DIS] Check for new screenshots in Play Store / GitHub repo and generate them
 - [x] [DIS] Generate final bundle from last commit in owncloud/android
 - [x] [QA] Design Test plan
 - [x] [DEV] Code Review
 - [x] [QA] Regression Test execution
 - [x] [QA] QA Approval
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - [x] [DOC] Ping in #android-dev-internal that we are close to sign the new tags
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [x] [DIS] Update screenshots and check they are OK in Play Store and in `README.md` (if needed)
 - [x] [GIT] Create and sign tag `v4.3.0` in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Move tag `latest` pointing the same commit as the release commit
 - [x] [GIT] Publish a new [release](https://github.com/owncloud/android/releases) in owncloud/android
 - [x] [DIS] Release published in Play Store
 - [x] [DIS] Publish post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))
 - [x] [COM] Ping in #android-dev-internal about the new release is out (@mmattel)
 - [ ] [GIT] Merge without rebasing `release/4.3.0` branch into `master`, in owncloud/android
 - [x] [DOC] Update documentation with new stuff by creating [issue](https://github.com/owncloud/docs-client-android/issues)
 - [ ] [DOC] Ping @TheOneRing to update release information in https://owncloud.com/mobile-apps/

### QA

Regression test: https://github.com/owncloud/QA/blob/master/Mobile/Android/Executions/Release_4.3/RegressionTest.md

Bugs & improvements:

- [x] (1) Shortcut icon in details view https://github.com/owncloud/android/issues/4359#issuecomment-2182633560 [FIXED]
- [x] (2) Release notes sorted https://github.com/owncloud/android/issues/4359#issuecomment-2189401417 [FIXED]
- [X] (3) Shortcut icon in oC10 account https://github.com/owncloud/android/issues/4359#issuecomment-2189444910 [FIXED]

**Comment by jesmrec** [comment]
### (1)

(created here till we have a PR)

1. Create a shortcut
2. Open `Details` view of the shortcut

Current: icon is incorrect
Expected: shortcuts icon there

**Comment by jesmrec** [comment]
### (2)

About the release notes. The list of items is sorted by the merging date, but that order might not be interesting for the user. I'd set the main features on the top and sorted by importante/relevance

For example (open to discussion):

- New Setting to remove automatically...
- Automatic discovery
- Manage Accounts new view + changes (i'd merge both in one one release note)
- New setting to removal...
- Shortcuts
- Password generator

(those are the main news)

- Lens icon in folder picker
- Improvements in remove dialog
- Accessibility
- Performance in av. offline
- Icons in open in web

(those are improvements with less impact)

and then, the bug fixes and others. 

This is just an example, the important is the idea about how to sort the entries there

**Comment by mmattel** [comment]
> About the release notes. ... I'd set the main features on the top and sorted by importante/relevance

That should also go into the release notes we have in docs-main in the android release notes section. Helping hands next week if I have infos you can reference 😄

**Comment by jesmrec** [comment]
### (3)

Creating a shortcut in oC10 account, the icon is not the proper one:

![Screenshot 2024-06-25 at 18 45 36](https://github.com/owncloud/android/assets/14894746/9ba9e0bf-7b2b-4d16-b028-17aea71e8c5f)

**Comment by jesmrec** [comment]
> That should also go into the release notes we have in docs-main in the [android release notes section](https://doc.owncloud.com/android_release_notes.html). Helping hands next week if I have infos you can reference 😄

We can post the list somewhere, let us know and will send the list (now only visible in the app itself). I guess that the [technical changelog ](https://github.com/owncloud/android/blob/release/4.3.0/CHANGELOG.md#changelog-for-owncloud-android-client-430-2024-07-01) does not fit that documentation, right @mmattel ?

**Comment by Aitorbp** [comment]
> ### (3)
> Creating a shortcut in oC10 account, the icon is not the proper one:
> 
> ![Screenshot 2024-06-25 at 18 45 36](https://private-user-images.githubusercontent.com/14894746/342824887-9ba9e0bf-7b2b-4d16-b028-17aea71e8c5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTIxNTIsIm5iZiI6MTcxOTM5MTg1MiwicGF0aCI6Ii8xNDg5NDc0Ni8zNDI4MjQ4ODctOWJhOWUwYmYtN2IyYi00ZDE2LWIwMjgtMTdhZWE3MWU4YzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA4NTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwN2Y1Mzg2NjliOTYzZDlkMzBjOTZmMTc5OTY1MDQ4MDYyOTA5M2Y4OGNlZWM5YmNkNGY3NGJiYjI1Y2M2OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tOqiB1LSdFwPDWZ0notdSR-MfSh_hTZhMuFpMJsMcHc)

Regarding this report, in OC10 we are not receiving the `mimetype` of the shortcuts correctly. We should receive a `text/uri-list type`,  as in OCIS, but instead we receive `application/octet-stream` , which is the value that is set by default. To choose the icon we always use the `mimetype`, except in the case of `transfers`, which do not have a `mimetype` and we have to trust the extension of the file. Only in this case if we receive the icon correctly.
As a conclusion, I would not change anything in the code, since it is the server's responsibility to bring us this data correctly. What do you think? @JuancaG05 @jesmrec

**Comment by jesmrec** [comment]
If the server returns an "incorrect" mimetype, we have to live with it. I wouldn't play with the extension amap. In fact, i'd re-check at some point the use of the extension in the transfers, in order to unify criteria and avoid that same file could show two different icons.

**Comment by Aitorbp** [comment]
> If the server returns an "incorrect" mimetype, we have to live with it. I wouldn't play with the extension amap. In fact, i'd re-check at some point the use of the extension in the transfers, in order to unify criteria and avoid that same file could show two different icons.

The problem is transfer object doesn't have mimetype, because of that we use the extension in this case. 
Reports 1 and 2 should be fixed. @jesmrec

**Comment by jesmrec** [comment]
(1) is fixed
(2) is not fixed. The order to show in the release notes comes from the order in the ViewModel, not from the order in the resources' files.
(3) is wont fix ftm

**Comment by Aitorbp** [comment]
> (1) is fixed (2) is not fixed. The order to show in the release notes comes from the order in the ViewModel, not from the order in the resources' files. (3) is wont fix ftm

@jesmrec I think now is fixed the report (2)

**Comment by jesmrec** [comment]
(2) fixed now
