### ISSUE TITLE
[FEATURE REQUEST] Show same remove dialog for every kind of file or folder

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4377]
This is an improvement from https://github.com/owncloud/android/issues/4342

After such improvement, those files with a thumbnail (images, txt files) show a different dialog including the thumbnail.

But, other items with no thumbnail keep the old dialog. We can complete and use the same dialog for every kind of file or folder, adding the same thumbnail/placeholder displayed in the list of files.

Does this make sense?

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/feature_name
- [x] Development tasks
  - [x] Unify remove dialogs 
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master
