### ISSUE TITLE
[FEATURE REQUEST] Allow to go to the destination folder when the copy/move operation is finished

### ISSUE THREAD

**Issue by Aitorbp** [owncloud/android#4379]
**Is your feature request related to a problem? Please describe.**
Currently in the application, the operation of copying/moving a file when the operation is finished, the app keeps us in the source path and not in the destination path. There is nothing wrong with this, but I think usability would be improved if we at least gave the user the opportunity to choose whether to navigate to the source or the destination of the operation.

**Describe the solution you'd like**
As a first iteration I propose to open dialog when the copy/move operation is finished. Inside the dialog I would ask the users if they want to navigate to the destination folder where they have copied/moved the file.

**Describe alternatives you've considered**
Alternatively you could skip the dialog directly and redirect to the copied/moved folder.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/allow_go_destination_folder_copy_move_operation
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
  - [ ] Implement unit tests (if needed)
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

**Comment by jesmrec** [comment]
My solution for this would be staying users in the folder they started to execute the action, i mean, where the copied/moved item was placed in first instance.

**Comment by JuancaG05** [comment]
Be careful with modal dialogs: they are a flaw for usability in most cases, they are too intrusive. They should be used for really necessary warnings (alerts) or for confirmation about an action the user performed. In this case, neither of the cases apply. If a user always wants to stay in the source folder and not in the destination one, you'll make them do one more click every time they do a copy/move operation. Not sure about this proposal.

Please, check behaviour with other similar apps (Google Drive, OneDrive, Dropbox...) to make a comparison.

**Comment by Aitorbp** [comment]
Behaviour similar apps:
Google Drive:  the app keeps us in the source path (copy/move)
Box: the app keeps us in the source path (copy/move)
Google Files: the app keeps us in the source path (copy/move)

**Comment by jesmrec** [comment]
So, it's clear we should keep the current behaviour (stay in source folder), and adding an option in snackbar as enhancement. I'd add as `Contributions are welcome` in this one or other feature.

**Comment by mykh-hailo** [comment]
@jesmrec can I take care of this issue?

**Comment by jesmrec** [comment]
ok @mykh-hailo but please, for this issue it'd be good that you share first your thoughts with us about how to implement or the final result (a mock up would be fantastic!!), so, we will be all aligned with the expected result. What do you think?

**Comment by mykh-hailo** [comment]
@jesmrec here is my plan for this ticket.
Once copy or move operation is done, I am going to show snackbar with `Go to Folder` Action which brings me to the destination folder.
Here is my mock up.

<img width="451" height="957" alt="Image" src="https://github.com/user-attachments/assets/f4b6351a-a629-4c97-ba7e-6bb0e2a9ef7a" />

**Comment by jesmrec** [comment]
OK, about the naming:

`The file is copied/moved` -> `The file has been copied/moved` or `File correctly copied/moved` 
`GO TO FOLDER` -> `GO TO TARGET FOLDER` (not clear which folder to go to).

what do you think, @joragua ?

**Comment by jesmrec** [comment]
You have to pay special attention to the browsing. Jumping from a folder (the current one) to the target (it could be in a different space) may not be an easy one.

**Comment by mykh-hailo** [comment]
@jesmrec I have one more issue found related to this issue.
When you are in the folder picker activity to select a destination, the three-dot menu allows you to copy or move files again. Selecting this option opens the folder picker once more, which results in a loop.
What do you think? Shall I fix this issue too?

**Comment by jesmrec** [comment]
> @jesmrec I have one more issue found related to this issue.
When you are in the folder picker activity to select a destination, the three-dot menu allows you to copy or move files again. Selecting this option opens the folder picker once more, which results in a loop.
What do you think? Shall I fix this issue too?

that's a good catch. The three-dot-button should not be visible in the folder picker mode.

If the fix is "easy", you can include it here. If not, please address a different PR in order not to mix. A mixture of "complicated" fixes makes the code review more difficult.

**Comment by mykh-hailo** [comment]
@jesmrec @joragua 
Could you please check my PR for this issue?
Thank you.
