### ISSUE TITLE
[FEATURE REQUEST] Add status message when (un)setting av. offline from preview

### ISSUE THREAD

**Issue by joragua** [owncloud/android#4382]
**Is your feature request related to a problem? Please describe.**
When you are in a preview (text/image) and you click the (un)set as available offline button there aren't feedback and changes in button's name so it is confused because you don't know how the file is. Also there is a little glitch when you click in the menu. It seems that when you click one option in the menu, you are always clicking the first one.

https://github.com/owncloud/android/assets/160487817/e25176f0-c834-4838-9094-f20c2bf94d4e

**Describe the solution you'd like**
A little dialog related with the function that it is used, can be shown in the bottom of the screen. The same when you are in file's details. Also, change the label when the file is available offline or not.

https://github.com/owncloud/android/assets/160487817/efd0e2b2-2a34-4207-bda0-e18a8581e1c2

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/add_feedback_in_preview_menu
- [x] Development tasks
  - [x] Show a snackbar when (un)setting av.offline from text preview
  - [x] Change the label of options menu in text preview
  - [x] Show a snackbar when (un)setting av.offline from image preview
  - [x] Change the label of options menu in image preview
  - [x] Show a snackbar when (un)setting av.offline from audio preview
  - [x] Change the label of options menu in audio preview
  - [x] Show a snackbar when (un)setting av.offline from video preview
  - [x] Change the label of options menu in video preview
  - [x] Implement unit tests (if needed)
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

**Comment by JuancaG05** [comment]
This seems a good improvement! We should always give feedback to the user when they do any kind of action 😄

A Snackbar seems a good approach here when we press the `(Un)set available offline` button 👍 

But, take into account that if the text doesn't change immediately is because the process of do/undo a file available offline takes a while (download the file or remove it), so we could show different Snackbars depending on the status of the process: one when it is being downloaded or removed and another one when it has already finished
