### ISSUE TITLE
[FEATURE REQUEST] Delete space from list of Spaces

### ISSUE THREAD

**Issue by Aitorbp** [owncloud/android#4392]
**Is your feature request related to a problem? Please describe.**
Currently the application has not the possibility to delete a Space. Could be great to add this new functionality. 

**Describe the solution you'd like**
When a long press over the Space container is done, the application navigate to the space clicked. I would change this behavior to add the delete function on the long press. I would add a dialog to delete the space.
In subsequent iterations, you could do something similar to how you find the operations menu of a file. I would also add the option to rename Space from the application.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/delete_space_from_list_of_spaces
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
  - [ ] Implement unit tests (if needed)
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

**Comment by jesmrec** [comment]
Delete/Disable spaces from clients is not intended from product perspective.
