### ISSUE TITLE
[TECHNICAL] Rely on `resharing` capability

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4397]
The `resharing` capability has been set to `false` by default in oCIS servers (https://github.com/owncloud/ocis/issues/8842), and we realised that we're sending the wrong permissions within the `OCShare` object. We always give it share permission although the server doesn't allow it. We also show the `Can share` switch enabled when editing a share. So, several acceptance criteria here:

- Send correct permissions within the `OCShare` object, depending on `resharing` capability
- If `resharing` capability is false, disable the `Can share` switch for shares

### TASKS

- [x] Research (if needed)
- [x] Create branch technical/rely_on_resharing_capability_ocis
- [x] Development tasks
  - [x] Set correct permissions in `OCShare` object
  - [x] Disable `Can share` switch when `resharing` is false
  - [x] Implement unit tests (if needed)
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/rely_on_resharing_capability_ocis into master

**Comment by TheOneRing** [comment]
Correction:
The code enabling resharing for the share jail was removed. The capability will always be false.
Our main concern is to disable resharing for the sharejail in any case. Files in the sharejail might provide the `R` permission but we should never offer the option to share them.

**Comment by jesmrec** [comment]
iOS related: https://github.com/owncloud/ios-app/issues/1353

**Comment by jesmrec** [comment]
Follow up: https://github.com/owncloud/ocis/issues/9681

**Comment by jesmrec** [comment]
Rolling version not following the `R`: propfinded items with `R` are not allowed to be reshared.
