### ISSUE TITLE
[EPIC] Improvements in accessibility

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4398]
The app needs several improvements in accessibility terms. We'll group them here to have them all together. The related issues are:

- [x] https://github.com/owncloud/android/issues/4360
- [x] https://github.com/owncloud/android/issues/4361
- [x] https://github.com/owncloud/android/issues/4362
- [x] https://github.com/owncloud/android/issues/4363
- [x] https://github.com/owncloud/android/issues/4364
- [x] https://github.com/owncloud/android/issues/4365
- [x] https://github.com/owncloud/android/issues/4366
- [x] https://github.com/owncloud/android/issues/4367
- [x] https://github.com/owncloud/android/issues/4368
- [x] https://github.com/owncloud/android/issues/4369
- [x] https://github.com/owncloud/android/issues/4370
- [x] https://github.com/owncloud/android/issues/4371
- [x] https://github.com/owncloud/android/issues/4372
- [x] https://github.com/owncloud/android/issues/4373
- [x] https://github.com/owncloud/android/issues/4374
- [x] https://github.com/owncloud/android/issues/4447
- [x] https://github.com/owncloud/android/issues/4458
- [x] https://github.com/owncloud/android/issues/4469
- [x] https://github.com/owncloud/android/issues/4473
- [x] https://github.com/owncloud/android/issues/4452
