### ISSUE TITLE
[RELEASE] 4.2.2

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4409]
### TASKS:

 - [x] [GIT] Create branch `release/4.2.2` in owncloud/android from `latest`
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DIS] Create a folder for the new version like `4.2.2_YYYY-MM-DD` inside the `changelog` folder with the proper fixes
 - ~~[DIS] Copy the `unreleased` folder in `master` branch to `changelog` folder in this branch, to avoid Calens' conflicts problems~~
 - [x] [DEV] Add release notes to `ReleaseNotesViewModel.kt` (in case patch release before OEM)
 - [x] [DIS] Generate final bundle from last commit in owncloud/android
 - [x] [DEV] Code Review
 - [x] [QA] Test execution
 - [x] [QA] Trigger BitRise builds for unit tests and UI tests, in case CHANGELOG conflicts avoid them in GitHub
 - [x] [QA] QA Approval
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store
 - [x] [GIT] Create and sign tag `v4.2.2` in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Move tag `latest` pointing the same commit as the release commit
 - [x] [GIT] Publish a new [release](https://github.com/owncloud/android/releases) in owncloud/android
 - [x] [DIS] Release published in Play Store
 - [x] [COM] Inform `#updates` in internal chat that release is out
 - [x] [GIT] Fix conflicts if they happen. GitHub option will help and will merge `master` into release branch, getting it ready to fast forward
 - [ ] [GIT] Merge without rebasing `release/4.2.2` branch into `master`, in owncloud/android

### QA

QA checks:

- [x] Smoke test
- [x] Upgrade test

Bugs & improvements:

- [ ] (1) ...
