### ISSUE TITLE
[FEATURE REQUEST] Quota improvements from GraphAPI

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4411]
That comes from https://github.com/owncloud/android/pull/4401#issuecomment-2122995186

Some improvements we could add, taking advantage of GraphAPI:

- If quota is exceeded, currently we show `No storage usage information available`. I'd show the bar full instead. We can also take advantage of the `state` field that comes in the response:

```
 "quota": {
                "remaining": 0,
                "state": "exceeded",
                "total": 1000000000,
                "used": 1423007244
            },
```

playing with colors depending on the status is another option (normal, nearing, exceeded)

- Quota is updated in some scenarios, that we could spread to those ones in which the value changes locally:

   -  Adding a new file
   - Deleting a new file
   - (Maybe all of these cases can be handled updating the quota in the synchronization/refresh operation)
   
They could trigger a new request to update the values

- Show spaces' quota as well

- Showing the quota in manage accounts dialog

- Checking if quota can be retrieved from other different endpoint, without fetching whole info about all spaces.

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/quota_improvements
- [x] Development tasks
  - [x] Add state and total values in quota properties
  - [x] Update drawer when quota is exceeded
  - [x] Update drawer when quota is nearing
  - [x] Update drawer when quota is critical
  - [x] Update quota when a new file is uploaded
  - [x] Update quota when a file is copied
  - [x] Update quota when a file is removed
  - [x] Update quota when a file is moved
  - [x] Show quota in manage accounts dialog
  - [x] Implement unit tests (if needed)
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

**Comment by jesmrec** [comment]
Put an eye on https://github.com/owncloud/enterprise/issues/5808

Could be another fix/improvement to do.

**Comment by joragua** [comment]
### EXCEEDED QUOTA

When the quota is exceeded, the progress bar looks:

![Captura de pantalla 2024-10-08 a las 14 05 13 (2)](https://github.com/user-attachments/assets/1c571c18-3432-479f-9839-811319098e24)

### NEARING QUOTA

I don't know how to display the quota when the state is `nearing`. Now, we have the `total`  and the `used` with the progress bar. In my opinion, in this case, we can replace the color by yellow or something like that, but change the string I don't think it's a good idea.

@jesmrec @JuancaG05 Take a look and comment if you have more ideas 🚀

**Comment by joragua** [comment]
Yeah, I agree with you. I'll continue with your idea and I'll update the screenshots when it's "finished" 😄

**Comment by joragua** [comment]
Here, the two different cases:

### EXCEDEED QUOTA

![Captura de pantalla 2024-10-09 a las 18 09 04](https://github.com/user-attachments/assets/53a57034-9a13-48cd-8a77-0220a1deb737)

### NEARING QUOTA

![Captura de pantalla 2024-10-09 a las 18 10 24](https://github.com/user-attachments/assets/22083aaf-87f6-416f-938f-1be2333d26ad)

**Comment by jesmrec** [comment]
cool! just an small clarification, in the nearing message:  i think `Close to the quota limit` sounds better

**Comment by joragua** [comment]
Hi @tbsbdr! 😄 We have some doubts related with this issue. Do you agree with the string below numerical quota: `The quota is exceeded`, `Close to the quota limit`, `Very close to the quota limit`? How can we highlight all these strings to get the user's attention? We consider not to use colors because we could have problems with the branding.

**Comment by joragua** [comment]
This is how the manage accounts looks with the quota:

![Captura de pantalla 2024-10-10 a las 13 27 03](https://github.com/user-attachments/assets/a394ca36-b8cd-4b46-be14-dcddbfcfa37c)

(In this case the quota is critical, but it's the same with other quota states)

**Comment by jesmrec** [comment]
option 3 merges 1 and 2. That's my favorite

**Comment by tbsbdr** [comment]
@joragua I observed that people don't know the word "quota", because of that I'd start to rename it to `storage` if you agree.

My proposal is:

1. `The quota is exceeded` --> **Storage full**
2. `Close to the quota limit` --> **Storage nearly full**
3. `Very close to the quota limit` --> **Storage very nearly full**

Would that be an improvement?

**get the user's attention**

Hm.. I'd expect a color as a visual hint. If somehow possible and if not "too expensive", let's use a color. Note on branding: The comprehensive branding as we still provide it should be cut back in the future. With this in mind, I'd encourage to cut ties with the past where possible which can mean to not pay much attention to branding. just my 2 cents.


![screenshot_003195](https://github.com/user-attachments/assets/7f1143b2-0d2a-4470-946a-39d960b69dd4)

**Comment by joragua** [comment]
### Tasks that are done ✅ 

- Updated the drawer when the quota is nearing, critical or exceeded:

| Exceeded Quota  | Nearing Quota |
| ----------------- | ----------------- |
| <img width="326" alt="Exceeded quota" src="https://github.com/user-attachments/assets/ef37c182-65e3-49bd-a018-66f2feb07b9e"> | <img width="326" alt="Nearing quota" src="https://github.com/user-attachments/assets/b9e1db90-3f1e-4adf-82a6-e274a3f75db3">|


| Critical Quota | Normal limited quota |
| ----------------- | ----------------- |
| <img width="326" alt="Critical quota" src="https://github.com/user-attachments/assets/d6f3700a-0ad2-41bd-8f2a-9178e68e115c"> | <img width="326" alt="Normal quota" src="https://github.com/user-attachments/assets/ce9ef20a-7bbd-4454-8d5e-84d7c731a375">|

- Updated the quota when a file is added, removed or moved:
https://github.com/user-attachments/assets/9384bfbb-f3ec-49bb-909b-31c6a8cc027f

- Added the quota in the manage accounts dialog:

<img width="326" alt="Captura de pantalla 2024-10-14 a las 10 23 25" src="https://github.com/user-attachments/assets/cb3d3afb-7e85-4555-9c5d-d50734bdb24d">
