### ISSUE TITLE
[FEATURE REQUEST] Open and create .url shortcut files

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/android#4413]
Please implement support for creating and opening .url files.
The feature should behave similarly to https://github.com/owncloud/ios-app/pull/1344 but follow the normal android UX.
### TASKS

- [x] Research (if needed)
- [x] Create branch feature/open_create_url_shortcut_files
- [x] Development tasks
  - [x] Create dialog fragment with url and name file inputs
  - [x] Upload the file to the server
  - [x] Click on file url and download
  - [x] Open alert dialog to navigate to browser
  - [x] Redirect to the browser
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/open_create_url_shortcut_files into master

**Comment by jesmrec** [comment]
Some Android specific details:

- `Shortcuts` should be a new option in the FAB menu

- We need an icon, similar to the iOS one, for the `.url` files

- As first iteration, only two input fields: name (taking care of name conflicts) and url (with no validation, but error handling). Later, we can take advantage of deeplinks as iOS does (open to discussion)

quick info about .url files

https://fileinfo.com/extension/url
https://www.lyberty.com/encyc/articles/tech/dot_url_format_-_an_unofficial_guide.html
