### ISSUE TITLE
[RELEASE] 4.3.0_enterprise

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4426]
### TASKS:

- ~[GIT] Create a new branch `release/4.3.0_enterprise` (optional)~
- ~[DIS] Update release notes in app with the proper content for enterprise release~
- [x] [GIT] Create and sign tag `v4.3.0_enterprise` in HEAD commit of `release/4.3.0_enterprise` branch
- [x] [DEV] Approve and merge changes in ownBrander
  - [x] Update version number in ownBrander
- [x] [OPS] Block oB button
- [x] [OPS] Deploy oB
- [x] [QA] Generate final APKs files from signed commit in builder machine and perform some basic checks:
    - [x] Installation of apk/aab generated by builder machine
    - ~App update from previous version (generated in advance)~
- [x] [QA] Tell @TheOneRing about the completion of the task
- [x] [OPS] Enable button
- ~[GIT] Fix conflicts in branch if they happen. No rebasing.~
- ~[GIT] Merge without rebasing `release/4.3.0_enterprise` branch into `master`, in owncloud/android~
