### ISSUE TITLE
[RELEASE] 4.3.1_enterprise

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4445]
### TASKS:

- [x] [GIT] Create and sign tag `v4.3.1_enterprise` 
- [x] [DEV] Approve and merge changes in ownBrander
  - [x] Update version number in ownBrander
- [x] [OPS] Block oB button
- [x] [OPS] Deploy oB
- [x] [QA] Generate final APKs files from signed commit in builder machine and perform some basic checks:
    - [x] Installation of apk/aab generated by builder machine
    - [x] App update from previous version (generated in advance)
- [x] [OPS] Enable button

**Comment by jesmrec** [comment]
Everything done.
