### ISSUE TITLE
[RELEASE] 4.4.0-beta.1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4450]
### TASKS:

 - [x] [GIT] Create branch `release/4.4.0-beta.1` in owncloud/android from master
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DEV] Check release notes in `ReleaseNotesViewModel.kt` to assure nothing important is missing there
 - [x] [DIS] Prepare post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))
 - [x] [DIS] Generate final bundle from last commit in owncloud/android
 - [x] [QA] Design Test plan
 - [x] [DEV] Code Review
 - [x] [QA] Smoke Test execution
 - [x] [QA] QA Approval
 - [x] [DIS] Upload release APK and bundle to internal owncloud instance
 - [x] [DIS] Upload & publish release bundle and changelog in Play Store (open testing track)
 - [x] [GIT] Create and sign tag `v4.4.0-beta.1` in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Publish a new [release](https://github.com/owncloud/android/releases) in owncloud/android
 - [x] [DIS] Release published in Play Store
 - [x] [DIS] Publish post in central.owncloud.org ([`Category:News + Tag:android`](https://central.owncloud.org/tags/c/news/5/android))
 - [x] [COM] Inform in public chat that release is out
 - [ ] [GIT] Merge without rebasing `release/4.4.0-beta.1` branch into `master`, in owncloud/android

### QA

Smoke test:

Bugs & improvements:

- [ ] (1) ...
