### ISSUE TITLE
[RELEASE] 4.4.0

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4460]
### TASKS:

 - [x] [COM] Ping in #android-dev-internal about the new release (@mmattel)
 - [x] [GIT] Create branch `release/M.m.p` in owncloud/android from `master`
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
 - [x] [DOC] Update [SBOM](https://infinite.owncloud.com/f/31e6d44f-f373-557c-9ab3-1748fc0c650d$4994cd9c-1c17-4254-829a-f5ef6e1ff7e3%215080be84-fbcc-4aca-956e-b278a7090418)
 - [x] [DIS] Move Calens files from `unreleased` to a new folder like `M.m.p_YYYY-MM-DD` inside the `changelog` folder
 - [x] [DEV] Check and reorder release notes in `ReleaseNotesViewModel.kt` to assure nothing important is missing there
 - [x] [DEV] Code review
 - [x] [DIS] Generate final bundle and APK from last commit in release branch
 - [x] [COM] Prepare post in central.owncloud.org ([Category:News + Tag:android](https://central.owncloud.org/tags/c/news/5/android))
 - [x] [DIS] Check for new screenshots in Play Store/GitHub/F-Droid and generate them
 - [x] [QA] Design test plan
 - [x] [QA] Regression test execution
 - [x] [QA] QA approval
 - [x] [DIS] Upload release APK and bundle to internal ownCloud instance
 - [x] [COM] Ping in #android-dev-internal that we are close to sign the new tags (@mmattel)
 - [x] [DIS] Upload and publish release bundle and changelog in Play Store
 - [x] [DIS] Update screenshots in Play Store/GitHub/F-Droid
 - [x] [GIT] Create and sign tag `vM.m.p` in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Move tag `latest` pointing the same commit as the release commit
 - [x] [DIS] Publish a new [release](https://github.com/owncloud/android/releases) in owncloud/android
 - [x] [DIS] Release published in Play Store
 - [x] [COM] Publish post in central.owncloud.org ([Category:News + Tag:android](https://central.owncloud.org/tags/c/news/5/android))
 - [x] [COM] Inform in #general that release is out
 - [x] [GIT] Merge `master` into `release/M.m.p`, fixing all the conflicts that could happen, in owncloud/android
 - [x] [GIT] Merge without rebasing `release/M.m.p` branch into `master`, in owncloud/android
 - [x] [COM] Ping @TheOneRing to update release information in https://owncloud.com/mobile-apps/
 - ~~[DOC] Update documentation with new stuff by creating [issue](https://github.com/owncloud/docs-client-android/issues)~~

### QA

Regression test:

Bugs & improvements:

- [ ] (1) ...

**Comment by jesmrec** [comment]
[wip]

**Server version**:  oCIS 5.0.7, oC10.15.0<br>
**Device & Android version**: Xiaomi Redmi 13 Android 14,  Samsung Galaxy Tab A8 Android 14<br>


- [X] Fresh install
- [ ] Smoke test
  - [X] Auth (basic, oauth2, oidc) 
  - [X] Transfers
  - [X] Multiaccount
  - [X] Security (passcode / pattern)
  - [X] E2E tests 
      - [X] oCIS 
      - [ ] oC10 
  - [ ] Changelog
     - [X] resharing based capability 
     - [X] shares in not root
     - [X] list filtering not working after rotating
     - [X] the color of some elements is set up correctly -> to be tested in enterprise 
     - [X] audio player in Android 14
  - [ ] Doc provider
- [ ] Upgrade from latest stable
- [ ] Generate and check aab
