### ISSUE TITLE
[RELEASE] 4.4.0_enterprise

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4477]
### TASKS:

- ~~[GIT] Create branch `release/M.m.p_enterprise` in owncloud/android from `latest` (or the corresponding release tag)~~
- ~~[DOC] Update [SBOM](https://infinite.owncloud.com/f/31e6d44f-f373-557c-9ab3-1748fc0c650d$4994cd9c-1c17-4254-829a-f5ef6e1ff7e3%215080be84-fbcc-4aca-956e-b278a7090418)~~
- ~~[DIS] Update release notes in app and changelog in `M.m.p_YYYY-MM-DD` (already released version) with the proper content for the release~~
- ~~[DIS] Copy the `unreleased` folder in `master` branch into this branch, to avoid Calens conflicts problems~~
- ~~[DEV] Check and reorder release notes in `ReleaseNotesViewModel.kt` to assure nothing important is missing there~~
- ~~[DEV] Code review~~
- ~~[DIS] Generate final bundle and APK from last commit in the release branch~~
- ~~[QA] Design test plan~~
- ~~[QA] Test execution~~
- ~~[QA] Trigger BitRise builds for unit tests and UI tests, in case changelog conflicts avoid them in GitHub~~
- ~~[QA] QA approval~~
- ~~[DIS] Upload release APK and bundle to internal ownCloud instance~~
- [x] [GIT] Create and sign tag `v4.4.0_enterprise` in HEAD commit of release branch, in owncloud/android
- [x] [DEV] Approve and merge changes in ownBrander
  - [x] Update version number in ownBrander
- [x] [COM] Ping @NannaBarz to block oB button
- [x] [COM] Ping @NannaBarz to deploy oB
- [x] [QA] Generate final APKs from signed commit in builder machine and perform some basic checks
    - [x] Installation of APK/bundle generated by builder machine
    - [x] https://github.com/owncloud/android/issues/4442 
    - [x] https://github.com/owncloud/ownbrander/issues/1088
       - [X] Search bubble with default color
       - [X] Search bubble with branded color
    - [x] App update from previous version (generated in advance)
- [x] [COM] Notify result in internal chat
- [x] [COM] Ping @NannaBarz to enable oB button
- ~~[GIT] Merge `master` into `release/M.m.p_enterprise`, fixing all the conflicts that could happen, in owncloud/android~~
- ~~[GIT] Merge without rebasing `release/M.m.p_enterprise` branch into `master`, in owncloud/android~~

**Comment by jesmrec** [comment]
Done!!
