### ISSUE TITLE
[FEATURE REQUEST] oCIS Users light

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4490]
oCIS allows to create several kind of users (admin, space admin, user and light user). Android app supports all of them but light uses.

This kind of user is similar to the guest user of oC10. Light user lacks of `Personal` space and is granted to access to spaces. 

Android app does not support users without a `Personal`. If a light user tries to connect the app, will get an error `it was not found`.

We'll have to find the way to allow this feature.

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/light_users
- [x] Development tasks
  - [x] Authentication
  - [x] Check if the account is a light user
  - [x] Show empty personal space
  - [x] Disable refresh operation from available offline view
  - [x] Show unavailable quota in manage accounts
  - [x] Show unavailable quota in drawer
  - [x] Disable automatic uploads when there are only light users in the device
  - [x] Disable light users in accounts list for automatic uploads when there are accounts in the device which are not light users
  - [x] Adapt `ReceiveExternalFiles` for light users
  - [x] Disable oCIS accounts warning dialog for light users
  - [x] Implement unit tests (if needed)
- [x] Code review and apply changes requested
- [x] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master
