### ISSUE TITLE
[RELEASE] 4.4.1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4501]
### TASKS:

 - [x] [GIT] Create branch `release/4.4.1` in owncloud/android from `latest`
 - [x] [DEV] Update version number and name in build.gradle in owncloudApp module
- ~~[DOC] Update [SBOM](https://infinite.owncloud.com/f/31e6d44f-f373-557c-9ab3-1748fc0c650d$4994cd9c-1c17-4254-829a-f5ef6e1ff7e3%215080be84-fbcc-4aca-956e-b278a7090418)~~
 - [x] [DIS] Update release notes in app and changelog in `unreleased` with the proper content for the release
 - [x] [DIS] Move Calens files from `unreleased` to a new folder like `M.m.p_YYYY-MM-DD` inside the `changelog` folder
 - [x] [DIS] Copy the `unreleased` folder in `master` branch into this branch, to avoid Calens conflicts problems
 - [x] [DEV] Check and reorder release notes in `ReleaseNotesViewModel.kt` to assure nothing important is missing there
 - [x] [DEV] Code review
 - [x] [DIS] Generate final bundle and APK from last commit in the release branch
- ~~[DIS] Check for new screenshots in Play Store/GitHub/F-Droid and generate them~~
- ~~[QA] Design test plan~~
 - [x] [QA] Test execution
 - [x] [QA] Trigger BitRise builds for unit tests and UI tests, in case changelog conflicts avoid them in GitHub
 - [x] [QA] QA approval
 - [x] [DIS] Upload release APK and bundle to internal ownCloud instance
 - [x] [DIS] Upload and publish release bundle and changelog in Play Store
 - ~~[DIS] Update screenshots in Play Store/GitHub/F-Droid~~
 - [x] [GIT] Create and sign tag `v4.4.1` in HEAD commit of release branch, in owncloud/android
 - [x] [GIT] Move tag `latest` pointing the same commit as the release commit
 - [x] [DIS] Publish a new [release](https://github.com/owncloud/android/releases) in owncloud/android
 - [x] [DIS] Release published in Play Store
 - [x] [COM] Inform in #general that release is out
 - [x] [GIT] Merge `master` into `release/4.4.1`, fixing all the conflicts that could happen, in owncloud/android
 - [x] [GIT] Merge without rebasing `release/4.4.1` branch into `master`, in owncloud/android
 - [x] [COM] Ping @TheOneRing to update release information in https://owncloud.com/mobile-apps/

### QA

QA checks:

https://github.com/owncloud/android/issues/4501#issuecomment-2435206892

Bugs & improvements:

- [ ] (1) ...

**Comment by jesmrec** [comment]
**Server version**: 5.0.8<br>
**Device & Android version**: Xiaomi Redmi 13, Pixel 2, Samsung Galaxy Tab A8<br>
**Android app version**: 4.4.1 


- [ ] Fresh install
- [ ] Smoke test
  - [ ] Auth (basic, oauth2, oidc) 
  - [ ] Transfers
  - [ ] Multiaccount
  - [ ] Security (passcode / pattern)
  - [ ] E2E tests 
      - oCIS 
      - oC10 
  - [ ] Doc provider
- [ ] Upgrade from latest stable
- [ ] Generate and check aab

**Comment by jesmrec** [comment]
The change that was undone to fix https://github.com/owncloud/android/issues/4495 has caused a regression in the original PR. Automatic uploads with behaviour `copy` are not removed from `/tmp`. This is the scenario i tested (still more scenarios to test):

1. Enable automatic uploads with `copy` (kept in original folder) behaviour
2. Take some pictures
3. Wait 15 minutes 

Current: uploads finish correctly, but the `/tmp` folder is not cleaned up

**Comment by joragua** [comment]
@jesmrec The bug that was reported it's fixed 😄
