### ISSUE TITLE
[TECHNICAL] Detekt: static code analyzer

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4506]
Adding a new static code analyzer for Kotlin: https://detekt.dev/

### TASKS

- [X] Research (if needed)
- [X] Create branch feature/detekt
- [X] Initial set up of the tool
- [X] First try to integrate in CI (github actions)
- [X] Launch the analyzer to get an initial set of existing code smells
- [X] Analyze the code smells and decide what to do with them
- [X] Check if more rules should be added or removed from the set of existing rules
- [ ] Fix all code smells:
  - [x] MaxLineLength: max 150 characters per line -> CR ✅
  - [x] LongMethod: refactor all methods with more than 100 lines -> CR ✅
  - [x] UnusedPrivateMember -> CR ✅
  - [x] UnusedPrivateProperty -> CR ✅
  - [x] UseIfInsteadOfWhen -> CR ✅
  - [x] UseLet -> CR ✅
  - [x] SpacingBetweenPackageAndImports -> CR ✅
  - [x] ExplicitItLambdaParameter (data module) -> CR ✅
  - [x] CollapsibleIfStatements -> CR ✅
  - [x] UnusedParameter -> CR ✅
  - [x] InvalidPackageDeclaration -> CR ✅
  - [x] ExpressionBodySyntax -> CR ✅
  - [x] NewLineAtEndOfFile -> CR ✅
  - [x] MemberNameEqualsClassName -> CR ✅
  - [x] ForbiddenComment -> CR ✅
  - [x] WildCardImport -> CR ✅
  - [x] VariableNaming -> CR ✅
  - [x] EmptySecondaryConstructor -> CR ✅
  - [x] NotImplementedDeclaration -> CR ✅
  - [x] MandatoryBracesLoops -> CR ✅
  - [x] ClassOrdering -> CR ✅
  - [x] MatchingDeclarationName -> CR ✅
  - [x] ImplicitDefaultLocale -> CR ✅
  - [x] SpreadOperator (in migrations, add ALLMIGRATIONS to array directly) -> CR ✅
  - [x] UtilityClassWithPublicConstructor -> CR ✅
  - [x] OptionalUnit -> CR ✅
  - [x] BracesOnIfStatements -> CR ✅
  - [x] BracesOnWhenStatements -> CR ✅
  - [x] AlsoCouldBeApply -> CR ✅
  - [x] SwallowedException -> CR ✅
  - [x] PrintStackTrace -> CR ✅
  - [x] InstanceOfCheckForException -> CR ✅
  - [x] ConstructorParameterNaming -> CR ✅
  - [x] ThrowingExceptionsWithoutMessageOrCause -> CR ✅
  - [x] ComplexCondition -> CR ✅
  - [ ] CognitiveComplexMethod (in other issue)
  - [ ] NestedBlockDepth (in other issue)
  - [ ] LoopWithTooManyJumpStatements (in other issue)
- [x] Final CI setup (correct branching and setup ready to go)
- [x] No code smells -> green CI
- [x] Add Calens file
- [x] Code review and apply changes requested
- [ ] Merge branch feature/detekt into master

**Comment by jesmrec** [comment]
Some dependency on https://github.com/owncloud/android/issues/4478.

Gradle version to push on, will determine the basic detekt version to use
