### ISSUE TITLE
[FEATURE REQUEST] Multi-Personal (1st round)

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4514]
Now, app is able to connect to one `Personal` space. 

The ability of having multiple `Personal` should be supported and displayed in the list of spaces as any other one.

### TASKS

- [x] Research (if needed)
- [x] Create branch feature/multi_personal1
- [x] Development tasks
  - [x] First approach: show all personal spaces in Spaces tab
  - [x] Implement unit tests (if needed)
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch feature/multi_personal1 into master

**Comment by jesmrec** [comment]
[feat: hack not to show the dialog with oC version not supported warning](https://github.com/owncloud/android/commit/27f3ce693f9a7b3c4855dfa50691ba7b4ba381b7) -> fixed via server. Dismissable, nothing to do at this regard.

[feat: hack to consider share_jail non-required](https://github.com/owncloud/android/commit/67f97875f3041b9a7e67474e237da0389a6302bc) -> fixed via server. Dismissable, nothing to do at this regard.

[feat: hack to consider lastModifiedDateTime, webUrl and driveAlias in spaces non-required](https://github.com/owncloud/android/commit/b64664399e8acd61d3b690bb59fa63467e3471ee) -> manual migration in DB. Optional: check which other are also "nullable" to migrate everything at the time.

[feat: hack to mock a default quota for multi-personal accounts](https://github.com/owncloud/android/commit/639484f9fb30e54af16642fd0a0a859fc8f89fb8) -> maybe use the capability `has_multiple_personal` to decide. Check if a [better combination of values](https://github.com/owncloud/android/commit/639484f9fb30e54af16642fd0a0a859fc8f89fb8#diff-e41f3efd2ae73b5c6c711be49657d2d65583ebf4ea98fa0fb2a070097c023df5R45) exist to mock the inexistent quota (no personal as it is). Value "-4" could fit.

[feat: hack to retrieve only personal spaces in multi-personal accounts](https://github.com/owncloud/android/commit/8c75995186abe855ddcc54570599067a001fe160) -> use the capability `has_multiple_personal` to make the decision.

[feat: hack to continue with login process even when first PROPFIND returns a 404](https://github.com/owncloud/android/commit/ebd3514059eaf9a51d53e9473d45d66fae18005c) -> assuming that the 404 will happen only in case of user light or kws. Done in user light, could dismiss.

[feat: hack to show empty view with no personal space in "Personal" tab](https://github.com/owncloud/android/commit/5330a3e6b061a68c6a9e96c93b7d57b0de00a0fc) -> change `isLightUser = true` with logic to make the decision in base of the quota (-4).  Use the capability as condition to add with OR. If user light implements, discard.

[feat: hack to avoid refreshes over personal space in "Av. offline" tab](https://github.com/owncloud/android/commit/fbf9e248cf7750047e194752bbe0912c1901ad05) -> in users light. To apply everywhere. Discard this commit because a crash is fixed in users light's PR

[feat: hack to make spaces header appear with personal spaces as well](https://github.com/owncloud/android/commit/6584a7b1f9fc7731abe46194bf7b05c3b36a6893) -> add extra condition to assure that personal spaces show the header whether the capability is true.

[feat: hack to show storage information not available message in drawer and manage accounts dialog](https://github.com/owncloud/android/commit/7b151b2a2e8e29fee1ed415cc4f40a0ce0daaa2f): fix together with [feat: hack to mock a default quota for multi-personal accounts](https://github.com/owncloud/android/commit/639484f9fb30e54af16642fd0a0a859fc8f89fb8)

[feat: hack to show correct toolbar and apply correct navigation when entering a personal space](https://github.com/owncloud/android/commit/4eb60a202c4ed3f07f7478b0b067fec03b49a296) -> add extra condition to assure that personal spaces show the header whether the capability is true.

[feat: hack not to show space header in "Av. offline" tab](https://github.com/owncloud/android/commit/67b66d963e05464ebc9b1e89e9af8296263b0a4b) -> move forward, no problem.
