### ISSUE TITLE
[TECHNICAL] Pending unit tests for `OCRemoteServerInfoDataSource`

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4517]
After performing some changes in the authentication - authorization flow in the issue:

https://github.com/owncloud/android/issues/4500

the `OCRemoteServerInfoDataSource` unit tests need some improvements to be totally adapted and covering the new scenarios. 

### TASKS

- [x] Research (if needed)
- [x] Create branch technical/tests_server_info_datasource
- [x] Development tasks
  - [x] Adapt unit tests in `OCRemoteServerInfoDataSource`
- [x] Code review and apply changes requested
- [ ] Merge branch technical/tests_server_info_datasource into master
