### ISSUE TITLE
[TECHNICAL] Technical improvements for user quota

### ISSUE THREAD

**Issue by joragua** [owncloud/android#4521]
Right now, the user quota is fetched (`getStoredQuota` method) from the database multiple times in `DrawerActivity` because it is not get as a `Flow`. In this issue we are going to improve performance by fetching the user quota as `Flow` and remove unnecessary calls from the activity.

### TASKS

- [x] Research (if needed)
- [x] Create branch technical/technical_improvements_for_quota
- [x] Development tasks
  - [x] Create a new use case (`GetStoredQuotaAsStreamUseCase`)
  - [x] Remove unnecessary calls from `DrawerActivity`
  - [x] Fix some elements from drawer
  - [x] Implement unit tests (if needed)
- [x] Code review and apply changes requested
- [x] Design test plan
- [x] QA
- [ ] Merge branch technical/technical_improvements_for_quota

**Comment by joragua** [comment]
Apart from technical work, the progress bar in the drawer has been removed when the quota is unlimited

<img width="278" alt="Captura de pantalla 2025-01-09 a las 10 40 25" src="https://github.com/user-attachments/assets/7a9740a7-7358-463a-ab42-c8d218aadb7b" />
